namespace Tourist_Management.Other
{
    partial class frmFilterRecords
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmFilterRecords));
            this.GroupBox3 = new System.Windows.Forms.GroupBox();
            this.btnShowAll = new System.Windows.Forms.Button();
            this.btnSearch = new System.Windows.Forms.Button();
            this.btnclear = new System.Windows.Forms.Button();
            this.btncancel = new System.Windows.Forms.Button();
            this.btnSelect = new System.Windows.Forms.Button();
            this.GroupBox1 = new System.Windows.Forms.GroupBox();
            this.txtval4 = new System.Windows.Forms.TextBox();
            this.cmbOp4 = new  Tourist_Management.User_Controls.ComboBox();
            this.cmbFld4 = new  Tourist_Management.User_Controls.ComboBox();
            this.txtval3 = new System.Windows.Forms.TextBox();
            this.cmbOp3 = new  Tourist_Management.User_Controls.ComboBox();
            this.cmbFld3 = new  Tourist_Management.User_Controls.ComboBox();
            this.txtval2 = new System.Windows.Forms.TextBox();
            this.cmbOp2 = new  Tourist_Management.User_Controls.ComboBox();
            this.cmbFld2 = new  Tourist_Management.User_Controls.ComboBox();
            this.Label3 = new System.Windows.Forms.Label();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label1 = new System.Windows.Forms.Label();
            this.txtval1 = new System.Windows.Forms.TextBox();
            this.cmbOp1 = new  Tourist_Management.User_Controls.ComboBox();
            this.cmbFld1 = new  Tourist_Management.User_Controls.ComboBox();
            this.flx = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.label12 = new System.Windows.Forms.Label();
            this.groupBox19 = new System.Windows.Forms.GroupBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.GroupBox3.SuspendLayout();
            this.GroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.flx)).BeginInit();
            this.SuspendLayout();
            this.GroupBox3.BackColor = System.Drawing.Color.Transparent;
            this.GroupBox3.Controls.Add(this.btnShowAll);
            this.GroupBox3.Controls.Add(this.btnSearch);
            this.GroupBox3.Controls.Add(this.btnclear);
            this.GroupBox3.Location = new System.Drawing.Point(489, 34);
            this.GroupBox3.Name = "GroupBox3";
            this.GroupBox3.Size = new System.Drawing.Size(266, 57);
            this.GroupBox3.TabIndex = 102;
            this.GroupBox3.TabStop = false;
            this.btnShowAll.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnShowAll.ForeColor = System.Drawing.Color.Black;
            this.btnShowAll.Image = global::Tourist_Management.Properties.Resources.sum;
            this.btnShowAll.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnShowAll.Location = new System.Drawing.Point(94, 13);
            this.btnShowAll.Name = "btnShowAll";
            this.btnShowAll.Size = new System.Drawing.Size(80, 34);
            this.btnShowAll.TabIndex = 13;
            this.btnShowAll.Text = "Show &All";
            this.btnShowAll.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnShowAll.Click += new System.EventHandler(this.btnShowAll_Click);
            this.btnSearch.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSearch.ForeColor = System.Drawing.Color.Black;
            this.btnSearch.Image = global::Tourist_Management.Properties.Resources.search;
            this.btnSearch.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSearch.Location = new System.Drawing.Point(8, 13);
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.Size = new System.Drawing.Size(80, 34);
            this.btnSearch.TabIndex = 12;
            this.btnSearch.Text = "S&earch";
            this.btnSearch.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSearch.Click += new System.EventHandler(this.btnSearch_Click);
            this.btnclear.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnclear.ForeColor = System.Drawing.Color.Black;
            this.btnclear.Image = global::Tourist_Management.Properties.Resources._001_16;
            this.btnclear.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnclear.Location = new System.Drawing.Point(180, 13);
            this.btnclear.Name = "btnclear";
            this.btnclear.Size = new System.Drawing.Size(80, 34);
            this.btnclear.TabIndex = 11;
            this.btnclear.Text = "C&lear";
            this.btnclear.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnclear.Click += new System.EventHandler(this.btnclear_Click);
            this.btncancel.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btncancel.ForeColor = System.Drawing.Color.Black;
            this.btncancel.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btncancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btncancel.Location = new System.Drawing.Point(670, 446);
            this.btncancel.Name = "btncancel";
            this.btncancel.Size = new System.Drawing.Size(80, 34);
            this.btncancel.TabIndex = 10;
            this.btncancel.Text = "&Cancel";
            this.btncancel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btncancel.Click += new System.EventHandler(this.btncancel_Click);
            this.btnSelect.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSelect.ForeColor = System.Drawing.Color.Black;
            this.btnSelect.Image = global::Tourist_Management.Properties.Resources.Apply;
            this.btnSelect.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSelect.Location = new System.Drawing.Point(584, 446);
            this.btnSelect.Name = "btnSelect";
            this.btnSelect.Size = new System.Drawing.Size(80, 34);
            this.btnSelect.TabIndex = 9;
            this.btnSelect.Text = "&Select";
            this.btnSelect.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSelect.Click += new System.EventHandler(this.btnSelect_Click);
            this.GroupBox1.BackColor = System.Drawing.Color.Transparent;
            this.GroupBox1.Controls.Add(this.txtval4);
            this.GroupBox1.Controls.Add(this.cmbOp4);
            this.GroupBox1.Controls.Add(this.cmbFld4);
            this.GroupBox1.Controls.Add(this.txtval3);
            this.GroupBox1.Controls.Add(this.cmbOp3);
            this.GroupBox1.Controls.Add(this.cmbFld3);
            this.GroupBox1.Controls.Add(this.txtval2);
            this.GroupBox1.Controls.Add(this.cmbOp2);
            this.GroupBox1.Controls.Add(this.cmbFld2);
            this.GroupBox1.Controls.Add(this.Label3);
            this.GroupBox1.Controls.Add(this.Label2);
            this.GroupBox1.Controls.Add(this.Label1);
            this.GroupBox1.Controls.Add(this.txtval1);
            this.GroupBox1.Controls.Add(this.cmbOp1);
            this.GroupBox1.Controls.Add(this.cmbFld1);
            this.GroupBox1.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.GroupBox1.Location = new System.Drawing.Point(13, 34);
            this.GroupBox1.Name = "GroupBox1";
            this.GroupBox1.Size = new System.Drawing.Size(457, 57);
            this.GroupBox1.TabIndex = 101;
            this.GroupBox1.TabStop = false;
            this.txtval4.BackColor = System.Drawing.Color.White;
            this.txtval4.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtval4.ForeColor = System.Drawing.Color.Black;
            this.txtval4.Location = new System.Drawing.Point(284, 174);
            this.txtval4.Name = "txtval4";
            this.txtval4.Size = new System.Drawing.Size(159, 21);
            this.txtval4.TabIndex = 15;
            this.cmbOp4.BackColor = System.Drawing.Color.White;
            this.cmbOp4.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbOp4.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbOp4.ForeColor = System.Drawing.Color.Black;
            this.cmbOp4.FormattingEnabled = true;
            this.cmbOp4.Location = new System.Drawing.Point(148, 174);
            this.cmbOp4.Name = "cmbOp4";
            this.cmbOp4.Size = new System.Drawing.Size(121, 21);
            this.cmbOp4.TabIndex = 14;
            this.cmbFld4.BackColor = System.Drawing.Color.White;
            this.cmbFld4.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFld4.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbFld4.ForeColor = System.Drawing.Color.Black;
            this.cmbFld4.FormattingEnabled = true;
            this.cmbFld4.Location = new System.Drawing.Point(15, 174);
            this.cmbFld4.Name = "cmbFld4";
            this.cmbFld4.Size = new System.Drawing.Size(116, 21);
            this.cmbFld4.TabIndex = 13;
            this.txtval3.BackColor = System.Drawing.Color.White;
            this.txtval3.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtval3.ForeColor = System.Drawing.Color.Black;
            this.txtval3.Location = new System.Drawing.Point(284, 147);
            this.txtval3.Name = "txtval3";
            this.txtval3.Size = new System.Drawing.Size(159, 21);
            this.txtval3.TabIndex = 12;
            this.cmbOp3.BackColor = System.Drawing.Color.White;
            this.cmbOp3.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbOp3.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbOp3.ForeColor = System.Drawing.Color.Black;
            this.cmbOp3.FormattingEnabled = true;
            this.cmbOp3.Location = new System.Drawing.Point(148, 147);
            this.cmbOp3.Name = "cmbOp3";
            this.cmbOp3.Size = new System.Drawing.Size(121, 21);
            this.cmbOp3.TabIndex = 11;
            this.cmbFld3.BackColor = System.Drawing.Color.White;
            this.cmbFld3.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFld3.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbFld3.ForeColor = System.Drawing.Color.Black;
            this.cmbFld3.FormattingEnabled = true;
            this.cmbFld3.Location = new System.Drawing.Point(15, 147);
            this.cmbFld3.Name = "cmbFld3";
            this.cmbFld3.Size = new System.Drawing.Size(116, 21);
            this.cmbFld3.TabIndex = 10;
            this.txtval2.BackColor = System.Drawing.Color.White;
            this.txtval2.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtval2.ForeColor = System.Drawing.Color.Black;
            this.txtval2.Location = new System.Drawing.Point(284, 120);
            this.txtval2.Name = "txtval2";
            this.txtval2.Size = new System.Drawing.Size(159, 21);
            this.txtval2.TabIndex = 9;
            this.cmbOp2.BackColor = System.Drawing.Color.White;
            this.cmbOp2.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbOp2.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbOp2.ForeColor = System.Drawing.Color.Black;
            this.cmbOp2.FormattingEnabled = true;
            this.cmbOp2.Location = new System.Drawing.Point(148, 120);
            this.cmbOp2.Name = "cmbOp2";
            this.cmbOp2.Size = new System.Drawing.Size(121, 21);
            this.cmbOp2.TabIndex = 8;
            this.cmbFld2.BackColor = System.Drawing.Color.White;
            this.cmbFld2.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFld2.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbFld2.ForeColor = System.Drawing.Color.Black;
            this.cmbFld2.FormattingEnabled = true;
            this.cmbFld2.Location = new System.Drawing.Point(15, 120);
            this.cmbFld2.Name = "cmbFld2";
            this.cmbFld2.Size = new System.Drawing.Size(116, 21);
            this.cmbFld2.TabIndex = 7;
            this.Label3.AutoSize = true;
            this.Label3.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Label3.ForeColor = System.Drawing.Color.Black;
            this.Label3.Location = new System.Drawing.Point(284, 11);
            this.Label3.Name = "Label3";
            this.Label3.Size = new System.Drawing.Size(39, 13);
            this.Label3.TabIndex = 6;
            this.Label3.Text = "Value";
            this.Label2.AutoSize = true;
            this.Label2.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Label2.ForeColor = System.Drawing.Color.Black;
            this.Label2.Location = new System.Drawing.Point(148, 11);
            this.Label2.Name = "Label2";
            this.Label2.Size = new System.Drawing.Size(58, 13);
            this.Label2.TabIndex = 5;
            this.Label2.Text = "Operator";
            this.Label1.AutoSize = true;
            this.Label1.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Label1.ForeColor = System.Drawing.Color.Black;
            this.Label1.Location = new System.Drawing.Point(16, 11);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(73, 13);
            this.Label1.TabIndex = 4;
            this.Label1.Text = "Fileld Name";
            this.txtval1.BackColor = System.Drawing.Color.White;
            this.txtval1.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtval1.ForeColor = System.Drawing.Color.Black;
            this.txtval1.Location = new System.Drawing.Point(284, 28);
            this.txtval1.Name = "txtval1";
            this.txtval1.Size = new System.Drawing.Size(159, 21);
            this.txtval1.TabIndex = 3;
            this.txtval1.TextChanged += new System.EventHandler(this.txtval1_TextChanged);
            this.txtval1.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtval1_KeyDown);
            this.cmbOp1.BackColor = System.Drawing.Color.White;
            this.cmbOp1.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbOp1.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbOp1.ForeColor = System.Drawing.Color.Black;
            this.cmbOp1.FormattingEnabled = true;
            this.cmbOp1.Location = new System.Drawing.Point(148, 28);
            this.cmbOp1.Name = "cmbOp1";
            this.cmbOp1.Size = new System.Drawing.Size(121, 21);
            this.cmbOp1.TabIndex = 2;
            this.cmbFld1.BackColor = System.Drawing.Color.White;
            this.cmbFld1.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFld1.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbFld1.ForeColor = System.Drawing.Color.Black;
            this.cmbFld1.FormattingEnabled = true;
            this.cmbFld1.Location = new System.Drawing.Point(15, 28);
            this.cmbFld1.Name = "cmbFld1";
            this.cmbFld1.Size = new System.Drawing.Size(116, 21);
            this.cmbFld1.TabIndex = 1;
            this.flx.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.flx.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.flx.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.flx.Location = new System.Drawing.Point(6, 97);
            this.flx.Name = "flx";
            this.flx.Size = new System.Drawing.Size(751, 343);
            this.flx.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("flx.Styles"));
            this.flx.TabIndex = 305;
            this.flx.Click += new System.EventHandler(this.flx_Click_1);
            this.flx.DoubleClick += new System.EventHandler(this.flx_DoubleClick);
            this.label12.AutoSize = true;
            this.label12.BackColor = System.Drawing.Color.Transparent;
            this.label12.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label12.Location = new System.Drawing.Point(3, 9);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(239, 14);
            this.label12.TabIndex = 309;
            this.label12.Text = "SELECT TOUR TO RETIEVE VALUES";
            this.groupBox19.BackColor = System.Drawing.Color.Gray;
            this.groupBox19.Location = new System.Drawing.Point(242, 19);
            this.groupBox19.Name = "groupBox19";
            this.groupBox19.Size = new System.Drawing.Size(514, 2);
            this.groupBox19.TabIndex = 308;
            this.groupBox19.TabStop = false;
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.ForeColor = System.Drawing.Color.Green;
            this.label6.Location = new System.Drawing.Point(8, 467);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(129, 13);
            this.label6.TabIndex = 312;
            this.label6.Text = "To Selcet Press Enter";
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Verdana", 8.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label4.Location = new System.Drawing.Point(8, 446);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(93, 13);
            this.label4.TabIndex = 310;
            this.label4.Text = "SHORT KEYS :";
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(766, 487);
            this.ControlBox = false;
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.groupBox19);
            this.Controls.Add(this.flx);
            this.Controls.Add(this.btnSelect);
            this.Controls.Add(this.btncancel);
            this.Controls.Add(this.GroupBox3);
            this.Controls.Add(this.GroupBox1);
            this.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "frmFilterRecords";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmFilterRecords_Load);
            this.GroupBox3.ResumeLayout(false);
            this.GroupBox1.ResumeLayout(false);
            this.GroupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.flx)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        internal System.Windows.Forms.GroupBox GroupBox3;
        internal System.Windows.Forms.Button btnShowAll;
        internal System.Windows.Forms.Button btnSearch;
        internal System.Windows.Forms.Button btnclear;
        internal System.Windows.Forms.Button btncancel;
        internal System.Windows.Forms.Button btnSelect;
        internal System.Windows.Forms.GroupBox GroupBox1;
        internal System.Windows.Forms.Label Label3;
        internal System.Windows.Forms.Label Label2;
        internal System.Windows.Forms.Label Label1;
        internal System.Windows.Forms.TextBox txtval1;
        internal  Tourist_Management.User_Controls.ComboBox cmbOp1;
        internal  Tourist_Management.User_Controls.ComboBox cmbFld1;
        internal System.Windows.Forms.TextBox txtval2;
        internal  Tourist_Management.User_Controls.ComboBox cmbOp2;
        internal  Tourist_Management.User_Controls.ComboBox cmbFld2;
        internal System.Windows.Forms.TextBox txtval4;
        internal  Tourist_Management.User_Controls.ComboBox cmbOp4;
        internal  Tourist_Management.User_Controls.ComboBox cmbFld4;
        internal System.Windows.Forms.TextBox txtval3;
        internal  Tourist_Management.User_Controls.ComboBox cmbOp3;
        internal  Tourist_Management.User_Controls.ComboBox cmbFld3;
        private C1.Win.C1FlexGrid.C1FlexGrid flx;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.GroupBox groupBox19;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label4;
    }
}