namespace Tourist_Management.Transaction
{
    partial class frmVoucherType
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmVoucherType));
            this.tcVoucher = new System.Windows.Forms.TabControl();
            this.tabAddV = new System.Windows.Forms.TabPage();
            this.groupBox12 = new System.Windows.Forms.GroupBox();
            this.rdbGuide = new System.Windows.Forms.RadioButton();
            this.rdbDriver = new System.Windows.Forms.RadioButton();
            this.groupBox11 = new System.Windows.Forms.GroupBox();
            this.txtNoOfVehicles = new System.Windows.Forms.TextBox();
            this.lblVehicle = new System.Windows.Forms.Label();
            this.groupBox9 = new System.Windows.Forms.GroupBox();
            this.txtBilling = new System.Windows.Forms.TextBox();
            this.label17 = new System.Windows.Forms.Label();
            this.txtOther = new System.Windows.Forms.TextBox();
            this.label18 = new System.Windows.Forms.Label();
            this.label22 = new System.Windows.Forms.Label();
            this.txtConf = new System.Windows.Forms.TextBox();
            this.groupBox10 = new System.Windows.Forms.GroupBox();
            this.txtAmenTo = new System.Windows.Forms.TextBox();
            this.txtRef = new System.Windows.Forms.TextBox();
            this.label20 = new System.Windows.Forms.Label();
            this.label21 = new System.Windows.Forms.Label();
            this.groupBox8 = new System.Windows.Forms.GroupBox();
            this.toDate = new System.Windows.Forms.DateTimePicker();
            this.fromDate = new System.Windows.Forms.DateTimePicker();
            this.label12 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.noOfAdultsTxt = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.noOfChilderenTxt = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.cmbGuide = new  Tourist_Management.User_Controls.ComboBox();
            this.amountTxt = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.cmbVoucherType = new  Tourist_Management.User_Controls.ComboBox();
            this.btnShow = new System.Windows.Forms.Button();
            this.label36 = new System.Windows.Forms.Label();
            this.label37 = new System.Windows.Forms.Label();
            this.lblResposible = new System.Windows.Forms.Label();
            this.cmbDriver = new  Tourist_Management.User_Controls.ComboBox();
            this.txtClientName = new System.Windows.Forms.TextBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.rdbCancell = new System.Windows.Forms.RadioButton();
            this.rdbAmend = new System.Windows.Forms.RadioButton();
            this.rdbNormal = new System.Windows.Forms.RadioButton();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnAdd = new System.Windows.Forms.Button();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.btnTour = new System.Windows.Forms.Button();
            this.txtTourNo = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.tbVV = new System.Windows.Forms.TabPage();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.btnRetrieve = new System.Windows.Forms.Button();
            this.grdPayments = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.chkExSum = new System.Windows.Forms.CheckBox();
            this.btnEmail = new System.Windows.Forms.Button();
            this.groupBox16 = new System.Windows.Forms.GroupBox();
            this.richTextBox1 = new System.Windows.Forms.RichTextBox();
            this.groupBox15 = new System.Windows.Forms.GroupBox();
            this.button1 = new System.Windows.Forms.Button();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.label10 = new System.Windows.Forms.Label();
            this.button2 = new System.Windows.Forms.Button();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.textBox3 = new System.Windows.Forms.TextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.pbCompLogo = new System.Windows.Forms.PictureBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.label16 = new System.Windows.Forms.Label();
            this.vehicleTypeLbl = new System.Windows.Forms.Label();
            this.label25 = new System.Windows.Forms.Label();
            this.brandLbl = new System.Windows.Forms.Label();
            this.label24 = new System.Windows.Forms.Label();
            this.vehicleNoLbl = new System.Windows.Forms.Label();
            this.label27 = new System.Windows.Forms.Label();
            this.modelLbl = new System.Windows.Forms.Label();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.label3 = new System.Windows.Forms.Label();
            this.driverNameLbl = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.driverCodeLbl = new System.Windows.Forms.Label();
            this.btnPrint = new System.Windows.Forms.Button();
            this.btnClose = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.rtbBody = new System.Windows.Forms.RichTextBox();
            this.btnUpdateEmail = new System.Windows.Forms.Button();
            this.txtCC = new System.Windows.Forms.TextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.btnEmailConts = new System.Windows.Forms.Button();
            this.txtSubject = new System.Windows.Forms.TextBox();
            this.txtTo = new System.Windows.Forms.TextBox();
            this.label19 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.lblComplete = new System.Windows.Forms.Label();
            this.tcVoucher.SuspendLayout();
            this.tabAddV.SuspendLayout();
            this.groupBox12.SuspendLayout();
            this.groupBox11.SuspendLayout();
            this.groupBox9.SuspendLayout();
            this.groupBox10.SuspendLayout();
            this.groupBox8.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.tbVV.SuspendLayout();
            this.groupBox5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdPayments)).BeginInit();
            this.tabPage3.SuspendLayout();
            this.groupBox16.SuspendLayout();
            this.groupBox15.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbCompLogo)).BeginInit();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            this.tcVoucher.Controls.Add(this.tabAddV);
            this.tcVoucher.Controls.Add(this.tbVV);
            this.tcVoucher.Controls.Add(this.tabPage3);
            this.tcVoucher.Location = new System.Drawing.Point(6, 7);
            this.tcVoucher.Name = "tcVoucher";
            this.tcVoucher.SelectedIndex = 0;
            this.tcVoucher.Size = new System.Drawing.Size(629, 457);
            this.tcVoucher.TabIndex = 450;
            this.tabAddV.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tabAddV.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tabAddV.Controls.Add(this.groupBox12);
            this.tabAddV.Controls.Add(this.groupBox11);
            this.tabAddV.Controls.Add(this.groupBox9);
            this.tabAddV.Controls.Add(this.groupBox10);
            this.tabAddV.Controls.Add(this.groupBox8);
            this.tabAddV.Controls.Add(this.groupBox7);
            this.tabAddV.Controls.Add(this.groupBox6);
            this.tabAddV.Controls.Add(this.groupBox4);
            this.tabAddV.Controls.Add(this.btnCancel);
            this.tabAddV.Controls.Add(this.btnAdd);
            this.tabAddV.Controls.Add(this.groupBox1);
            this.tabAddV.Location = new System.Drawing.Point(4, 22);
            this.tabAddV.Name = "tabAddV";
            this.tabAddV.Padding = new System.Windows.Forms.Padding(3);
            this.tabAddV.Size = new System.Drawing.Size(621, 431);
            this.tabAddV.TabIndex = 0;
            this.tabAddV.Text = "Voucher Details";
            this.tabAddV.UseVisualStyleBackColor = true;
            this.groupBox12.BackColor = System.Drawing.Color.Transparent;
            this.groupBox12.Controls.Add(this.rdbGuide);
            this.groupBox12.Controls.Add(this.rdbDriver);
            this.groupBox12.Location = new System.Drawing.Point(244, 8);
            this.groupBox12.Name = "groupBox12";
            this.groupBox12.Size = new System.Drawing.Size(132, 43);
            this.groupBox12.TabIndex = 455;
            this.groupBox12.TabStop = false;
            this.groupBox12.Text = "Responsible";
            this.rdbGuide.AutoSize = true;
            this.rdbGuide.Location = new System.Drawing.Point(69, 19);
            this.rdbGuide.Name = "rdbGuide";
            this.rdbGuide.Size = new System.Drawing.Size(53, 17);
            this.rdbGuide.TabIndex = 2;
            this.rdbGuide.Text = "Guide";
            this.rdbGuide.UseVisualStyleBackColor = true;
            this.rdbGuide.CheckedChanged += new System.EventHandler(this.rdbGuide_CheckedChanged);
            this.rdbDriver.AutoSize = true;
            this.rdbDriver.Checked = true;
            this.rdbDriver.Location = new System.Drawing.Point(6, 19);
            this.rdbDriver.Name = "rdbDriver";
            this.rdbDriver.Size = new System.Drawing.Size(53, 17);
            this.rdbDriver.TabIndex = 1;
            this.rdbDriver.TabStop = true;
            this.rdbDriver.Text = "Driver";
            this.rdbDriver.UseVisualStyleBackColor = true;
            this.groupBox11.Controls.Add(this.txtNoOfVehicles);
            this.groupBox11.Controls.Add(this.lblVehicle);
            this.groupBox11.Location = new System.Drawing.Point(178, 132);
            this.groupBox11.Name = "groupBox11";
            this.groupBox11.Size = new System.Drawing.Size(162, 70);
            this.groupBox11.TabIndex = 488;
            this.groupBox11.TabStop = false;
            this.txtNoOfVehicles.Location = new System.Drawing.Point(7, 44);
            this.txtNoOfVehicles.Multiline = true;
            this.txtNoOfVehicles.Name = "txtNoOfVehicles";
            this.txtNoOfVehicles.Size = new System.Drawing.Size(149, 21);
            this.txtNoOfVehicles.TabIndex = 469;
            this.lblVehicle.AutoSize = true;
            this.lblVehicle.Location = new System.Drawing.Point(10, 17);
            this.lblVehicle.Name = "lblVehicle";
            this.lblVehicle.Size = new System.Drawing.Size(80, 13);
            this.lblVehicle.TabIndex = 470;
            this.lblVehicle.Text = "Vehicel Type";
            this.groupBox9.Controls.Add(this.txtBilling);
            this.groupBox9.Controls.Add(this.label17);
            this.groupBox9.Controls.Add(this.txtOther);
            this.groupBox9.Controls.Add(this.label18);
            this.groupBox9.Controls.Add(this.label22);
            this.groupBox9.Controls.Add(this.txtConf);
            this.groupBox9.Location = new System.Drawing.Point(10, 204);
            this.groupBox9.Name = "groupBox9";
            this.groupBox9.Size = new System.Drawing.Size(605, 123);
            this.groupBox9.TabIndex = 489;
            this.groupBox9.TabStop = false;
            this.txtBilling.Font = new System.Drawing.Font("Verdana", 7F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtBilling.Location = new System.Drawing.Point(117, 21);
            this.txtBilling.Multiline = true;
            this.txtBilling.Name = "txtBilling";
            this.txtBilling.Size = new System.Drawing.Size(480, 26);
            this.txtBilling.TabIndex = 473;
            this.txtBilling.Text = "All extras to be collected directly";
            this.label17.AutoSize = true;
            this.label17.Location = new System.Drawing.Point(9, 23);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(106, 13);
            this.label17.TabIndex = 474;
            this.label17.Text = "Billing Instruction";
            this.txtOther.Font = new System.Drawing.Font("Verdana", 7F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtOther.Location = new System.Drawing.Point(117, 51);
            this.txtOther.Multiline = true;
            this.txtOther.Name = "txtOther";
            this.txtOther.Size = new System.Drawing.Size(480, 26);
            this.txtOther.TabIndex = 478;
            this.label18.AutoSize = true;
            this.label18.Location = new System.Drawing.Point(9, 53);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(104, 13);
            this.label18.TabIndex = 479;
            this.label18.Text = "Other Instruction";
            this.label22.AutoSize = true;
            this.label22.Location = new System.Drawing.Point(9, 85);
            this.label22.Name = "label22";
            this.label22.Size = new System.Drawing.Size(81, 13);
            this.label22.TabIndex = 485;
            this.label22.Text = "Confirmation";
            this.txtConf.Font = new System.Drawing.Font("Verdana", 7F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtConf.Location = new System.Drawing.Point(117, 82);
            this.txtConf.Multiline = true;
            this.txtConf.Name = "txtConf";
            this.txtConf.Size = new System.Drawing.Size(480, 26);
            this.txtConf.TabIndex = 484;
            this.txtConf.Text = "Above arrangement is confirmed on the telephone by Kumara to Lakshan";
            this.groupBox10.Controls.Add(this.txtAmenTo);
            this.groupBox10.Controls.Add(this.txtRef);
            this.groupBox10.Controls.Add(this.label20);
            this.groupBox10.Controls.Add(this.label21);
            this.groupBox10.Location = new System.Drawing.Point(10, 328);
            this.groupBox10.Name = "groupBox10";
            this.groupBox10.Size = new System.Drawing.Size(521, 100);
            this.groupBox10.TabIndex = 489;
            this.groupBox10.TabStop = false;
            this.txtAmenTo.Enabled = false;
            this.txtAmenTo.Font = new System.Drawing.Font("Verdana", 7F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAmenTo.Location = new System.Drawing.Point(6, 38);
            this.txtAmenTo.Multiline = true;
            this.txtAmenTo.Name = "txtAmenTo";
            this.txtAmenTo.ReadOnly = true;
            this.txtAmenTo.Size = new System.Drawing.Size(119, 54);
            this.txtAmenTo.TabIndex = 482;
            this.txtAmenTo.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtRef.Font = new System.Drawing.Font("Verdana", 7F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtRef.Location = new System.Drawing.Point(132, 38);
            this.txtRef.Multiline = true;
            this.txtRef.Name = "txtRef";
            this.txtRef.Size = new System.Drawing.Size(380, 54);
            this.txtRef.TabIndex = 480;
            this.txtRef.Text = "Kindly send the confirmation along with the invoice in order to make the full pay" +
                "ment.";
            this.label20.AutoSize = true;
            this.label20.Location = new System.Drawing.Point(281, 17);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(65, 13);
            this.label20.TabIndex = 481;
            this.label20.Text = "Reference";
            this.label21.AutoSize = true;
            this.label21.Location = new System.Drawing.Point(29, 17);
            this.label21.Name = "label21";
            this.label21.Size = new System.Drawing.Size(65, 13);
            this.label21.TabIndex = 483;
            this.label21.Text = "Amend To";
            this.groupBox8.Controls.Add(this.toDate);
            this.groupBox8.Controls.Add(this.fromDate);
            this.groupBox8.Controls.Add(this.label12);
            this.groupBox8.Controls.Add(this.label13);
            this.groupBox8.Location = new System.Drawing.Point(349, 132);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new System.Drawing.Size(265, 67);
            this.groupBox8.TabIndex = 488;
            this.groupBox8.TabStop = false;
            this.toDate.Location = new System.Drawing.Point(47, 40);
            this.toDate.Name = "toDate";
            this.toDate.Size = new System.Drawing.Size(212, 21);
            this.toDate.TabIndex = 464;
            this.fromDate.Location = new System.Drawing.Point(47, 14);
            this.fromDate.Name = "fromDate";
            this.fromDate.Size = new System.Drawing.Size(212, 21);
            this.fromDate.TabIndex = 462;
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(9, 18);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(40, 13);
            this.label12.TabIndex = 463;
            this.label12.Text = "From ";
            this.label13.AutoSize = true;
            this.label13.Location = new System.Drawing.Point(9, 44);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(21, 13);
            this.label13.TabIndex = 465;
            this.label13.Text = "To";
            this.groupBox7.Controls.Add(this.noOfAdultsTxt);
            this.groupBox7.Controls.Add(this.label4);
            this.groupBox7.Controls.Add(this.noOfChilderenTxt);
            this.groupBox7.Controls.Add(this.label5);
            this.groupBox7.Location = new System.Drawing.Point(10, 132);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(162, 70);
            this.groupBox7.TabIndex = 487;
            this.groupBox7.TabStop = false;
            this.noOfAdultsTxt.Location = new System.Drawing.Point(68, 44);
            this.noOfAdultsTxt.Name = "noOfAdultsTxt";
            this.noOfAdultsTxt.Size = new System.Drawing.Size(83, 21);
            this.noOfAdultsTxt.TabIndex = 467;
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(9, 47);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(42, 13);
            this.label4.TabIndex = 468;
            this.label4.Text = "Adults";
            this.noOfChilderenTxt.Location = new System.Drawing.Point(68, 15);
            this.noOfChilderenTxt.Name = "noOfChilderenTxt";
            this.noOfChilderenTxt.Size = new System.Drawing.Size(83, 21);
            this.noOfChilderenTxt.TabIndex = 469;
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(7, 19);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(55, 13);
            this.label5.TabIndex = 470;
            this.label5.Text = "Children";
            this.groupBox6.Controls.Add(this.cmbGuide);
            this.groupBox6.Controls.Add(this.amountTxt);
            this.groupBox6.Controls.Add(this.label2);
            this.groupBox6.Controls.Add(this.cmbVoucherType);
            this.groupBox6.Controls.Add(this.btnShow);
            this.groupBox6.Controls.Add(this.label36);
            this.groupBox6.Controls.Add(this.label37);
            this.groupBox6.Controls.Add(this.lblResposible);
            this.groupBox6.Controls.Add(this.cmbDriver);
            this.groupBox6.Controls.Add(this.txtClientName);
            this.groupBox6.Location = new System.Drawing.Point(10, 54);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(608, 78);
            this.groupBox6.TabIndex = 486;
            this.groupBox6.TabStop = false;
            this.cmbGuide.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbGuide.FormattingEnabled = true;
            this.cmbGuide.Location = new System.Drawing.Point(454, 15);
            this.cmbGuide.Name = "cmbGuide";
            this.cmbGuide.Size = new System.Drawing.Size(111, 21);
            this.cmbGuide.TabIndex = 478;
            this.cmbGuide.Visible = false;
            this.amountTxt.Location = new System.Drawing.Point(383, 43);
            this.amountTxt.Name = "amountTxt";
            this.amountTxt.Size = new System.Drawing.Size(214, 21);
            this.amountTxt.TabIndex = 458;
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(9, 20);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(45, 14);
            this.label2.TabIndex = 455;
            this.label2.Text = "Guest";
            this.cmbVoucherType.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbVoucherType.Enabled = false;
            this.cmbVoucherType.FormattingEnabled = true;
            this.cmbVoucherType.Location = new System.Drawing.Point(68, 43);
            this.cmbVoucherType.Name = "cmbVoucherType";
            this.cmbVoucherType.Size = new System.Drawing.Size(225, 21);
            this.cmbVoucherType.TabIndex = 456;
            this.cmbVoucherType.SelectedIndexChanged += new System.EventHandler(this.cmbVoucherType_SelectedIndexChanged);
            this.btnShow.Enabled = false;
            this.btnShow.Font = new System.Drawing.Font("Wingdings 3", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(2)));
            this.btnShow.Location = new System.Drawing.Point(571, 15);
            this.btnShow.Name = "btnShow";
            this.btnShow.Size = new System.Drawing.Size(26, 23);
            this.btnShow.TabIndex = 256;
            this.btnShow.Text = "";
            this.btnShow.UseVisualStyleBackColor = true;
            this.btnShow.Click += new System.EventHandler(this.btnShow_Click);
            this.label36.AutoSize = true;
            this.label36.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label36.Location = new System.Drawing.Point(8, 45);
            this.label36.Name = "label36";
            this.label36.Size = new System.Drawing.Size(39, 14);
            this.label36.TabIndex = 457;
            this.label36.Text = "Type";
            this.label37.AutoSize = true;
            this.label37.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label37.Location = new System.Drawing.Point(323, 47);
            this.label37.Name = "label37";
            this.label37.Size = new System.Drawing.Size(57, 14);
            this.label37.TabIndex = 459;
            this.label37.Text = "Amount";
            this.lblResposible.AutoSize = true;
            this.lblResposible.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblResposible.Location = new System.Drawing.Point(323, 19);
            this.lblResposible.Name = "lblResposible";
            this.lblResposible.Size = new System.Drawing.Size(49, 14);
            this.lblResposible.TabIndex = 451;
            this.lblResposible.Text = "Driver";
            this.cmbDriver.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbDriver.FormattingEnabled = true;
            this.cmbDriver.Location = new System.Drawing.Point(383, 16);
            this.cmbDriver.Name = "cmbDriver";
            this.cmbDriver.Size = new System.Drawing.Size(182, 21);
            this.cmbDriver.TabIndex = 450;
            this.cmbDriver.SelectedIndexChanged += new System.EventHandler(this.changeDriverImg);
            this.txtClientName.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtClientName.Location = new System.Drawing.Point(67, 17);
            this.txtClientName.Name = "txtClientName";
            this.txtClientName.Size = new System.Drawing.Size(229, 18);
            this.txtClientName.TabIndex = 477;
            this.groupBox4.Controls.Add(this.rdbCancell);
            this.groupBox4.Controls.Add(this.rdbAmend);
            this.groupBox4.Controls.Add(this.rdbNormal);
            this.groupBox4.Location = new System.Drawing.Point(378, 8);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(238, 43);
            this.groupBox4.TabIndex = 475;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Invoice Type";
            this.rdbCancell.AutoSize = true;
            this.rdbCancell.Enabled = false;
            this.rdbCancell.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbCancell.ForeColor = System.Drawing.Color.Red;
            this.rdbCancell.Location = new System.Drawing.Point(170, 18);
            this.rdbCancell.Name = "rdbCancell";
            this.rdbCancell.Size = new System.Drawing.Size(68, 17);
            this.rdbCancell.TabIndex = 2;
            this.rdbCancell.Text = "Cancel";
            this.rdbCancell.UseVisualStyleBackColor = true;
            this.rdbAmend.AutoSize = true;
            this.rdbAmend.Enabled = false;
            this.rdbAmend.Location = new System.Drawing.Point(74, 18);
            this.rdbAmend.Name = "rdbAmend";
            this.rdbAmend.Size = new System.Drawing.Size(81, 17);
            this.rdbAmend.TabIndex = 1;
            this.rdbAmend.Text = "Amendment";
            this.rdbAmend.UseVisualStyleBackColor = true;
            this.rdbNormal.AutoSize = true;
            this.rdbNormal.Checked = true;
            this.rdbNormal.Location = new System.Drawing.Point(7, 18);
            this.rdbNormal.Name = "rdbNormal";
            this.rdbNormal.Size = new System.Drawing.Size(58, 17);
            this.rdbNormal.TabIndex = 0;
            this.rdbNormal.TabStop = true;
            this.rdbNormal.Text = "Normal";
            this.rdbNormal.UseVisualStyleBackColor = true;
            this.btnCancel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCancel.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Image = global::Tourist_Management.Properties.Resources.close;
            this.btnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.Location = new System.Drawing.Point(537, 383);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(75, 31);
            this.btnCancel.TabIndex = 472;
            this.btnCancel.Text = "&Cancel";
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click_1);
            this.btnAdd.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnAdd.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAdd.Image = global::Tourist_Management.Properties.Resources.add_16;
            this.btnAdd.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAdd.Location = new System.Drawing.Point(537, 346);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new System.Drawing.Size(75, 31);
            this.btnAdd.TabIndex = 471;
            this.btnAdd.Text = "&Add";
            this.btnAdd.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAdd.UseVisualStyleBackColor = true;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            this.groupBox1.BackColor = System.Drawing.Color.Transparent;
            this.groupBox1.Controls.Add(this.btnTour);
            this.groupBox1.Controls.Add(this.txtTourNo);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Location = new System.Drawing.Point(10, 8);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(230, 43);
            this.groupBox1.TabIndex = 454;
            this.groupBox1.TabStop = false;
            this.btnTour.Location = new System.Drawing.Point(193, 14);
            this.btnTour.Name = "btnTour";
            this.btnTour.Size = new System.Drawing.Size(30, 23);
            this.btnTour.TabIndex = 1;
            this.btnTour.Text = "...";
            this.btnTour.UseVisualStyleBackColor = true;
            this.btnTour.Click += new System.EventHandler(this.btnTour_Click);
            this.txtTourNo.Enabled = false;
            this.txtTourNo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTourNo.ForeColor = System.Drawing.Color.Blue;
            this.txtTourNo.Location = new System.Drawing.Point(63, 15);
            this.txtTourNo.Name = "txtTourNo";
            this.txtTourNo.ReadOnly = true;
            this.txtTourNo.Size = new System.Drawing.Size(124, 21);
            this.txtTourNo.TabIndex = 255;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(5, 19);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(55, 14);
            this.label1.TabIndex = 254;
            this.label1.Text = "Tour Id";
            this.tbVV.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tbVV.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tbVV.Controls.Add(this.groupBox5);
            this.tbVV.Controls.Add(this.grdPayments);
            this.tbVV.Location = new System.Drawing.Point(4, 22);
            this.tbVV.Name = "tbVV";
            this.tbVV.Padding = new System.Windows.Forms.Padding(3);
            this.tbVV.Size = new System.Drawing.Size(621, 431);
            this.tbVV.TabIndex = 1;
            this.tbVV.Text = "View Vouchers";
            this.tbVV.UseVisualStyleBackColor = true;
            this.groupBox5.Controls.Add(this.btnRetrieve);
            this.groupBox5.Location = new System.Drawing.Point(443, 369);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(175, 55);
            this.groupBox5.TabIndex = 8;
            this.groupBox5.TabStop = false;
            this.btnRetrieve.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnRetrieve.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRetrieve.Image = global::Tourist_Management.Properties.Resources.arrow_left_green_48;
            this.btnRetrieve.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRetrieve.Location = new System.Drawing.Point(6, 14);
            this.btnRetrieve.Name = "btnRetrieve";
            this.btnRetrieve.Size = new System.Drawing.Size(165, 35);
            this.btnRetrieve.TabIndex = 3;
            this.btnRetrieve.Text = "&Retrieve Selected";
            this.btnRetrieve.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRetrieve.UseVisualStyleBackColor = true;
            this.btnRetrieve.Click += new System.EventHandler(this.btnRetrieve_Click);
            this.grdPayments.AllowEditing = false;
            this.grdPayments.AutoResize = false;
            this.grdPayments.BackColor = System.Drawing.Color.White;
            this.grdPayments.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdPayments.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdPayments.Location = new System.Drawing.Point(4, 3);
            this.grdPayments.Name = "grdPayments";
            this.grdPayments.Size = new System.Drawing.Size(617, 365);
            this.grdPayments.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdPayments.Styles"));
            this.grdPayments.TabIndex = 7;
            this.tabPage3.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tabPage3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tabPage3.Controls.Add(this.chkExSum);
            this.tabPage3.Controls.Add(this.btnEmail);
            this.tabPage3.Controls.Add(this.groupBox16);
            this.tabPage3.Controls.Add(this.groupBox15);
            this.tabPage3.Location = new System.Drawing.Point(4, 22);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage3.Size = new System.Drawing.Size(621, 431);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "Email";
            this.tabPage3.UseVisualStyleBackColor = true;
            this.chkExSum.AutoSize = true;
            this.chkExSum.Checked = true;
            this.chkExSum.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkExSum.Location = new System.Drawing.Point(415, 350);
            this.chkExSum.Name = "chkExSum";
            this.chkExSum.Size = new System.Drawing.Size(108, 17);
            this.chkExSum.TabIndex = 251;
            this.chkExSum.Text = "Attach Invoice";
            this.chkExSum.UseVisualStyleBackColor = true;
            this.btnEmail.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnEmail.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEmail.Location = new System.Drawing.Point(526, 347);
            this.btnEmail.Name = "btnEmail";
            this.btnEmail.Size = new System.Drawing.Size(87, 22);
            this.btnEmail.TabIndex = 250;
            this.btnEmail.Text = "&Email This";
            this.btnEmail.UseVisualStyleBackColor = true;
            this.btnEmail.Click += new System.EventHandler(this.btnEmail_Click);
            this.groupBox16.BackColor = System.Drawing.Color.Transparent;
            this.groupBox16.Controls.Add(this.richTextBox1);
            this.groupBox16.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox16.Location = new System.Drawing.Point(23, 148);
            this.groupBox16.Name = "groupBox16";
            this.groupBox16.Size = new System.Drawing.Size(590, 165);
            this.groupBox16.TabIndex = 249;
            this.groupBox16.TabStop = false;
            this.groupBox16.Text = "Email Body";
            this.richTextBox1.AccessibleRole = System.Windows.Forms.AccessibleRole.None;
            this.richTextBox1.Location = new System.Drawing.Point(10, 25);
            this.richTextBox1.Name = "richTextBox1";
            this.richTextBox1.Size = new System.Drawing.Size(574, 134);
            this.richTextBox1.TabIndex = 0;
            this.richTextBox1.Text = "";
            this.groupBox15.BackColor = System.Drawing.Color.Transparent;
            this.groupBox15.Controls.Add(this.button1);
            this.groupBox15.Controls.Add(this.textBox1);
            this.groupBox15.Controls.Add(this.label10);
            this.groupBox15.Controls.Add(this.button2);
            this.groupBox15.Controls.Add(this.textBox2);
            this.groupBox15.Controls.Add(this.textBox3);
            this.groupBox15.Controls.Add(this.label11);
            this.groupBox15.Controls.Add(this.label14);
            this.groupBox15.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox15.Location = new System.Drawing.Point(23, 16);
            this.groupBox15.Name = "groupBox15";
            this.groupBox15.Size = new System.Drawing.Size(590, 115);
            this.groupBox15.TabIndex = 245;
            this.groupBox15.TabStop = false;
            this.groupBox15.Text = "General Details";
            this.button1.BackColor = System.Drawing.SystemColors.Control;
            this.button1.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.button1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.button1.Location = new System.Drawing.Point(687, 24);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(135, 23);
            this.button1.TabIndex = 10;
            this.button1.Text = "Update Agent Email";
            this.button1.UseVisualStyleBackColor = false;
            this.textBox1.Location = new System.Drawing.Point(68, 51);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(516, 21);
            this.textBox1.TabIndex = 9;
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(7, 54);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(25, 13);
            this.label10.TabIndex = 8;
            this.label10.Text = "CC";
            this.button2.BackColor = System.Drawing.SystemColors.Control;
            this.button2.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.button2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.button2.Location = new System.Drawing.Point(645, 24);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(33, 23);
            this.button2.TabIndex = 7;
            this.button2.Text = "...";
            this.button2.UseVisualStyleBackColor = false;
            this.textBox2.Location = new System.Drawing.Point(68, 77);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new System.Drawing.Size(516, 21);
            this.textBox2.TabIndex = 5;
            this.textBox3.Location = new System.Drawing.Point(68, 24);
            this.textBox3.Name = "textBox3";
            this.textBox3.Size = new System.Drawing.Size(516, 21);
            this.textBox3.TabIndex = 4;
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(7, 80);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(50, 13);
            this.label11.TabIndex = 2;
            this.label11.Text = "Subject";
            this.label14.AutoSize = true;
            this.label14.Location = new System.Drawing.Point(7, 27);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(21, 13);
            this.label14.TabIndex = 1;
            this.label14.Text = "To";
            this.pbCompLogo.BackColor = System.Drawing.Color.Transparent;
            this.pbCompLogo.Image = global::Tourist_Management.Properties.Resources.noimage;
            this.pbCompLogo.Location = new System.Drawing.Point(709, 29);
            this.pbCompLogo.Name = "pbCompLogo";
            this.pbCompLogo.Size = new System.Drawing.Size(110, 101);
            this.pbCompLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbCompLogo.TabIndex = 433;
            this.pbCompLogo.TabStop = false;
            this.groupBox3.BackColor = System.Drawing.Color.Transparent;
            this.groupBox3.Controls.Add(this.label16);
            this.groupBox3.Controls.Add(this.vehicleTypeLbl);
            this.groupBox3.Controls.Add(this.label25);
            this.groupBox3.Controls.Add(this.brandLbl);
            this.groupBox3.Controls.Add(this.label24);
            this.groupBox3.Controls.Add(this.vehicleNoLbl);
            this.groupBox3.Controls.Add(this.label27);
            this.groupBox3.Controls.Add(this.modelLbl);
            this.groupBox3.Location = new System.Drawing.Point(642, 222);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(254, 130);
            this.groupBox3.TabIndex = 461;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Vehicle Details";
            this.label16.AutoSize = true;
            this.label16.Location = new System.Drawing.Point(12, 50);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(67, 13);
            this.label16.TabIndex = 434;
            this.label16.Text = "Vehicle No";
            this.vehicleTypeLbl.AutoSize = true;
            this.vehicleTypeLbl.Location = new System.Drawing.Point(110, 29);
            this.vehicleTypeLbl.Name = "vehicleTypeLbl";
            this.vehicleTypeLbl.Size = new System.Drawing.Size(12, 13);
            this.vehicleTypeLbl.TabIndex = 429;
            this.vehicleTypeLbl.Text = "-";
            this.label25.AutoSize = true;
            this.label25.Location = new System.Drawing.Point(12, 99);
            this.label25.Name = "label25";
            this.label25.Size = new System.Drawing.Size(40, 13);
            this.label25.TabIndex = 437;
            this.label25.Text = "Model";
            this.brandLbl.AutoSize = true;
            this.brandLbl.Location = new System.Drawing.Point(110, 77);
            this.brandLbl.Name = "brandLbl";
            this.brandLbl.Size = new System.Drawing.Size(12, 13);
            this.brandLbl.TabIndex = 430;
            this.brandLbl.Text = "-";
            this.label24.AutoSize = true;
            this.label24.BackColor = System.Drawing.Color.Transparent;
            this.label24.Location = new System.Drawing.Point(12, 27);
            this.label24.Name = "label24";
            this.label24.Size = new System.Drawing.Size(35, 13);
            this.label24.TabIndex = 435;
            this.label24.Text = "Type";
            this.vehicleNoLbl.AutoSize = true;
            this.vehicleNoLbl.Location = new System.Drawing.Point(110, 52);
            this.vehicleNoLbl.Name = "vehicleNoLbl";
            this.vehicleNoLbl.Size = new System.Drawing.Size(12, 13);
            this.vehicleNoLbl.TabIndex = 431;
            this.vehicleNoLbl.Text = "-";
            this.label27.AutoSize = true;
            this.label27.Location = new System.Drawing.Point(12, 75);
            this.label27.Name = "label27";
            this.label27.Size = new System.Drawing.Size(41, 13);
            this.label27.TabIndex = 436;
            this.label27.Text = "Brand";
            this.modelLbl.AutoSize = true;
            this.modelLbl.Location = new System.Drawing.Point(110, 101);
            this.modelLbl.Name = "modelLbl";
            this.modelLbl.Size = new System.Drawing.Size(12, 13);
            this.modelLbl.TabIndex = 432;
            this.modelLbl.Text = "-";
            this.groupBox2.BackColor = System.Drawing.Color.Transparent;
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Controls.Add(this.driverNameLbl);
            this.groupBox2.Controls.Add(this.label6);
            this.groupBox2.Controls.Add(this.driverCodeLbl);
            this.groupBox2.Location = new System.Drawing.Point(642, 136);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(254, 74);
            this.groupBox2.TabIndex = 460;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Driver Details";
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(12, 26);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(80, 13);
            this.label3.TabIndex = 425;
            this.label3.Text = "Driver Name";
            this.driverNameLbl.AutoSize = true;
            this.driverNameLbl.Location = new System.Drawing.Point(110, 26);
            this.driverNameLbl.Name = "driverNameLbl";
            this.driverNameLbl.Size = new System.Drawing.Size(12, 13);
            this.driverNameLbl.TabIndex = 426;
            this.driverNameLbl.Text = "-";
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(12, 52);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(77, 13);
            this.label6.TabIndex = 427;
            this.label6.Text = "Driver Code";
            this.driverCodeLbl.AutoSize = true;
            this.driverCodeLbl.Location = new System.Drawing.Point(110, 52);
            this.driverCodeLbl.Name = "driverCodeLbl";
            this.driverCodeLbl.Size = new System.Drawing.Size(12, 13);
            this.driverCodeLbl.TabIndex = 428;
            this.driverCodeLbl.Text = "-";
            this.btnPrint.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPrint.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPrint.Image = global::Tourist_Management.Properties.Resources.search;
            this.btnPrint.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPrint.Location = new System.Drawing.Point(360, 471);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.Size = new System.Drawing.Size(89, 29);
            this.btnPrint.TabIndex = 471;
            this.btnPrint.Text = "&Preview";
            this.btnPrint.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPrint.UseVisualStyleBackColor = true;
            this.btnPrint.Click += new System.EventHandler(this.btnPrint_Click);
            this.btnClose.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnClose.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClose.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnClose.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.Location = new System.Drawing.Point(538, 470);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new System.Drawing.Size(84, 30);
            this.btnClose.TabIndex = 453;
            this.btnClose.Text = "&Close";
            this.btnClose.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose.UseVisualStyleBackColor = true;
            this.btnClose.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnOk.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnOk.Enabled = false;
            this.btnOk.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Image = global::Tourist_Management.Properties.Resources.floppy;
            this.btnOk.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOk.Location = new System.Drawing.Point(452, 470);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(84, 30);
            this.btnOk.TabIndex = 452;
            this.btnOk.Text = "&Save";
            this.btnOk.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.rtbBody.AccessibleRole = System.Windows.Forms.AccessibleRole.None;
            this.rtbBody.Location = new System.Drawing.Point(10, 25);
            this.rtbBody.Name = "rtbBody";
            this.rtbBody.Size = new System.Drawing.Size(608, 110);
            this.rtbBody.TabIndex = 0;
            this.rtbBody.Text = "";
            this.btnUpdateEmail.BackColor = System.Drawing.SystemColors.Control;
            this.btnUpdateEmail.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.btnUpdateEmail.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnUpdateEmail.Location = new System.Drawing.Point(482, 22);
            this.btnUpdateEmail.Name = "btnUpdateEmail";
            this.btnUpdateEmail.Size = new System.Drawing.Size(135, 23);
            this.btnUpdateEmail.TabIndex = 10;
            this.btnUpdateEmail.Text = "Update Agent Email";
            this.btnUpdateEmail.UseVisualStyleBackColor = false;
            this.txtCC.Location = new System.Drawing.Point(68, 51);
            this.txtCC.Name = "txtCC";
            this.txtCC.Size = new System.Drawing.Size(549, 20);
            this.txtCC.TabIndex = 9;
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(7, 54);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(25, 13);
            this.label9.TabIndex = 8;
            this.label9.Text = "CC";
            this.btnEmailConts.BackColor = System.Drawing.SystemColors.Control;
            this.btnEmailConts.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.btnEmailConts.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnEmailConts.Location = new System.Drawing.Point(443, 22);
            this.btnEmailConts.Name = "btnEmailConts";
            this.btnEmailConts.Size = new System.Drawing.Size(33, 23);
            this.btnEmailConts.TabIndex = 7;
            this.btnEmailConts.Text = "...";
            this.btnEmailConts.UseVisualStyleBackColor = false;
            this.txtSubject.Location = new System.Drawing.Point(68, 77);
            this.txtSubject.Name = "txtSubject";
            this.txtSubject.Size = new System.Drawing.Size(549, 20);
            this.txtSubject.TabIndex = 5;
            this.txtTo.Location = new System.Drawing.Point(68, 24);
            this.txtTo.Name = "txtTo";
            this.txtTo.Size = new System.Drawing.Size(369, 20);
            this.txtTo.TabIndex = 4;
            this.label19.AutoSize = true;
            this.label19.Location = new System.Drawing.Point(7, 80);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(50, 13);
            this.label19.TabIndex = 2;
            this.label19.Text = "Subject";
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(7, 27);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(21, 13);
            this.label7.TabIndex = 1;
            this.label7.Text = "To";
            this.lblComplete.AutoSize = true;
            this.lblComplete.BackColor = System.Drawing.Color.Transparent;
            this.lblComplete.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblComplete.ForeColor = System.Drawing.Color.Green;
            this.lblComplete.Location = new System.Drawing.Point(8, 475);
            this.lblComplete.Name = "lblComplete";
            this.lblComplete.Size = new System.Drawing.Size(164, 18);
            this.lblComplete.TabIndex = 472;
            this.lblComplete.Text = "Tour is completed";
            this.lblComplete.Visible = false;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(642, 507);
            this.ControlBox = false;
            this.Controls.Add(this.lblComplete);
            this.Controls.Add(this.pbCompLogo);
            this.Controls.Add(this.btnPrint);
            this.Controls.Add(this.tcVoucher);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox3);
            this.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.Name = "frmVoucherType";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmVoucherType_Load);
            this.tcVoucher.ResumeLayout(false);
            this.tabAddV.ResumeLayout(false);
            this.groupBox12.ResumeLayout(false);
            this.groupBox12.PerformLayout();
            this.groupBox11.ResumeLayout(false);
            this.groupBox11.PerformLayout();
            this.groupBox9.ResumeLayout(false);
            this.groupBox9.PerformLayout();
            this.groupBox10.ResumeLayout(false);
            this.groupBox10.PerformLayout();
            this.groupBox8.ResumeLayout(false);
            this.groupBox8.PerformLayout();
            this.groupBox7.ResumeLayout(false);
            this.groupBox7.PerformLayout();
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.tbVV.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdPayments)).EndInit();
            this.tabPage3.ResumeLayout(false);
            this.tabPage3.PerformLayout();
            this.groupBox16.ResumeLayout(false);
            this.groupBox15.ResumeLayout(false);
            this.groupBox15.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbCompLogo)).EndInit();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.TabControl tcVoucher;
        private System.Windows.Forms.TabPage tabAddV;
        private System.Windows.Forms.Button btnPrint;
        private  Tourist_Management.User_Controls.ComboBox cmbDriver;
        private System.Windows.Forms.Label lblResposible;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.DateTimePicker toDate;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.DateTimePicker fromDate;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label vehicleTypeLbl;
        private System.Windows.Forms.Label label25;
        private System.Windows.Forms.Label brandLbl;
        private System.Windows.Forms.Label label24;
        private System.Windows.Forms.Label vehicleNoLbl;
        private System.Windows.Forms.Label label27;
        private System.Windows.Forms.Label modelLbl;
        private System.Windows.Forms.Label label37;
        private System.Windows.Forms.TextBox amountTxt;
        private System.Windows.Forms.Label label36;
        private  Tourist_Management.User_Controls.ComboBox cmbVoucherType;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Button btnTour;
        private System.Windows.Forms.TextBox txtTourNo;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.PictureBox pbCompLogo;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label driverNameLbl;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label driverCodeLbl;
        private System.Windows.Forms.TabPage tbVV;
        private C1.Win.C1FlexGrid.C1FlexGrid grdPayments;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.Button btnRetrieve;
        private System.Windows.Forms.RichTextBox rtbBody;
        private System.Windows.Forms.Button btnUpdateEmail;
        private System.Windows.Forms.TextBox txtCC;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Button btnEmailConts;
        private System.Windows.Forms.TextBox txtSubject;
        private System.Windows.Forms.TextBox txtTo;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.GroupBox groupBox15;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.TextBox textBox3;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.CheckBox chkExSum;
        private System.Windows.Forms.Button btnEmail;
        private System.Windows.Forms.GroupBox groupBox16;
        private System.Windows.Forms.RichTextBox richTextBox1;
        private System.Windows.Forms.Button btnAdd;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.TextBox txtBilling;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.RadioButton rdbAmend;
        private System.Windows.Forms.RadioButton rdbNormal;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox noOfChilderenTxt;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox noOfAdultsTxt;
        private System.Windows.Forms.TextBox txtClientName;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.TextBox txtOther;
        private System.Windows.Forms.Label label21;
        private System.Windows.Forms.TextBox txtAmenTo;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.TextBox txtRef;
        private System.Windows.Forms.Button btnShow;
        private System.Windows.Forms.Label label22;
        private System.Windows.Forms.TextBox txtConf;
        private System.Windows.Forms.GroupBox groupBox6;
        private System.Windows.Forms.GroupBox groupBox7;
        private System.Windows.Forms.GroupBox groupBox8;
        private System.Windows.Forms.GroupBox groupBox9;
        private System.Windows.Forms.GroupBox groupBox10;
        private System.Windows.Forms.RadioButton rdbCancell;
        private System.Windows.Forms.GroupBox groupBox11;
        private System.Windows.Forms.TextBox txtNoOfVehicles;
        private System.Windows.Forms.Label lblVehicle;
        private System.Windows.Forms.GroupBox groupBox12;
        private System.Windows.Forms.RadioButton rdbDriver;
        private System.Windows.Forms.RadioButton rdbGuide;
        private  Tourist_Management.User_Controls.ComboBox cmbGuide;
        private System.Windows.Forms.Label lblComplete;
    }
}