namespace Tourist_Management.Reports
{
    partial class frmFuelMeter
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmFuelMeter));
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.chkDefault = new System.Windows.Forms.CheckBox();
            this.txtFuelRate = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.grdFM = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.rdbAnnual = new System.Windows.Forms.RadioButton();
            this.rdbMonthly = new System.Windows.Forms.RadioButton();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.rdbAll = new System.Windows.Forms.RadioButton();
            this.rdbSelected = new System.Windows.Forms.RadioButton();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.drpDriver = new Tourist_Management.DropDowns.DropSearch();
            this.label36 = new System.Windows.Forms.Label();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.dtpIToDate = new System.Windows.Forms.DateTimePicker();
            this.label33 = new System.Windows.Forms.Label();
            this.dtpIFromDate = new System.Windows.Forms.DateTimePicker();
            this.label37 = new System.Windows.Forms.Label();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnPreview = new System.Windows.Forms.Button();
            this.groupBox1.SuspendLayout();
            this.groupBox5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdFM)).BeginInit();
            this.groupBox4.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.SuspendLayout();
            this.groupBox1.BackColor = System.Drawing.Color.Transparent;
            this.groupBox1.Controls.Add(this.groupBox5);
            this.groupBox1.Controls.Add(this.grdFM);
            this.groupBox1.Controls.Add(this.groupBox4);
            this.groupBox1.Controls.Add(this.groupBox3);
            this.groupBox1.Controls.Add(this.groupBox2);
            this.groupBox1.Controls.Add(this.groupBox7);
            this.groupBox1.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.Location = new System.Drawing.Point(12, 12);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(956, 366);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox5.Controls.Add(this.chkDefault);
            this.groupBox5.Controls.Add(this.txtFuelRate);
            this.groupBox5.Controls.Add(this.label1);
            this.groupBox5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.groupBox5.Location = new System.Drawing.Point(6, 59);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(343, 51);
            this.groupBox5.TabIndex = 361;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "FUEL RATE";
            this.chkDefault.AutoSize = true;
            this.chkDefault.Checked = true;
            this.chkDefault.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkDefault.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkDefault.ForeColor = System.Drawing.SystemColors.ControlText;
            this.chkDefault.Location = new System.Drawing.Point(225, 23);
            this.chkDefault.Name = "chkDefault";
            this.chkDefault.Size = new System.Drawing.Size(108, 17);
            this.chkDefault.TabIndex = 248;
            this.chkDefault.Text = "Set As Default";
            this.chkDefault.UseVisualStyleBackColor = true;
            this.txtFuelRate.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFuelRate.Location = new System.Drawing.Point(83, 21);
            this.txtFuelRate.Name = "txtFuelRate";
            this.txtFuelRate.Size = new System.Drawing.Size(124, 21);
            this.txtFuelRate.TabIndex = 247;
            this.txtFuelRate.TextChanged += new System.EventHandler(this.txtFuelRate_TextChanged);
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.label1.Location = new System.Drawing.Point(8, 25);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(69, 13);
            this.label1.TabIndex = 246;
            this.label1.Text = "Rate (LKR)";
            this.grdFM.BackColor = System.Drawing.Color.Transparent;
            this.grdFM.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.grdFM.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.grdFM.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdFM.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdFM.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grdFM.Location = new System.Drawing.Point(17, 115);
            this.grdFM.Name = "grdFM";
            this.grdFM.Size = new System.Drawing.Size(926, 241);
            this.grdFM.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdFM.Styles"));
            this.grdFM.TabIndex = 360;
            this.groupBox4.Controls.Add(this.rdbAnnual);
            this.groupBox4.Controls.Add(this.rdbMonthly);
            this.groupBox4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.groupBox4.Location = new System.Drawing.Point(790, 9);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(160, 51);
            this.groupBox4.TabIndex = 358;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "TYPE";
            this.rdbAnnual.AutoSize = true;
            this.rdbAnnual.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbAnnual.ForeColor = System.Drawing.SystemColors.ControlText;
            this.rdbAnnual.Location = new System.Drawing.Point(89, 21);
            this.rdbAnnual.Name = "rdbAnnual";
            this.rdbAnnual.Size = new System.Drawing.Size(64, 17);
            this.rdbAnnual.TabIndex = 1;
            this.rdbAnnual.Text = "Annual";
            this.rdbAnnual.UseVisualStyleBackColor = true;
            this.rdbAnnual.CheckedChanged += new System.EventHandler(this.rdbAnnual_CheckedChanged);
            this.rdbMonthly.AutoSize = true;
            this.rdbMonthly.Checked = true;
            this.rdbMonthly.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbMonthly.ForeColor = System.Drawing.SystemColors.ControlText;
            this.rdbMonthly.Location = new System.Drawing.Point(13, 21);
            this.rdbMonthly.Name = "rdbMonthly";
            this.rdbMonthly.Size = new System.Drawing.Size(69, 17);
            this.rdbMonthly.TabIndex = 0;
            this.rdbMonthly.TabStop = true;
            this.rdbMonthly.Text = "Monthly";
            this.rdbMonthly.UseVisualStyleBackColor = true;
            this.rdbMonthly.CheckedChanged += new System.EventHandler(this.rdbMonthly_CheckedChanged);
            this.groupBox3.Controls.Add(this.rdbAll);
            this.groupBox3.Controls.Add(this.rdbSelected);
            this.groupBox3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.groupBox3.Location = new System.Drawing.Point(426, 9);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(143, 51);
            this.groupBox3.TabIndex = 357;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "TYPE";
            this.rdbAll.AutoSize = true;
            this.rdbAll.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbAll.ForeColor = System.Drawing.SystemColors.ControlText;
            this.rdbAll.Location = new System.Drawing.Point(95, 21);
            this.rdbAll.Name = "rdbAll";
            this.rdbAll.Size = new System.Drawing.Size(39, 17);
            this.rdbAll.TabIndex = 1;
            this.rdbAll.Text = "All";
            this.rdbAll.UseVisualStyleBackColor = true;
            this.rdbAll.CheckedChanged += new System.EventHandler(this.rdbAll_CheckedChanged);
            this.rdbSelected.AutoSize = true;
            this.rdbSelected.Checked = true;
            this.rdbSelected.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbSelected.ForeColor = System.Drawing.SystemColors.ControlText;
            this.rdbSelected.Location = new System.Drawing.Point(15, 21);
            this.rdbSelected.Name = "rdbSelected";
            this.rdbSelected.Size = new System.Drawing.Size(74, 17);
            this.rdbSelected.TabIndex = 0;
            this.rdbSelected.TabStop = true;
            this.rdbSelected.Text = "Selected";
            this.rdbSelected.UseVisualStyleBackColor = true;
            this.rdbSelected.CheckedChanged += new System.EventHandler(this.rdbSelected_CheckedChanged);
            this.groupBox2.BackColor = System.Drawing.Color.Transparent;
            this.groupBox2.Controls.Add(this.drpDriver);
            this.groupBox2.Controls.Add(this.label36);
            this.groupBox2.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.groupBox2.Location = new System.Drawing.Point(575, 9);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(209, 51);
            this.groupBox2.TabIndex = 356;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "BY DRIVER";
            this.drpDriver.BackColor = System.Drawing.Color.Transparent;
            this.drpDriver.DataSource = null;
            this.drpDriver.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpDriver.Location = new System.Drawing.Point(48, 18);
            this.drpDriver.Name = "drpDriver";
            this.drpDriver.SelectedText = "";
            this.drpDriver.SelectedValue = "";
            this.drpDriver.Size = new System.Drawing.Size(155, 21);
            this.drpDriver.TabIndex = 380;
            this.drpDriver.Selected_TextChanged += new System.EventHandler(this.drpDriver_Selected_TextChanged);
            this.label36.AutoSize = true;
            this.label36.BackColor = System.Drawing.Color.Transparent;
            this.label36.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label36.ForeColor = System.Drawing.Color.Black;
            this.label36.Location = new System.Drawing.Point(7, 22);
            this.label36.Name = "label36";
            this.label36.Size = new System.Drawing.Size(43, 13);
            this.label36.TabIndex = 379;
            this.label36.Text = "Driver";
            this.groupBox7.BackColor = System.Drawing.Color.Transparent;
            this.groupBox7.Controls.Add(this.dtpIToDate);
            this.groupBox7.Controls.Add(this.label33);
            this.groupBox7.Controls.Add(this.dtpIFromDate);
            this.groupBox7.Controls.Add(this.label37);
            this.groupBox7.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.groupBox7.Location = new System.Drawing.Point(6, 9);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(413, 51);
            this.groupBox7.TabIndex = 355;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "BY DATE";
            this.dtpIToDate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpIToDate.Location = new System.Drawing.Point(275, 20);
            this.dtpIToDate.Name = "dtpIToDate";
            this.dtpIToDate.Size = new System.Drawing.Size(132, 20);
            this.dtpIToDate.TabIndex = 249;
            this.dtpIToDate.ValueChanged += new System.EventHandler(this.dtpIToDate_ValueChanged);
            this.label33.AutoSize = true;
            this.label33.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label33.ForeColor = System.Drawing.SystemColors.ControlText;
            this.label33.Location = new System.Drawing.Point(218, 23);
            this.label33.Name = "label33";
            this.label33.Size = new System.Drawing.Size(52, 13);
            this.label33.TabIndex = 248;
            this.label33.Text = "Date To";
            this.dtpIFromDate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpIFromDate.Location = new System.Drawing.Point(76, 20);
            this.dtpIFromDate.Name = "dtpIFromDate";
            this.dtpIFromDate.Size = new System.Drawing.Size(131, 20);
            this.dtpIFromDate.TabIndex = 247;
            this.dtpIFromDate.ValueChanged += new System.EventHandler(this.dtpIFromDate_ValueChanged);
            this.label37.AutoSize = true;
            this.label37.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label37.ForeColor = System.Drawing.SystemColors.ControlText;
            this.label37.Location = new System.Drawing.Point(8, 23);
            this.label37.Name = "label37";
            this.label37.Size = new System.Drawing.Size(67, 13);
            this.label37.TabIndex = 246;
            this.label37.Text = "Date From";
            this.btnCancel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCancel.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.Location = new System.Drawing.Point(893, 384);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(72, 30);
            this.btnCancel.TabIndex = 6;
            this.btnCancel.Text = "&Cancel";
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnPreview.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPreview.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPreview.Image = global::Tourist_Management.Properties.Resources.search;
            this.btnPreview.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPreview.Location = new System.Drawing.Point(815, 384);
            this.btnPreview.Name = "btnPreview";
            this.btnPreview.Size = new System.Drawing.Size(72, 30);
            this.btnPreview.TabIndex = 5;
            this.btnPreview.Text = "&Preview";
            this.btnPreview.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPreview.UseVisualStyleBackColor = true;
            this.btnPreview.Click += new System.EventHandler(this.btnPreview_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(980, 422);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnPreview);
            this.Controls.Add(this.groupBox1);
            this.Name = "frmFuelMeter";
            this.Text = "frmFuelMeter";
            this.Load += new System.EventHandler(this.frmFuelMeter_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdFM)).EndInit();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox7.ResumeLayout(false);
            this.groupBox7.PerformLayout();
            this.ResumeLayout(false);
        }
        #endregion
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox groupBox7;
        private System.Windows.Forms.DateTimePicker dtpIToDate;
        private System.Windows.Forms.Label label33;
        private System.Windows.Forms.DateTimePicker dtpIFromDate;
        private System.Windows.Forms.Label label37;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label label36;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.RadioButton rdbSelected;
        private System.Windows.Forms.RadioButton rdbAll;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.RadioButton rdbAnnual;
        private System.Windows.Forms.RadioButton rdbMonthly;
        private C1.Win.C1FlexGrid.C1FlexGrid grdFM;
        private DropDowns.DropSearch drpDriver;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnPreview;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.CheckBox chkDefault;
        private System.Windows.Forms.TextBox txtFuelRate;
        private System.Windows.Forms.Label label1;
    }
}