namespace Tourist_Management.Reports
{
    partial class frmGeneralReports
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            this.label1 = new System.Windows.Forms.Label();
            this.drpDriver = new Tourist_Management.DropDowns.DropSearch();
            this.btnPreview = new System.Windows.Forms.Button();
            this.button1 = new System.Windows.Forms.Button();
            this.label2 = new System.Windows.Forms.Label();
            this.cmbFilter = new  Tourist_Management.User_Controls.ComboBox();
            this.txtFilter = new System.Windows.Forms.TextBox();
            this.grdReport = new System.Windows.Forms.DataGridView();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.grpFilterByDate = new System.Windows.Forms.GroupBox();
            this.dtpDate2 = new System.Windows.Forms.DateTimePicker();
            this.dtpDate1 = new System.Windows.Forms.DateTimePicker();
            this.lblDateCol1 = new System.Windows.Forms.Label();
            this.lblDateCol2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.btnCancel = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.grdReport)).BeginInit();
            this.groupBox1.SuspendLayout();
            this.grpFilterByDate.SuspendLayout();
            this.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(41, 46);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(84, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "Select Report";
            this.drpDriver.BackColor = System.Drawing.Color.Transparent;
            this.drpDriver.DataSource = null;
            this.drpDriver.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpDriver.Location = new System.Drawing.Point(145, 41);
            this.drpDriver.Name = "drpDriver";
            this.drpDriver.SelectedText = "";
            this.drpDriver.SelectedValue = "";
            this.drpDriver.Size = new System.Drawing.Size(416, 20);
            this.drpDriver.TabIndex = 364;
            this.btnPreview.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPreview.Image = global::Tourist_Management.Properties.Resources.search;
            this.btnPreview.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPreview.Location = new System.Drawing.Point(710, 535);
            this.btnPreview.Name = "btnPreview";
            this.btnPreview.Size = new System.Drawing.Size(75, 30);
            this.btnPreview.TabIndex = 365;
            this.btnPreview.Text = "Preview";
            this.btnPreview.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPreview.UseVisualStyleBackColor = true;
            this.btnPreview.Click += new System.EventHandler(this.btnPreview_Click);
            this.button1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.button1.Image = global::Tourist_Management.Properties.Resources.floppy;
            this.button1.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button1.Location = new System.Drawing.Point(808, 535);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(75, 30);
            this.button1.TabIndex = 366;
            this.button1.Text = "Export";
            this.button1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.label2.Location = new System.Drawing.Point(41, 79);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(54, 13);
            this.label2.TabIndex = 367;
            this.label2.Text = "Filter By";
            this.cmbFilter.FormattingEnabled = true;
            this.cmbFilter.Location = new System.Drawing.Point(145, 71);
            this.cmbFilter.Name = "cmbFilter";
            this.cmbFilter.Size = new System.Drawing.Size(165, 21);
            this.cmbFilter.TabIndex = 368;
            this.cmbFilter.SelectedIndexChanged += new System.EventHandler(this.cmbFilter_SelectedIndexChanged);
            this.txtFilter.Location = new System.Drawing.Point(133, 91);
            this.txtFilter.Name = "txtFilter";
            this.txtFilter.Size = new System.Drawing.Size(165, 22);
            this.txtFilter.TabIndex = 369;
            this.txtFilter.TextChanged += new System.EventHandler(this.txtFilter_TextChanged);
            this.grdReport.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.grdReport.Location = new System.Drawing.Point(32, 130);
            this.grdReport.Name = "grdReport";
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.DarkCyan;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.grdReport.RowHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.grdReport.Size = new System.Drawing.Size(905, 370);
            this.grdReport.TabIndex = 370;
            this.groupBox1.BackColor = System.Drawing.Color.Transparent;
            this.groupBox1.Controls.Add(this.grpFilterByDate);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.grdReport);
            this.groupBox1.Controls.Add(this.txtFilter);
            this.groupBox1.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.groupBox1.Location = new System.Drawing.Point(12, 12);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(978, 517);
            this.groupBox1.TabIndex = 371;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "EXCEL REPORTS";
            this.grpFilterByDate.Controls.Add(this.dtpDate2);
            this.grpFilterByDate.Controls.Add(this.dtpDate1);
            this.grpFilterByDate.Controls.Add(this.lblDateCol1);
            this.grpFilterByDate.Controls.Add(this.lblDateCol2);
            this.grpFilterByDate.Controls.Add(this.label3);
            this.grpFilterByDate.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.grpFilterByDate.Location = new System.Drawing.Point(392, 58);
            this.grpFilterByDate.Name = "grpFilterByDate";
            this.grpFilterByDate.Size = new System.Drawing.Size(545, 55);
            this.grpFilterByDate.TabIndex = 371;
            this.grpFilterByDate.TabStop = false;
            this.grpFilterByDate.Text = "FILTER BY DATE";
            this.grpFilterByDate.Visible = false;
            this.dtpDate2.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpDate2.Location = new System.Drawing.Point(352, 21);
            this.dtpDate2.Name = "dtpDate2";
            this.dtpDate2.Size = new System.Drawing.Size(140, 21);
            this.dtpDate2.TabIndex = 368;
            this.dtpDate2.ValueChanged += new System.EventHandler(this.dtpDate2_ValueChanged);
            this.dtpDate1.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpDate1.Location = new System.Drawing.Point(93, 21);
            this.dtpDate1.Name = "dtpDate1";
            this.dtpDate1.Size = new System.Drawing.Size(140, 21);
            this.dtpDate1.TabIndex = 0;
            this.dtpDate1.ValueChanged += new System.EventHandler(this.dtpDate1_ValueChanged);
            this.lblDateCol1.AutoSize = true;
            this.lblDateCol1.BackColor = System.Drawing.Color.Transparent;
            this.lblDateCol1.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.lblDateCol1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lblDateCol1.Location = new System.Drawing.Point(23, 27);
            this.lblDateCol1.Name = "lblDateCol1";
            this.lblDateCol1.Size = new System.Drawing.Size(60, 13);
            this.lblDateCol1.TabIndex = 367;
            this.lblDateCol1.Text = "DateCol1";
            this.lblDateCol2.AutoSize = true;
            this.lblDateCol2.BackColor = System.Drawing.Color.Transparent;
            this.lblDateCol2.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.lblDateCol2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lblDateCol2.Location = new System.Drawing.Point(281, 27);
            this.lblDateCol2.Name = "lblDateCol2";
            this.lblDateCol2.Size = new System.Drawing.Size(60, 13);
            this.lblDateCol2.TabIndex = 367;
            this.lblDateCol2.Text = "DateCol2";
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.label3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.label3.Location = new System.Drawing.Point(17, 27);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(0, 13);
            this.label3.TabIndex = 367;
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.label4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.label4.Location = new System.Drawing.Point(29, 94);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(64, 13);
            this.label4.TabIndex = 369;
            this.label4.Text = "Filter Text";
            this.btnCancel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCancel.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.Location = new System.Drawing.Point(901, 535);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(75, 30);
            this.btnCancel.TabIndex = 372;
            this.btnCancel.Text = "Cancel";
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(1002, 569);
            this.ControlBox = false;
            this.Controls.Add(this.drpDriver);
            this.Controls.Add(this.btnPreview);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.cmbFilter);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.groupBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmGeneralReports";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmGeneralReports_Load);
            ((System.ComponentModel.ISupportInitialize)(this.grdReport)).EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.grpFilterByDate.ResumeLayout(false);
            this.grpFilterByDate.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.Label label1;
        private DropDowns.DropSearch drpDriver;
        private System.Windows.Forms.Button btnPreview;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Label label2;
        private  Tourist_Management.User_Controls.ComboBox cmbFilter;
        private System.Windows.Forms.TextBox txtFilter;
        private System.Windows.Forms.DataGridView grdReport;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.GroupBox grpFilterByDate;
        private System.Windows.Forms.DateTimePicker dtpDate2;
        private System.Windows.Forms.DateTimePicker dtpDate1;
        private System.Windows.Forms.Label lblDateCol1;
        private System.Windows.Forms.Label lblDateCol2;
        private System.Windows.Forms.Label label3;
    }
}