namespace Tourist_Management.User_Controls
{
    partial class ucHotelNavigation
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Component Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucHotelNavigation));
            this.grdHotel = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.groupBox8 = new System.Windows.Forms.GroupBox();
            this.pbHE = new System.Windows.Forms.ProgressBar();
            this.btnAEGenerate = new System.Windows.Forms.Button();
            this.drpHotel = new DropDowns.DropSearch();
            this.label17 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.groupBox19 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.gbHotelDetails = new System.Windows.Forms.GroupBox();
            this.cmbMarket = new  Tourist_Management.User_Controls.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.lblToDate = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.lblFromDate = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.lblSeasonName = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.grdMealSup = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.lblIsPaid = new System.Windows.Forms.Label();
            this.lblCancelled = new System.Windows.Forms.Label();
            this.bntCopyLastRow = new System.Windows.Forms.Button();
            this.btnChangeDates = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.grdHotel)).BeginInit();
            this.groupBox8.SuspendLayout();
            this.gbHotelDetails.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdMealSup)).BeginInit();
            this.SuspendLayout();
            this.grdHotel.AllowSorting = C1.Win.C1FlexGrid.AllowSortingEnum.None;
            this.grdHotel.BackColor = System.Drawing.Color.Transparent;
            this.grdHotel.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdHotel.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdHotel.Location = new System.Drawing.Point(9, 77);
            this.grdHotel.Name = "grdHotel";
            this.grdHotel.Size = new System.Drawing.Size(838, 172);
            this.grdHotel.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdHotel.Styles"));
            this.grdHotel.TabIndex = 5;
            this.grdHotel.KeyDown += new System.Windows.Forms.KeyEventHandler(this.grdHotel_KeyDown);
            this.grdHotel.CellButtonClick += new C1.Win.C1FlexGrid.RowColEventHandler(this.grdHotel_CellButtonClick);
            this.groupBox8.BackColor = System.Drawing.Color.Transparent;
            this.groupBox8.Controls.Add(this.pbHE);
            this.groupBox8.Controls.Add(this.btnAEGenerate);
            this.groupBox8.Location = new System.Drawing.Point(621, 221);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new System.Drawing.Size(235, 39);
            this.groupBox8.TabIndex = 13;
            this.groupBox8.TabStop = false;
            this.groupBox8.Visible = false;
            this.pbHE.Location = new System.Drawing.Point(104, 11);
            this.pbHE.Name = "pbHE";
            this.pbHE.Size = new System.Drawing.Size(727, 22);
            this.pbHE.TabIndex = 247;
            this.btnAEGenerate.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.btnAEGenerate.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnAEGenerate.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAEGenerate.Location = new System.Drawing.Point(8, 11);
            this.btnAEGenerate.Name = "btnAEGenerate";
            this.btnAEGenerate.Size = new System.Drawing.Size(87, 22);
            this.btnAEGenerate.TabIndex = 246;
            this.btnAEGenerate.Text = "&Generate";
            this.btnAEGenerate.UseVisualStyleBackColor = true;
            this.btnAEGenerate.Click += new System.EventHandler(this.btnAEGenerate_Click);
            this.drpHotel.BackColor = System.Drawing.Color.Transparent;
            this.drpHotel.DataSource = null;
            this.drpHotel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpHotel.FormName = "";
            this.drpHotel.Location = new System.Drawing.Point(315, 81);
            this.drpHotel.Name = "drpHotel";
            this.drpHotel.SelectedText = "";
            this.drpHotel.SelectedValue = "";
            this.drpHotel.Size = new System.Drawing.Size(209, 23);
            this.drpHotel.TabIndex = 245;
            this.drpHotel.Visible = false;
            this.drpHotel.Selected_TextChanged += new System.EventHandler(this.drpHotel_Selected_TextChanged);
            this.label17.AutoSize = true;
            this.label17.Location = new System.Drawing.Point(226, 123);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(73, 13);
            this.label17.TabIndex = 244;
            this.label17.Text = "Hotel Name";
            this.label17.Visible = false;
            this.label12.AutoSize = true;
            this.label12.BackColor = System.Drawing.Color.Transparent;
            this.label12.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.ForeColor = System.Drawing.Color.Blue;
            this.label12.Location = new System.Drawing.Point(12, 57);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(88, 13);
            this.label12.TabIndex = 309;
            this.label12.Text = "ROOM RATES";
            this.groupBox19.BackColor = System.Drawing.Color.Gray;
            this.groupBox19.Location = new System.Drawing.Point(101, 70);
            this.groupBox19.Name = "groupBox19";
            this.groupBox19.Size = new System.Drawing.Size(741, 2);
            this.groupBox19.TabIndex = 308;
            this.groupBox19.TabStop = false;
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.Blue;
            this.label1.Location = new System.Drawing.Point(13, 286);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(136, 13);
            this.label1.TabIndex = 312;
            this.label1.Text = "MEAL SUPPLEMENTS";
            this.groupBox1.BackColor = System.Drawing.Color.Gray;
            this.groupBox1.Location = new System.Drawing.Point(150, 297);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(697, 2);
            this.groupBox1.TabIndex = 311;
            this.groupBox1.TabStop = false;
            this.gbHotelDetails.BackColor = System.Drawing.Color.Transparent;
            this.gbHotelDetails.Controls.Add(this.cmbMarket);
            this.gbHotelDetails.Controls.Add(this.label2);
            this.gbHotelDetails.Controls.Add(this.lblToDate);
            this.gbHotelDetails.Controls.Add(this.label5);
            this.gbHotelDetails.Controls.Add(this.lblFromDate);
            this.gbHotelDetails.Controls.Add(this.label3);
            this.gbHotelDetails.Controls.Add(this.lblSeasonName);
            this.gbHotelDetails.Controls.Add(this.label15);
            this.gbHotelDetails.Location = new System.Drawing.Point(9, 4);
            this.gbHotelDetails.Name = "gbHotelDetails";
            this.gbHotelDetails.Size = new System.Drawing.Size(838, 52);
            this.gbHotelDetails.TabIndex = 313;
            this.gbHotelDetails.TabStop = false;
            this.gbHotelDetails.Enter += new System.EventHandler(this.gbHotelDetails_Enter);
            this.cmbMarket.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbMarket.FormattingEnabled = true;
            this.cmbMarket.Location = new System.Drawing.Point(106, 16);
            this.cmbMarket.Name = "cmbMarket";
            this.cmbMarket.Size = new System.Drawing.Size(181, 21);
            this.cmbMarket.TabIndex = 322;
            this.cmbMarket.SelectedValueChanged += new System.EventHandler(this.cmbMarket_SelectedValueChanged);
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.Red;
            this.label2.Location = new System.Drawing.Point(6, 19);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(102, 13);
            this.label2.TabIndex = 321;
            this.label2.Text = "Hotel Market : ";
            this.lblToDate.AutoSize = true;
            this.lblToDate.BackColor = System.Drawing.Color.Transparent;
            this.lblToDate.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblToDate.ForeColor = System.Drawing.Color.Red;
            this.lblToDate.Location = new System.Drawing.Point(689, 34);
            this.lblToDate.Name = "lblToDate";
            this.lblToDate.Size = new System.Drawing.Size(15, 13);
            this.lblToDate.TabIndex = 320;
            this.lblToDate.Text = "_";
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.Red;
            this.label5.Location = new System.Drawing.Point(596, 34);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(82, 13);
            this.label5.TabIndex = 319;
            this.label5.Text = "Season To: ";
            this.lblFromDate.AutoSize = true;
            this.lblFromDate.BackColor = System.Drawing.Color.Transparent;
            this.lblFromDate.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblFromDate.ForeColor = System.Drawing.Color.Red;
            this.lblFromDate.Location = new System.Drawing.Point(689, 18);
            this.lblFromDate.Name = "lblFromDate";
            this.lblFromDate.Size = new System.Drawing.Size(15, 13);
            this.lblFromDate.TabIndex = 318;
            this.lblFromDate.Text = "_";
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.Red;
            this.label3.Location = new System.Drawing.Point(595, 18);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(104, 13);
            this.label3.TabIndex = 317;
            this.label3.Text = "Season From : ";
            this.lblSeasonName.AutoSize = true;
            this.lblSeasonName.BackColor = System.Drawing.Color.Transparent;
            this.lblSeasonName.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSeasonName.ForeColor = System.Drawing.Color.Red;
            this.lblSeasonName.Location = new System.Drawing.Point(428, 19);
            this.lblSeasonName.Name = "lblSeasonName";
            this.lblSeasonName.Size = new System.Drawing.Size(15, 13);
            this.lblSeasonName.TabIndex = 316;
            this.lblSeasonName.Text = "_";
            this.label15.AutoSize = true;
            this.label15.BackColor = System.Drawing.Color.Transparent;
            this.label15.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label15.ForeColor = System.Drawing.Color.Red;
            this.label15.Location = new System.Drawing.Point(333, 20);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(104, 13);
            this.label15.TabIndex = 315;
            this.label15.Text = "Hotel Season : ";
            this.grdMealSup.BackColor = System.Drawing.Color.Transparent;
            this.grdMealSup.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdMealSup.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdMealSup.Location = new System.Drawing.Point(9, 304);
            this.grdMealSup.Name = "grdMealSup";
            this.grdMealSup.Size = new System.Drawing.Size(838, 86);
            this.grdMealSup.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdMealSup.Styles"));
            this.grdMealSup.TabIndex = 314;
            this.grdMealSup.KeyDown += new System.Windows.Forms.KeyEventHandler(this.grdMealSup_KeyDown);
            this.grdMealSup.CellButtonClick += new C1.Win.C1FlexGrid.RowColEventHandler(this.grdMealSup_CellButtonClick);
            this.grdMealSup.RowColChange += new System.EventHandler(this.grdMealSup_RowColChange);
            this.lblIsPaid.AutoSize = true;
            this.lblIsPaid.BackColor = System.Drawing.Color.Transparent;
            this.lblIsPaid.Font = new System.Drawing.Font("Verdana", 26.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblIsPaid.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.lblIsPaid.Location = new System.Drawing.Point(274, 220);
            this.lblIsPaid.Name = "lblIsPaid";
            this.lblIsPaid.Size = new System.Drawing.Size(279, 42);
            this.lblIsPaid.TabIndex = 315;
            this.lblIsPaid.Text = "ALREADY PAID";
            this.lblIsPaid.Visible = false;
            this.lblCancelled.AutoSize = true;
            this.lblCancelled.BackColor = System.Drawing.Color.Transparent;
            this.lblCancelled.Font = new System.Drawing.Font("Verdana", 26.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCancelled.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblCancelled.Location = new System.Drawing.Point(300, 178);
            this.lblCancelled.Name = "lblCancelled";
            this.lblCancelled.Size = new System.Drawing.Size(225, 42);
            this.lblCancelled.TabIndex = 316;
            this.lblCancelled.Text = "CANCELLED";
            this.lblCancelled.Visible = false;
            this.bntCopyLastRow.Location = new System.Drawing.Point(9, 254);
            this.bntCopyLastRow.Name = "bntCopyLastRow";
            this.bntCopyLastRow.Size = new System.Drawing.Size(101, 23);
            this.bntCopyLastRow.TabIndex = 317;
            this.bntCopyLastRow.Text = "Copy Last Row";
            this.bntCopyLastRow.UseVisualStyleBackColor = true;
            this.bntCopyLastRow.Click += new System.EventHandler(this.bntCopyLastRow_Click);
            this.btnChangeDates.Location = new System.Drawing.Point(114, 253);
            this.btnChangeDates.Name = "btnChangeDates";
            this.btnChangeDates.Size = new System.Drawing.Size(101, 23);
            this.btnChangeDates.TabIndex = 318;
            this.btnChangeDates.Text = "Update Dates";
            this.btnChangeDates.UseVisualStyleBackColor = true;
            this.btnChangeDates.Click += new System.EventHandler(this.btnChangeDates_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.Controls.Add(this.btnChangeDates);
            this.Controls.Add(this.drpHotel);
            this.Controls.Add(this.bntCopyLastRow);
            this.Controls.Add(this.lblCancelled);
            this.Controls.Add(this.lblIsPaid);
            this.Controls.Add(this.grdMealSup);
            this.Controls.Add(this.gbHotelDetails);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.groupBox8);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.groupBox19);
            this.Controls.Add(this.grdHotel);
            this.Controls.Add(this.label17);
            this.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "ucHotelNavigation";
            this.Size = new System.Drawing.Size(850, 398);
            this.Load += new System.EventHandler(this.ucHotelNavigation_Load);
            ((System.ComponentModel.ISupportInitialize)(this.grdHotel)).EndInit();
            this.groupBox8.ResumeLayout(false);
            this.gbHotelDetails.ResumeLayout(false);
            this.gbHotelDetails.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdMealSup)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        public C1.Win.C1FlexGrid.C1FlexGrid grdHotel;
        public System.Windows.Forms.GroupBox groupBox8;
        public System.Windows.Forms.ProgressBar pbHE;
        public System.Windows.Forms.Button btnAEGenerate;
        public DropDowns.DropSearch drpHotel;
        public System.Windows.Forms.Label label17;
        public System.Windows.Forms.Label label12;
        public System.Windows.Forms.GroupBox groupBox19;
        public System.Windows.Forms.Label label1;
        public System.Windows.Forms.GroupBox groupBox1;
        public System.Windows.Forms.GroupBox gbHotelDetails;
        public System.Windows.Forms.Label label15;
        public System.Windows.Forms.Label lblSeasonName;
        public C1.Win.C1FlexGrid.C1FlexGrid grdMealSup;
        public System.Windows.Forms.Label lblFromDate;
        public System.Windows.Forms.Label label3;
        public System.Windows.Forms.Label lblToDate;
        public System.Windows.Forms.Label label5;
        public System.Windows.Forms.Label label2;
        private  Tourist_Management.User_Controls.ComboBox cmbMarket;
        public System.Windows.Forms.Label lblIsPaid;
        public System.Windows.Forms.Label lblCancelled;
        private System.Windows.Forms.Button bntCopyLastRow;
        private System.Windows.Forms.Button btnChangeDates;
    }
}
