namespace Tourist_Management.User_Controls
{
    partial class ucPayments
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Component Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucPayments));
            this.rdbConfirm = new System.Windows.Forms.RadioButton();
            this.btnClearEntities = new System.Windows.Forms.Button();
            this.btnAdd = new System.Windows.Forms.Button();
            this.label12 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.txtBalanceIOU = new System.Windows.Forms.TextBox();
            this.rdbHotel = new System.Windows.Forms.RadioButton();
            this.chkMulIOU = new System.Windows.Forms.CheckBox();
            this.btnIOU = new System.Windows.Forms.Button();
            this.txtIOUNo = new System.Windows.Forms.TextBox();
            this.rdbAgent = new System.Windows.Forms.RadioButton();
            this.txtSettledIOU = new System.Windows.Forms.TextBox();
            this.rdbGuide = new System.Windows.Forms.RadioButton();
            this.rdbDriver = new System.Windows.Forms.RadioButton();
            this.lblGuest = new System.Windows.Forms.Label();
            this.btnTour = new System.Windows.Forms.Button();
            this.label9 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.gbBasic = new System.Windows.Forms.GroupBox();
            this.rdbOther = new System.Windows.Forms.RadioButton();
            this.txtTourNo = new System.Windows.Forms.TextBox();
            this.btnClearStatus = new System.Windows.Forms.Button();
            this.label10 = new System.Windows.Forms.Label();
            this.gbStatus = new System.Windows.Forms.GroupBox();
            this.rdbCancel = new System.Windows.Forms.RadioButton();
            this.lblStatus = new System.Windows.Forms.Label();
            this.chkPrint = new System.Windows.Forms.CheckBox();
            this.lblVoucherNo = new System.Windows.Forms.Label();
            this.drpPayableTo = new Tourist_Management.DropDowns.DropSearch();
            this.dtpPaidDate = new System.Windows.Forms.DateTimePicker();
            this.txtChkNo = new System.Windows.Forms.TextBox();
            this.lblType = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.btnPrint = new System.Windows.Forms.Button();
            this.label4 = new System.Windows.Forms.Label();
            this.btnClose = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.grdPay = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.lblMain = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.drpPayee = new Tourist_Management.DropDowns.DropSearch();
            this.label7 = new System.Windows.Forms.Label();
            this.txtRefNo = new System.Windows.Forms.TextBox();
            this.lblPayRec = new System.Windows.Forms.Label();
            this.gbBasic1 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.cmbCompany = new  Tourist_Management.User_Controls.ComboBox();
            this.label6 = new System.Windows.Forms.Label();
            this.txtDescription = new System.Windows.Forms.TextBox();
            this.gbIOU = new System.Windows.Forms.GroupBox();
            this.label3 = new System.Windows.Forms.Label();
            this.gbBasic2 = new System.Windows.Forms.GroupBox();
            this.gbChk = new System.Windows.Forms.GroupBox();
            this.dtpChkDate = new System.Windows.Forms.DateTimePicker();
            this.lblDebit = new System.Windows.Forms.Label();
            this.lblCredit = new System.Windows.Forms.Label();
            this.lblDifDebit = new System.Windows.Forms.Label();
            this.lblDifCredit = new System.Windows.Forms.Label();
            this.btnSettleRest = new System.Windows.Forms.Button();
            this.gbCurrency = new System.Windows.Forms.GroupBox();
            this.btnEncash = new System.Windows.Forms.Button();
            this.dtpExchangeDate = new System.Windows.Forms.DateTimePicker();
            this.label17 = new System.Windows.Forms.Label();
            this.cmbExchangeToAccount = new  Tourist_Management.User_Controls.ComboBox();
            this.label16 = new System.Windows.Forms.Label();
            this.txtErate = new System.Windows.Forms.TextBox();
            this.label15 = new System.Windows.Forms.Label();
            this.txtRrate = new System.Windows.Forms.TextBox();
            this.label14 = new System.Windows.Forms.Label();
            this.cmbCurrency = new  Tourist_Management.User_Controls.ComboBox();
            this.label13 = new System.Windows.Forms.Label();
            this.lblError = new System.Windows.Forms.Label();
            this.gbBasic.SuspendLayout();
            this.gbStatus.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdPay)).BeginInit();
            this.gbBasic1.SuspendLayout();
            this.gbIOU.SuspendLayout();
            this.gbBasic2.SuspendLayout();
            this.gbChk.SuspendLayout();
            this.gbCurrency.SuspendLayout();
            this.SuspendLayout();
            this.rdbConfirm.AutoSize = true;
            this.rdbConfirm.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbConfirm.ForeColor = System.Drawing.Color.Green;
            this.rdbConfirm.Location = new System.Drawing.Point(7, 34);
            this.rdbConfirm.Name = "rdbConfirm";
            this.rdbConfirm.Size = new System.Drawing.Size(147, 17);
            this.rdbConfirm.TabIndex = 1;
            this.rdbConfirm.TabStop = true;
            this.rdbConfirm.Text = "Confirm Statement";
            this.rdbConfirm.UseVisualStyleBackColor = true;
            this.btnClearEntities.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClearEntities.Location = new System.Drawing.Point(513, 8);
            this.btnClearEntities.Name = "btnClearEntities";
            this.btnClearEntities.Size = new System.Drawing.Size(22, 20);
            this.btnClearEntities.TabIndex = 407;
            this.btnClearEntities.Text = "X";
            this.btnClearEntities.UseVisualStyleBackColor = true;
            this.btnClearEntities.Visible = false;
            this.btnClearEntities.Click += new System.EventHandler(this.btnClearEntities_Click);
            this.btnAdd.Enabled = false;
            this.btnAdd.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAdd.Location = new System.Drawing.Point(272, 17);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new System.Drawing.Size(30, 20);
            this.btnAdd.TabIndex = 403;
            this.btnAdd.Text = "+";
            this.btnAdd.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.btnAdd.UseVisualStyleBackColor = true;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            this.label12.AutoSize = true;
            this.label12.BackColor = System.Drawing.Color.Transparent;
            this.label12.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.Location = new System.Drawing.Point(13, 43);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(41, 12);
            this.label12.TabIndex = 402;
            this.label12.Text = "Settled";
            this.label11.AutoSize = true;
            this.label11.BackColor = System.Drawing.Color.Transparent;
            this.label11.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label11.Location = new System.Drawing.Point(154, 44);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(45, 12);
            this.label11.TabIndex = 401;
            this.label11.Text = "Balance";
            this.txtBalanceIOU.Enabled = false;
            this.txtBalanceIOU.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtBalanceIOU.ForeColor = System.Drawing.Color.Blue;
            this.txtBalanceIOU.Location = new System.Drawing.Point(203, 42);
            this.txtBalanceIOU.Name = "txtBalanceIOU";
            this.txtBalanceIOU.ReadOnly = true;
            this.txtBalanceIOU.Size = new System.Drawing.Size(99, 18);
            this.txtBalanceIOU.TabIndex = 400;
            this.txtBalanceIOU.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.rdbHotel.AutoSize = true;
            this.rdbHotel.BackColor = System.Drawing.Color.Transparent;
            this.rdbHotel.Location = new System.Drawing.Point(262, 39);
            this.rdbHotel.Name = "rdbHotel";
            this.rdbHotel.Size = new System.Drawing.Size(50, 16);
            this.rdbHotel.TabIndex = 406;
            this.rdbHotel.Text = "Hotel";
            this.rdbHotel.UseVisualStyleBackColor = false;
            this.rdbHotel.Visible = false;
            this.rdbHotel.CheckedChanged += new System.EventHandler(this.rdb_CheckedChanged);
            this.chkMulIOU.AutoSize = true;
            this.chkMulIOU.Enabled = false;
            this.chkMulIOU.ForeColor = System.Drawing.Color.Blue;
            this.chkMulIOU.Location = new System.Drawing.Point(63, 66);
            this.chkMulIOU.Name = "chkMulIOU";
            this.chkMulIOU.Size = new System.Drawing.Size(128, 16);
            this.chkMulIOU.TabIndex = 404;
            this.chkMulIOU.Text = "Settle Multiple IOUs";
            this.chkMulIOU.UseVisualStyleBackColor = true;
            this.chkMulIOU.CheckStateChanged += new System.EventHandler(this.chkMulIOU_CheckedChanged);
            this.btnIOU.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnIOU.Location = new System.Drawing.Point(237, 17);
            this.btnIOU.Name = "btnIOU";
            this.btnIOU.Size = new System.Drawing.Size(34, 20);
            this.btnIOU.TabIndex = 397;
            this.btnIOU.Text = "...";
            this.btnIOU.UseVisualStyleBackColor = true;
            this.btnIOU.Click += new System.EventHandler(this.btnIOU_Click);
            this.txtIOUNo.Enabled = false;
            this.txtIOUNo.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtIOUNo.ForeColor = System.Drawing.Color.Blue;
            this.txtIOUNo.Location = new System.Drawing.Point(63, 18);
            this.txtIOUNo.Name = "txtIOUNo";
            this.txtIOUNo.ReadOnly = true;
            this.txtIOUNo.Size = new System.Drawing.Size(168, 18);
            this.txtIOUNo.TabIndex = 398;
            this.txtIOUNo.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txtIOUNo.TextChanged += new System.EventHandler(this.txtIOUNo_TextChanged);
            this.rdbAgent.AutoSize = true;
            this.rdbAgent.BackColor = System.Drawing.Color.Transparent;
            this.rdbAgent.Location = new System.Drawing.Point(205, 39);
            this.rdbAgent.Name = "rdbAgent";
            this.rdbAgent.Size = new System.Drawing.Size(53, 16);
            this.rdbAgent.TabIndex = 405;
            this.rdbAgent.Text = "Agent";
            this.rdbAgent.UseVisualStyleBackColor = false;
            this.rdbAgent.Visible = false;
            this.rdbAgent.CheckedChanged += new System.EventHandler(this.rdb_CheckedChanged);
            this.txtSettledIOU.Enabled = false;
            this.txtSettledIOU.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSettledIOU.ForeColor = System.Drawing.Color.Blue;
            this.txtSettledIOU.Location = new System.Drawing.Point(63, 41);
            this.txtSettledIOU.Name = "txtSettledIOU";
            this.txtSettledIOU.ReadOnly = true;
            this.txtSettledIOU.Size = new System.Drawing.Size(83, 18);
            this.txtSettledIOU.TabIndex = 399;
            this.txtSettledIOU.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.rdbGuide.AutoSize = true;
            this.rdbGuide.BackColor = System.Drawing.Color.Transparent;
            this.rdbGuide.Location = new System.Drawing.Point(147, 39);
            this.rdbGuide.Name = "rdbGuide";
            this.rdbGuide.Size = new System.Drawing.Size(52, 16);
            this.rdbGuide.TabIndex = 404;
            this.rdbGuide.Text = "Guide";
            this.rdbGuide.UseVisualStyleBackColor = false;
            this.rdbGuide.Visible = false;
            this.rdbGuide.CheckedChanged += new System.EventHandler(this.rdb_CheckedChanged);
            this.rdbDriver.AutoSize = true;
            this.rdbDriver.BackColor = System.Drawing.Color.Transparent;
            this.rdbDriver.Checked = true;
            this.rdbDriver.Location = new System.Drawing.Point(90, 39);
            this.rdbDriver.Name = "rdbDriver";
            this.rdbDriver.Size = new System.Drawing.Size(54, 16);
            this.rdbDriver.TabIndex = 403;
            this.rdbDriver.TabStop = true;
            this.rdbDriver.Text = "Driver";
            this.rdbDriver.UseVisualStyleBackColor = false;
            this.rdbDriver.Visible = false;
            this.rdbDriver.CheckedChanged += new System.EventHandler(this.rdb_CheckedChanged);
            this.lblGuest.AutoSize = true;
            this.lblGuest.BackColor = System.Drawing.Color.Transparent;
            this.lblGuest.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblGuest.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.lblGuest.Location = new System.Drawing.Point(275, 17);
            this.lblGuest.Name = "lblGuest";
            this.lblGuest.Size = new System.Drawing.Size(15, 12);
            this.lblGuest.TabIndex = 402;
            this.lblGuest.Text = "\"\"";
            this.btnTour.Location = new System.Drawing.Point(235, 12);
            this.btnTour.Name = "btnTour";
            this.btnTour.Size = new System.Drawing.Size(34, 23);
            this.btnTour.TabIndex = 399;
            this.btnTour.Text = "...";
            this.btnTour.UseVisualStyleBackColor = true;
            this.btnTour.Click += new System.EventHandler(this.btnTour_Click);
            this.label9.AutoSize = true;
            this.label9.BackColor = System.Drawing.Color.Transparent;
            this.label9.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(13, 17);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(44, 12);
            this.label9.TabIndex = 401;
            this.label9.Text = "Tour ID";
            this.label8.BackColor = System.Drawing.Color.Gray;
            this.label8.Location = new System.Drawing.Point(15, 34);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(808, 2);
            this.label8.TabIndex = 417;
            this.gbBasic.BackColor = System.Drawing.Color.Transparent;
            this.gbBasic.Controls.Add(this.rdbOther);
            this.gbBasic.Controls.Add(this.btnClearEntities);
            this.gbBasic.Controls.Add(this.rdbHotel);
            this.gbBasic.Controls.Add(this.rdbAgent);
            this.gbBasic.Controls.Add(this.rdbGuide);
            this.gbBasic.Controls.Add(this.rdbDriver);
            this.gbBasic.Controls.Add(this.lblGuest);
            this.gbBasic.Controls.Add(this.btnTour);
            this.gbBasic.Controls.Add(this.label9);
            this.gbBasic.Controls.Add(this.txtTourNo);
            this.gbBasic.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbBasic.Location = new System.Drawing.Point(15, 50);
            this.gbBasic.Name = "gbBasic";
            this.gbBasic.Size = new System.Drawing.Size(537, 63);
            this.gbBasic.TabIndex = 413;
            this.gbBasic.TabStop = false;
            this.rdbOther.AutoSize = true;
            this.rdbOther.BackColor = System.Drawing.Color.Transparent;
            this.rdbOther.Location = new System.Drawing.Point(318, 39);
            this.rdbOther.Name = "rdbOther";
            this.rdbOther.Size = new System.Drawing.Size(37, 16);
            this.rdbOther.TabIndex = 408;
            this.rdbOther.Text = "All";
            this.rdbOther.UseVisualStyleBackColor = false;
            this.rdbOther.Visible = false;
            this.rdbOther.CheckedChanged += new System.EventHandler(this.rdbOther_CheckedChanged);
            this.txtTourNo.Enabled = false;
            this.txtTourNo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTourNo.ForeColor = System.Drawing.Color.Blue;
            this.txtTourNo.Location = new System.Drawing.Point(90, 13);
            this.txtTourNo.Name = "txtTourNo";
            this.txtTourNo.ReadOnly = true;
            this.txtTourNo.Size = new System.Drawing.Size(139, 21);
            this.txtTourNo.TabIndex = 400;
            this.txtTourNo.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.btnClearStatus.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClearStatus.Location = new System.Drawing.Point(198, 8);
            this.btnClearStatus.Name = "btnClearStatus";
            this.btnClearStatus.Size = new System.Drawing.Size(22, 20);
            this.btnClearStatus.TabIndex = 398;
            this.btnClearStatus.Text = "X";
            this.btnClearStatus.UseVisualStyleBackColor = true;
            this.btnClearStatus.Click += new System.EventHandler(this.btnClearStatus_Click);
            this.label10.AutoSize = true;
            this.label10.BackColor = System.Drawing.Color.Transparent;
            this.label10.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.Location = new System.Drawing.Point(13, 21);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(44, 12);
            this.label10.TabIndex = 390;
            this.label10.Text = "IOU No";
            this.gbStatus.BackColor = System.Drawing.Color.Transparent;
            this.gbStatus.Controls.Add(this.btnClearStatus);
            this.gbStatus.Controls.Add(this.rdbConfirm);
            this.gbStatus.Controls.Add(this.rdbCancel);
            this.gbStatus.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbStatus.Location = new System.Drawing.Point(329, 112);
            this.gbStatus.Name = "gbStatus";
            this.gbStatus.Size = new System.Drawing.Size(223, 56);
            this.gbStatus.TabIndex = 418;
            this.gbStatus.TabStop = false;
            this.gbStatus.Text = "Status";
            this.rdbCancel.AutoSize = true;
            this.rdbCancel.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbCancel.ForeColor = System.Drawing.Color.Red;
            this.rdbCancel.Location = new System.Drawing.Point(7, 15);
            this.rdbCancel.Name = "rdbCancel";
            this.rdbCancel.Size = new System.Drawing.Size(139, 17);
            this.rdbCancel.TabIndex = 0;
            this.rdbCancel.TabStop = true;
            this.rdbCancel.Text = "Cancel Statement";
            this.rdbCancel.UseVisualStyleBackColor = true;
            this.lblStatus.AutoSize = true;
            this.lblStatus.BackColor = System.Drawing.Color.Transparent;
            this.lblStatus.Font = new System.Drawing.Font("Verdana", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblStatus.ForeColor = System.Drawing.Color.Red;
            this.lblStatus.Location = new System.Drawing.Point(11, 571);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Size = new System.Drawing.Size(22, 16);
            this.lblStatus.TabIndex = 416;
            this.lblStatus.Text = "\"\"";
            this.lblStatus.Visible = false;
            this.chkPrint.AutoSize = true;
            this.chkPrint.BackColor = System.Drawing.Color.Transparent;
            this.chkPrint.Checked = true;
            this.chkPrint.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkPrint.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkPrint.Location = new System.Drawing.Point(450, 580);
            this.chkPrint.Name = "chkPrint";
            this.chkPrint.Size = new System.Drawing.Size(136, 17);
            this.chkPrint.TabIndex = 415;
            this.chkPrint.Text = "Preview After Save";
            this.chkPrint.UseVisualStyleBackColor = false;
            this.lblVoucherNo.BackColor = System.Drawing.Color.Transparent;
            this.lblVoucherNo.Font = new System.Drawing.Font("Verdana", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblVoucherNo.Location = new System.Drawing.Point(609, 12);
            this.lblVoucherNo.Name = "lblVoucherNo";
            this.lblVoucherNo.Size = new System.Drawing.Size(215, 18);
            this.lblVoucherNo.TabIndex = 414;
            this.lblVoucherNo.Text = "\"\"";
            this.drpPayableTo.BackColor = System.Drawing.Color.Transparent;
            this.drpPayableTo.DataSource = null;
            this.drpPayableTo.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpPayableTo.Location = new System.Drawing.Point(77, 35);
            this.drpPayableTo.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.drpPayableTo.Name = "drpPayableTo";
            this.drpPayableTo.SelectedText = "";
            this.drpPayableTo.SelectedValue = "";
            this.drpPayableTo.Size = new System.Drawing.Size(179, 18);
            this.drpPayableTo.TabIndex = 382;
            this.drpPayableTo.Selected_TextChanged += new System.EventHandler(this.drpPayableTo_Selected_TextChanged);
            this.drpPayableTo.Load += new System.EventHandler(this.drpPayableTo_Load);
            this.dtpPaidDate.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpPaidDate.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpPaidDate.Location = new System.Drawing.Point(77, 61);
            this.dtpPaidDate.Name = "dtpPaidDate";
            this.dtpPaidDate.Size = new System.Drawing.Size(179, 18);
            this.dtpPaidDate.TabIndex = 383;
            this.dtpPaidDate.ValueChanged += new System.EventHandler(this.dtpPaidDate_ValueChanged);
            this.txtChkNo.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtChkNo.Location = new System.Drawing.Point(78, 14);
            this.txtChkNo.MaxLength = 50;
            this.txtChkNo.Name = "txtChkNo";
            this.txtChkNo.Size = new System.Drawing.Size(177, 20);
            this.txtChkNo.TabIndex = 385;
            this.lblType.BackColor = System.Drawing.Color.Transparent;
            this.lblType.Font = new System.Drawing.Font("Verdana", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblType.Location = new System.Drawing.Point(350, 12);
            this.lblType.Name = "lblType";
            this.lblType.Size = new System.Drawing.Size(251, 18);
            this.lblType.TabIndex = 408;
            this.lblType.Text = "VoucherNo :";
            this.lblType.TextAlign = System.Drawing.ContentAlignment.TopRight;
            this.lblType.Click += new System.EventHandler(this.lblType_Click);
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(9, 65);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(29, 12);
            this.label2.TabIndex = 387;
            this.label2.Text = "Date";
            this.btnPrint.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPrint.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPrint.Image = global::Tourist_Management.Properties.Resources.search;
            this.btnPrint.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPrint.Location = new System.Drawing.Point(592, 575);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.Size = new System.Drawing.Size(76, 29);
            this.btnPrint.TabIndex = 407;
            this.btnPrint.Text = "&Preview";
            this.btnPrint.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPrint.UseVisualStyleBackColor = true;
            this.btnPrint.Click += new System.EventHandler(this.btnPrint_Click);
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(6, 17);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(70, 13);
            this.label4.TabIndex = 389;
            this.label4.Text = "Cheque No";
            this.btnClose.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnClose.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClose.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnClose.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.Location = new System.Drawing.Point(752, 575);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new System.Drawing.Size(72, 30);
            this.btnClose.TabIndex = 406;
            this.btnClose.Text = "&Close";
            this.btnClose.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose.UseVisualStyleBackColor = true;
            this.btnClose.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnOk.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnOk.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Image = global::Tourist_Management.Properties.Resources.floppy;
            this.btnOk.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOk.Location = new System.Drawing.Point(674, 575);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(72, 30);
            this.btnOk.TabIndex = 405;
            this.btnOk.Text = "&Save";
            this.btnOk.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.grdPay.AllowSorting = C1.Win.C1FlexGrid.AllowSortingEnum.None;
            this.grdPay.BackColor = System.Drawing.Color.Transparent;
            this.grdPay.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.grdPay.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdPay.ColumnInfo = "0,0,0,0,0,85,Columns:";
            this.grdPay.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grdPay.Location = new System.Drawing.Point(13, 206);
            this.grdPay.Name = "grdPay";
            this.grdPay.Size = new System.Drawing.Size(810, 272);
            this.grdPay.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdPay.Styles"));
            this.grdPay.TabIndex = 404;
            this.grdPay.RowColChange += new System.EventHandler(this.grdPay_RowColChange);
            this.grdPay.AfterEdit += new C1.Win.C1FlexGrid.RowColEventHandler(this.grdPay_AfterEdit);
            this.grdPay.CellButtonClick += new C1.Win.C1FlexGrid.RowColEventHandler(this.grdPay_CellButtonClick);
            this.grdPay.Click += new System.EventHandler(this.grdPay_Click);
            this.grdPay.KeyDown += new System.Windows.Forms.KeyEventHandler(this.grdPay_KeyDown);
            this.lblMain.BackColor = System.Drawing.Color.Transparent;
            this.lblMain.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblMain.ForeColor = System.Drawing.Color.Blue;
            this.lblMain.Location = new System.Drawing.Point(18, 12);
            this.lblMain.Name = "lblMain";
            this.lblMain.Size = new System.Drawing.Size(326, 18);
            this.lblMain.TabIndex = 403;
            this.lblMain.Text = "TYPE";
            this.lblMain.Click += new System.EventHandler(this.lblMain_Click);
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(12, 16);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(63, 12);
            this.label5.TabIndex = 390;
            this.label5.Text = "Description";
            this.drpPayee.BackColor = System.Drawing.Color.Transparent;
            this.drpPayee.DataSource = null;
            this.drpPayee.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpPayee.Location = new System.Drawing.Point(548, 14);
            this.drpPayee.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.drpPayee.Name = "drpPayee";
            this.drpPayee.SelectedText = "";
            this.drpPayee.SelectedValue = "";
            this.drpPayee.Size = new System.Drawing.Size(248, 20);
            this.drpPayee.TabIndex = 393;
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.Transparent;
            this.label7.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(498, 18);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(42, 13);
            this.label7.TabIndex = 392;
            this.label7.Text = "Payee";
            this.txtRefNo.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtRefNo.Location = new System.Drawing.Point(77, 87);
            this.txtRefNo.MaxLength = 50;
            this.txtRefNo.Name = "txtRefNo";
            this.txtRefNo.Size = new System.Drawing.Size(179, 18);
            this.txtRefNo.TabIndex = 375;
            this.lblPayRec.BackColor = System.Drawing.Color.Transparent;
            this.lblPayRec.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPayRec.Location = new System.Drawing.Point(9, 37);
            this.lblPayRec.Name = "lblPayRec";
            this.lblPayRec.Size = new System.Drawing.Size(61, 23);
            this.lblPayRec.TabIndex = 376;
            this.lblPayRec.Text = "Payable To";
            this.gbBasic1.BackColor = System.Drawing.Color.Transparent;
            this.gbBasic1.Controls.Add(this.drpPayableTo);
            this.gbBasic1.Controls.Add(this.dtpPaidDate);
            this.gbBasic1.Controls.Add(this.label2);
            this.gbBasic1.Controls.Add(this.txtRefNo);
            this.gbBasic1.Controls.Add(this.lblPayRec);
            this.gbBasic1.Controls.Add(this.label1);
            this.gbBasic1.Controls.Add(this.cmbCompany);
            this.gbBasic1.Controls.Add(this.label6);
            this.gbBasic1.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbBasic1.Location = new System.Drawing.Point(559, 50);
            this.gbBasic1.Name = "gbBasic1";
            this.gbBasic1.Size = new System.Drawing.Size(265, 114);
            this.gbBasic1.TabIndex = 411;
            this.gbBasic1.TabStop = false;
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(9, 90);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(38, 12);
            this.label1.TabIndex = 386;
            this.label1.Text = "Ref No";
            this.cmbCompany.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCompany.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCompany.FormattingEnabled = true;
            this.cmbCompany.Location = new System.Drawing.Point(77, 12);
            this.cmbCompany.Name = "cmbCompany";
            this.cmbCompany.Size = new System.Drawing.Size(179, 20);
            this.cmbCompany.TabIndex = 384;
            this.cmbCompany.SelectedIndexChanged += new System.EventHandler(this.cmbCompany_SelectedIndexChanged);
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(9, 15);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(52, 12);
            this.label6.TabIndex = 388;
            this.label6.Text = "Company";
            this.txtDescription.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDescription.Location = new System.Drawing.Point(77, 13);
            this.txtDescription.MaxLength = 200;
            this.txtDescription.Multiline = true;
            this.txtDescription.Name = "txtDescription";
            this.txtDescription.Size = new System.Drawing.Size(404, 19);
            this.txtDescription.TabIndex = 391;
            this.gbIOU.BackColor = System.Drawing.Color.Transparent;
            this.gbIOU.Controls.Add(this.chkMulIOU);
            this.gbIOU.Controls.Add(this.btnAdd);
            this.gbIOU.Controls.Add(this.label12);
            this.gbIOU.Controls.Add(this.label11);
            this.gbIOU.Controls.Add(this.txtBalanceIOU);
            this.gbIOU.Controls.Add(this.txtSettledIOU);
            this.gbIOU.Controls.Add(this.btnIOU);
            this.gbIOU.Controls.Add(this.txtIOUNo);
            this.gbIOU.Controls.Add(this.label10);
            this.gbIOU.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbIOU.Location = new System.Drawing.Point(220, 407);
            this.gbIOU.Name = "gbIOU";
            this.gbIOU.Size = new System.Drawing.Size(310, 89);
            this.gbIOU.TabIndex = 412;
            this.gbIOU.TabStop = false;
            this.gbIOU.Visible = false;
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(275, 18);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(82, 13);
            this.label3.TabIndex = 391;
            this.label3.Text = "Cheque Date";
            this.gbBasic2.BackColor = System.Drawing.Color.Transparent;
            this.gbBasic2.Controls.Add(this.txtDescription);
            this.gbBasic2.Controls.Add(this.label5);
            this.gbBasic2.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbBasic2.Location = new System.Drawing.Point(329, 164);
            this.gbBasic2.Name = "gbBasic2";
            this.gbBasic2.Size = new System.Drawing.Size(494, 37);
            this.gbBasic2.TabIndex = 409;
            this.gbBasic2.TabStop = false;
            this.gbChk.BackColor = System.Drawing.Color.Transparent;
            this.gbChk.Controls.Add(this.drpPayee);
            this.gbChk.Controls.Add(this.label7);
            this.gbChk.Controls.Add(this.dtpChkDate);
            this.gbChk.Controls.Add(this.label3);
            this.gbChk.Controls.Add(this.txtChkNo);
            this.gbChk.Controls.Add(this.label4);
            this.gbChk.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbChk.Location = new System.Drawing.Point(14, 523);
            this.gbChk.Name = "gbChk";
            this.gbChk.Size = new System.Drawing.Size(810, 45);
            this.gbChk.TabIndex = 410;
            this.gbChk.TabStop = false;
            this.dtpChkDate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpChkDate.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpChkDate.Location = new System.Drawing.Point(362, 14);
            this.dtpChkDate.Name = "dtpChkDate";
            this.dtpChkDate.Size = new System.Drawing.Size(115, 20);
            this.dtpChkDate.TabIndex = 390;
            this.lblDebit.BackColor = System.Drawing.Color.Transparent;
            this.lblDebit.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDebit.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDebit.Location = new System.Drawing.Point(573, 481);
            this.lblDebit.Name = "lblDebit";
            this.lblDebit.Size = new System.Drawing.Size(85, 23);
            this.lblDebit.TabIndex = 419;
            this.lblDebit.Text = "Debit";
            this.lblDebit.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblCredit.BackColor = System.Drawing.Color.Transparent;
            this.lblCredit.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblCredit.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCredit.Location = new System.Drawing.Point(661, 481);
            this.lblCredit.Name = "lblCredit";
            this.lblCredit.Size = new System.Drawing.Size(85, 23);
            this.lblCredit.TabIndex = 420;
            this.lblCredit.Text = "Credit";
            this.lblCredit.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblDifDebit.BackColor = System.Drawing.Color.Transparent;
            this.lblDifDebit.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDifDebit.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDifDebit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblDifDebit.Location = new System.Drawing.Point(661, 506);
            this.lblDifDebit.Name = "lblDifDebit";
            this.lblDifDebit.Size = new System.Drawing.Size(85, 23);
            this.lblDifDebit.TabIndex = 421;
            this.lblDifDebit.Text = "Difference";
            this.lblDifDebit.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblDifDebit.Visible = false;
            this.lblDifCredit.BackColor = System.Drawing.Color.Transparent;
            this.lblDifCredit.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDifCredit.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDifCredit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblDifCredit.Location = new System.Drawing.Point(573, 506);
            this.lblDifCredit.Name = "lblDifCredit";
            this.lblDifCredit.Size = new System.Drawing.Size(85, 23);
            this.lblDifCredit.TabIndex = 422;
            this.lblDifCredit.Text = "Difference";
            this.lblDifCredit.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblDifCredit.Visible = false;
            this.btnSettleRest.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnSettleRest.Image = global::Tourist_Management.Properties.Resources.sum;
            this.btnSettleRest.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSettleRest.Location = new System.Drawing.Point(13, 482);
            this.btnSettleRest.Name = "btnSettleRest";
            this.btnSettleRest.Size = new System.Drawing.Size(165, 32);
            this.btnSettleRest.TabIndex = 423;
            this.btnSettleRest.Text = "Settle Rest With Petty Cash";
            this.btnSettleRest.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSettleRest.UseVisualStyleBackColor = true;
            this.btnSettleRest.Click += new System.EventHandler(this.btnSettleRest_Click);
            this.gbCurrency.Controls.Add(this.btnEncash);
            this.gbCurrency.Controls.Add(this.dtpExchangeDate);
            this.gbCurrency.Controls.Add(this.label17);
            this.gbCurrency.Controls.Add(this.cmbExchangeToAccount);
            this.gbCurrency.Controls.Add(this.label16);
            this.gbCurrency.Controls.Add(this.txtErate);
            this.gbCurrency.Controls.Add(this.label15);
            this.gbCurrency.Controls.Add(this.txtRrate);
            this.gbCurrency.Controls.Add(this.label14);
            this.gbCurrency.Controls.Add(this.cmbCurrency);
            this.gbCurrency.Controls.Add(this.label13);
            this.gbCurrency.Location = new System.Drawing.Point(15, 122);
            this.gbCurrency.Name = "gbCurrency";
            this.gbCurrency.Size = new System.Drawing.Size(308, 66);
            this.gbCurrency.TabIndex = 424;
            this.gbCurrency.TabStop = false;
            this.btnEncash.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnEncash.Image = global::Tourist_Management.Properties.Resources.coins;
            this.btnEncash.ImageAlign = System.Drawing.ContentAlignment.TopCenter;
            this.btnEncash.Location = new System.Drawing.Point(206, 16);
            this.btnEncash.Name = "btnEncash";
            this.btnEncash.Size = new System.Drawing.Size(95, 40);
            this.btnEncash.TabIndex = 399;
            this.btnEncash.Text = "Encash";
            this.btnEncash.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btnEncash.UseVisualStyleBackColor = true;
            this.btnEncash.Click += new System.EventHandler(this.btnEncash_Click);
            this.dtpExchangeDate.Enabled = false;
            this.dtpExchangeDate.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpExchangeDate.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpExchangeDate.Location = new System.Drawing.Point(260, 60);
            this.dtpExchangeDate.Name = "dtpExchangeDate";
            this.dtpExchangeDate.Size = new System.Drawing.Size(36, 18);
            this.dtpExchangeDate.TabIndex = 397;
            this.dtpExchangeDate.Visible = false;
            this.label17.AutoSize = true;
            this.label17.BackColor = System.Drawing.Color.Transparent;
            this.label17.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label17.Location = new System.Drawing.Point(69, 68);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(48, 12);
            this.label17.TabIndex = 398;
            this.label17.Text = "Ex. Date";
            this.label17.Visible = false;
            this.cmbExchangeToAccount.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbExchangeToAccount.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbExchangeToAccount.FormattingEnabled = true;
            this.cmbExchangeToAccount.Location = new System.Drawing.Point(220, 60);
            this.cmbExchangeToAccount.Name = "cmbExchangeToAccount";
            this.cmbExchangeToAccount.Size = new System.Drawing.Size(34, 20);
            this.cmbExchangeToAccount.TabIndex = 395;
            this.cmbExchangeToAccount.Visible = false;
            this.label16.AutoSize = true;
            this.label16.BackColor = System.Drawing.Color.Transparent;
            this.label16.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label16.Location = new System.Drawing.Point(16, 68);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(47, 12);
            this.label16.TabIndex = 396;
            this.label16.Text = "Account";
            this.label16.Visible = false;
            this.txtErate.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtErate.Location = new System.Drawing.Point(176, 65);
            this.txtErate.MaxLength = 50;
            this.txtErate.Name = "txtErate";
            this.txtErate.Size = new System.Drawing.Size(40, 18);
            this.txtErate.TabIndex = 393;
            this.txtErate.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txtErate.Visible = false;
            this.txtErate.TextChanged += new System.EventHandler(this.txtErate_TextChanged);
            this.label15.AutoSize = true;
            this.label15.BackColor = System.Drawing.Color.Transparent;
            this.label15.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label15.Location = new System.Drawing.Point(123, 68);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(47, 12);
            this.label15.TabIndex = 394;
            this.label15.Text = "Ex. Rate";
            this.label15.Visible = false;
            this.txtRrate.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtRrate.Location = new System.Drawing.Point(90, 41);
            this.txtRrate.MaxLength = 50;
            this.txtRrate.Name = "txtRrate";
            this.txtRrate.Size = new System.Drawing.Size(109, 18);
            this.txtRrate.TabIndex = 391;
            this.txtRrate.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.label14.AutoSize = true;
            this.label14.BackColor = System.Drawing.Color.Transparent;
            this.label14.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label14.Location = new System.Drawing.Point(16, 44);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(68, 12);
            this.label14.TabIndex = 392;
            this.label14.Text = "Receiv. Rate";
            this.cmbCurrency.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCurrency.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCurrency.FormattingEnabled = true;
            this.cmbCurrency.Location = new System.Drawing.Point(90, 15);
            this.cmbCurrency.Name = "cmbCurrency";
            this.cmbCurrency.Size = new System.Drawing.Size(109, 20);
            this.cmbCurrency.TabIndex = 389;
            this.cmbCurrency.SelectedIndexChanged += new System.EventHandler(this.cmbCurrency_SelectedIndexChanged);
            this.label13.AutoSize = true;
            this.label13.BackColor = System.Drawing.Color.Transparent;
            this.label13.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.Location = new System.Drawing.Point(16, 18);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(51, 12);
            this.label13.TabIndex = 390;
            this.label13.Text = "Currency";
            this.lblError.BackColor = System.Drawing.Color.White;
            this.lblError.Font = new System.Drawing.Font("Microsoft Sans Serif", 30F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblError.ForeColor = System.Drawing.Color.Red;
            this.lblError.Location = new System.Drawing.Point(26, 232);
            this.lblError.Name = "lblError";
            this.lblError.Size = new System.Drawing.Size(771, 235);
            this.lblError.TabIndex = 425;
            this.lblError.Text = "Cannot Issue";
            this.lblError.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.lblError.Visible = false;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.lblError);
            this.Controls.Add(this.gbCurrency);
            this.Controls.Add(this.btnSettleRest);
            this.Controls.Add(this.lblDifCredit);
            this.Controls.Add(this.lblDifDebit);
            this.Controls.Add(this.lblCredit);
            this.Controls.Add(this.lblDebit);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.gbBasic);
            this.Controls.Add(this.gbStatus);
            this.Controls.Add(this.lblStatus);
            this.Controls.Add(this.chkPrint);
            this.Controls.Add(this.lblVoucherNo);
            this.Controls.Add(this.lblType);
            this.Controls.Add(this.btnPrint);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.grdPay);
            this.Controls.Add(this.lblMain);
            this.Controls.Add(this.gbBasic1);
            this.Controls.Add(this.gbIOU);
            this.Controls.Add(this.gbBasic2);
            this.Controls.Add(this.gbChk);
            this.Name = "ucPayments";
            this.Size = new System.Drawing.Size(834, 610);
            this.Load += new System.EventHandler(this.ucPayments_Load);
            this.gbBasic.ResumeLayout(false);
            this.gbBasic.PerformLayout();
            this.gbStatus.ResumeLayout(false);
            this.gbStatus.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdPay)).EndInit();
            this.gbBasic1.ResumeLayout(false);
            this.gbBasic1.PerformLayout();
            this.gbIOU.ResumeLayout(false);
            this.gbIOU.PerformLayout();
            this.gbBasic2.ResumeLayout(false);
            this.gbBasic2.PerformLayout();
            this.gbChk.ResumeLayout(false);
            this.gbChk.PerformLayout();
            this.gbCurrency.ResumeLayout(false);
            this.gbCurrency.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        public System.Windows.Forms.RadioButton rdbConfirm;
        public System.Windows.Forms.Button btnClearEntities;
        public System.Windows.Forms.Button btnAdd;
        public System.Windows.Forms.Label label12;
        public System.Windows.Forms.Label label11;
        public System.Windows.Forms.TextBox txtBalanceIOU;
        public System.Windows.Forms.RadioButton rdbHotel;
        public System.Windows.Forms.CheckBox chkMulIOU;
        public System.Windows.Forms.Button btnIOU;
        public System.Windows.Forms.TextBox txtIOUNo;
        public System.Windows.Forms.RadioButton rdbAgent;
        public System.Windows.Forms.TextBox txtSettledIOU;
        public System.Windows.Forms.RadioButton rdbGuide;
        public System.Windows.Forms.RadioButton rdbDriver;
        public System.Windows.Forms.Label lblGuest;
        public System.Windows.Forms.Button btnTour;
        public System.Windows.Forms.Label label9;
        public System.Windows.Forms.Label label8;
        public System.Windows.Forms.GroupBox gbBasic;
        public System.Windows.Forms.TextBox txtTourNo;
        public System.Windows.Forms.Button btnClearStatus;
        public System.Windows.Forms.Label label10;
        public System.Windows.Forms.GroupBox gbStatus;
        public System.Windows.Forms.RadioButton rdbCancel;
        public System.Windows.Forms.Label lblStatus;
        public System.Windows.Forms.CheckBox chkPrint;
        public System.Windows.Forms.Label lblVoucherNo;
        public DropDowns.DropSearch drpPayableTo;
        public System.Windows.Forms.DateTimePicker dtpPaidDate;
        public System.Windows.Forms.TextBox txtChkNo;
        public System.Windows.Forms.Label lblType;
        public System.Windows.Forms.Label label2;
        public System.Windows.Forms.Button btnPrint;
        public System.Windows.Forms.Label label4;
        public System.Windows.Forms.Button btnClose;
        public System.Windows.Forms.Button btnOk;
        public C1.Win.C1FlexGrid.C1FlexGrid grdPay;
        public System.Windows.Forms.Label lblMain;
        public System.Windows.Forms.Label label5;
        public DropDowns.DropSearch drpPayee;
        public System.Windows.Forms.Label label7;
        public System.Windows.Forms.TextBox txtRefNo;
        public System.Windows.Forms.Label lblPayRec;
        public System.Windows.Forms.GroupBox gbBasic1;
        public System.Windows.Forms.Label label1;
        public  Tourist_Management.User_Controls.ComboBox cmbCompany;
        public System.Windows.Forms.Label label6;
        public System.Windows.Forms.TextBox txtDescription;
        public System.Windows.Forms.GroupBox gbIOU;
        public System.Windows.Forms.Label label3;
        public System.Windows.Forms.GroupBox gbBasic2;
        public System.Windows.Forms.GroupBox gbChk;
        public System.Windows.Forms.DateTimePicker dtpChkDate;
        private System.Windows.Forms.Label lblDebit;
        private System.Windows.Forms.Label lblCredit;
        private System.Windows.Forms.Label lblDifDebit;
        private System.Windows.Forms.Label lblDifCredit;
        private System.Windows.Forms.Button btnSettleRest;
        public  Tourist_Management.User_Controls.ComboBox cmbCurrency;
        public System.Windows.Forms.Label label13;
        public System.Windows.Forms.TextBox txtErate;
        public System.Windows.Forms.Label label15;
        public System.Windows.Forms.TextBox txtRrate;
        public System.Windows.Forms.Label label14;
        public System.Windows.Forms.RadioButton rdbOther;
        public  Tourist_Management.User_Controls.ComboBox cmbExchangeToAccount;
        public System.Windows.Forms.Label label16;
        public System.Windows.Forms.DateTimePicker dtpExchangeDate;
        public System.Windows.Forms.Label label17;
        private System.Windows.Forms.Button btnEncash;
        private System.Windows.Forms.Label lblError;
        public System.Windows.Forms.GroupBox gbCurrency;
    }
}
