namespace Tourist_Management.User_Controls
{
    partial class ucPaymentsReport
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Component Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucPaymentsReport));
            this.grdPay = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.lblName = new System.Windows.Forms.Label();
            this.gbType = new System.Windows.Forms.GroupBox();
            this.chkCancel = new System.Windows.Forms.CheckBox();
            this.btnClearFilter = new System.Windows.Forms.Button();
            this.label2 = new System.Windows.Forms.Label();
            this.rdbUnsettled = new System.Windows.Forms.RadioButton();
            this.rdbSettled = new System.Windows.Forms.RadioButton();
            this.gbGroupBy = new System.Windows.Forms.GroupBox();
            this.radioButton1 = new System.Windows.Forms.RadioButton();
            this.radioButton2 = new System.Windows.Forms.RadioButton();
            this.radioButton3 = new System.Windows.Forms.RadioButton();
            this.btnShow = new System.Windows.Forms.Button();
            this.groupBox31 = new System.Windows.Forms.GroupBox();
            this.chkCmpny = new System.Windows.Forms.CheckBox();
            this.cmbCompany = new  Tourist_Management.User_Controls.ComboBox();
            this.label43 = new System.Windows.Forms.Label();
            this.groupBox10 = new System.Windows.Forms.GroupBox();
            this.drpHandled = new Tourist_Management.DropDowns.DropSearch();
            this.chkAllHandled = new System.Windows.Forms.CheckBox();
            this.label40 = new System.Windows.Forms.Label();
            this.label24 = new System.Windows.Forms.Label();
            this.groupBox8 = new System.Windows.Forms.GroupBox();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.dtpToDate = new System.Windows.Forms.DateTimePicker();
            this.label33 = new System.Windows.Forms.Label();
            this.dtpFromDate = new System.Windows.Forms.DateTimePicker();
            this.label37 = new System.Windows.Forms.Label();
            this.groupBox9 = new System.Windows.Forms.GroupBox();
            this.drpPaid = new Tourist_Management.DropDowns.DropSearch();
            this.chkPaidBy = new System.Windows.Forms.CheckBox();
            this.lblPayOrReceive = new System.Windows.Forms.Label();
            this.chkFilterByDate = new System.Windows.Forms.CheckBox();
            this.btnPrint = new System.Windows.Forms.Button();
            this.btnClose = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.grdPay)).BeginInit();
            this.gbType.SuspendLayout();
            this.gbGroupBy.SuspendLayout();
            this.groupBox31.SuspendLayout();
            this.groupBox10.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.groupBox9.SuspendLayout();
            this.SuspendLayout();
            this.grdPay.BackColor = System.Drawing.Color.Transparent;
            this.grdPay.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.grdPay.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.grdPay.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdPay.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdPay.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grdPay.Location = new System.Drawing.Point(10, 127);
            this.grdPay.Name = "grdPay";
            this.grdPay.Size = new System.Drawing.Size(968, 318);
            this.grdPay.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdPay.Styles"));
            this.grdPay.TabIndex = 405;
            this.lblName.AutoSize = true;
            this.lblName.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblName.Location = new System.Drawing.Point(6, 5);
            this.lblName.Name = "lblName";
            this.lblName.Size = new System.Drawing.Size(167, 18);
            this.lblName.TabIndex = 406;
            this.lblName.Text = "I.O.U. Statements";
            this.gbType.Controls.Add(this.chkCancel);
            this.gbType.Controls.Add(this.btnClearFilter);
            this.gbType.Controls.Add(this.label2);
            this.gbType.Controls.Add(this.rdbUnsettled);
            this.gbType.Controls.Add(this.rdbSettled);
            this.gbType.Location = new System.Drawing.Point(804, 52);
            this.gbType.Name = "gbType";
            this.gbType.Size = new System.Drawing.Size(135, 69);
            this.gbType.TabIndex = 407;
            this.gbType.TabStop = false;
            this.chkCancel.AutoSize = true;
            this.chkCancel.BackColor = System.Drawing.Color.Transparent;
            this.chkCancel.Location = new System.Drawing.Point(6, 49);
            this.chkCancel.Name = "chkCancel";
            this.chkCancel.Size = new System.Drawing.Size(126, 17);
            this.chkCancel.TabIndex = 356;
            this.chkCancel.Text = "Show Cancelled Also";
            this.chkCancel.UseVisualStyleBackColor = false;
            this.btnClearFilter.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClearFilter.Location = new System.Drawing.Point(116, 5);
            this.btnClearFilter.Name = "btnClearFilter";
            this.btnClearFilter.Size = new System.Drawing.Size(18, 20);
            this.btnClearFilter.TabIndex = 419;
            this.btnClearFilter.Text = "X";
            this.btnClearFilter.UseVisualStyleBackColor = true;
            this.btnClearFilter.Click += new System.EventHandler(this.btnClearFilter_Click);
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.SystemColors.Control;
            this.label2.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label2.Location = new System.Drawing.Point(1, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(54, 14);
            this.label2.TabIndex = 356;
            this.label2.Text = "FILTER";
            this.rdbUnsettled.AutoSize = true;
            this.rdbUnsettled.Location = new System.Drawing.Point(63, 25);
            this.rdbUnsettled.Name = "rdbUnsettled";
            this.rdbUnsettled.Size = new System.Drawing.Size(70, 17);
            this.rdbUnsettled.TabIndex = 1;
            this.rdbUnsettled.TabStop = true;
            this.rdbUnsettled.Text = "Unsettled";
            this.rdbUnsettled.UseVisualStyleBackColor = true;
            this.rdbSettled.AutoSize = true;
            this.rdbSettled.Location = new System.Drawing.Point(5, 25);
            this.rdbSettled.Name = "rdbSettled";
            this.rdbSettled.Size = new System.Drawing.Size(58, 17);
            this.rdbSettled.TabIndex = 0;
            this.rdbSettled.TabStop = true;
            this.rdbSettled.Text = "Settled";
            this.rdbSettled.UseVisualStyleBackColor = true;
            this.gbGroupBy.Controls.Add(this.radioButton1);
            this.gbGroupBy.Controls.Add(this.radioButton2);
            this.gbGroupBy.Controls.Add(this.radioButton3);
            this.gbGroupBy.Location = new System.Drawing.Point(621, 458);
            this.gbGroupBy.Name = "gbGroupBy";
            this.gbGroupBy.Size = new System.Drawing.Size(200, 47);
            this.gbGroupBy.TabIndex = 408;
            this.gbGroupBy.TabStop = false;
            this.gbGroupBy.Text = "Report Group By";
            this.radioButton1.AutoSize = true;
            this.radioButton1.Checked = true;
            this.radioButton1.Location = new System.Drawing.Point(9, 19);
            this.radioButton1.Name = "radioButton1";
            this.radioButton1.Size = new System.Drawing.Size(51, 17);
            this.radioButton1.TabIndex = 2;
            this.radioButton1.TabStop = true;
            this.radioButton1.Text = "None";
            this.radioButton1.UseVisualStyleBackColor = true;
            this.radioButton2.AutoSize = true;
            this.radioButton2.Location = new System.Drawing.Point(131, 19);
            this.radioButton2.Name = "radioButton2";
            this.radioButton2.Size = new System.Drawing.Size(65, 17);
            this.radioButton2.TabIndex = 1;
            this.radioButton2.Text = "Handled";
            this.radioButton2.UseVisualStyleBackColor = true;
            this.radioButton3.AutoSize = true;
            this.radioButton3.Location = new System.Drawing.Point(64, 19);
            this.radioButton3.Name = "radioButton3";
            this.radioButton3.Size = new System.Drawing.Size(62, 17);
            this.radioButton3.TabIndex = 0;
            this.radioButton3.Text = "Paid To";
            this.radioButton3.UseVisualStyleBackColor = true;
            this.btnShow.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnShow.Image = global::Tourist_Management.Properties.Resources.filter;
            this.btnShow.Location = new System.Drawing.Point(943, 71);
            this.btnShow.Name = "btnShow";
            this.btnShow.Size = new System.Drawing.Size(35, 36);
            this.btnShow.TabIndex = 409;
            this.btnShow.UseVisualStyleBackColor = true;
            this.btnShow.Click += new System.EventHandler(this.btnShow_Click);
            this.groupBox31.BackColor = System.Drawing.Color.Transparent;
            this.groupBox31.Controls.Add(this.chkCmpny);
            this.groupBox31.Controls.Add(this.cmbCompany);
            this.groupBox31.Controls.Add(this.label43);
            this.groupBox31.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox31.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.groupBox31.Location = new System.Drawing.Point(202, 48);
            this.groupBox31.Name = "groupBox31";
            this.groupBox31.Size = new System.Drawing.Size(224, 51);
            this.groupBox31.TabIndex = 417;
            this.groupBox31.TabStop = false;
            this.groupBox31.Text = "BY COMPANY";
            this.chkCmpny.AutoSize = true;
            this.chkCmpny.BackColor = System.Drawing.Color.White;
            this.chkCmpny.Location = new System.Drawing.Point(103, 1);
            this.chkCmpny.Name = "chkCmpny";
            this.chkCmpny.Size = new System.Drawing.Size(15, 14);
            this.chkCmpny.TabIndex = 381;
            this.chkCmpny.UseVisualStyleBackColor = false;
            this.chkCmpny.CheckedChanged += new System.EventHandler(this.chkCmpny_CheckedChanged);
            this.cmbCompany.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCompany.Enabled = false;
            this.cmbCompany.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCompany.FormattingEnabled = true;
            this.cmbCompany.Location = new System.Drawing.Point(66, 18);
            this.cmbCompany.Name = "cmbCompany";
            this.cmbCompany.Size = new System.Drawing.Size(149, 21);
            this.cmbCompany.TabIndex = 380;
            this.label43.AutoSize = true;
            this.label43.BackColor = System.Drawing.Color.Transparent;
            this.label43.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label43.ForeColor = System.Drawing.Color.Black;
            this.label43.Location = new System.Drawing.Point(5, 22);
            this.label43.Name = "label43";
            this.label43.Size = new System.Drawing.Size(62, 13);
            this.label43.TabIndex = 379;
            this.label43.Text = "Company";
            this.groupBox10.Controls.Add(this.drpHandled);
            this.groupBox10.Controls.Add(this.chkAllHandled);
            this.groupBox10.Controls.Add(this.label40);
            this.groupBox10.Location = new System.Drawing.Point(623, 52);
            this.groupBox10.Name = "groupBox10";
            this.groupBox10.Size = new System.Drawing.Size(175, 53);
            this.groupBox10.TabIndex = 416;
            this.groupBox10.TabStop = false;
            this.drpHandled.BackColor = System.Drawing.Color.Transparent;
            this.drpHandled.DataSource = null;
            this.drpHandled.Enabled = false;
            this.drpHandled.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpHandled.Location = new System.Drawing.Point(8, 22);
            this.drpHandled.Name = "drpHandled";
            this.drpHandled.SelectedText = "";
            this.drpHandled.SelectedValue = "";
            this.drpHandled.Size = new System.Drawing.Size(160, 21);
            this.drpHandled.TabIndex = 352;
            this.chkAllHandled.AutoSize = true;
            this.chkAllHandled.BackColor = System.Drawing.Color.White;
            this.chkAllHandled.Location = new System.Drawing.Point(95, 2);
            this.chkAllHandled.Name = "chkAllHandled";
            this.chkAllHandled.Size = new System.Drawing.Size(15, 14);
            this.chkAllHandled.TabIndex = 355;
            this.chkAllHandled.UseVisualStyleBackColor = false;
            this.chkAllHandled.CheckedChanged += new System.EventHandler(this.chkAllHandled_CheckedChanged);
            this.label40.AutoSize = true;
            this.label40.BackColor = System.Drawing.SystemColors.Control;
            this.label40.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label40.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label40.Location = new System.Drawing.Point(0, 0);
            this.label40.Name = "label40";
            this.label40.Size = new System.Drawing.Size(95, 14);
            this.label40.TabIndex = 353;
            this.label40.Text = "HANDLED BY";
            this.label24.AutoSize = true;
            this.label24.BackColor = System.Drawing.Color.Transparent;
            this.label24.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label24.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label24.Location = new System.Drawing.Point(13, 45);
            this.label24.Name = "label24";
            this.label24.Size = new System.Drawing.Size(116, 14);
            this.label24.TabIndex = 413;
            this.label24.Text = "FILTER BY DATE";
            this.groupBox8.BackColor = System.Drawing.Color.Gray;
            this.groupBox8.Location = new System.Drawing.Point(8, 26);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new System.Drawing.Size(975, 1);
            this.groupBox8.TabIndex = 411;
            this.groupBox8.TabStop = false;
            this.groupBox7.BackColor = System.Drawing.Color.Transparent;
            this.groupBox7.Controls.Add(this.dtpToDate);
            this.groupBox7.Controls.Add(this.label33);
            this.groupBox7.Controls.Add(this.dtpFromDate);
            this.groupBox7.Controls.Add(this.label37);
            this.groupBox7.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox7.Location = new System.Drawing.Point(10, 49);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(188, 72);
            this.groupBox7.TabIndex = 410;
            this.groupBox7.TabStop = false;
            this.dtpToDate.Enabled = false;
            this.dtpToDate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpToDate.Location = new System.Drawing.Point(38, 45);
            this.dtpToDate.Name = "dtpToDate";
            this.dtpToDate.Size = new System.Drawing.Size(131, 20);
            this.dtpToDate.TabIndex = 249;
            this.label33.AutoSize = true;
            this.label33.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label33.Location = new System.Drawing.Point(3, 47);
            this.label33.Name = "label33";
            this.label33.Size = new System.Drawing.Size(21, 13);
            this.label33.TabIndex = 248;
            this.label33.Text = "To";
            this.dtpFromDate.Enabled = false;
            this.dtpFromDate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpFromDate.Location = new System.Drawing.Point(38, 19);
            this.dtpFromDate.Name = "dtpFromDate";
            this.dtpFromDate.Size = new System.Drawing.Size(132, 20);
            this.dtpFromDate.TabIndex = 247;
            this.label37.AutoSize = true;
            this.label37.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label37.Location = new System.Drawing.Point(3, 21);
            this.label37.Name = "label37";
            this.label37.Size = new System.Drawing.Size(36, 13);
            this.label37.TabIndex = 246;
            this.label37.Text = "From";
            this.groupBox9.Controls.Add(this.drpPaid);
            this.groupBox9.Controls.Add(this.chkPaidBy);
            this.groupBox9.Controls.Add(this.lblPayOrReceive);
            this.groupBox9.Location = new System.Drawing.Point(437, 49);
            this.groupBox9.Name = "groupBox9";
            this.groupBox9.Size = new System.Drawing.Size(173, 53);
            this.groupBox9.TabIndex = 415;
            this.groupBox9.TabStop = false;
            this.drpPaid.BackColor = System.Drawing.Color.Transparent;
            this.drpPaid.DataSource = null;
            this.drpPaid.Enabled = false;
            this.drpPaid.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpPaid.Location = new System.Drawing.Point(8, 19);
            this.drpPaid.Name = "drpPaid";
            this.drpPaid.SelectedText = "";
            this.drpPaid.SelectedValue = "";
            this.drpPaid.Size = new System.Drawing.Size(160, 21);
            this.drpPaid.TabIndex = 349;
            this.chkPaidBy.AutoSize = true;
            this.chkPaidBy.BackColor = System.Drawing.Color.White;
            this.chkPaidBy.Location = new System.Drawing.Point(67, 0);
            this.chkPaidBy.Name = "chkPaidBy";
            this.chkPaidBy.Size = new System.Drawing.Size(15, 14);
            this.chkPaidBy.TabIndex = 354;
            this.chkPaidBy.UseVisualStyleBackColor = false;
            this.chkPaidBy.CheckedChanged += new System.EventHandler(this.chkPaidBy_CheckedChanged);
            this.lblPayOrReceive.AutoSize = true;
            this.lblPayOrReceive.BackColor = System.Drawing.SystemColors.Control;
            this.lblPayOrReceive.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPayOrReceive.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.lblPayOrReceive.Location = new System.Drawing.Point(4, -1);
            this.lblPayOrReceive.Name = "lblPayOrReceive";
            this.lblPayOrReceive.Size = new System.Drawing.Size(64, 14);
            this.lblPayOrReceive.TabIndex = 353;
            this.lblPayOrReceive.Text = "PAID TO";
            this.chkFilterByDate.AutoSize = true;
            this.chkFilterByDate.BackColor = System.Drawing.Color.White;
            this.chkFilterByDate.Location = new System.Drawing.Point(129, 46);
            this.chkFilterByDate.Name = "chkFilterByDate";
            this.chkFilterByDate.Size = new System.Drawing.Size(15, 14);
            this.chkFilterByDate.TabIndex = 418;
            this.chkFilterByDate.UseVisualStyleBackColor = false;
            this.chkFilterByDate.CheckedChanged += new System.EventHandler(this.chkFilterByDate_CheckedChanged);
            this.btnPrint.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPrint.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPrint.Image = global::Tourist_Management.Properties.Resources.search;
            this.btnPrint.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPrint.Location = new System.Drawing.Point(825, 475);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.Size = new System.Drawing.Size(76, 29);
            this.btnPrint.TabIndex = 420;
            this.btnPrint.Text = "&Preview";
            this.btnPrint.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPrint.UseVisualStyleBackColor = true;
            this.btnPrint.Click += new System.EventHandler(this.btnPrint_Click);
            this.btnClose.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnClose.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClose.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnClose.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.Location = new System.Drawing.Point(906, 474);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new System.Drawing.Size(72, 30);
            this.btnClose.TabIndex = 419;
            this.btnClose.Text = "&Close";
            this.btnClose.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose.UseVisualStyleBackColor = true;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.btnPrint);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.chkFilterByDate);
            this.Controls.Add(this.btnShow);
            this.Controls.Add(this.groupBox31);
            this.Controls.Add(this.groupBox10);
            this.Controls.Add(this.label24);
            this.Controls.Add(this.groupBox8);
            this.Controls.Add(this.groupBox7);
            this.Controls.Add(this.groupBox9);
            this.Controls.Add(this.gbGroupBy);
            this.Controls.Add(this.gbType);
            this.Controls.Add(this.lblName);
            this.Controls.Add(this.grdPay);
            this.Name = "ucPaymentsReport";
            this.Size = new System.Drawing.Size(987, 516);
            this.Load += new System.EventHandler(this.ucPaymentsReport_Load);
            ((System.ComponentModel.ISupportInitialize)(this.grdPay)).EndInit();
            this.gbType.ResumeLayout(false);
            this.gbType.PerformLayout();
            this.gbGroupBy.ResumeLayout(false);
            this.gbGroupBy.PerformLayout();
            this.groupBox31.ResumeLayout(false);
            this.groupBox31.PerformLayout();
            this.groupBox10.ResumeLayout(false);
            this.groupBox10.PerformLayout();
            this.groupBox7.ResumeLayout(false);
            this.groupBox7.PerformLayout();
            this.groupBox9.ResumeLayout(false);
            this.groupBox9.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        public C1.Win.C1FlexGrid.C1FlexGrid grdPay;
        private System.Windows.Forms.Label lblName;
        private System.Windows.Forms.GroupBox gbType;
        private System.Windows.Forms.RadioButton rdbUnsettled;
        private System.Windows.Forms.RadioButton rdbSettled;
        private System.Windows.Forms.GroupBox gbGroupBy;
        private System.Windows.Forms.RadioButton radioButton1;
        private System.Windows.Forms.RadioButton radioButton2;
        private System.Windows.Forms.RadioButton radioButton3;
        private System.Windows.Forms.Button btnShow;
        private System.Windows.Forms.GroupBox groupBox31;
        private System.Windows.Forms.CheckBox chkCmpny;
        private  Tourist_Management.User_Controls.ComboBox cmbCompany;
        private System.Windows.Forms.Label label43;
        private System.Windows.Forms.GroupBox groupBox10;
        private DropDowns.DropSearch drpHandled;
        private System.Windows.Forms.CheckBox chkAllHandled;
        private System.Windows.Forms.Label label40;
        private System.Windows.Forms.Label label24;
        private System.Windows.Forms.GroupBox groupBox8;
        private System.Windows.Forms.GroupBox groupBox7;
        private System.Windows.Forms.DateTimePicker dtpToDate;
        private System.Windows.Forms.Label label33;
        private System.Windows.Forms.DateTimePicker dtpFromDate;
        private System.Windows.Forms.Label label37;
        private System.Windows.Forms.GroupBox groupBox9;
        private DropDowns.DropSearch drpPaid;
        private System.Windows.Forms.CheckBox chkPaidBy;
        private System.Windows.Forms.Label lblPayOrReceive;
        private System.Windows.Forms.CheckBox chkFilterByDate;
        private System.Windows.Forms.Label label2;
        public System.Windows.Forms.Button btnClearFilter;
        public System.Windows.Forms.Button btnPrint;
        public System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.CheckBox chkCancel;
    }
}
