namespace Tourist_Management.User_Controls
{
    partial class ucTransEmail
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Component Designer generated code
        private void InitializeComponent()
        {
            this.groupBox16 = new System.Windows.Forms.GroupBox();
            this.rtbBody = new System.Windows.Forms.RichTextBox();
            this.groupBox15 = new System.Windows.Forms.GroupBox();
            this.txtCC = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.btnEmailConts = new System.Windows.Forms.Button();
            this.txtSubject = new System.Windows.Forms.TextBox();
            this.txtTo = new System.Windows.Forms.TextBox();
            this.label19 = new System.Windows.Forms.Label();
            this.label18 = new System.Windows.Forms.Label();
            this.groupBox11 = new System.Windows.Forms.GroupBox();
            this.chkTotEx = new System.Windows.Forms.CheckBox();
            this.chkExSum = new System.Windows.Forms.CheckBox();
            this.chkSightD = new System.Windows.Forms.CheckBox();
            this.chkHotelD = new System.Windows.Forms.CheckBox();
            this.chkVehicleD = new System.Windows.Forms.CheckBox();
            this.chkDriverD = new System.Windows.Forms.CheckBox();
            this.btnEmail = new System.Windows.Forms.Button();
            this.groupBox16.SuspendLayout();
            this.groupBox15.SuspendLayout();
            this.groupBox11.SuspendLayout();
            this.SuspendLayout();
            this.groupBox16.BackColor = System.Drawing.Color.Transparent;
            this.groupBox16.Controls.Add(this.rtbBody);
            this.groupBox16.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox16.Location = new System.Drawing.Point(12, 183);
            this.groupBox16.Name = "groupBox16";
            this.groupBox16.Size = new System.Drawing.Size(728, 162);
            this.groupBox16.TabIndex = 242;
            this.groupBox16.TabStop = false;
            this.groupBox16.Text = "Email Body";
            this.rtbBody.AccessibleRole = System.Windows.Forms.AccessibleRole.None;
            this.rtbBody.Location = new System.Drawing.Point(9, 19);
            this.rtbBody.Name = "rtbBody";
            this.rtbBody.Size = new System.Drawing.Size(704, 137);
            this.rtbBody.TabIndex = 0;
            this.rtbBody.Text = "";
            this.groupBox15.BackColor = System.Drawing.Color.Transparent;
            this.groupBox15.Controls.Add(this.txtCC);
            this.groupBox15.Controls.Add(this.label1);
            this.groupBox15.Controls.Add(this.btnEmailConts);
            this.groupBox15.Controls.Add(this.txtSubject);
            this.groupBox15.Controls.Add(this.txtTo);
            this.groupBox15.Controls.Add(this.label19);
            this.groupBox15.Controls.Add(this.label18);
            this.groupBox15.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox15.Location = new System.Drawing.Point(204, 7);
            this.groupBox15.Name = "groupBox15";
            this.groupBox15.Size = new System.Drawing.Size(536, 174);
            this.groupBox15.TabIndex = 241;
            this.groupBox15.TabStop = false;
            this.groupBox15.Text = "General Details";
            this.txtCC.Location = new System.Drawing.Point(68, 53);
            this.txtCC.Name = "txtCC";
            this.txtCC.Size = new System.Drawing.Size(453, 21);
            this.txtCC.TabIndex = 9;
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(7, 56);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(25, 13);
            this.label1.TabIndex = 8;
            this.label1.Text = "CC";
            this.btnEmailConts.BackColor = System.Drawing.SystemColors.Control;
            this.btnEmailConts.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnEmailConts.Location = new System.Drawing.Point(486, 22);
            this.btnEmailConts.Name = "btnEmailConts";
            this.btnEmailConts.Size = new System.Drawing.Size(33, 23);
            this.btnEmailConts.TabIndex = 7;
            this.btnEmailConts.Text = "...";
            this.btnEmailConts.UseVisualStyleBackColor = false;
            this.btnEmailConts.Click += new System.EventHandler(this.btnEmailConts_Click);
            this.txtSubject.Location = new System.Drawing.Point(68, 77);
            this.txtSubject.Name = "txtSubject";
            this.txtSubject.Size = new System.Drawing.Size(453, 21);
            this.txtSubject.TabIndex = 5;
            this.txtTo.Location = new System.Drawing.Point(68, 24);
            this.txtTo.Name = "txtTo";
            this.txtTo.Size = new System.Drawing.Size(412, 21);
            this.txtTo.TabIndex = 4;
            this.label19.AutoSize = true;
            this.label19.Location = new System.Drawing.Point(7, 80);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(50, 13);
            this.label19.TabIndex = 2;
            this.label19.Text = "Subject";
            this.label18.AutoSize = true;
            this.label18.Location = new System.Drawing.Point(7, 27);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(21, 13);
            this.label18.TabIndex = 1;
            this.label18.Text = "To";
            this.groupBox11.BackColor = System.Drawing.Color.Transparent;
            this.groupBox11.Controls.Add(this.chkTotEx);
            this.groupBox11.Controls.Add(this.chkExSum);
            this.groupBox11.Controls.Add(this.chkSightD);
            this.groupBox11.Controls.Add(this.chkHotelD);
            this.groupBox11.Controls.Add(this.chkVehicleD);
            this.groupBox11.Controls.Add(this.chkDriverD);
            this.groupBox11.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox11.Location = new System.Drawing.Point(6, 7);
            this.groupBox11.Name = "groupBox11";
            this.groupBox11.Size = new System.Drawing.Size(191, 174);
            this.groupBox11.TabIndex = 240;
            this.groupBox11.TabStop = false;
            this.groupBox11.Text = "Email Attachments";
            this.chkTotEx.AutoSize = true;
            this.chkTotEx.Enabled = false;
            this.chkTotEx.Location = new System.Drawing.Point(9, 147);
            this.chkTotEx.Name = "chkTotEx";
            this.chkTotEx.Size = new System.Drawing.Size(126, 17);
            this.chkTotEx.TabIndex = 5;
            this.chkTotEx.Text = "Total Expenditure";
            this.chkTotEx.UseVisualStyleBackColor = true;
            this.chkExSum.AutoSize = true;
            this.chkExSum.Checked = true;
            this.chkExSum.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkExSum.Location = new System.Drawing.Point(9, 121);
            this.chkExSum.Name = "chkExSum";
            this.chkExSum.Size = new System.Drawing.Size(154, 17);
            this.chkExSum.TabIndex = 4;
            this.chkExSum.Text = "Expenditure Summary";
            this.chkExSum.UseVisualStyleBackColor = true;
            this.chkSightD.AutoSize = true;
            this.chkSightD.Enabled = false;
            this.chkSightD.Location = new System.Drawing.Point(9, 98);
            this.chkSightD.Name = "chkSightD";
            this.chkSightD.Size = new System.Drawing.Size(186, 17);
            this.chkSightD.TabIndex = 3;
            this.chkSightD.Text = "Attach Sightseeing/s Details";
            this.chkSightD.UseVisualStyleBackColor = true;
            this.chkHotelD.AutoSize = true;
            this.chkHotelD.Enabled = false;
            this.chkHotelD.Location = new System.Drawing.Point(9, 75);
            this.chkHotelD.Name = "chkHotelD";
            this.chkHotelD.Size = new System.Drawing.Size(149, 17);
            this.chkHotelD.TabIndex = 2;
            this.chkHotelD.Text = "Attach Hotel/s Details";
            this.chkHotelD.UseVisualStyleBackColor = true;
            this.chkVehicleD.AutoSize = true;
            this.chkVehicleD.Enabled = false;
            this.chkVehicleD.Location = new System.Drawing.Point(9, 50);
            this.chkVehicleD.Name = "chkVehicleD";
            this.chkVehicleD.Size = new System.Drawing.Size(161, 17);
            this.chkVehicleD.TabIndex = 1;
            this.chkVehicleD.Text = "Attach Vehicle/s Details";
            this.chkVehicleD.UseVisualStyleBackColor = true;
            this.chkDriverD.AutoSize = true;
            this.chkDriverD.Enabled = false;
            this.chkDriverD.Location = new System.Drawing.Point(9, 27);
            this.chkDriverD.Name = "chkDriverD";
            this.chkDriverD.Size = new System.Drawing.Size(156, 17);
            this.chkDriverD.TabIndex = 0;
            this.chkDriverD.Text = "Attach Driver/s Details";
            this.chkDriverD.UseVisualStyleBackColor = true;
            this.btnEmail.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnEmail.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEmail.Location = new System.Drawing.Point(650, 351);
            this.btnEmail.Name = "btnEmail";
            this.btnEmail.Size = new System.Drawing.Size(75, 23);
            this.btnEmail.TabIndex = 243;
            this.btnEmail.Text = "&Email This";
            this.btnEmail.UseVisualStyleBackColor = true;
            this.btnEmail.Click += new System.EventHandler(this.btnEmail_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.Controls.Add(this.groupBox16);
            this.Controls.Add(this.groupBox15);
            this.Controls.Add(this.groupBox11);
            this.Controls.Add(this.btnEmail);
            this.Name = "ucTransEmail";
            this.Size = new System.Drawing.Size(752, 384);
            this.Load += new System.EventHandler(this.ucTransEmail_Load);
            this.groupBox16.ResumeLayout(false);
            this.groupBox15.ResumeLayout(false);
            this.groupBox15.PerformLayout();
            this.groupBox11.ResumeLayout(false);
            this.groupBox11.PerformLayout();
            this.ResumeLayout(false);
        }
        #endregion
        public System.Windows.Forms.GroupBox groupBox16;
        public System.Windows.Forms.RichTextBox rtbBody;
        public System.Windows.Forms.GroupBox groupBox15;
        public System.Windows.Forms.TextBox txtSubject;
        public System.Windows.Forms.TextBox txtTo;
        public System.Windows.Forms.Label label19;
        public System.Windows.Forms.Label label18;
        public System.Windows.Forms.GroupBox groupBox11;
        public System.Windows.Forms.CheckBox chkTotEx;
        public System.Windows.Forms.CheckBox chkExSum;
        public System.Windows.Forms.CheckBox chkSightD;
        public System.Windows.Forms.CheckBox chkHotelD;
        public System.Windows.Forms.CheckBox chkVehicleD;
        public System.Windows.Forms.CheckBox chkDriverD;
        public System.Windows.Forms.Button btnEmail;
        public System.Windows.Forms.Button btnEmailConts;
        public System.Windows.Forms.TextBox txtCC;
        public System.Windows.Forms.Label label1;
    }
}
