namespace Tourist_Management.User_Controls
{
    partial class ucTransOther
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Component Designer generated code
        private void InitializeComponent()
        {
            this.groupBox40 = new System.Windows.Forms.GroupBox();
            this.rtbArrangement = new System.Windows.Forms.RichTextBox();
            this.label55 = new System.Windows.Forms.Label();
            this.groupBox32 = new System.Windows.Forms.GroupBox();
            this.label39 = new System.Windows.Forms.Label();
            this.label38 = new System.Windows.Forms.Label();
            this.label37 = new System.Windows.Forms.Label();
            this.groupBox33 = new System.Windows.Forms.GroupBox();
            this.rtbOtherInstructions = new System.Windows.Forms.RichTextBox();
            this.label36 = new System.Windows.Forms.Label();
            this.rtbBillingIns = new System.Windows.Forms.RichTextBox();
            this.groupBox31 = new System.Windows.Forms.GroupBox();
            this.label35 = new System.Windows.Forms.Label();
            this.rtbAmendNo = new System.Windows.Forms.RichTextBox();
            this.rtbReferance = new System.Windows.Forms.RichTextBox();
            this.rtbNotice = new System.Windows.Forms.RichTextBox();
            this.btnBilling = new System.Windows.Forms.Button();
            this.btnOther = new System.Windows.Forms.Button();
            this.SuspendLayout();
            this.groupBox40.BackColor = System.Drawing.Color.Gray;
            this.groupBox40.Location = new System.Drawing.Point(214, 187);
            this.groupBox40.Name = "groupBox40";
            this.groupBox40.Size = new System.Drawing.Size(525, 3);
            this.groupBox40.TabIndex = 344;
            this.groupBox40.TabStop = false;
            this.rtbArrangement.AccessibleRole = System.Windows.Forms.AccessibleRole.None;
            this.rtbArrangement.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rtbArrangement.Location = new System.Drawing.Point(5, 197);
            this.rtbArrangement.Name = "rtbArrangement";
            this.rtbArrangement.Size = new System.Drawing.Size(729, 38);
            this.rtbArrangement.TabIndex = 345;
            this.rtbArrangement.Text = "Above arrangement is confirmed on the telephone by to ";
            this.label55.AutoSize = true;
            this.label55.BackColor = System.Drawing.Color.Transparent;
            this.label55.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label55.ForeColor = System.Drawing.Color.Blue;
            this.label55.Location = new System.Drawing.Point(6, 177);
            this.label55.Name = "label55";
            this.label55.Size = new System.Drawing.Size(205, 13);
            this.label55.TabIndex = 343;
            this.label55.Text = "ARRANGEMENT CONFIRMATION";
            this.groupBox32.BackColor = System.Drawing.Color.Gray;
            this.groupBox32.Location = new System.Drawing.Point(155, 89);
            this.groupBox32.Name = "groupBox32";
            this.groupBox32.Size = new System.Drawing.Size(584, 3);
            this.groupBox32.TabIndex = 334;
            this.groupBox32.TabStop = false;
            this.label39.AutoSize = true;
            this.label39.BackColor = System.Drawing.Color.Transparent;
            this.label39.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label39.Location = new System.Drawing.Point(610, 254);
            this.label39.Name = "label39";
            this.label39.Size = new System.Drawing.Size(45, 13);
            this.label39.TabIndex = 342;
            this.label39.Text = "Others";
            this.label38.AutoSize = true;
            this.label38.BackColor = System.Drawing.Color.Transparent;
            this.label38.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label38.Location = new System.Drawing.Point(348, 254);
            this.label38.Name = "label38";
            this.label38.Size = new System.Drawing.Size(71, 13);
            this.label38.TabIndex = 340;
            this.label38.Text = "References";
            this.label37.AutoSize = true;
            this.label37.BackColor = System.Drawing.Color.Transparent;
            this.label37.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label37.Location = new System.Drawing.Point(45, 259);
            this.label37.Name = "label37";
            this.label37.Size = new System.Drawing.Size(158, 13);
            this.label37.TabIndex = 338;
            this.label37.Text = "Amendment To Voucher #";
            this.groupBox33.BackColor = System.Drawing.Color.Gray;
            this.groupBox33.Location = new System.Drawing.Point(6, 247);
            this.groupBox33.Name = "groupBox33";
            this.groupBox33.Size = new System.Drawing.Size(735, 3);
            this.groupBox33.TabIndex = 337;
            this.groupBox33.TabStop = false;
            this.rtbOtherInstructions.AccessibleRole = System.Windows.Forms.AccessibleRole.None;
            this.rtbOtherInstructions.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.rtbOtherInstructions.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rtbOtherInstructions.Location = new System.Drawing.Point(2, 100);
            this.rtbOtherInstructions.Name = "rtbOtherInstructions";
            this.rtbOtherInstructions.Size = new System.Drawing.Size(687, 70);
            this.rtbOtherInstructions.TabIndex = 335;
            this.rtbOtherInstructions.Text = "";
            this.label36.AutoSize = true;
            this.label36.BackColor = System.Drawing.Color.Transparent;
            this.label36.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label36.ForeColor = System.Drawing.Color.Blue;
            this.label36.Location = new System.Drawing.Point(3, 80);
            this.label36.Name = "label36";
            this.label36.Size = new System.Drawing.Size(149, 13);
            this.label36.TabIndex = 333;
            this.label36.Text = "OTHER INSTRUCTIONS";
            this.rtbBillingIns.AccessibleRole = System.Windows.Forms.AccessibleRole.None;
            this.rtbBillingIns.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rtbBillingIns.Location = new System.Drawing.Point(4, 23);
            this.rtbBillingIns.Name = "rtbBillingIns";
            this.rtbBillingIns.Size = new System.Drawing.Size(685, 52);
            this.rtbBillingIns.TabIndex = 332;
            this.rtbBillingIns.Text = "All extras to be collected directly";
            this.groupBox31.BackColor = System.Drawing.Color.Gray;
            this.groupBox31.Location = new System.Drawing.Point(169, 13);
            this.groupBox31.Name = "groupBox31";
            this.groupBox31.Size = new System.Drawing.Size(572, 2);
            this.groupBox31.TabIndex = 331;
            this.groupBox31.TabStop = false;
            this.label35.AutoSize = true;
            this.label35.BackColor = System.Drawing.Color.Transparent;
            this.label35.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label35.ForeColor = System.Drawing.Color.Blue;
            this.label35.Location = new System.Drawing.Point(2, 3);
            this.label35.Name = "label35";
            this.label35.Size = new System.Drawing.Size(159, 13);
            this.label35.TabIndex = 330;
            this.label35.Text = "BILLING INSTRUCTIONS";
            this.rtbAmendNo.Enabled = false;
            this.rtbAmendNo.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rtbAmendNo.Location = new System.Drawing.Point(11, 277);
            this.rtbAmendNo.Name = "rtbAmendNo";
            this.rtbAmendNo.ReadOnly = true;
            this.rtbAmendNo.Size = new System.Drawing.Size(229, 22);
            this.rtbAmendNo.TabIndex = 346;
            this.rtbAmendNo.Text = "";
            this.rtbReferance.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rtbReferance.Location = new System.Drawing.Point(271, 269);
            this.rtbReferance.Name = "rtbReferance";
            this.rtbReferance.Size = new System.Drawing.Size(230, 43);
            this.rtbReferance.TabIndex = 347;
            this.rtbReferance.Text = "";
            this.rtbNotice.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rtbNotice.Location = new System.Drawing.Point(508, 268);
            this.rtbNotice.Name = "rtbNotice";
            this.rtbNotice.Size = new System.Drawing.Size(227, 46);
            this.rtbNotice.TabIndex = 348;
            this.rtbNotice.Text = "Kindly send the confirmation along with the invoice in order to make the full pay" +
                "ment.Please provide with the accommodation facilities for the chauffeur guide at" +
                " the driver\'s quarters.";
            this.btnBilling.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnBilling.Font = new System.Drawing.Font("Wingdings", 30F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(2)));
            this.btnBilling.Location = new System.Drawing.Point(690, 23);
            this.btnBilling.Name = "btnBilling";
            this.btnBilling.Size = new System.Drawing.Size(44, 52);
            this.btnBilling.TabIndex = 349;
            this.btnBilling.Text = "";
            this.btnBilling.UseVisualStyleBackColor = true;
            this.btnBilling.Click += new System.EventHandler(this.btnBilling_Click);
            this.btnOther.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnOther.Font = new System.Drawing.Font("Wingdings", 30F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(2)));
            this.btnOther.Location = new System.Drawing.Point(691, 100);
            this.btnOther.Name = "btnOther";
            this.btnOther.Size = new System.Drawing.Size(44, 70);
            this.btnOther.TabIndex = 350;
            this.btnOther.Text = "";
            this.btnOther.UseVisualStyleBackColor = true;
            this.btnOther.Click += new System.EventHandler(this.btnOther_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.Controls.Add(this.btnOther);
            this.Controls.Add(this.btnBilling);
            this.Controls.Add(this.rtbNotice);
            this.Controls.Add(this.rtbReferance);
            this.Controls.Add(this.rtbAmendNo);
            this.Controls.Add(this.groupBox40);
            this.Controls.Add(this.rtbArrangement);
            this.Controls.Add(this.label55);
            this.Controls.Add(this.groupBox32);
            this.Controls.Add(this.label39);
            this.Controls.Add(this.label38);
            this.Controls.Add(this.label37);
            this.Controls.Add(this.groupBox33);
            this.Controls.Add(this.rtbOtherInstructions);
            this.Controls.Add(this.label36);
            this.Controls.Add(this.rtbBillingIns);
            this.Controls.Add(this.groupBox31);
            this.Controls.Add(this.label35);
            this.Name = "ucTransOther";
            this.Size = new System.Drawing.Size(744, 329);
            this.Load += new System.EventHandler(this.ucTransOther_Load);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        public System.Windows.Forms.GroupBox groupBox40;
        public System.Windows.Forms.RichTextBox rtbArrangement;
        public System.Windows.Forms.Label label55;
        public System.Windows.Forms.GroupBox groupBox32;
        public System.Windows.Forms.Label label39;
        public System.Windows.Forms.Label label38;
        public System.Windows.Forms.Label label37;
        public System.Windows.Forms.GroupBox groupBox33;
        public System.Windows.Forms.RichTextBox rtbOtherInstructions;
        public System.Windows.Forms.Label label36;
        public System.Windows.Forms.RichTextBox rtbBillingIns;
        public System.Windows.Forms.GroupBox groupBox31;
        public System.Windows.Forms.Label label35;
        public System.Windows.Forms.RichTextBox rtbAmendNo;
        public System.Windows.Forms.RichTextBox rtbReferance;
        public System.Windows.Forms.RichTextBox rtbNotice;
        public System.Windows.Forms.Button btnBilling;
        public System.Windows.Forms.Button btnOther;
    }
}
