namespace Tourist_Management.Settings
{
    partial class frmBackup
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmBackup));
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.label3 = new System.Windows.Forms.Label();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.btnBrowse = new System.Windows.Forms.Button();
            this.txtPath = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.folderBrowserDialog1 = new System.Windows.Forms.FolderBrowserDialog();
            this.tv = new System.Windows.Forms.TreeView();
            this.imgLst = new System.Windows.Forms.ImageList(this.components);
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.label6 = new System.Windows.Forms.Label();
            this.optUS = new System.Windows.Forms.RadioButton();
            this.optWN = new System.Windows.Forms.RadioButton();
            this.txtserver = new System.Windows.Forms.TextBox();
            this.Label5 = new System.Windows.Forms.Label();
            this.Label4 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.chkManual = new System.Windows.Forms.CheckBox();
            this.txtuserID = new System.Windows.Forms.TextBox();
            this.btnCon = new System.Windows.Forms.Button();
            this.cmbDB = new  Tourist_Management.User_Controls.ComboBox();
            this.txtpw = new System.Windows.Forms.TextBox();
            this.btnBackup = new System.Windows.Forms.Button();
            this.btnBackupLog = new System.Windows.Forms.Button();
            this.btnRestore = new System.Windows.Forms.Button();
            this.btnVerify = new System.Windows.Forms.Button();
            this.grdComSup = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.progressBar1 = new System.Windows.Forms.ProgressBar();
            this.button5 = new System.Windows.Forms.Button();
            this.openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            this.label9 = new System.Windows.Forms.Label();
            this.opR = new System.Windows.Forms.RadioButton();
            this.opB = new System.Windows.Forms.RadioButton();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdComSup)).BeginInit();
            this.SuspendLayout();
            this.groupBox1.BackColor = System.Drawing.Color.White;
            this.groupBox1.Location = new System.Drawing.Point(11, 32);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(591, 2);
            this.groupBox1.TabIndex = 296;
            this.groupBox1.TabStop = false;
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.RoyalBlue;
            this.label1.Location = new System.Drawing.Point(12, 9);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(193, 18);
            this.label1.TabIndex = 295;
            this.label1.Text = "Make System Backup";
            this.groupBox2.BackColor = System.Drawing.Color.Transparent;
            this.groupBox2.Controls.Add(this.label9);
            this.groupBox2.Controls.Add(this.opR);
            this.groupBox2.Controls.Add(this.opB);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Controls.Add(this.textBox1);
            this.groupBox2.Controls.Add(this.btnBrowse);
            this.groupBox2.Controls.Add(this.txtPath);
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Location = new System.Drawing.Point(221, 40);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(381, 100);
            this.groupBox2.TabIndex = 299;
            this.groupBox2.TabStop = false;
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(8, 76);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(86, 13);
            this.label3.TabIndex = 220;
            this.label3.Text = "Backup Name";
            this.textBox1.Location = new System.Drawing.Point(102, 73);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(269, 21);
            this.textBox1.TabIndex = 219;
            this.textBox1.Text = ".bak";
            this.btnBrowse.BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            this.btnBrowse.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBrowse.Location = new System.Drawing.Point(344, 45);
            this.btnBrowse.Name = "btnBrowse";
            this.btnBrowse.Size = new System.Drawing.Size(27, 23);
            this.btnBrowse.TabIndex = 218;
            this.btnBrowse.Text = "...";
            this.btnBrowse.UseVisualStyleBackColor = false;
            this.btnBrowse.Click += new System.EventHandler(this.btnBrowse_Click);
            this.txtPath.Enabled = false;
            this.txtPath.Location = new System.Drawing.Point(102, 46);
            this.txtPath.Name = "txtPath";
            this.txtPath.ReadOnly = true;
            this.txtPath.Size = new System.Drawing.Size(238, 21);
            this.txtPath.TabIndex = 1;
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(8, 49);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(32, 13);
            this.label2.TabIndex = 0;
            this.label2.Text = "Path";
            this.tv.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.tv.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tv.ForeColor = System.Drawing.Color.Black;
            this.tv.Location = new System.Drawing.Point(11, 48);
            this.tv.Name = "tv";
            this.tv.Size = new System.Drawing.Size(204, 271);
            this.tv.TabIndex = 300;
            this.tv.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.tv_AfterSelect);
            this.imgLst.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgLst.ImageStream")));
            this.imgLst.TransparentColor = System.Drawing.Color.Transparent;
            this.imgLst.Images.SetKeyName(0, "TreeMain2.bmp");
            this.imgLst.Images.SetKeyName(1, "SVR2.bmp");
            this.groupBox3.BackColor = System.Drawing.Color.Transparent;
            this.groupBox3.Controls.Add(this.label6);
            this.groupBox3.Controls.Add(this.optUS);
            this.groupBox3.Controls.Add(this.optWN);
            this.groupBox3.Controls.Add(this.txtserver);
            this.groupBox3.Controls.Add(this.Label5);
            this.groupBox3.Controls.Add(this.Label4);
            this.groupBox3.Controls.Add(this.label7);
            this.groupBox3.Controls.Add(this.label8);
            this.groupBox3.Controls.Add(this.chkManual);
            this.groupBox3.Controls.Add(this.txtuserID);
            this.groupBox3.Controls.Add(this.btnCon);
            this.groupBox3.Controls.Add(this.cmbDB);
            this.groupBox3.Controls.Add(this.txtpw);
            this.groupBox3.Location = new System.Drawing.Point(221, 146);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(381, 144);
            this.groupBox3.TabIndex = 301;
            this.groupBox3.TabStop = false;
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.label6.Location = new System.Drawing.Point(8, 15);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(88, 13);
            this.label6.TabIndex = 14;
            this.label6.Text = "Authentication";
            this.optUS.AutoSize = true;
            this.optUS.Checked = true;
            this.optUS.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.optUS.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.optUS.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.optUS.Location = new System.Drawing.Point(184, 12);
            this.optUS.Name = "optUS";
            this.optUS.Size = new System.Drawing.Size(53, 18);
            this.optUS.TabIndex = 1;
            this.optUS.TabStop = true;
            this.optUS.Text = "User";
            this.optUS.UseVisualStyleBackColor = true;
            this.optWN.AutoSize = true;
            this.optWN.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.optWN.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.optWN.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.optWN.Location = new System.Drawing.Point(104, 12);
            this.optWN.Name = "optWN";
            this.optWN.Size = new System.Drawing.Size(74, 18);
            this.optWN.TabIndex = 0;
            this.optWN.Text = "Windows";
            this.optWN.UseVisualStyleBackColor = true;
            this.optWN.CheckedChanged += new System.EventHandler(this.optWN_CheckedChanged);
            this.txtserver.Enabled = false;
            this.txtserver.Location = new System.Drawing.Point(120, 34);
            this.txtserver.Name = "txtserver";
            this.txtserver.Size = new System.Drawing.Size(250, 21);
            this.txtserver.TabIndex = 7;
            this.Label5.AutoSize = true;
            this.Label5.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.Label5.Location = new System.Drawing.Point(8, 119);
            this.Label5.Name = "Label5";
            this.Label5.Size = new System.Drawing.Size(61, 13);
            this.Label5.TabIndex = 13;
            this.Label5.Text = "Database";
            this.Label4.AutoSize = true;
            this.Label4.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.Label4.Location = new System.Drawing.Point(8, 90);
            this.Label4.Name = "Label4";
            this.Label4.Size = new System.Drawing.Size(61, 13);
            this.Label4.TabIndex = 12;
            this.Label4.Text = "Password";
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.label7.Location = new System.Drawing.Point(8, 61);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(51, 13);
            this.label7.TabIndex = 11;
            this.label7.Text = "User ID";
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.label8.Location = new System.Drawing.Point(8, 38);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(90, 13);
            this.label8.TabIndex = 10;
            this.label8.Text = "Server Manual";
            this.chkManual.AutoSize = true;
            this.chkManual.Location = new System.Drawing.Point(102, 38);
            this.chkManual.Name = "chkManual";
            this.chkManual.Size = new System.Drawing.Size(15, 14);
            this.chkManual.TabIndex = 8;
            this.chkManual.UseVisualStyleBackColor = true;
            this.chkManual.CheckedChanged += new System.EventHandler(this.chkManual_CheckedChanged);
            this.txtuserID.Location = new System.Drawing.Point(102, 61);
            this.txtuserID.Name = "txtuserID";
            this.txtuserID.Size = new System.Drawing.Size(269, 21);
            this.txtuserID.TabIndex = 6;
            this.btnCon.BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            this.btnCon.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCon.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.btnCon.Location = new System.Drawing.Point(308, 86);
            this.btnCon.Name = "btnCon";
            this.btnCon.Size = new System.Drawing.Size(63, 24);
            this.btnCon.TabIndex = 5;
            this.btnCon.Text = "&Connect";
            this.btnCon.UseVisualStyleBackColor = false;
            this.btnCon.Click += new System.EventHandler(this.btnCon_Click);
            this.cmbDB.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbDB.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.cmbDB.FormattingEnabled = true;
            this.cmbDB.Location = new System.Drawing.Point(102, 115);
            this.cmbDB.Name = "cmbDB";
            this.cmbDB.Size = new System.Drawing.Size(269, 21);
            this.cmbDB.TabIndex = 2;
            this.txtpw.Location = new System.Drawing.Point(102, 88);
            this.txtpw.Name = "txtpw";
            this.txtpw.PasswordChar = '*';
            this.txtpw.Size = new System.Drawing.Size(202, 21);
            this.txtpw.TabIndex = 1;
            this.btnBackup.BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            this.btnBackup.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBackup.Location = new System.Drawing.Point(225, 296);
            this.btnBackup.Name = "btnBackup";
            this.btnBackup.Size = new System.Drawing.Size(90, 23);
            this.btnBackup.TabIndex = 302;
            this.btnBackup.Text = "&Backup";
            this.btnBackup.UseVisualStyleBackColor = false;
            this.btnBackup.Click += new System.EventHandler(this.btnBackup_Click);
            this.btnBackupLog.BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            this.btnBackupLog.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBackupLog.Location = new System.Drawing.Point(320, 296);
            this.btnBackupLog.Name = "btnBackupLog";
            this.btnBackupLog.Size = new System.Drawing.Size(90, 23);
            this.btnBackupLog.TabIndex = 303;
            this.btnBackupLog.Text = "Backup &Log";
            this.btnBackupLog.UseVisualStyleBackColor = false;
            this.btnRestore.BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            this.btnRestore.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRestore.Location = new System.Drawing.Point(414, 296);
            this.btnRestore.Name = "btnRestore";
            this.btnRestore.Size = new System.Drawing.Size(90, 23);
            this.btnRestore.TabIndex = 304;
            this.btnRestore.Text = "&Restore";
            this.btnRestore.UseVisualStyleBackColor = false;
            this.btnRestore.Click += new System.EventHandler(this.btnRestore_Click);
            this.btnVerify.BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            this.btnVerify.Enabled = false;
            this.btnVerify.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnVerify.Location = new System.Drawing.Point(509, 296);
            this.btnVerify.Name = "btnVerify";
            this.btnVerify.Size = new System.Drawing.Size(90, 23);
            this.btnVerify.TabIndex = 305;
            this.btnVerify.Text = "&Verify";
            this.btnVerify.UseVisualStyleBackColor = false;
            this.btnVerify.Click += new System.EventHandler(this.btnVerify_Click);
            this.grdComSup.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.grdComSup.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.grdComSup.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdComSup.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdComSup.Location = new System.Drawing.Point(11, 334);
            this.grdComSup.Name = "grdComSup";
            this.grdComSup.Size = new System.Drawing.Size(591, 110);
            this.grdComSup.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdComSup.Styles"));
            this.grdComSup.TabIndex = 306;
            this.progressBar1.Location = new System.Drawing.Point(11, 451);
            this.progressBar1.Name = "progressBar1";
            this.progressBar1.Size = new System.Drawing.Size(493, 23);
            this.progressBar1.TabIndex = 307;
            this.button5.BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            this.button5.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button5.Location = new System.Drawing.Point(509, 451);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(90, 23);
            this.button5.TabIndex = 308;
            this.button5.Text = "Cl&ose";
            this.button5.UseVisualStyleBackColor = false;
            this.button5.Click += new System.EventHandler(this.button5_Click);
            this.openFileDialog1.FileName = "openFileDialog1";
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.label9.Location = new System.Drawing.Point(8, 23);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(42, 13);
            this.label9.TabIndex = 223;
            this.label9.Text = "Action";
            this.opR.AutoSize = true;
            this.opR.Checked = true;
            this.opR.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.opR.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.opR.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.opR.Location = new System.Drawing.Point(184, 20);
            this.opR.Name = "opR";
            this.opR.Size = new System.Drawing.Size(69, 18);
            this.opR.TabIndex = 222;
            this.opR.TabStop = true;
            this.opR.Text = "Restore";
            this.opR.UseVisualStyleBackColor = true;
            this.opR.CheckedChanged += new System.EventHandler(this.opR_CheckedChanged);
            this.opB.AutoSize = true;
            this.opB.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.opB.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.opB.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.opB.Location = new System.Drawing.Point(104, 20);
            this.opB.Name = "opB";
            this.opB.Size = new System.Drawing.Size(65, 18);
            this.opB.TabIndex = 221;
            this.opB.Text = "Backup";
            this.opB.UseVisualStyleBackColor = true;
            this.opB.CheckedChanged += new System.EventHandler(this.opB_CheckedChanged);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(614, 481);
            this.ControlBox = false;
            this.Controls.Add(this.button5);
            this.Controls.Add(this.progressBar1);
            this.Controls.Add(this.grdComSup);
            this.Controls.Add(this.btnVerify);
            this.Controls.Add(this.btnRestore);
            this.Controls.Add(this.btnBackupLog);
            this.Controls.Add(this.btnBackup);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.tv);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.label1);
            this.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "frmBackup";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmBackup_Load);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdComSup)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Button btnBrowse;
        private System.Windows.Forms.TextBox txtPath;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.FolderBrowserDialog folderBrowserDialog1;
        private System.Windows.Forms.TreeView tv;
        private System.Windows.Forms.ImageList imgLst;
        internal System.Windows.Forms.GroupBox groupBox3;
        internal System.Windows.Forms.TextBox txtserver;
        internal System.Windows.Forms.Label Label5;
        internal System.Windows.Forms.Label Label4;
        internal System.Windows.Forms.Label label7;
        internal System.Windows.Forms.Label label8;
        internal System.Windows.Forms.CheckBox chkManual;
        internal System.Windows.Forms.TextBox txtuserID;
        internal  Tourist_Management.User_Controls.ComboBox cmbDB;
        internal System.Windows.Forms.TextBox txtpw;
        private System.Windows.Forms.Button btnBackup;
        private System.Windows.Forms.Button btnBackupLog;
        private System.Windows.Forms.Button btnRestore;
        private System.Windows.Forms.Button btnVerify;
        private C1.Win.C1FlexGrid.C1FlexGrid grdComSup;
        private System.Windows.Forms.ProgressBar progressBar1;
        private System.Windows.Forms.Button button5;
        private System.Windows.Forms.Button btnCon;
        internal System.Windows.Forms.RadioButton optUS;
        internal System.Windows.Forms.RadioButton optWN;
        internal System.Windows.Forms.Label label6;
        private System.Windows.Forms.OpenFileDialog openFileDialog1;
        internal System.Windows.Forms.Label label9;
        internal System.Windows.Forms.RadioButton opR;
        internal System.Windows.Forms.RadioButton opB;
    }
}