namespace Tourist_Management.Settings
{
    partial class frmChangePswd
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmChangePswd));
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.chkUnmask = new System.Windows.Forms.CheckBox();
            this.txtUserName = new System.Windows.Forms.TextBox();
            this.picCurPswd = new System.Windows.Forms.PictureBox();
            this.picConPswd = new System.Windows.Forms.PictureBox();
            this.txtConPswd = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.groupBox27 = new System.Windows.Forms.GroupBox();
            this.txtNewPswd = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.txtCurPswd = new System.Windows.Forms.TextBox();
            this.label15 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.imageList1 = new System.Windows.Forms.ImageList(this.components);
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.label3 = new System.Windows.Forms.Label();
            this.lblRealPswd = new System.Windows.Forms.Label();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picCurPswd)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.picConPswd)).BeginInit();
            this.SuspendLayout();
            this.groupBox2.BackColor = System.Drawing.Color.Transparent;
            this.groupBox2.Controls.Add(this.chkUnmask);
            this.groupBox2.Controls.Add(this.txtUserName);
            this.groupBox2.Controls.Add(this.picCurPswd);
            this.groupBox2.Controls.Add(this.picConPswd);
            this.groupBox2.Controls.Add(this.txtConPswd);
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Controls.Add(this.groupBox27);
            this.groupBox2.Controls.Add(this.txtNewPswd);
            this.groupBox2.Controls.Add(this.label1);
            this.groupBox2.Controls.Add(this.txtCurPswd);
            this.groupBox2.Controls.Add(this.label15);
            this.groupBox2.Controls.Add(this.label7);
            this.groupBox2.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.Location = new System.Drawing.Point(14, 45);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(400, 171);
            this.groupBox2.TabIndex = 316;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "User Details";
            this.chkUnmask.AutoSize = true;
            this.chkUnmask.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkUnmask.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkUnmask.Location = new System.Drawing.Point(147, 147);
            this.chkUnmask.Name = "chkUnmask";
            this.chkUnmask.Size = new System.Drawing.Size(112, 17);
            this.chkUnmask.TabIndex = 4;
            this.chkUnmask.Text = "Unmask Password";
            this.chkUnmask.UseVisualStyleBackColor = true;
            this.chkUnmask.CheckedChanged += new System.EventHandler(this.chkUnmask_CheckedChanged);
            this.txtUserName.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.txtUserName.Enabled = false;
            this.txtUserName.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtUserName.ForeColor = System.Drawing.Color.Black;
            this.txtUserName.Location = new System.Drawing.Point(146, 18);
            this.txtUserName.MaxLength = 50;
            this.txtUserName.Name = "txtUserName";
            this.txtUserName.ReadOnly = true;
            this.txtUserName.Size = new System.Drawing.Size(203, 21);
            this.txtUserName.TabIndex = 0;
            this.picCurPswd.Location = new System.Drawing.Point(355, 46);
            this.picCurPswd.Name = "picCurPswd";
            this.picCurPswd.Size = new System.Drawing.Size(28, 24);
            this.picCurPswd.TabIndex = 317;
            this.picCurPswd.TabStop = false;
            this.picConPswd.Location = new System.Drawing.Point(355, 121);
            this.picConPswd.Name = "picConPswd";
            this.picConPswd.Size = new System.Drawing.Size(28, 24);
            this.picConPswd.TabIndex = 316;
            this.picConPswd.TabStop = false;
            this.txtConPswd.BackColor = System.Drawing.SystemColors.Window;
            this.txtConPswd.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtConPswd.ForeColor = System.Drawing.Color.Black;
            this.txtConPswd.Location = new System.Drawing.Point(146, 120);
            this.txtConPswd.MaxLength = 50;
            this.txtConPswd.Name = "txtConPswd";
            this.txtConPswd.PasswordChar = '*';
            this.txtConPswd.Size = new System.Drawing.Size(203, 21);
            this.txtConPswd.TabIndex = 3;
            this.txtConPswd.TextChanged += new System.EventHandler(this.txtConPswd_TextChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(15, 124);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(111, 13);
            this.label2.TabIndex = 314;
            this.label2.Text = "Confirm Password";
            this.groupBox27.BackColor = System.Drawing.Color.Gray;
            this.groupBox27.Location = new System.Drawing.Point(10, 79);
            this.groupBox27.Name = "groupBox27";
            this.groupBox27.Size = new System.Drawing.Size(370, 2);
            this.groupBox27.TabIndex = 313;
            this.groupBox27.TabStop = false;
            this.txtNewPswd.BackColor = System.Drawing.SystemColors.Window;
            this.txtNewPswd.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNewPswd.ForeColor = System.Drawing.Color.Black;
            this.txtNewPswd.Location = new System.Drawing.Point(146, 93);
            this.txtNewPswd.MaxLength = 50;
            this.txtNewPswd.Name = "txtNewPswd";
            this.txtNewPswd.PasswordChar = '*';
            this.txtNewPswd.Size = new System.Drawing.Size(203, 21);
            this.txtNewPswd.TabIndex = 2;
            this.txtNewPswd.TextChanged += new System.EventHandler(this.txtNewPswd_TextChanged);
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(15, 97);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(89, 13);
            this.label1.TabIndex = 261;
            this.label1.Text = "New Password";
            this.txtCurPswd.BackColor = System.Drawing.SystemColors.Window;
            this.txtCurPswd.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCurPswd.ForeColor = System.Drawing.Color.Black;
            this.txtCurPswd.Location = new System.Drawing.Point(146, 45);
            this.txtCurPswd.MaxLength = 50;
            this.txtCurPswd.Name = "txtCurPswd";
            this.txtCurPswd.PasswordChar = '*';
            this.txtCurPswd.Size = new System.Drawing.Size(203, 21);
            this.txtCurPswd.TabIndex = 1;
            this.txtCurPswd.Validated += new System.EventHandler(this.txtCurPswd_Validated);
            this.label15.AutoSize = true;
            this.label15.Location = new System.Drawing.Point(15, 48);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(109, 13);
            this.label15.TabIndex = 253;
            this.label15.Text = "Current Password";
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(15, 21);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(65, 13);
            this.label7.TabIndex = 251;
            this.label7.Text = "Username";
            this.imageList1.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream")));
            this.imageList1.TransparentColor = System.Drawing.Color.Transparent;
            this.imageList1.Images.SetKeyName(0, "correct");
            this.imageList1.Images.SetKeyName(1, "wrong");
            this.btnCancel.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Location = new System.Drawing.Point(344, 222);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(70, 23);
            this.btnCancel.TabIndex = 1;
            this.btnCancel.Text = "&Close";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnOk.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Location = new System.Drawing.Point(268, 222);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(70, 23);
            this.btnOk.TabIndex = 0;
            this.btnOk.Text = "&Save";
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.groupBox1.BackColor = System.Drawing.Color.White;
            this.groupBox1.Location = new System.Drawing.Point(13, 29);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(403, 3);
            this.groupBox1.TabIndex = 320;
            this.groupBox1.TabStop = false;
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.RoyalBlue;
            this.label3.Location = new System.Drawing.Point(12, 9);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(240, 18);
            this.label3.TabIndex = 319;
            this.label3.Text = "Change Current Password";
            this.lblRealPswd.AutoSize = true;
            this.lblRealPswd.Location = new System.Drawing.Point(14, 226);
            this.lblRealPswd.Name = "lblRealPswd";
            this.lblRealPswd.Size = new System.Drawing.Size(57, 13);
            this.lblRealPswd.TabIndex = 321;
            this.lblRealPswd.Text = "CurPswd";
            this.lblRealPswd.Visible = false;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(426, 251);
            this.ControlBox = false;
            this.Controls.Add(this.lblRealPswd);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.groupBox2);
            this.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "frmChangePswd";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmChangePswd_Load);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picCurPswd)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.picConPswd)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.TextBox txtCurPswd;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TextBox txtNewPswd;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.GroupBox groupBox27;
        private System.Windows.Forms.TextBox txtConPswd;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.PictureBox picConPswd;
        private System.Windows.Forms.ImageList imageList1;
        private System.Windows.Forms.PictureBox picCurPswd;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox txtUserName;
        private System.Windows.Forms.CheckBox chkUnmask;
        private System.Windows.Forms.Label lblRealPswd;
    }
}