namespace Tourist_Management.Settings
{
    partial class frmChangeTypes
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmChangeTypes));
            this.label12 = new System.Windows.Forms.Label();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.txtGuest = new System.Windows.Forms.TextBox();
            this.btnTour = new System.Windows.Forms.Button();
            this.txtTourNo = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.tcChangeTypes = new System.Windows.Forms.TabControl();
            this.tpVoucher = new System.Windows.Forms.TabPage();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.rdbConf = new System.Windows.Forms.RadioButton();
            this.rdbVou = new System.Windows.Forms.RadioButton();
            this.grdCI = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.label2 = new System.Windows.Forms.Label();
            this.grpSelectType = new System.Windows.Forms.GroupBox();
            this.rdbCancellation = new System.Windows.Forms.RadioButton();
            this.rdbComplementary = new System.Windows.Forms.RadioButton();
            this.rdbMeal = new System.Windows.Forms.RadioButton();
            this.cmbAmendNo = new  Tourist_Management.User_Controls.ComboBox();
            this.rdbAmend = new System.Windows.Forms.RadioButton();
            this.rdbReserv = new System.Windows.Forms.RadioButton();
            this.tpOther = new System.Windows.Forms.TabPage();
            this.chkIsCompleted = new System.Windows.Forms.CheckBox();
            this.label7 = new System.Windows.Forms.Label();
            this.drpMarketingDep = new DropDowns.DropSearch();
            this.drpAgent = new DropDowns.DropSearch();
            this.cmbCompany = new  Tourist_Management.User_Controls.ComboBox();
            this.label36 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label51 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.groupBox3.SuspendLayout();
            this.tcChangeTypes.SuspendLayout();
            this.tpVoucher.SuspendLayout();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdCI)).BeginInit();
            this.grpSelectType.SuspendLayout();
            this.tpOther.SuspendLayout();
            this.SuspendLayout();
            this.label12.AutoSize = true;
            this.label12.BackColor = System.Drawing.Color.Transparent;
            this.label12.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label12.Location = new System.Drawing.Point(12, 8);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(99, 14);
            this.label12.TabIndex = 308;
            this.label12.Text = "SELECT TOUR";
            this.groupBox3.BackColor = System.Drawing.Color.Transparent;
            this.groupBox3.Controls.Add(this.txtGuest);
            this.groupBox3.Controls.Add(this.btnTour);
            this.groupBox3.Controls.Add(this.txtTourNo);
            this.groupBox3.Controls.Add(this.label1);
            this.groupBox3.Location = new System.Drawing.Point(12, 21);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(620, 53);
            this.groupBox3.TabIndex = 312;
            this.groupBox3.TabStop = false;
            this.txtGuest.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.txtGuest.Enabled = false;
            this.txtGuest.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtGuest.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.txtGuest.Location = new System.Drawing.Point(276, 21);
            this.txtGuest.Name = "txtGuest";
            this.txtGuest.ReadOnly = true;
            this.txtGuest.Size = new System.Drawing.Size(338, 21);
            this.txtGuest.TabIndex = 256;
            this.txtGuest.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTour.Location = new System.Drawing.Point(233, 20);
            this.btnTour.Name = "btnTour";
            this.btnTour.Size = new System.Drawing.Size(37, 23);
            this.btnTour.TabIndex = 0;
            this.btnTour.Text = "...";
            this.btnTour.UseVisualStyleBackColor = true;
            this.btnTour.Click += new System.EventHandler(this.btnTour_Click);
            this.txtTourNo.Enabled = false;
            this.txtTourNo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTourNo.ForeColor = System.Drawing.Color.Blue;
            this.txtTourNo.Location = new System.Drawing.Point(62, 21);
            this.txtTourNo.Name = "txtTourNo";
            this.txtTourNo.ReadOnly = true;
            this.txtTourNo.Size = new System.Drawing.Size(165, 21);
            this.txtTourNo.TabIndex = 255;
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(5, 23);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(51, 13);
            this.label1.TabIndex = 254;
            this.label1.Text = "Tour ID";
            this.tcChangeTypes.Appearance = System.Windows.Forms.TabAppearance.FlatButtons;
            this.tcChangeTypes.Controls.Add(this.tpVoucher);
            this.tcChangeTypes.Controls.Add(this.tpOther);
            this.tcChangeTypes.Location = new System.Drawing.Point(12, 85);
            this.tcChangeTypes.Name = "tcChangeTypes";
            this.tcChangeTypes.SelectedIndex = 0;
            this.tcChangeTypes.Size = new System.Drawing.Size(620, 331);
            this.tcChangeTypes.TabIndex = 314;
            this.tpVoucher.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tpVoucher.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tpVoucher.Controls.Add(this.groupBox1);
            this.tpVoucher.Controls.Add(this.grdCI);
            this.tpVoucher.Controls.Add(this.label2);
            this.tpVoucher.Controls.Add(this.grpSelectType);
            this.tpVoucher.Location = new System.Drawing.Point(4, 25);
            this.tpVoucher.Name = "tpVoucher";
            this.tpVoucher.Padding = new System.Windows.Forms.Padding(3);
            this.tpVoucher.Size = new System.Drawing.Size(612, 302);
            this.tpVoucher.TabIndex = 0;
            this.tpVoucher.Text = "Change Voucher Type";
            this.tpVoucher.UseVisualStyleBackColor = true;
            this.groupBox1.BackColor = System.Drawing.Color.Transparent;
            this.groupBox1.Controls.Add(this.rdbConf);
            this.groupBox1.Controls.Add(this.rdbVou);
            this.groupBox1.Location = new System.Drawing.Point(103, 2);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(338, 33);
            this.groupBox1.TabIndex = 318;
            this.groupBox1.TabStop = false;
            this.rdbConf.AutoSize = true;
            this.rdbConf.Checked = true;
            this.rdbConf.Location = new System.Drawing.Point(5, 13);
            this.rdbConf.Name = "rdbConf";
            this.rdbConf.Size = new System.Drawing.Size(123, 17);
            this.rdbConf.TabIndex = 3;
            this.rdbConf.TabStop = true;
            this.rdbConf.Text = "Change Confirmation";
            this.rdbConf.UseVisualStyleBackColor = true;
            this.rdbConf.CheckedChanged += new System.EventHandler(this.rdbConf_CheckedChanged);
            this.rdbVou.AutoSize = true;
            this.rdbVou.Location = new System.Drawing.Point(161, 12);
            this.rdbVou.Name = "rdbVou";
            this.rdbVou.Size = new System.Drawing.Size(122, 17);
            this.rdbVou.TabIndex = 2;
            this.rdbVou.Text = "Change Voucher No";
            this.rdbVou.UseVisualStyleBackColor = true;
            this.grdCI.BackColor = System.Drawing.Color.Transparent;
            this.grdCI.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdCI.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdCI.Location = new System.Drawing.Point(10, 71);
            this.grdCI.Name = "grdCI";
            this.grdCI.Size = new System.Drawing.Size(592, 216);
            this.grdCI.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdCI.Styles"));
            this.grdCI.TabIndex = 314;
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label2.Location = new System.Drawing.Point(2, 16);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(102, 14);
            this.label2.TabIndex = 318;
            this.label2.Text = "CHANGE TYPE";
            this.grpSelectType.BackColor = System.Drawing.Color.Transparent;
            this.grpSelectType.Controls.Add(this.rdbCancellation);
            this.grpSelectType.Controls.Add(this.rdbComplementary);
            this.grpSelectType.Controls.Add(this.rdbMeal);
            this.grpSelectType.Controls.Add(this.cmbAmendNo);
            this.grpSelectType.Controls.Add(this.rdbAmend);
            this.grpSelectType.Controls.Add(this.rdbReserv);
            this.grpSelectType.Location = new System.Drawing.Point(102, 29);
            this.grpSelectType.Name = "grpSelectType";
            this.grpSelectType.Size = new System.Drawing.Size(499, 38);
            this.grpSelectType.TabIndex = 317;
            this.grpSelectType.TabStop = false;
            this.grpSelectType.Visible = false;
            this.rdbCancellation.AutoSize = true;
            this.rdbCancellation.Location = new System.Drawing.Point(277, 14);
            this.rdbCancellation.Name = "rdbCancellation";
            this.rdbCancellation.Size = new System.Drawing.Size(83, 17);
            this.rdbCancellation.TabIndex = 5;
            this.rdbCancellation.Text = "Cancellation";
            this.rdbCancellation.UseVisualStyleBackColor = true;
            this.rdbComplementary.AutoSize = true;
            this.rdbComplementary.Location = new System.Drawing.Point(154, 14);
            this.rdbComplementary.Name = "rdbComplementary";
            this.rdbComplementary.Size = new System.Drawing.Size(97, 17);
            this.rdbComplementary.TabIndex = 4;
            this.rdbComplementary.Text = "Complementary";
            this.rdbComplementary.UseVisualStyleBackColor = true;
            this.rdbMeal.AutoSize = true;
            this.rdbMeal.Location = new System.Drawing.Point(100, 14);
            this.rdbMeal.Name = "rdbMeal";
            this.rdbMeal.Size = new System.Drawing.Size(48, 17);
            this.rdbMeal.TabIndex = 3;
            this.rdbMeal.Text = "Meal";
            this.rdbMeal.UseVisualStyleBackColor = true;
            this.cmbAmendNo.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbAmendNo.Enabled = false;
            this.cmbAmendNo.FormattingEnabled = true;
            this.cmbAmendNo.Location = new System.Drawing.Point(449, 14);
            this.cmbAmendNo.Name = "cmbAmendNo";
            this.cmbAmendNo.Size = new System.Drawing.Size(42, 21);
            this.cmbAmendNo.TabIndex = 1;
            this.rdbAmend.AutoSize = true;
            this.rdbAmend.Checked = true;
            this.rdbAmend.Location = new System.Drawing.Point(380, 14);
            this.rdbAmend.Name = "rdbAmend";
            this.rdbAmend.Size = new System.Drawing.Size(58, 17);
            this.rdbAmend.TabIndex = 0;
            this.rdbAmend.TabStop = true;
            this.rdbAmend.Text = "Amend";
            this.rdbAmend.UseVisualStyleBackColor = true;
            this.rdbAmend.CheckedChanged += new System.EventHandler(this.rdbAmend_CheckedChanged);
            this.rdbReserv.AutoSize = true;
            this.rdbReserv.Location = new System.Drawing.Point(4, 14);
            this.rdbReserv.Name = "rdbReserv";
            this.rdbReserv.Size = new System.Drawing.Size(82, 17);
            this.rdbReserv.TabIndex = 2;
            this.rdbReserv.Text = "Reservation";
            this.rdbReserv.UseVisualStyleBackColor = true;
            this.tpOther.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tpOther.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tpOther.Controls.Add(this.drpAgent);
            this.tpOther.Controls.Add(this.drpMarketingDep);
            this.tpOther.Controls.Add(this.chkIsCompleted);
            this.tpOther.Controls.Add(this.label7);
            this.tpOther.Controls.Add(this.cmbCompany);
            this.tpOther.Controls.Add(this.label36);
            this.tpOther.Controls.Add(this.label6);
            this.tpOther.Controls.Add(this.label5);
            this.tpOther.Controls.Add(this.label4);
            this.tpOther.Controls.Add(this.label51);
            this.tpOther.Controls.Add(this.label3);
            this.tpOther.Location = new System.Drawing.Point(4, 25);
            this.tpOther.Name = "tpOther";
            this.tpOther.Padding = new System.Windows.Forms.Padding(3);
            this.tpOther.Size = new System.Drawing.Size(612, 302);
            this.tpOther.TabIndex = 1;
            this.tpOther.Text = "Other Changes";
            this.tpOther.UseVisualStyleBackColor = true;
            this.chkIsCompleted.AutoSize = true;
            this.chkIsCompleted.BackColor = System.Drawing.Color.Transparent;
            this.chkIsCompleted.Enabled = false;
            this.chkIsCompleted.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkIsCompleted.ForeColor = System.Drawing.SystemColors.ControlText;
            this.chkIsCompleted.Location = new System.Drawing.Point(387, 107);
            this.chkIsCompleted.Name = "chkIsCompleted";
            this.chkIsCompleted.Size = new System.Drawing.Size(129, 17);
            this.chkIsCompleted.TabIndex = 346;
            this.chkIsCompleted.Text = "Tour Completed";
            this.chkIsCompleted.UseVisualStyleBackColor = false;
            this.chkIsCompleted.CheckedChanged += new System.EventHandler(this.chkIsCompleted_CheckedChanged);
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.Transparent;
            this.label7.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label7.Location = new System.Drawing.Point(317, 77);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(288, 14);
            this.label7.TabIndex = 345;
            this.label7.Text = "CHANGE  STATE ___________________";
            this.drpMarketingDep.BackColor = System.Drawing.Color.Transparent;
            this.drpMarketingDep.DataSource = null;
            this.drpMarketingDep.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpMarketingDep.FormName = "";
            this.drpMarketingDep.Location = new System.Drawing.Point(104, 104);
            this.drpMarketingDep.Name = "drpMarketingDep";
            this.drpMarketingDep.SelectedText = "";
            this.drpMarketingDep.SelectedValue = "";
            this.drpMarketingDep.Size = new System.Drawing.Size(195, 23);
            this.drpMarketingDep.TabIndex = 335;
            this.drpAgent.BackColor = System.Drawing.Color.Transparent;
            this.drpAgent.DataSource = null;
            this.drpAgent.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpAgent.FormName = "";
            this.drpAgent.Location = new System.Drawing.Point(104, 31);
            this.drpAgent.Name = "drpAgent";
            this.drpAgent.SelectedText = "";
            this.drpAgent.SelectedValue = "";
            this.drpAgent.Size = new System.Drawing.Size(195, 23);
            this.drpAgent.TabIndex = 243;
            this.cmbCompany.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCompany.Enabled = false;
            this.cmbCompany.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCompany.FormattingEnabled = true;
            this.cmbCompany.Location = new System.Drawing.Point(387, 31);
            this.cmbCompany.Name = "cmbCompany";
            this.cmbCompany.Size = new System.Drawing.Size(215, 21);
            this.cmbCompany.TabIndex = 344;
            this.label36.AutoSize = true;
            this.label36.BackColor = System.Drawing.Color.Transparent;
            this.label36.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label36.Location = new System.Drawing.Point(319, 35);
            this.label36.Name = "label36";
            this.label36.Size = new System.Drawing.Size(62, 13);
            this.label36.TabIndex = 343;
            this.label36.Text = "Company";
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label6.Location = new System.Drawing.Point(317, 7);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(289, 14);
            this.label6.TabIndex = 337;
            this.label6.Text = "CHANGE COMPANY_________________";
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label5.Location = new System.Drawing.Point(6, 77);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(291, 14);
            this.label5.TabIndex = 336;
            this.label5.Text = "CHANGE HANDLED PERSON___________";
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label4.Location = new System.Drawing.Point(5, 7);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(292, 14);
            this.label4.TabIndex = 315;
            this.label4.Text = "CHANGE AGENT____________________";
            this.label51.AutoSize = true;
            this.label51.BackColor = System.Drawing.Color.Transparent;
            this.label51.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label51.Location = new System.Drawing.Point(8, 107);
            this.label51.Name = "label51";
            this.label51.Size = new System.Drawing.Size(90, 13);
            this.label51.TabIndex = 334;
            this.label51.Text = "Marketing Dep";
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Location = new System.Drawing.Point(7, 34);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(77, 13);
            this.label3.TabIndex = 242;
            this.label3.Text = "Agent Name";
            this.btnCancel.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.Location = new System.Drawing.Point(550, 422);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(68, 27);
            this.btnCancel.TabIndex = 316;
            this.btnCancel.Text = "&Cancel";
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnOk.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Image = global::Tourist_Management.Properties.Resources.floppy;
            this.btnOk.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOk.Location = new System.Drawing.Point(481, 422);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(68, 27);
            this.btnOk.TabIndex = 315;
            this.btnOk.Text = "&Save";
            this.btnOk.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(642, 454);
            this.ControlBox = false;
            this.Controls.Add(this.tcChangeTypes);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.label12);
            this.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "frmChangeTypes";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmChangeTypes_Load);
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.tcChangeTypes.ResumeLayout(false);
            this.tpVoucher.ResumeLayout(false);
            this.tpVoucher.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdCI)).EndInit();
            this.grpSelectType.ResumeLayout(false);
            this.grpSelectType.PerformLayout();
            this.tpOther.ResumeLayout(false);
            this.tpOther.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.Button btnTour;
        private System.Windows.Forms.TextBox txtTourNo;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox txtGuest;
        private System.Windows.Forms.TabControl tcChangeTypes;
        private System.Windows.Forms.TabPage tpVoucher;
        private System.Windows.Forms.TabPage tpOther;
        private C1.Win.C1FlexGrid.C1FlexGrid grdCI;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.GroupBox grpSelectType;
        private  Tourist_Management.User_Controls.ComboBox cmbAmendNo;
        private System.Windows.Forms.RadioButton rdbAmend;
        private System.Windows.Forms.RadioButton rdbReserv;
        private DropDowns.DropSearch drpAgent;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private DropDowns.DropSearch drpMarketingDep;
        private System.Windows.Forms.Label label51;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private  Tourist_Management.User_Controls.ComboBox cmbCompany;
        private System.Windows.Forms.Label label36;
        private System.Windows.Forms.RadioButton rdbMeal;
        private System.Windows.Forms.RadioButton rdbComplementary;
        private System.Windows.Forms.RadioButton rdbCancellation;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.RadioButton rdbConf;
        private System.Windows.Forms.RadioButton rdbVou;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.CheckBox chkIsCompleted;
    }
}