namespace Tourist_Management.Settings
{
    partial class frmFilterDrvGuide
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmFilterDrvGuide));
            this.cmbMainFilter = new  Tourist_Management.User_Controls.ComboBox();
            this.grdFilter = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.btnClear = new System.Windows.Forms.Button();
            this.grdLang = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.button2 = new System.Windows.Forms.Button();
            this.groupBox20 = new System.Windows.Forms.GroupBox();
            this.label18 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.btnGrid = new System.Windows.Forms.Button();
            this.btnFilter = new System.Windows.Forms.Button();
            this.gbFilter = new System.Windows.Forms.GroupBox();
            this.cmdFilter4 = new  Tourist_Management.User_Controls.ComboBox();
            this.cmdFilter1 = new  Tourist_Management.User_Controls.ComboBox();
            this.txtValue1 = new System.Windows.Forms.TextBox();
            this.txtValue2 = new System.Windows.Forms.TextBox();
            this.cmdFilter2 = new  Tourist_Management.User_Controls.ComboBox();
            this.txtValue3 = new System.Windows.Forms.TextBox();
            this.cmdFilter5 = new  Tourist_Management.User_Controls.ComboBox();
            this.cmdFilter3 = new  Tourist_Management.User_Controls.ComboBox();
            this.txtValue5 = new System.Windows.Forms.TextBox();
            this.txtValue4 = new System.Windows.Forms.TextBox();
            this.btnSelect = new System.Windows.Forms.Button();
            this.gbSpeaks = new System.Windows.Forms.GroupBox();
            this.rdbOne = new System.Windows.Forms.RadioButton();
            this.rdbAll = new System.Windows.Forms.RadioButton();
            ((System.ComponentModel.ISupportInitialize)(this.grdFilter)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdLang)).BeginInit();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.gbFilter.SuspendLayout();
            this.gbSpeaks.SuspendLayout();
            this.SuspendLayout();
            this.cmbMainFilter.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbMainFilter.FormattingEnabled = true;
            this.cmbMainFilter.Items.AddRange(new object[] {
            "Driver",
            "Guide"});
            this.cmbMainFilter.Location = new System.Drawing.Point(6, 19);
            this.cmbMainFilter.Name = "cmbMainFilter";
            this.cmbMainFilter.Size = new System.Drawing.Size(99, 22);
            this.cmbMainFilter.TabIndex = 2;
            this.cmbMainFilter.SelectedIndexChanged += new System.EventHandler(this.cmbMainFilter_SelectedValueChanged);
            this.grdFilter.BackColor = System.Drawing.Color.Transparent;
            this.grdFilter.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.grdFilter.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdFilter.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdFilter.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grdFilter.Location = new System.Drawing.Point(331, 35);
            this.grdFilter.Name = "grdFilter";
            this.grdFilter.Size = new System.Drawing.Size(686, 321);
            this.grdFilter.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdFilter.Styles"));
            this.grdFilter.TabIndex = 315;
            this.btnClear.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnClear.Image = global::Tourist_Management.Properties.Resources.clear;
            this.btnClear.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClear.Location = new System.Drawing.Point(857, 362);
            this.btnClear.Name = "btnClear";
            this.btnClear.Size = new System.Drawing.Size(81, 28);
            this.btnClear.TabIndex = 316;
            this.btnClear.Text = "Clear";
            this.btnClear.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClear.UseVisualStyleBackColor = true;
            this.btnClear.Click += new System.EventHandler(this.button1_Click);
            this.grdLang.BackColor = System.Drawing.Color.Transparent;
            this.grdLang.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.grdLang.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.grdLang.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdLang.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdLang.Location = new System.Drawing.Point(6, 12);
            this.grdLang.Name = "grdLang";
            this.grdLang.Size = new System.Drawing.Size(301, 168);
            this.grdLang.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdLang.Styles"));
            this.grdLang.TabIndex = 320;
            this.grdLang.Click += new System.EventHandler(this.grdLang_Click);
            this.button2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.button2.Image = global::Tourist_Management.Properties.Resources.delete;
            this.button2.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button2.Location = new System.Drawing.Point(939, 362);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(81, 28);
            this.button2.TabIndex = 321;
            this.button2.Text = "Close";
            this.button2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            this.groupBox20.BackColor = System.Drawing.Color.Gray;
            this.groupBox20.Location = new System.Drawing.Point(224, 15);
            this.groupBox20.Name = "groupBox20";
            this.groupBox20.Size = new System.Drawing.Size(499, 1);
            this.groupBox20.TabIndex = 376;
            this.groupBox20.TabStop = false;
            this.label18.AutoSize = true;
            this.label18.BackColor = System.Drawing.Color.Transparent;
            this.label18.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label18.ForeColor = System.Drawing.Color.Gray;
            this.label18.Location = new System.Drawing.Point(4, 3);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(221, 14);
            this.label18.TabIndex = 375;
            this.label18.Text = "SEARCH FOR A DRIVER / GUIDE";
            this.groupBox1.BackColor = System.Drawing.Color.Transparent;
            this.groupBox1.Controls.Add(this.cmbMainFilter);
            this.groupBox1.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.Location = new System.Drawing.Point(7, 35);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(111, 51);
            this.groupBox1.TabIndex = 377;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Search In";
            this.groupBox2.BackColor = System.Drawing.Color.Transparent;
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Controls.Add(this.btnGrid);
            this.groupBox2.Controls.Add(this.btnFilter);
            this.groupBox2.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.Location = new System.Drawing.Point(7, 92);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(314, 76);
            this.groupBox2.TabIndex = 378;
            this.groupBox2.TabStop = false;
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.label4.Location = new System.Drawing.Point(10, 50);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(131, 12);
            this.label4.TabIndex = 328;
            this.label4.Text = "SEARCH BY LANGUAGE";
            this.label4.Click += new System.EventHandler(this.btnGrid_Click);
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.label3.Location = new System.Drawing.Point(10, 18);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(111, 12);
            this.label3.TabIndex = 327;
            this.label3.Text = "SEARCH BY BASICS";
            this.label3.Click += new System.EventHandler(this.btnFilter_Click);
            this.btnGrid.BackColor = System.Drawing.Color.White;
            this.btnGrid.Font = new System.Drawing.Font("Webdings", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(2)));
            this.btnGrid.ForeColor = System.Drawing.Color.DarkGray;
            this.btnGrid.Location = new System.Drawing.Point(5, 43);
            this.btnGrid.Name = "btnGrid";
            this.btnGrid.Size = new System.Drawing.Size(302, 24);
            this.btnGrid.TabIndex = 326;
            this.btnGrid.Text = "";
            this.btnGrid.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGrid.UseVisualStyleBackColor = false;
            this.btnGrid.Click += new System.EventHandler(this.btnGrid_Click);
            this.btnFilter.BackColor = System.Drawing.Color.White;
            this.btnFilter.Font = new System.Drawing.Font("Webdings", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(2)));
            this.btnFilter.ForeColor = System.Drawing.Color.DarkGray;
            this.btnFilter.Location = new System.Drawing.Point(5, 13);
            this.btnFilter.Name = "btnFilter";
            this.btnFilter.Size = new System.Drawing.Size(302, 24);
            this.btnFilter.TabIndex = 325;
            this.btnFilter.Text = "4";
            this.btnFilter.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFilter.UseVisualStyleBackColor = false;
            this.btnFilter.Click += new System.EventHandler(this.btnFilter_Click);
            this.gbFilter.BackColor = System.Drawing.Color.Transparent;
            this.gbFilter.Controls.Add(this.cmdFilter4);
            this.gbFilter.Controls.Add(this.cmdFilter1);
            this.gbFilter.Controls.Add(this.txtValue1);
            this.gbFilter.Controls.Add(this.txtValue2);
            this.gbFilter.Controls.Add(this.cmdFilter2);
            this.gbFilter.Controls.Add(this.txtValue3);
            this.gbFilter.Controls.Add(this.cmdFilter5);
            this.gbFilter.Controls.Add(this.grdLang);
            this.gbFilter.Controls.Add(this.cmdFilter3);
            this.gbFilter.Controls.Add(this.txtValue5);
            this.gbFilter.Controls.Add(this.txtValue4);
            this.gbFilter.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbFilter.Location = new System.Drawing.Point(7, 170);
            this.gbFilter.Name = "gbFilter";
            this.gbFilter.Size = new System.Drawing.Size(314, 186);
            this.gbFilter.TabIndex = 379;
            this.gbFilter.TabStop = false;
            this.cmdFilter4.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmdFilter4.FormattingEnabled = true;
            this.cmdFilter4.Location = new System.Drawing.Point(9, 115);
            this.cmdFilter4.Name = "cmdFilter4";
            this.cmdFilter4.Size = new System.Drawing.Size(148, 22);
            this.cmdFilter4.TabIndex = 30;
            this.cmdFilter4.SelectedValueChanged += new System.EventHandler(this.cmdFilter4_SelectedValueChanged);
            this.cmdFilter1.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmdFilter1.FormattingEnabled = true;
            this.cmdFilter1.Location = new System.Drawing.Point(9, 19);
            this.cmdFilter1.Name = "cmdFilter1";
            this.cmdFilter1.Size = new System.Drawing.Size(148, 22);
            this.cmdFilter1.TabIndex = 24;
            this.cmdFilter1.SelectedValueChanged += new System.EventHandler(this.cmdFilter1_SelectedValueChanged);
            this.txtValue1.Location = new System.Drawing.Point(172, 20);
            this.txtValue1.Name = "txtValue1";
            this.txtValue1.Size = new System.Drawing.Size(121, 20);
            this.txtValue1.TabIndex = 23;
            this.txtValue1.TextChanged += new System.EventHandler(this.txtValue1_TextChanged);
            this.txtValue2.Location = new System.Drawing.Point(172, 52);
            this.txtValue2.Name = "txtValue2";
            this.txtValue2.Size = new System.Drawing.Size(121, 20);
            this.txtValue2.TabIndex = 25;
            this.txtValue2.TextChanged += new System.EventHandler(this.txtValue2_TextChanged);
            this.cmdFilter2.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmdFilter2.FormattingEnabled = true;
            this.cmdFilter2.Location = new System.Drawing.Point(9, 51);
            this.cmdFilter2.Name = "cmdFilter2";
            this.cmdFilter2.Size = new System.Drawing.Size(148, 22);
            this.cmdFilter2.TabIndex = 26;
            this.cmdFilter2.SelectedValueChanged += new System.EventHandler(this.cmdFilter2_SelectedValueChanged);
            this.txtValue3.Location = new System.Drawing.Point(172, 84);
            this.txtValue3.Name = "txtValue3";
            this.txtValue3.Size = new System.Drawing.Size(121, 20);
            this.txtValue3.TabIndex = 27;
            this.txtValue3.TextChanged += new System.EventHandler(this.txtValue3_TextChanged);
            this.cmdFilter5.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmdFilter5.FormattingEnabled = true;
            this.cmdFilter5.Location = new System.Drawing.Point(9, 147);
            this.cmdFilter5.Name = "cmdFilter5";
            this.cmdFilter5.Size = new System.Drawing.Size(148, 22);
            this.cmdFilter5.TabIndex = 32;
            this.cmdFilter5.SelectedValueChanged += new System.EventHandler(this.cmdFilter5_SelectedValueChanged);
            this.cmdFilter3.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmdFilter3.FormattingEnabled = true;
            this.cmdFilter3.Location = new System.Drawing.Point(9, 83);
            this.cmdFilter3.Name = "cmdFilter3";
            this.cmdFilter3.Size = new System.Drawing.Size(148, 22);
            this.cmdFilter3.TabIndex = 28;
            this.cmdFilter3.SelectedValueChanged += new System.EventHandler(this.cmdFilter3_SelectedValueChanged);
            this.txtValue5.Location = new System.Drawing.Point(172, 148);
            this.txtValue5.Name = "txtValue5";
            this.txtValue5.Size = new System.Drawing.Size(121, 20);
            this.txtValue5.TabIndex = 31;
            this.txtValue5.TextChanged += new System.EventHandler(this.txtValue5_TextChanged);
            this.txtValue4.Location = new System.Drawing.Point(172, 116);
            this.txtValue4.Name = "txtValue4";
            this.txtValue4.Size = new System.Drawing.Size(121, 20);
            this.txtValue4.TabIndex = 29;
            this.txtValue4.TextChanged += new System.EventHandler(this.txtValue4_TextChanged);
            this.btnSelect.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnSelect.Image = global::Tourist_Management.Properties.Resources.ok;
            this.btnSelect.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSelect.Location = new System.Drawing.Point(775, 362);
            this.btnSelect.Name = "btnSelect";
            this.btnSelect.Size = new System.Drawing.Size(81, 28);
            this.btnSelect.TabIndex = 380;
            this.btnSelect.Text = "&Select";
            this.btnSelect.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSelect.UseVisualStyleBackColor = true;
            this.btnSelect.Click += new System.EventHandler(this.btnSelect_Click);
            this.gbSpeaks.BackColor = System.Drawing.Color.Transparent;
            this.gbSpeaks.Controls.Add(this.rdbOne);
            this.gbSpeaks.Controls.Add(this.rdbAll);
            this.gbSpeaks.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbSpeaks.Location = new System.Drawing.Point(7, 358);
            this.gbSpeaks.Name = "gbSpeaks";
            this.gbSpeaks.Size = new System.Drawing.Size(314, 39);
            this.gbSpeaks.TabIndex = 381;
            this.gbSpeaks.TabStop = false;
            this.gbSpeaks.Text = "Speaks";
            this.gbSpeaks.Visible = false;
            this.rdbOne.AutoSize = true;
            this.rdbOne.Location = new System.Drawing.Point(167, 15);
            this.rdbOne.Name = "rdbOne";
            this.rdbOne.Size = new System.Drawing.Size(90, 18);
            this.rdbOne.TabIndex = 1;
            this.rdbOne.Text = "Atleast One";
            this.rdbOne.UseVisualStyleBackColor = true;
            this.rdbAll.AutoSize = true;
            this.rdbAll.Checked = true;
            this.rdbAll.Location = new System.Drawing.Point(50, 15);
            this.rdbAll.Name = "rdbAll";
            this.rdbAll.Size = new System.Drawing.Size(91, 18);
            this.rdbAll.TabIndex = 0;
            this.rdbAll.TabStop = true;
            this.rdbAll.Text = "All Selected";
            this.rdbAll.UseVisualStyleBackColor = true;
            this.rdbAll.CheckedChanged += new System.EventHandler(this.rdbAll_CheckedChanged);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(1026, 402);
            this.ControlBox = false;
            this.Controls.Add(this.gbSpeaks);
            this.Controls.Add(this.btnSelect);
            this.Controls.Add(this.gbFilter);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.groupBox20);
            this.Controls.Add(this.label18);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.btnClear);
            this.Controls.Add(this.grdFilter);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.Name = "frmFilterDrvGuide";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmFilterDrvGuide_Load);
            ((System.ComponentModel.ISupportInitialize)(this.grdFilter)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdLang)).EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.gbFilter.ResumeLayout(false);
            this.gbFilter.PerformLayout();
            this.gbSpeaks.ResumeLayout(false);
            this.gbSpeaks.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private C1.Win.C1FlexGrid.C1FlexGrid grdFilter;
        private System.Windows.Forms.Button btnClear;
        private C1.Win.C1FlexGrid.C1FlexGrid grdLang;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.GroupBox groupBox20;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Button btnGrid;
        private System.Windows.Forms.Button btnFilter;
        private System.Windows.Forms.GroupBox gbFilter;
        private  Tourist_Management.User_Controls.ComboBox cmdFilter1;
        private System.Windows.Forms.TextBox txtValue1;
        private System.Windows.Forms.TextBox txtValue2;
        private  Tourist_Management.User_Controls.ComboBox cmdFilter2;
        private System.Windows.Forms.TextBox txtValue3;
        private  Tourist_Management.User_Controls.ComboBox cmdFilter5;
        private  Tourist_Management.User_Controls.ComboBox cmdFilter3;
        private System.Windows.Forms.TextBox txtValue5;
        private System.Windows.Forms.TextBox txtValue4;
        private  Tourist_Management.User_Controls.ComboBox cmdFilter4;
        private System.Windows.Forms.Button btnSelect;
        private System.Windows.Forms.GroupBox gbSpeaks;
        private System.Windows.Forms.RadioButton rdbOne;
        private System.Windows.Forms.RadioButton rdbAll;
        public  Tourist_Management.User_Controls.ComboBox cmbMainFilter;
    }
}