namespace Tourist_Management.Main
{
    partial class frmMDIMain
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmMDIMain));
            this.menuStrip = new System.Windows.Forms.MenuStrip();
            this.toolStrip = new System.Windows.Forms.ToolStrip();
            this.statusStrip = new System.Windows.Forms.StatusStrip();
            this.toolSCompany = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel2 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolSCommon = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel3 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolSLogIn = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel4 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolSLogOut = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel5 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolSDate = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel1 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolSUser = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolTip = new System.Windows.Forms.ToolTip(this.components);
            this.pbLock = new System.Windows.Forms.PictureBox();
            this.pnlTreeMain = new System.Windows.Forms.Panel();
            this.pnlRecent = new System.Windows.Forms.Panel();
            this.label1 = new System.Windows.Forms.Label();
            this.btnRecent = new System.Windows.Forms.Button();
            this.flxR = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.pnlTree = new System.Windows.Forms.Panel();
            this.btnTree = new System.Windows.Forms.Button();
            this.treeMain = new System.Windows.Forms.TreeView();
            this.tabMain = new System.Windows.Forms.TabControl();
            this.popUp = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.ExpandToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.closeOtherFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.imgTree = new System.Windows.Forms.ImageList(this.components);
            this.helpMenu = new System.Windows.Forms.ToolStripMenuItem();
            this.pnlTime = new System.Windows.Forms.Panel();
            this.lblTime = new System.Windows.Forms.Label();
            this.tmerMain = new System.Windows.Forms.Timer(this.components);
            this.PnlLFTOP = new System.Windows.Forms.Panel();
            this.lblProduct = new System.Windows.Forms.Label();
            this.pbMain = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.pbLock)).BeginInit();
            this.pnlTreeMain.SuspendLayout();
            this.pnlRecent.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.flxR)).BeginInit();
            this.pnlTree.SuspendLayout();
            this.popUp.SuspendLayout();
            this.pnlTime.SuspendLayout();
            this.PnlLFTOP.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbMain)).BeginInit();
            this.SuspendLayout();
            this.menuStrip.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.menuStrip.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.menuStrip.Location = new System.Drawing.Point(0, 0);
            this.menuStrip.Name = "menuStrip";
            this.menuStrip.Size = new System.Drawing.Size(1033, 24);
            this.menuStrip.TabIndex = 0;
            this.menuStrip.Text = "MenuStrip";
            this.toolStrip.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.toolStrip.LayoutStyle = System.Windows.Forms.ToolStripLayoutStyle.HorizontalStackWithOverflow;
            this.toolStrip.Location = new System.Drawing.Point(0, 24);
            this.toolStrip.Name = "toolStrip";
            this.toolStrip.Size = new System.Drawing.Size(1033, 25);
            this.toolStrip.TabIndex = 1;
            this.toolStrip.Text = "ToolStrip";
            this.toolStrip.ItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.toolStrip_ItemClicked);
            this.statusStrip.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.statusStrip.Location = new System.Drawing.Point(0, 518);
            this.statusStrip.Name = "statusStrip";
            this.statusStrip.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.statusStrip.Size = new System.Drawing.Size(1033, 22);
            this.statusStrip.TabIndex = 2;
            this.statusStrip.Text = "StatusStrip";
            this.toolSCompany.BackColor = System.Drawing.Color.Transparent;
            this.toolSCompany.Font = new System.Drawing.Font("Tahoma", 8.25F);
            this.toolSCompany.Image = ((System.Drawing.Image)(resources.GetObject("toolSCompany.Image")));
            this.toolSCompany.Name = "toolSCompany";
            this.toolSCompany.Size = new System.Drawing.Size(121, 17);
            this.toolSCompany.Text = "Tourist Management";
            this.toolStripStatusLabel2.BackColor = System.Drawing.Color.Transparent;
            this.toolStripStatusLabel2.Font = new System.Drawing.Font("Tahoma", 8.25F);
            this.toolStripStatusLabel2.Name = "toolStripStatusLabel2";
            this.toolStripStatusLabel2.Size = new System.Drawing.Size(22, 17);
            this.toolStripStatusLabel2.Text = "     ";
            this.toolSCommon.BackColor = System.Drawing.Color.Transparent;
            this.toolSCommon.Font = new System.Drawing.Font("Tahoma", 8.25F);
            this.toolSCommon.Image = ((System.Drawing.Image)(resources.GetObject("toolSCommon.Image")));
            this.toolSCommon.Name = "toolSCommon";
            this.toolSCommon.Size = new System.Drawing.Size(81, 17);
            this.toolSCommon.Text = "TM Common";
            this.toolStripStatusLabel3.BackColor = System.Drawing.Color.Transparent;
            this.toolStripStatusLabel3.Font = new System.Drawing.Font("Tahoma", 8.25F);
            this.toolStripStatusLabel3.Name = "toolStripStatusLabel3";
            this.toolStripStatusLabel3.Size = new System.Drawing.Size(22, 17);
            this.toolStripStatusLabel3.Text = "     ";
            this.toolSLogIn.BackColor = System.Drawing.Color.Transparent;
            this.toolSLogIn.Name = "toolSLogIn";
            this.toolSLogIn.Size = new System.Drawing.Size(109, 17);
            this.toolSLogIn.Text = "toolStripStatusLabel4";
            this.toolStripStatusLabel4.BackColor = System.Drawing.Color.Transparent;
            this.toolStripStatusLabel4.Name = "toolStripStatusLabel4";
            this.toolStripStatusLabel4.Size = new System.Drawing.Size(22, 17);
            this.toolStripStatusLabel4.Text = "     ";
            this.toolSLogOut.BackColor = System.Drawing.Color.Transparent;
            this.toolSLogOut.Name = "toolSLogOut";
            this.toolSLogOut.Size = new System.Drawing.Size(109, 17);
            this.toolSLogOut.Text = "toolStripStatusLabel4";
            this.toolStripStatusLabel5.BackColor = System.Drawing.Color.Transparent;
            this.toolStripStatusLabel5.Name = "toolStripStatusLabel5";
            this.toolStripStatusLabel5.Size = new System.Drawing.Size(22, 17);
            this.toolStripStatusLabel5.Text = "     ";
            this.toolSDate.BackColor = System.Drawing.Color.Transparent;
            this.toolSDate.Name = "toolSDate";
            this.toolSDate.Size = new System.Drawing.Size(109, 17);
            this.toolSDate.Text = "toolStripStatusLabel4";
            this.toolStripStatusLabel1.BackColor = System.Drawing.Color.Transparent;
            this.toolStripStatusLabel1.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.toolStripStatusLabel1.Name = "toolStripStatusLabel1";
            this.toolStripStatusLabel1.Size = new System.Drawing.Size(22, 17);
            this.toolStripStatusLabel1.Text = "     ";
            this.toolSUser.BackColor = System.Drawing.Color.Transparent;
            this.toolSUser.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.toolSUser.Image = ((System.Drawing.Image)(resources.GetObject("toolSUser.Image")));
            this.toolSUser.Name = "toolSUser";
            this.toolSUser.Size = new System.Drawing.Size(52, 17);
            this.toolSUser.Text = "Admin";
            this.pbLock.BackColor = System.Drawing.Color.WhiteSmoke;
            this.pbLock.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pbLock.Image = global::Tourist_Management.Properties.Resources.locking;
            this.pbLock.Location = new System.Drawing.Point(801, 3);
            this.pbLock.Name = "pbLock";
            this.pbLock.Size = new System.Drawing.Size(45, 43);
            this.pbLock.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbLock.TabIndex = 1;
            this.pbLock.TabStop = false;
            this.toolTip.SetToolTip(this.pbLock, "Lock System");
            this.pbLock.Click += new System.EventHandler(this.pbLock_Click);
            this.pnlTreeMain.BackColor = System.Drawing.Color.White;
            this.pnlTreeMain.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pnlTreeMain.Controls.Add(this.pnlRecent);
            this.pnlTreeMain.Controls.Add(this.pnlTree);
            this.pnlTreeMain.Location = new System.Drawing.Point(2, 52);
            this.pnlTreeMain.Name = "pnlTreeMain";
            this.pnlTreeMain.Size = new System.Drawing.Size(254, 463);
            this.pnlTreeMain.TabIndex = 4;
            this.pnlRecent.BackColor = System.Drawing.Color.Transparent;
            this.pnlRecent.Controls.Add(this.label1);
            this.pnlRecent.Controls.Add(this.btnRecent);
            this.pnlRecent.Controls.Add(this.flxR);
            this.pnlRecent.Location = new System.Drawing.Point(1, 291);
            this.pnlRecent.Name = "pnlRecent";
            this.pnlRecent.Size = new System.Drawing.Size(253, 164);
            this.pnlRecent.TabIndex = 1;
            this.pnlRecent.MouseMove += new System.Windows.Forms.MouseEventHandler(this.pnlRecent_MouseMove);
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Underline, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label1.Location = new System.Drawing.Point(5, 3);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(248, 13);
            this.label1.TabIndex = 2;
            this.label1.Text = "     Most recently used                                             ";
            this.btnRecent.BackColor = System.Drawing.Color.Transparent;
            this.btnRecent.FlatAppearance.BorderColor = System.Drawing.Color.White;
            this.btnRecent.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRecent.Location = new System.Drawing.Point(233, -5);
            this.btnRecent.Name = "btnRecent";
            this.btnRecent.Size = new System.Drawing.Size(22, 21);
            this.btnRecent.TabIndex = 2;
            this.btnRecent.Text = "x";
            this.btnRecent.UseVisualStyleBackColor = false;
            this.btnRecent.Click += new System.EventHandler(this.btnRecent_Click);
            this.flxR.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.None;
            this.flxR.ColumnInfo = "1,0,0,0,0,90,Columns:0{Width:226;}\t";
            this.flxR.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.flxR.ForeColor = System.Drawing.Color.Black;
            this.flxR.Location = new System.Drawing.Point(4, 21);
            this.flxR.Name = "flxR";
            this.flxR.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.flxR.Size = new System.Drawing.Size(246, 138);
            this.flxR.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("flxR.Styles"));
            this.flxR.TabIndex = 0;
            this.flxR.Click += new System.EventHandler(this.flxR_Click);
            this.flxR.MouseLeave += new System.EventHandler(this.flxR_MouseLeave);
            this.flxR.MouseMove += new System.Windows.Forms.MouseEventHandler(this.flxR_MouseMove_1);
            this.pnlTree.BackColor = System.Drawing.Color.White;
            this.pnlTree.Controls.Add(this.btnTree);
            this.pnlTree.Controls.Add(this.treeMain);
            this.pnlTree.Location = new System.Drawing.Point(-2, -1);
            this.pnlTree.Name = "pnlTree";
            this.pnlTree.Size = new System.Drawing.Size(253, 289);
            this.pnlTree.TabIndex = 0;
            this.pnlTree.MouseMove += new System.Windows.Forms.MouseEventHandler(this.pnlTree_MouseMove);
            this.btnTree.BackColor = System.Drawing.Color.Transparent;
            this.btnTree.FlatAppearance.BorderColor = System.Drawing.Color.White;
            this.btnTree.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnTree.Location = new System.Drawing.Point(232, -4);
            this.btnTree.Name = "btnTree";
            this.btnTree.Size = new System.Drawing.Size(22, 21);
            this.btnTree.TabIndex = 1;
            this.btnTree.Text = "x";
            this.btnTree.UseVisualStyleBackColor = false;
            this.btnTree.Click += new System.EventHandler(this.btnTree_Click);
            this.treeMain.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.treeMain.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.treeMain.ForeColor = System.Drawing.Color.Black;
            this.treeMain.HideSelection = false;
            this.treeMain.Location = new System.Drawing.Point(3, 22);
            this.treeMain.Name = "treeMain";
            this.treeMain.Size = new System.Drawing.Size(223, 181);
            this.treeMain.TabIndex = 0;
            this.treeMain.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.treeMain_AfterSelect);
            this.treeMain.NodeMouseClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.treeMain_NodeMouseClick);
            this.treeMain.KeyDown += new System.Windows.Forms.KeyEventHandler(this.treeMain_KeyDown);
            this.tabMain.DrawMode = System.Windows.Forms.TabDrawMode.OwnerDrawFixed;
            this.tabMain.Font = new System.Drawing.Font("Times New Roman", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tabMain.Location = new System.Drawing.Point(274, 78);
            this.tabMain.Name = "tabMain";
            this.tabMain.SelectedIndex = 0;
            this.tabMain.Size = new System.Drawing.Size(721, 22);
            this.tabMain.TabIndex = 6;
            this.tabMain.DrawItem += new System.Windows.Forms.DrawItemEventHandler(this.tabMain_DrawItem);
            this.tabMain.SelectedIndexChanged += new System.EventHandler(this.tabMain_SelectedIndexChanged);
            this.tabMain.MouseClick += new System.Windows.Forms.MouseEventHandler(this.tabMain_MouseClick);
            this.popUp.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.ExpandToolStripMenuItem,
            this.closeOtherFormToolStripMenuItem});
            this.popUp.Name = "popUp";
            this.popUp.Size = new System.Drawing.Size(184, 48);
            this.ExpandToolStripMenuItem.BackColor = System.Drawing.Color.Azure;
            this.ExpandToolStripMenuItem.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.ExpandToolStripMenuItem.Name = "ExpandToolStripMenuItem";
            this.ExpandToolStripMenuItem.Size = new System.Drawing.Size(183, 22);
            this.ExpandToolStripMenuItem.Text = "Close this from";
            this.ExpandToolStripMenuItem.Click += new System.EventHandler(this.ExpandToolStripMenuItem_Click);
            this.closeOtherFormToolStripMenuItem.BackColor = System.Drawing.Color.Azure;
            this.closeOtherFormToolStripMenuItem.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.closeOtherFormToolStripMenuItem.Name = "closeOtherFormToolStripMenuItem";
            this.closeOtherFormToolStripMenuItem.Size = new System.Drawing.Size(183, 22);
            this.closeOtherFormToolStripMenuItem.Text = "Close all other forms";
            this.closeOtherFormToolStripMenuItem.Click += new System.EventHandler(this.closeOtherFormToolStripMenuItem_Click);
            this.imgTree.ColorDepth = System.Windows.Forms.ColorDepth.Depth8Bit;
            this.imgTree.ImageSize = new System.Drawing.Size(20, 20);
            this.imgTree.TransparentColor = System.Drawing.Color.Transparent;
            this.helpMenu.Name = "helpMenu";
            this.helpMenu.Size = new System.Drawing.Size(44, 20);
            this.helpMenu.Text = "&Help";
            this.pnlTime.BackColor = System.Drawing.Color.WhiteSmoke;
            this.pnlTime.Controls.Add(this.lblTime);
            this.pnlTime.Location = new System.Drawing.Point(849, 0);
            this.pnlTime.Name = "pnlTime";
            this.pnlTime.Size = new System.Drawing.Size(172, 49);
            this.pnlTime.TabIndex = 8;
            this.lblTime.AutoSize = true;
            this.lblTime.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTime.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.lblTime.Location = new System.Drawing.Point(52, 14);
            this.lblTime.Name = "lblTime";
            this.lblTime.Size = new System.Drawing.Size(51, 19);
            this.lblTime.TabIndex = 0;
            this.lblTime.Text = "label2";
            this.tmerMain.Tick += new System.EventHandler(this.tmerMain_Tick);
            this.PnlLFTOP.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.PnlLFTOP.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.PnlLFTOP.Controls.Add(this.lblProduct);
            this.PnlLFTOP.Controls.Add(this.pbMain);
            this.PnlLFTOP.Location = new System.Drawing.Point(263, 52);
            this.PnlLFTOP.Name = "PnlLFTOP";
            this.PnlLFTOP.Size = new System.Drawing.Size(752, 24);
            this.PnlLFTOP.TabIndex = 10;
            this.PnlLFTOP.SizeChanged += new System.EventHandler(this.PnlLFTOP_SizeChanged);
            this.lblProduct.BackColor = System.Drawing.Color.Transparent;
            this.lblProduct.Font = new System.Drawing.Font("Times New Roman", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblProduct.ForeColor = System.Drawing.Color.Blue;
            this.lblProduct.Location = new System.Drawing.Point(178, 1);
            this.lblProduct.Name = "lblProduct";
            this.lblProduct.Size = new System.Drawing.Size(300, 20);
            this.lblProduct.TabIndex = 4;
            this.lblProduct.Text = "RH Tour Inbound Management System";
            this.lblProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.pbMain.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pbMain.Location = new System.Drawing.Point(0, 0);
            this.pbMain.Name = "pbMain";
            this.pbMain.Size = new System.Drawing.Size(752, 23);
            this.pbMain.TabIndex = 5;
            this.pbMain.TabStop = false;
            this.AccessibleRole = System.Windows.Forms.AccessibleRole.MenuBar;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(1033, 540);
            this.Controls.Add(this.PnlLFTOP);
            this.Controls.Add(this.pbLock);
            this.Controls.Add(this.pnlTime);
            this.Controls.Add(this.pnlTreeMain);
            this.Controls.Add(this.tabMain);
            this.Controls.Add(this.statusStrip);
            this.Controls.Add(this.toolStrip);
            this.Controls.Add(this.menuStrip);
            this.IsMdiContainer = true;
            this.MainMenuStrip = this.menuStrip;
            this.MaximizeBox = false;
            this.Name = "frmMDIMain";
            this.Text = "RH Tour Inbound Management System";
            this.Activated += new System.EventHandler(this.frmMDIMain_Activated);
            this.Load += new System.EventHandler(this.frmMDIMain_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pbLock)).EndInit();
            this.pnlTreeMain.ResumeLayout(false);
            this.pnlRecent.ResumeLayout(false);
            this.pnlRecent.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.flxR)).EndInit();
            this.pnlTree.ResumeLayout(false);
            this.popUp.ResumeLayout(false);
            this.pnlTime.ResumeLayout(false);
            this.pnlTime.PerformLayout();
            this.PnlLFTOP.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbMain)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.MenuStrip menuStrip;
        private System.Windows.Forms.ToolStrip toolStrip;
        private System.Windows.Forms.StatusStrip statusStrip;
        private System.Windows.Forms.ToolTip toolTip;
        private System.Windows.Forms.Panel pnlTreeMain;
        private System.Windows.Forms.Panel pnlTree;
        private System.Windows.Forms.TreeView treeMain;
        private System.Windows.Forms.TabControl tabMain;
        private System.Windows.Forms.Button btnTree;
        internal System.Windows.Forms.ContextMenuStrip popUp;
        internal System.Windows.Forms.ToolStripMenuItem ExpandToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem closeOtherFormToolStripMenuItem;
        private System.Windows.Forms.ImageList imgTree;
        private System.Windows.Forms.ToolStripMenuItem helpMenu;
        private System.Windows.Forms.Panel pnlTime;
        private System.Windows.Forms.Label lblTime;
        private System.Windows.Forms.Timer tmerMain;
        internal System.Windows.Forms.PictureBox pbLock;
        private System.Windows.Forms.ToolStripStatusLabel toolSUser;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel1;
        private System.Windows.Forms.ToolStripStatusLabel toolSCompany;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel2;
        private System.Windows.Forms.ToolStripStatusLabel toolSCommon;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel3;
        internal System.Windows.Forms.Panel PnlLFTOP;
        private System.Windows.Forms.Panel pnlRecent;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button btnRecent;
        private C1.Win.C1FlexGrid.C1FlexGrid flxR;
        private System.Windows.Forms.PictureBox pbMain;
        private System.Windows.Forms.ToolStripStatusLabel toolSLogIn;
        private System.Windows.Forms.ToolStripStatusLabel toolSLogOut;
        private System.Windows.Forms.ToolStripStatusLabel toolSDate;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel4;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel5;
        internal System.Windows.Forms.Label lblProduct;
    }
}
