namespace Tourist_Management.Main
{
    partial class frmNewUser
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmNewUser));
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.drpEmp = new DropDowns.DropSearch();
            this.drpUserGroupID = new DropDowns.DropSearch();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.drpMarketingDep = new DropDowns.DropSearch();
            this.chkUnmask = new System.Windows.Forms.CheckBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.chkIsDirector = new System.Windows.Forms.CheckBox();
            this.chkIsManager = new System.Windows.Forms.CheckBox();
            this.chkIsAdmin = new System.Windows.Forms.CheckBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.ddlDays = new System.Windows.Forms.NumericUpDown();
            this.chkMustChng = new System.Windows.Forms.CheckBox();
            this.chkCanChange = new System.Windows.Forms.CheckBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.lblEmpPhoto = new System.Windows.Forms.Label();
            this.pbEmpPhoto = new System.Windows.Forms.PictureBox();
            this.label8 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.txtDesc = new System.Windows.Forms.TextBox();
            this.label54 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.txtPwHint = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.txtConfmPw = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.txtPw = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.txtName = new System.Windows.Forms.TextBox();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.pnlMain = new System.Windows.Forms.Panel();
            this.treeMain = new System.Windows.Forms.TreeView();
            this.flx = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.chkActive = new System.Windows.Forms.CheckBox();
            this.imgTree = new System.Windows.Forms.ImageList(this.components);
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ddlDays)).BeginInit();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbEmpPhoto)).BeginInit();
            this.tabPage2.SuspendLayout();
            this.pnlMain.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.flx)).BeginInit();
            this.SuspendLayout();
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Location = new System.Drawing.Point(5, 5);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(532, 338);
            this.tabControl1.TabIndex = 0;
            this.tabControl1.SelectedIndexChanged += new System.EventHandler(this.tabControl1_SelectedIndexChanged);
            this.tabPage1.Controls.Add(this.groupBox1);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(524, 312);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "User Deatils";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.groupBox1.Controls.Add(this.drpUserGroupID);
            this.groupBox1.Controls.Add(this.drpEmp);
            this.groupBox1.Controls.Add(this.groupBox4);
            this.groupBox1.Controls.Add(this.chkUnmask);
            this.groupBox1.Controls.Add(this.groupBox3);
            this.groupBox1.Controls.Add(this.groupBox2);
            this.groupBox1.Controls.Add(this.label8);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.txtDesc);
            this.groupBox1.Controls.Add(this.label54);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.txtPwHint);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.txtConfmPw);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.txtPw);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.txtName);
            this.groupBox1.Location = new System.Drawing.Point(14, 4);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(502, 300);
            this.groupBox1.TabIndex = 305;
            this.groupBox1.TabStop = false;
            this.drpEmp.BackColor = System.Drawing.Color.Transparent;
            this.drpEmp.DataSource = null;
            this.drpEmp.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpEmp.FormName = "";
            this.drpEmp.Location = new System.Drawing.Point(120, 168);
            this.drpEmp.Name = "drpEmp";
            this.drpEmp.SelectedText = "";
            this.drpEmp.SelectedValue = "";
            this.drpEmp.Size = new System.Drawing.Size(365, 23);
            this.drpEmp.TabIndex = 288;
            this.drpEmp.Selected_TextChanged += new System.EventHandler(this.drpEmp_Selected_TextChanged);
            this.drpUserGroupID.BackColor = System.Drawing.Color.Transparent;
            this.drpUserGroupID.DataSource = null;
            this.drpUserGroupID.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpUserGroupID.FormName = "";
            this.drpUserGroupID.Location = new System.Drawing.Point(120, 195);
            this.drpUserGroupID.Name = "drpUserGroupID";
            this.drpUserGroupID.SelectedText = "";
            this.drpUserGroupID.SelectedValue = "";
            this.drpUserGroupID.Size = new System.Drawing.Size(365, 23);
            this.drpUserGroupID.TabIndex = 300;
            this.drpUserGroupID.Click_Open += new System.EventHandler(this.drpUserGroupID_Click_Open);
            this.drpUserGroupID.Selected_TextChanged += new System.EventHandler(this.drpUserGroupID_Selected_TextChanged);
            this.groupBox4.Controls.Add(this.drpMarketingDep);
            this.groupBox4.Location = new System.Drawing.Point(261, 219);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(229, 54);
            this.groupBox4.TabIndex = 326;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Set Marketting Dep";
            this.drpMarketingDep.BackColor = System.Drawing.Color.Transparent;
            this.drpMarketingDep.DataSource = null;
            this.drpMarketingDep.Enabled = false;
            this.drpMarketingDep.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpMarketingDep.FormName = "";
            this.drpMarketingDep.Location = new System.Drawing.Point(6, 19);
            this.drpMarketingDep.Name = "drpMarketingDep";
            this.drpMarketingDep.SelectedText = "";
            this.drpMarketingDep.SelectedValue = "";
            this.drpMarketingDep.Size = new System.Drawing.Size(220, 23);
            this.drpMarketingDep.TabIndex = 335;
            this.chkUnmask.AutoSize = true;
            this.chkUnmask.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkUnmask.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkUnmask.Location = new System.Drawing.Point(353, 21);
            this.chkUnmask.Name = "chkUnmask";
            this.chkUnmask.Size = new System.Drawing.Size(112, 17);
            this.chkUnmask.TabIndex = 325;
            this.chkUnmask.Text = "Unmask Password";
            this.chkUnmask.UseVisualStyleBackColor = true;
            this.chkUnmask.CheckedChanged += new System.EventHandler(this.chkUnmask_CheckedChanged);
            this.groupBox3.Controls.Add(this.chkIsDirector);
            this.groupBox3.Controls.Add(this.chkIsManager);
            this.groupBox3.Controls.Add(this.chkIsAdmin);
            this.groupBox3.Controls.Add(this.label7);
            this.groupBox3.Controls.Add(this.label10);
            this.groupBox3.Controls.Add(this.label9);
            this.groupBox3.Controls.Add(this.ddlDays);
            this.groupBox3.Controls.Add(this.chkMustChng);
            this.groupBox3.Controls.Add(this.chkCanChange);
            this.groupBox3.Location = new System.Drawing.Point(11, 219);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(243, 53);
            this.groupBox3.TabIndex = 310;
            this.groupBox3.TabStop = false;
            this.chkIsDirector.AutoSize = true;
            this.chkIsDirector.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkIsDirector.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkIsDirector.Location = new System.Drawing.Point(162, 21);
            this.chkIsDirector.Name = "chkIsDirector";
            this.chkIsDirector.Size = new System.Drawing.Size(76, 17);
            this.chkIsDirector.TabIndex = 324;
            this.chkIsDirector.Text = "Is Director";
            this.chkIsDirector.UseVisualStyleBackColor = true;
            this.chkIsManager.AutoSize = true;
            this.chkIsManager.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkIsManager.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkIsManager.Location = new System.Drawing.Point(76, 21);
            this.chkIsManager.Name = "chkIsManager";
            this.chkIsManager.Size = new System.Drawing.Size(80, 17);
            this.chkIsManager.TabIndex = 323;
            this.chkIsManager.Text = "Is Manager";
            this.chkIsManager.UseVisualStyleBackColor = true;
            this.chkIsManager.CheckedChanged += new System.EventHandler(this.chkIsManager_CheckedChanged);
            this.chkIsAdmin.AutoSize = true;
            this.chkIsAdmin.Enabled = false;
            this.chkIsAdmin.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkIsAdmin.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkIsAdmin.Location = new System.Drawing.Point(6, 21);
            this.chkIsAdmin.Name = "chkIsAdmin";
            this.chkIsAdmin.Size = new System.Drawing.Size(64, 17);
            this.chkIsAdmin.TabIndex = 322;
            this.chkIsAdmin.Text = "IsAdmin";
            this.chkIsAdmin.UseVisualStyleBackColor = true;
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(6, 40);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(167, 13);
            this.label7.TabIndex = 321;
            this.label7.Text = "User must change the paswword ";
            this.label7.Visible = false;
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.Location = new System.Drawing.Point(174, 40);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(35, 13);
            this.label10.TabIndex = 320;
            this.label10.Text = "Every";
            this.label10.Visible = false;
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(254, 40);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(31, 13);
            this.label9.TabIndex = 319;
            this.label9.Text = "Days";
            this.label9.Visible = false;
            this.ddlDays.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ddlDays.Location = new System.Drawing.Point(213, 36);
            this.ddlDays.Name = "ddlDays";
            this.ddlDays.Size = new System.Drawing.Size(34, 21);
            this.ddlDays.TabIndex = 318;
            this.ddlDays.Visible = false;
            this.chkMustChng.AutoSize = true;
            this.chkMustChng.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkMustChng.Location = new System.Drawing.Point(337, 39);
            this.chkMustChng.Name = "chkMustChng";
            this.chkMustChng.Size = new System.Drawing.Size(142, 17);
            this.chkMustChng.TabIndex = 307;
            this.chkMustChng.Text = "Must change paswword ";
            this.chkMustChng.UseVisualStyleBackColor = true;
            this.chkMustChng.Visible = false;
            this.chkCanChange.AutoSize = true;
            this.chkCanChange.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkCanChange.Location = new System.Drawing.Point(337, 13);
            this.chkCanChange.Name = "chkCanChange";
            this.chkCanChange.Size = new System.Drawing.Size(132, 17);
            this.chkCanChange.TabIndex = 306;
            this.chkCanChange.Text = "Can change password";
            this.chkCanChange.UseVisualStyleBackColor = true;
            this.chkCanChange.Visible = false;
            this.groupBox2.BackColor = System.Drawing.Color.Transparent;
            this.groupBox2.Controls.Add(this.lblEmpPhoto);
            this.groupBox2.Controls.Add(this.pbEmpPhoto);
            this.groupBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.Location = new System.Drawing.Point(350, 39);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(134, 122);
            this.groupBox2.TabIndex = 303;
            this.groupBox2.TabStop = false;
            this.lblEmpPhoto.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblEmpPhoto.Location = new System.Drawing.Point(24, 24);
            this.lblEmpPhoto.Name = "lblEmpPhoto";
            this.lblEmpPhoto.Size = new System.Drawing.Size(84, 83);
            this.lblEmpPhoto.TabIndex = 242;
            this.lblEmpPhoto.Text = "Employee Photograph";
            this.lblEmpPhoto.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.pbEmpPhoto.BackColor = System.Drawing.Color.Transparent;
            this.pbEmpPhoto.Location = new System.Drawing.Point(8, 14);
            this.pbEmpPhoto.Name = "pbEmpPhoto";
            this.pbEmpPhoto.Size = new System.Drawing.Size(116, 103);
            this.pbEmpPhoto.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbEmpPhoto.TabIndex = 3;
            this.pbEmpPhoto.TabStop = false;
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(14, 202);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(61, 13);
            this.label8.TabIndex = 299;
            this.label8.Text = "User Group";
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(14, 141);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(60, 13);
            this.label6.TabIndex = 296;
            this.label6.Text = "Description";
            this.txtDesc.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDesc.Location = new System.Drawing.Point(120, 135);
            this.txtDesc.Name = "txtDesc";
            this.txtDesc.Size = new System.Drawing.Size(221, 21);
            this.txtDesc.TabIndex = 295;
            this.label54.AutoSize = true;
            this.label54.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label54.Location = new System.Drawing.Point(14, 172);
            this.label54.Name = "label54";
            this.label54.Size = new System.Drawing.Size(85, 13);
            this.label54.TabIndex = 287;
            this.label54.Text = "Select Employee";
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(14, 111);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(75, 13);
            this.label4.TabIndex = 286;
            this.label4.Text = "Password Hint";
            this.txtPwHint.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPwHint.Location = new System.Drawing.Point(120, 107);
            this.txtPwHint.Name = "txtPwHint";
            this.txtPwHint.Size = new System.Drawing.Size(221, 21);
            this.txtPwHint.TabIndex = 285;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(14, 82);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(93, 13);
            this.label3.TabIndex = 284;
            this.label3.Text = "Confirm Password";
            this.txtConfmPw.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtConfmPw.Location = new System.Drawing.Point(120, 78);
            this.txtConfmPw.Name = "txtConfmPw";
            this.txtConfmPw.PasswordChar = '*';
            this.txtConfmPw.Size = new System.Drawing.Size(221, 21);
            this.txtConfmPw.TabIndex = 283;
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(14, 54);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(53, 13);
            this.label2.TabIndex = 282;
            this.label2.Text = "Password";
            this.txtPw.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPw.Location = new System.Drawing.Point(120, 49);
            this.txtPw.Name = "txtPw";
            this.txtPw.PasswordChar = '*';
            this.txtPw.Size = new System.Drawing.Size(221, 21);
            this.txtPw.TabIndex = 281;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(14, 24);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(59, 13);
            this.label1.TabIndex = 280;
            this.label1.Text = "User Name";
            this.txtName.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtName.Location = new System.Drawing.Point(120, 20);
            this.txtName.Name = "txtName";
            this.txtName.Size = new System.Drawing.Size(221, 21);
            this.txtName.TabIndex = 279;
            this.tabPage2.Controls.Add(this.pnlMain);
            this.tabPage2.Controls.Add(this.flx);
            this.tabPage2.Location = new System.Drawing.Point(4, 22);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(524, 312);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "User Permission";
            this.tabPage2.UseVisualStyleBackColor = true;
            this.pnlMain.Controls.Add(this.treeMain);
            this.pnlMain.Location = new System.Drawing.Point(3, 3);
            this.pnlMain.Name = "pnlMain";
            this.pnlMain.Size = new System.Drawing.Size(264, 335);
            this.pnlMain.TabIndex = 13;
            this.treeMain.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.treeMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treeMain.Location = new System.Drawing.Point(0, 0);
            this.treeMain.Name = "treeMain";
            this.treeMain.Size = new System.Drawing.Size(264, 335);
            this.treeMain.TabIndex = 221;
            this.treeMain.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.treeMain_AfterSelect);
            this.flx.AllowMerging = C1.Win.C1FlexGrid.AllowMergingEnum.Free;
            this.flx.AllowSorting = C1.Win.C1FlexGrid.AllowSortingEnum.None;
            this.flx.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.Light3D;
            this.flx.ColumnInfo = "0,0,0,0,0,85,Columns:";
            this.flx.Location = new System.Drawing.Point(271, 1);
            this.flx.Name = "flx";
            this.flx.Size = new System.Drawing.Size(507, 337);
            this.flx.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("flx.Styles"));
            this.flx.TabIndex = 12;
            this.flx.AfterEdit += new C1.Win.C1FlexGrid.RowColEventHandler(this.flx_AfterEdit);
            this.btnCancel.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Location = new System.Drawing.Point(450, 363);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(75, 23);
            this.btnCancel.TabIndex = 215;
            this.btnCancel.Text = "&Cancel";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnOk.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Location = new System.Drawing.Point(369, 363);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(75, 23);
            this.btnOk.TabIndex = 214;
            this.btnOk.Text = "&OK";
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.chkActive.AutoSize = true;
            this.chkActive.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkActive.Location = new System.Drawing.Point(288, 366);
            this.chkActive.Name = "chkActive";
            this.chkActive.Size = new System.Drawing.Size(65, 17);
            this.chkActive.TabIndex = 292;
            this.chkActive.Text = "IsActive";
            this.chkActive.UseVisualStyleBackColor = true;
            this.imgTree.ColorDepth = System.Windows.Forms.ColorDepth.Depth8Bit;
            this.imgTree.ImageSize = new System.Drawing.Size(20, 20);
            this.imgTree.TransparentColor = System.Drawing.Color.Transparent;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(548, 396);
            this.Controls.Add(this.chkActive);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.tabControl1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmNewUser";
            this.Text = "User Settings";
            this.Load += new System.EventHandler(this.frmNewUser_Load);
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ddlDays)).EndInit();
            this.groupBox2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbEmpPhoto)).EndInit();
            this.tabPage2.ResumeLayout(false);
            this.pnlMain.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.flx)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private DropDowns.DropSearch drpEmp;
        private System.Windows.Forms.Label label54;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox txtPwHint;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox txtConfmPw;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox txtPw;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox txtName;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.TextBox txtDesc;
        private System.Windows.Forms.CheckBox chkActive;
        private System.Windows.Forms.Panel pnlMain;
        private System.Windows.Forms.TreeView treeMain;
        private C1.Win.C1FlexGrid.C1FlexGrid flx;
        private System.Windows.Forms.ImageList imgTree;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label lblEmpPhoto;
        private System.Windows.Forms.PictureBox pbEmpPhoto;
        private DropDowns.DropSearch drpUserGroupID;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.CheckBox chkIsAdmin;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.NumericUpDown ddlDays;
        private System.Windows.Forms.CheckBox chkMustChng;
        private System.Windows.Forms.CheckBox chkCanChange;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.CheckBox chkIsDirector;
        private System.Windows.Forms.CheckBox chkIsManager;
        private System.Windows.Forms.CheckBox chkUnmask;
        private System.Windows.Forms.GroupBox groupBox4;
        private DropDowns.DropSearch drpMarketingDep;
    }
}