namespace Tourist_Management.Master
{
    partial class frmCompany
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmCompany));
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tpCom = new System.Windows.Forms.TabPage();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.label8 = new System.Windows.Forms.Label();
            this.txtPostal1 = new System.Windows.Forms.TextBox();
            this.txtPhysical = new System.Windows.Forms.TextBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.label4 = new System.Windows.Forms.Label();
            this.txtPostal2 = new System.Windows.Forms.TextBox();
            this.txtPostal = new System.Windows.Forms.TextBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.label20 = new System.Windows.Forms.Label();
            this.txtEmailTo = new System.Windows.Forms.TextBox();
            this.label15 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.txtWeb = new System.Windows.Forms.TextBox();
            this.txtEmail = new System.Windows.Forms.TextBox();
            this.txtMob = new System.Windows.Forms.TextBox();
            this.txtFax = new System.Windows.Forms.TextBox();
            this.txtTel = new System.Windows.Forms.TextBox();
            this.txtConperson = new System.Windows.Forms.TextBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.lblCompLogo = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.btnClearLogo = new System.Windows.Forms.Button();
            this.btnUploadLogo = new System.Windows.Forms.Button();
            this.pbCompLogo = new System.Windows.Forms.PictureBox();
            this.txtDisName = new System.Windows.Forms.TextBox();
            this.txtComName = new System.Windows.Forms.TextBox();
            this.txtComCode = new System.Windows.Forms.TextBox();
            this.tpBNK = new System.Windows.Forms.TabPage();
            this.grdBNK = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.tpSummary = new System.Windows.Forms.TabPage();
            this.groupBox8 = new System.Windows.Forms.GroupBox();
            this.label18 = new System.Windows.Forms.Label();
            this.textBox7 = new System.Windows.Forms.TextBox();
            this.label19 = new System.Windows.Forms.Label();
            this.textBox8 = new System.Windows.Forms.TextBox();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.label16 = new System.Windows.Forms.Label();
            this.textBox5 = new System.Windows.Forms.TextBox();
            this.label17 = new System.Windows.Forms.Label();
            this.textBox6 = new System.Windows.Forms.TextBox();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.label13 = new System.Windows.Forms.Label();
            this.textBox3 = new System.Windows.Forms.TextBox();
            this.label14 = new System.Windows.Forms.Label();
            this.textBox4 = new System.Windows.Forms.TextBox();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.label12 = new System.Windows.Forms.Label();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.tabControl1.SuspendLayout();
            this.tpCom.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbCompLogo)).BeginInit();
            this.tpBNK.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdBNK)).BeginInit();
            this.tpSummary.SuspendLayout();
            this.groupBox8.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.groupBox5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.SuspendLayout();
            this.tabControl1.Controls.Add(this.tpCom);
            this.tabControl1.Controls.Add(this.tpBNK);
            this.tabControl1.Controls.Add(this.tpSummary);
            this.tabControl1.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tabControl1.Location = new System.Drawing.Point(2, 7);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(547, 425);
            this.tabControl1.TabIndex = 0;
            this.tpCom.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tpCom.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tpCom.Controls.Add(this.groupBox4);
            this.tpCom.Controls.Add(this.groupBox1);
            this.tpCom.Controls.Add(this.groupBox3);
            this.tpCom.Controls.Add(this.groupBox2);
            this.tpCom.Location = new System.Drawing.Point(4, 22);
            this.tpCom.Name = "tpCom";
            this.tpCom.Padding = new System.Windows.Forms.Padding(3);
            this.tpCom.Size = new System.Drawing.Size(539, 399);
            this.tpCom.TabIndex = 0;
            this.tpCom.Text = "Company";
            this.tpCom.UseVisualStyleBackColor = true;
            this.groupBox4.BackColor = System.Drawing.Color.Transparent;
            this.groupBox4.Controls.Add(this.label8);
            this.groupBox4.Controls.Add(this.txtPostal1);
            this.groupBox4.Controls.Add(this.txtPhysical);
            this.groupBox4.Location = new System.Drawing.Point(10, 235);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(254, 149);
            this.groupBox4.TabIndex = 18;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Physical Address";
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(9, 125);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(64, 13);
            this.label8.TabIndex = 14;
            this.label8.Text = "Postal Code";
            this.txtPostal1.Location = new System.Drawing.Point(74, 122);
            this.txtPostal1.Name = "txtPostal1";
            this.txtPostal1.Size = new System.Drawing.Size(166, 21);
            this.txtPostal1.TabIndex = 1;
            this.txtPhysical.BackColor = System.Drawing.Color.LightYellow;
            this.txtPhysical.Location = new System.Drawing.Point(74, 23);
            this.txtPhysical.Multiline = true;
            this.txtPhysical.Name = "txtPhysical";
            this.txtPhysical.Size = new System.Drawing.Size(166, 93);
            this.txtPhysical.TabIndex = 0;
            this.groupBox1.BackColor = System.Drawing.Color.Transparent;
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.txtPostal2);
            this.groupBox1.Controls.Add(this.txtPostal);
            this.groupBox1.Location = new System.Drawing.Point(270, 235);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(257, 149);
            this.groupBox1.TabIndex = 19;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Postal Address";
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(13, 125);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(64, 13);
            this.label4.TabIndex = 14;
            this.label4.Text = "Postal Code";
            this.txtPostal2.Location = new System.Drawing.Point(83, 121);
            this.txtPostal2.Name = "txtPostal2";
            this.txtPostal2.Size = new System.Drawing.Size(156, 21);
            this.txtPostal2.TabIndex = 1;
            this.txtPostal.Location = new System.Drawing.Point(83, 23);
            this.txtPostal.Multiline = true;
            this.txtPostal.Name = "txtPostal";
            this.txtPostal.Size = new System.Drawing.Size(156, 93);
            this.txtPostal.TabIndex = 0;
            this.groupBox3.BackColor = System.Drawing.Color.Transparent;
            this.groupBox3.Controls.Add(this.label20);
            this.groupBox3.Controls.Add(this.txtEmailTo);
            this.groupBox3.Controls.Add(this.label15);
            this.groupBox3.Controls.Add(this.label11);
            this.groupBox3.Controls.Add(this.label10);
            this.groupBox3.Controls.Add(this.label9);
            this.groupBox3.Controls.Add(this.label6);
            this.groupBox3.Controls.Add(this.label5);
            this.groupBox3.Controls.Add(this.txtWeb);
            this.groupBox3.Controls.Add(this.txtEmail);
            this.groupBox3.Controls.Add(this.txtMob);
            this.groupBox3.Controls.Add(this.txtFax);
            this.groupBox3.Controls.Add(this.txtTel);
            this.groupBox3.Controls.Add(this.txtConperson);
            this.groupBox3.Location = new System.Drawing.Point(9, 116);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(517, 116);
            this.groupBox3.TabIndex = 17;
            this.groupBox3.TabStop = false;
            this.label20.AutoSize = true;
            this.label20.Location = new System.Drawing.Point(291, 93);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(50, 13);
            this.label20.TabIndex = 17;
            this.label20.Text = "E-Mail To";
            this.txtEmailTo.Location = new System.Drawing.Point(344, 89);
            this.txtEmailTo.Name = "txtEmailTo";
            this.txtEmailTo.Size = new System.Drawing.Size(163, 21);
            this.txtEmailTo.TabIndex = 16;
            this.label15.AutoSize = true;
            this.label15.Location = new System.Drawing.Point(9, 17);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(81, 13);
            this.label15.TabIndex = 14;
            this.label15.Text = "Contact Person";
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(9, 92);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(29, 13);
            this.label11.TabIndex = 15;
            this.label11.Text = "Web";
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(291, 69);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(35, 13);
            this.label10.TabIndex = 14;
            this.label10.Text = "E-Mail";
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(291, 43);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(37, 13);
            this.label9.TabIndex = 13;
            this.label9.Text = "Mobile";
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(9, 67);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(25, 13);
            this.label6.TabIndex = 12;
            this.label6.Text = "Fax";
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(9, 42);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(57, 13);
            this.label5.TabIndex = 11;
            this.label5.Text = "Telephone";
            this.txtWeb.Location = new System.Drawing.Point(110, 90);
            this.txtWeb.Name = "txtWeb";
            this.txtWeb.Size = new System.Drawing.Size(157, 21);
            this.txtWeb.TabIndex = 3;
            this.txtEmail.Location = new System.Drawing.Point(344, 65);
            this.txtEmail.Name = "txtEmail";
            this.txtEmail.Size = new System.Drawing.Size(163, 21);
            this.txtEmail.TabIndex = 5;
            this.txtMob.Location = new System.Drawing.Point(344, 39);
            this.txtMob.Name = "txtMob";
            this.txtMob.Size = new System.Drawing.Size(163, 21);
            this.txtMob.TabIndex = 4;
            this.txtFax.Location = new System.Drawing.Point(110, 65);
            this.txtFax.Name = "txtFax";
            this.txtFax.Size = new System.Drawing.Size(157, 21);
            this.txtFax.TabIndex = 2;
            this.txtTel.Location = new System.Drawing.Point(110, 39);
            this.txtTel.Name = "txtTel";
            this.txtTel.Size = new System.Drawing.Size(157, 21);
            this.txtTel.TabIndex = 1;
            this.txtConperson.BackColor = System.Drawing.Color.LightYellow;
            this.txtConperson.Location = new System.Drawing.Point(110, 14);
            this.txtConperson.Name = "txtConperson";
            this.txtConperson.Size = new System.Drawing.Size(397, 21);
            this.txtConperson.TabIndex = 0;
            this.groupBox2.BackColor = System.Drawing.Color.Transparent;
            this.groupBox2.Controls.Add(this.lblCompLogo);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Controls.Add(this.label1);
            this.groupBox2.Controls.Add(this.btnClearLogo);
            this.groupBox2.Controls.Add(this.btnUploadLogo);
            this.groupBox2.Controls.Add(this.pbCompLogo);
            this.groupBox2.Controls.Add(this.txtDisName);
            this.groupBox2.Controls.Add(this.txtComName);
            this.groupBox2.Controls.Add(this.txtComCode);
            this.groupBox2.Location = new System.Drawing.Point(9, 3);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(517, 112);
            this.groupBox2.TabIndex = 16;
            this.groupBox2.TabStop = false;
            this.lblCompLogo.Location = new System.Drawing.Point(417, 34);
            this.lblCompLogo.Name = "lblCompLogo";
            this.lblCompLogo.Size = new System.Drawing.Size(71, 42);
            this.lblCompLogo.TabIndex = 3;
            this.lblCompLogo.Text = "Upload Company Logo";
            this.lblCompLogo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(9, 70);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(71, 13);
            this.label3.TabIndex = 11;
            this.label3.Text = "Display Name";
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(9, 44);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(34, 13);
            this.label2.TabIndex = 10;
            this.label2.Text = "Name";
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(9, 18);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(32, 13);
            this.label1.TabIndex = 9;
            this.label1.Text = "Code";
            this.btnClearLogo.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnClearLogo.Location = new System.Drawing.Point(458, 88);
            this.btnClearLogo.Name = "btnClearLogo";
            this.btnClearLogo.Size = new System.Drawing.Size(54, 21);
            this.btnClearLogo.TabIndex = 5;
            this.btnClearLogo.Text = "Clear";
            this.btnClearLogo.UseVisualStyleBackColor = true;
            this.btnClearLogo.Click += new System.EventHandler(this.btnClearLogo_Click);
            this.btnUploadLogo.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnUploadLogo.Location = new System.Drawing.Point(403, 88);
            this.btnUploadLogo.Name = "btnUploadLogo";
            this.btnUploadLogo.Size = new System.Drawing.Size(56, 21);
            this.btnUploadLogo.TabIndex = 4;
            this.btnUploadLogo.Text = "Upload";
            this.btnUploadLogo.UseVisualStyleBackColor = true;
            this.btnUploadLogo.Click += new System.EventHandler(this.btnUploadLogo_Click);
            this.pbCompLogo.BackColor = System.Drawing.Color.Transparent;
            this.pbCompLogo.Location = new System.Drawing.Point(404, 15);
            this.pbCompLogo.Name = "pbCompLogo";
            this.pbCompLogo.Size = new System.Drawing.Size(103, 72);
            this.pbCompLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbCompLogo.TabIndex = 3;
            this.pbCompLogo.TabStop = false;
            this.txtDisName.BackColor = System.Drawing.Color.LightYellow;
            this.txtDisName.Location = new System.Drawing.Point(83, 67);
            this.txtDisName.Name = "txtDisName";
            this.txtDisName.Size = new System.Drawing.Size(312, 21);
            this.txtDisName.TabIndex = 2;
            this.txtDisName.TextChanged += new System.EventHandler(this.txtDisName_TextChanged);
            this.txtDisName.Leave += new System.EventHandler(this.txtDisName_Leave);
            this.txtComName.BackColor = System.Drawing.Color.LightYellow;
            this.txtComName.Location = new System.Drawing.Point(83, 41);
            this.txtComName.Name = "txtComName";
            this.txtComName.Size = new System.Drawing.Size(312, 21);
            this.txtComName.TabIndex = 1;
            this.txtComName.TextChanged += new System.EventHandler(this.txtComName_TextChanged);
            this.txtComName.Leave += new System.EventHandler(this.txtComName_Leave);
            this.txtComCode.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.txtComCode.Location = new System.Drawing.Point(83, 15);
            this.txtComCode.Name = "txtComCode";
            this.txtComCode.Size = new System.Drawing.Size(312, 21);
            this.txtComCode.TabIndex = 0;
            this.tpBNK.Controls.Add(this.grdBNK);
            this.tpBNK.Location = new System.Drawing.Point(4, 22);
            this.tpBNK.Name = "tpBNK";
            this.tpBNK.Size = new System.Drawing.Size(539, 399);
            this.tpBNK.TabIndex = 3;
            this.tpBNK.Text = "Bank Details";
            this.tpBNK.UseVisualStyleBackColor = true;
            this.grdBNK.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdBNK.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdBNK.Cursor = System.Windows.Forms.Cursors.Default;
            this.grdBNK.Location = new System.Drawing.Point(6, 7);
            this.grdBNK.Name = "grdBNK";
            this.grdBNK.Size = new System.Drawing.Size(531, 386);
            this.grdBNK.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdBNK.Styles"));
            this.grdBNK.TabIndex = 1;
            this.grdBNK.RowColChange += new System.EventHandler(this.grdBNK_RowColChange);
            this.grdBNK.CellButtonClick += new C1.Win.C1FlexGrid.RowColEventHandler(this.grdBNK_CellButtonClick);
            this.grdBNK.KeyDown += new System.Windows.Forms.KeyEventHandler(this.grdBNK_KeyDown);
            this.tpSummary.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tpSummary.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tpSummary.Controls.Add(this.groupBox8);
            this.tpSummary.Controls.Add(this.groupBox7);
            this.tpSummary.Controls.Add(this.groupBox6);
            this.tpSummary.Controls.Add(this.groupBox5);
            this.tpSummary.Location = new System.Drawing.Point(4, 22);
            this.tpSummary.Name = "tpSummary";
            this.tpSummary.Padding = new System.Windows.Forms.Padding(3);
            this.tpSummary.Size = new System.Drawing.Size(539, 399);
            this.tpSummary.TabIndex = 4;
            this.tpSummary.Text = "Comapny Summary";
            this.tpSummary.UseVisualStyleBackColor = true;
            this.groupBox8.Controls.Add(this.label18);
            this.groupBox8.Controls.Add(this.textBox7);
            this.groupBox8.Controls.Add(this.label19);
            this.groupBox8.Controls.Add(this.textBox8);
            this.groupBox8.Location = new System.Drawing.Point(310, 120);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new System.Drawing.Size(174, 88);
            this.groupBox8.TabIndex = 3;
            this.groupBox8.TabStop = false;
            this.groupBox8.Text = "Guide Details";
            this.label18.AutoSize = true;
            this.label18.Location = new System.Drawing.Point(9, 55);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(50, 13);
            this.label18.TabIndex = 15;
            this.label18.Text = "Available";
            this.textBox7.ForeColor = System.Drawing.Color.Green;
            this.textBox7.Location = new System.Drawing.Point(65, 51);
            this.textBox7.Name = "textBox7";
            this.textBox7.ReadOnly = true;
            this.textBox7.Size = new System.Drawing.Size(97, 21);
            this.textBox7.TabIndex = 1;
            this.label19.AutoSize = true;
            this.label19.Location = new System.Drawing.Point(9, 28);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(31, 13);
            this.label19.TabIndex = 13;
            this.label19.Text = "Total";
            this.textBox8.ForeColor = System.Drawing.Color.Blue;
            this.textBox8.Location = new System.Drawing.Point(65, 24);
            this.textBox8.Name = "textBox8";
            this.textBox8.ReadOnly = true;
            this.textBox8.Size = new System.Drawing.Size(97, 21);
            this.textBox8.TabIndex = 0;
            this.groupBox7.Controls.Add(this.label16);
            this.groupBox7.Controls.Add(this.textBox5);
            this.groupBox7.Controls.Add(this.label17);
            this.groupBox7.Controls.Add(this.textBox6);
            this.groupBox7.Location = new System.Drawing.Point(40, 120);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(226, 88);
            this.groupBox7.TabIndex = 3;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "Comapny Details";
            this.label16.AutoSize = true;
            this.label16.Location = new System.Drawing.Point(9, 55);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(72, 13);
            this.label16.TabIndex = 15;
            this.label16.Text = "No Of Agents";
            this.textBox5.ForeColor = System.Drawing.Color.Blue;
            this.textBox5.Location = new System.Drawing.Point(101, 51);
            this.textBox5.Name = "textBox5";
            this.textBox5.ReadOnly = true;
            this.textBox5.Size = new System.Drawing.Size(115, 21);
            this.textBox5.TabIndex = 1;
            this.label17.AutoSize = true;
            this.label17.Location = new System.Drawing.Point(9, 28);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(89, 13);
            this.label17.TabIndex = 13;
            this.label17.Text = "No Of Employees";
            this.textBox6.ForeColor = System.Drawing.Color.Blue;
            this.textBox6.Location = new System.Drawing.Point(101, 24);
            this.textBox6.Name = "textBox6";
            this.textBox6.ReadOnly = true;
            this.textBox6.Size = new System.Drawing.Size(115, 21);
            this.textBox6.TabIndex = 0;
            this.groupBox6.Controls.Add(this.label13);
            this.groupBox6.Controls.Add(this.textBox3);
            this.groupBox6.Controls.Add(this.label14);
            this.groupBox6.Controls.Add(this.textBox4);
            this.groupBox6.Location = new System.Drawing.Point(310, 17);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(174, 88);
            this.groupBox6.TabIndex = 2;
            this.groupBox6.TabStop = false;
            this.groupBox6.Text = "Driver Details";
            this.label13.AutoSize = true;
            this.label13.Location = new System.Drawing.Point(9, 55);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(50, 13);
            this.label13.TabIndex = 15;
            this.label13.Text = "Available";
            this.textBox3.ForeColor = System.Drawing.Color.Green;
            this.textBox3.Location = new System.Drawing.Point(65, 51);
            this.textBox3.Name = "textBox3";
            this.textBox3.ReadOnly = true;
            this.textBox3.Size = new System.Drawing.Size(97, 21);
            this.textBox3.TabIndex = 1;
            this.label14.AutoSize = true;
            this.label14.Location = new System.Drawing.Point(9, 28);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(31, 13);
            this.label14.TabIndex = 13;
            this.label14.Text = "Total";
            this.textBox4.ForeColor = System.Drawing.Color.Blue;
            this.textBox4.Location = new System.Drawing.Point(65, 24);
            this.textBox4.Name = "textBox4";
            this.textBox4.ReadOnly = true;
            this.textBox4.Size = new System.Drawing.Size(97, 21);
            this.textBox4.TabIndex = 0;
            this.groupBox5.Controls.Add(this.label12);
            this.groupBox5.Controls.Add(this.textBox2);
            this.groupBox5.Controls.Add(this.label7);
            this.groupBox5.Controls.Add(this.textBox1);
            this.groupBox5.Location = new System.Drawing.Point(40, 17);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(226, 88);
            this.groupBox5.TabIndex = 1;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Vehicle Details";
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(9, 55);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(50, 13);
            this.label12.TabIndex = 15;
            this.label12.Text = "Available";
            this.textBox2.ForeColor = System.Drawing.Color.Green;
            this.textBox2.Location = new System.Drawing.Point(101, 51);
            this.textBox2.Name = "textBox2";
            this.textBox2.ReadOnly = true;
            this.textBox2.Size = new System.Drawing.Size(115, 21);
            this.textBox2.TabIndex = 1;
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(9, 28);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(31, 13);
            this.label7.TabIndex = 13;
            this.label7.Text = "Total";
            this.textBox1.ForeColor = System.Drawing.Color.Blue;
            this.textBox1.Location = new System.Drawing.Point(101, 24);
            this.textBox1.Name = "textBox1";
            this.textBox1.ReadOnly = true;
            this.textBox1.Size = new System.Drawing.Size(115, 21);
            this.textBox1.TabIndex = 0;
            this.btnCancel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCancel.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Image = global::Tourist_Management.Properties.Resources.cancel;
            this.btnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.Location = new System.Drawing.Point(477, 438);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(74, 29);
            this.btnCancel.TabIndex = 2;
            this.btnCancel.Text = "&Cancel";
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnOk.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnOk.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Image = global::Tourist_Management.Properties.Resources.floppy;
            this.btnOk.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOk.Location = new System.Drawing.Point(400, 438);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(74, 29);
            this.btnOk.TabIndex = 1;
            this.btnOk.Text = "&Save";
            this.btnOk.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.errorProvider1.ContainerControl = this;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(555, 471);
            this.ControlBox = false;
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.tabControl1);
            this.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.Name = "frmCompany";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmCompany_Load);
            this.tabControl1.ResumeLayout(false);
            this.tpCom.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbCompLogo)).EndInit();
            this.tpBNK.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdBNK)).EndInit();
            this.tpSummary.ResumeLayout(false);
            this.groupBox8.ResumeLayout(false);
            this.groupBox8.PerformLayout();
            this.groupBox7.ResumeLayout(false);
            this.groupBox7.PerformLayout();
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.ResumeLayout(false);
        }
        #endregion
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tpCom;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox txtPostal1;
        private System.Windows.Forms.TextBox txtPhysical;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox txtPostal2;
        private System.Windows.Forms.TextBox txtPostal;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox txtWeb;
        private System.Windows.Forms.TextBox txtEmail;
        private System.Windows.Forms.TextBox txtMob;
        private System.Windows.Forms.TextBox txtFax;
        private System.Windows.Forms.TextBox txtTel;
        private System.Windows.Forms.TextBox txtConperson;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label lblCompLogo;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button btnClearLogo;
        private System.Windows.Forms.Button btnUploadLogo;
        private System.Windows.Forms.PictureBox pbCompLogo;
        private System.Windows.Forms.TextBox txtDisName;
        private System.Windows.Forms.TextBox txtComName;
        private System.Windows.Forms.TextBox txtComCode;
        private System.Windows.Forms.TabPage tpBNK;
        private C1.Win.C1FlexGrid.C1FlexGrid grdBNK;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.TabPage tpSummary;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.GroupBox groupBox6;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.TextBox textBox3;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.TextBox textBox4;
        private System.Windows.Forms.GroupBox groupBox7;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.TextBox textBox6;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.TextBox textBox5;
        private System.Windows.Forms.GroupBox groupBox8;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.TextBox textBox7;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.TextBox textBox8;
        private System.Windows.Forms.ErrorProvider errorProvider1;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.TextBox txtEmailTo;
    }
}