namespace Tourist_Management.Master
{
    partial class frmEmployee
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmEmployee));
            this.tabEmployee = new System.Windows.Forms.TabControl();
            this.PersonalDetails = new System.Windows.Forms.TabPage();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.label18 = new System.Windows.Forms.Label();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.drpCountryID = new DropDowns.DropSearch();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.rdbIsMale = new System.Windows.Forms.RadioButton();
            this.rdbIsFemale = new System.Windows.Forms.RadioButton();
            this.dtpDOB = new System.Windows.Forms.DateTimePicker();
            this.label39 = new System.Windows.Forms.Label();
            this.label17 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.nudNoOfDependances = new System.Windows.Forms.NumericUpDown();
            this.label37 = new System.Windows.Forms.Label();
            this.cmbMaritalStatus = new  Tourist_Management.User_Controls.ComboBox();
            this.label36 = new System.Windows.Forms.Label();
            this.txtIdentityNo = new System.Windows.Forms.TextBox();
            this.cmbIdentityTypeID = new  Tourist_Management.User_Controls.ComboBox();
            this.label10 = new System.Windows.Forms.Label();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.lblEmpPhoto = new System.Windows.Forms.Label();
            this.btnClearLogo = new System.Windows.Forms.Button();
            this.btnUploadLogo = new System.Windows.Forms.Button();
            this.pbEmpPhoto = new System.Windows.Forms.PictureBox();
            this.label38 = new System.Windows.Forms.Label();
            this.txtRemarks = new System.Windows.Forms.TextBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.cmbMr_Mrs = new  Tourist_Management.User_Controls.ComboBox();
            this.label9 = new System.Windows.Forms.Label();
            this.txtFirstName = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.txtNickName = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.txtSurName = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.txtNameWithIntials = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.txtCode = new System.Windows.Forms.TextBox();
            this.lblID = new System.Windows.Forms.Label();
            this.ContactDetails = new System.Windows.Forms.TabPage();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.drpPMACountryID = new DropDowns.DropSearch();
            this.drpPOACountryID = new DropDowns.DropSearch();
            this.label49 = new System.Windows.Forms.Label();
            this.txtContEmail = new System.Windows.Forms.TextBox();
            this.label53 = new System.Windows.Forms.Label();
            this.label52 = new System.Windows.Forms.Label();
            this.label51 = new System.Windows.Forms.Label();
            this.label50 = new System.Windows.Forms.Label();
            this.label42 = new System.Windows.Forms.Label();
            this.label43 = new System.Windows.Forms.Label();
            this.txtContEmployer = new System.Windows.Forms.TextBox();
            this.txtContTel2 = new System.Windows.Forms.TextBox();
            this.label47 = new System.Windows.Forms.Label();
            this.label48 = new System.Windows.Forms.Label();
            this.txtContTel1 = new System.Windows.Forms.TextBox();
            this.txtContName = new System.Windows.Forms.TextBox();
            this.panel4 = new System.Windows.Forms.Panel();
            this.panel3 = new System.Windows.Forms.Panel();
            this.cmbCity2 = new  Tourist_Management.User_Controls.ComboBox();
            this.cmbCity1 = new  Tourist_Management.User_Controls.ComboBox();
            this.label44 = new System.Windows.Forms.Label();
            this.label45 = new System.Windows.Forms.Label();
            this.txtEmail = new System.Windows.Forms.TextBox();
            this.txtFaxNo = new System.Windows.Forms.TextBox();
            this.label41 = new System.Windows.Forms.Label();
            this.label40 = new System.Windows.Forms.Label();
            this.txtTelMobile = new System.Windows.Forms.TextBox();
            this.txtTelHome = new System.Windows.Forms.TextBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.txtPostalCode2 = new System.Windows.Forms.TextBox();
            this.label16 = new System.Windows.Forms.Label();
            this.txtPostalAdd = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.txtPostalCode1 = new System.Windows.Forms.TextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.txtPermanantAdd = new System.Windows.Forms.TextBox();
            this.BankingDetails = new System.Windows.Forms.TabPage();
            this.grdBNK = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.ServiceDetails = new System.Windows.Forms.TabPage();
            this.cmbStatus = new  Tourist_Management.User_Controls.ComboBox();
            this.label19 = new System.Windows.Forms.Label();
            this.label56 = new System.Windows.Forms.Label();
            this.txtBasicSalary = new System.Windows.Forms.TextBox();
            this.txtDesignation = new System.Windows.Forms.TextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.txtPrvEmployer = new System.Windows.Forms.TextBox();
            this.dtpDischargeDate = new System.Windows.Forms.DateTimePicker();
            this.dtpEngageDate = new System.Windows.Forms.DateTimePicker();
            this.label67 = new System.Windows.Forms.Label();
            this.lblDischarge = new System.Windows.Forms.Label();
            this.label64 = new System.Windows.Forms.Label();
            this.chkActive = new System.Windows.Forms.CheckBox();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.tabEmployee.SuspendLayout();
            this.PersonalDetails.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.groupBox6.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nudNoOfDependances)).BeginInit();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbEmpPhoto)).BeginInit();
            this.groupBox3.SuspendLayout();
            this.ContactDetails.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.BankingDetails.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdBNK)).BeginInit();
            this.ServiceDetails.SuspendLayout();
            this.SuspendLayout();
            this.tabEmployee.Controls.Add(this.PersonalDetails);
            this.tabEmployee.Controls.Add(this.ContactDetails);
            this.tabEmployee.Controls.Add(this.BankingDetails);
            this.tabEmployee.Controls.Add(this.ServiceDetails);
            this.tabEmployee.Location = new System.Drawing.Point(3, 12);
            this.tabEmployee.Name = "tabEmployee";
            this.tabEmployee.SelectedIndex = 0;
            this.tabEmployee.Size = new System.Drawing.Size(657, 427);
            this.tabEmployee.TabIndex = 0;
            this.PersonalDetails.Controls.Add(this.groupBox4);
            this.PersonalDetails.Controls.Add(this.groupBox2);
            this.PersonalDetails.Controls.Add(this.label38);
            this.PersonalDetails.Controls.Add(this.txtRemarks);
            this.PersonalDetails.Controls.Add(this.groupBox3);
            this.PersonalDetails.Controls.Add(this.lblID);
            this.PersonalDetails.Location = new System.Drawing.Point(4, 22);
            this.PersonalDetails.Name = "PersonalDetails";
            this.PersonalDetails.Padding = new System.Windows.Forms.Padding(3);
            this.PersonalDetails.Size = new System.Drawing.Size(649, 401);
            this.PersonalDetails.TabIndex = 0;
            this.PersonalDetails.Text = "Personal Details";
            this.PersonalDetails.UseVisualStyleBackColor = true;
            this.groupBox4.Controls.Add(this.label18);
            this.groupBox4.Controls.Add(this.groupBox7);
            this.groupBox4.Controls.Add(this.nudNoOfDependances);
            this.groupBox4.Controls.Add(this.label37);
            this.groupBox4.Controls.Add(this.cmbMaritalStatus);
            this.groupBox4.Controls.Add(this.label36);
            this.groupBox4.Controls.Add(this.txtIdentityNo);
            this.groupBox4.Controls.Add(this.cmbIdentityTypeID);
            this.groupBox4.Controls.Add(this.label10);
            this.groupBox4.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox4.Location = new System.Drawing.Point(21, 195);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(602, 151);
            this.groupBox4.TabIndex = 241;
            this.groupBox4.TabStop = false;
            this.label18.AutoSize = true;
            this.label18.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label18.Location = new System.Drawing.Point(13, 51);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(34, 13);
            this.label18.TabIndex = 269;
            this.label18.Text = "ID No";
            this.groupBox7.Controls.Add(this.drpCountryID);
            this.groupBox7.Controls.Add(this.groupBox6);
            this.groupBox7.Controls.Add(this.dtpDOB);
            this.groupBox7.Controls.Add(this.label39);
            this.groupBox7.Controls.Add(this.label17);
            this.groupBox7.Controls.Add(this.label12);
            this.groupBox7.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox7.Location = new System.Drawing.Point(333, 13);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(257, 122);
            this.groupBox7.TabIndex = 268;
            this.groupBox7.TabStop = false;
            this.drpCountryID.BackColor = System.Drawing.Color.Transparent;
            this.drpCountryID.DataSource = null;
            this.drpCountryID.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpCountryID.FormName = "";
            this.drpCountryID.Location = new System.Drawing.Point(86, 60);
            this.drpCountryID.Name = "drpCountryID";
            this.drpCountryID.SelectedText = "";
            this.drpCountryID.SelectedValue = "";
            this.drpCountryID.Size = new System.Drawing.Size(151, 23);
            this.drpCountryID.TabIndex = 1;
            this.drpCountryID.Click_Open += new System.EventHandler(this.drpCountryID_Click_Open);
            this.groupBox6.Controls.Add(this.rdbIsMale);
            this.groupBox6.Controls.Add(this.rdbIsFemale);
            this.groupBox6.Location = new System.Drawing.Point(86, 83);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(151, 30);
            this.groupBox6.TabIndex = 266;
            this.groupBox6.TabStop = false;
            this.rdbIsMale.AutoSize = true;
            this.rdbIsMale.Checked = true;
            this.rdbIsMale.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbIsMale.Location = new System.Drawing.Point(13, 9);
            this.rdbIsMale.Name = "rdbIsMale";
            this.rdbIsMale.Size = new System.Drawing.Size(47, 17);
            this.rdbIsMale.TabIndex = 0;
            this.rdbIsMale.TabStop = true;
            this.rdbIsMale.Text = "Male";
            this.rdbIsMale.UseVisualStyleBackColor = true;
            this.rdbIsFemale.AutoSize = true;
            this.rdbIsFemale.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbIsFemale.Location = new System.Drawing.Point(71, 9);
            this.rdbIsFemale.Name = "rdbIsFemale";
            this.rdbIsFemale.Size = new System.Drawing.Size(59, 17);
            this.rdbIsFemale.TabIndex = 1;
            this.rdbIsFemale.Text = "Female";
            this.rdbIsFemale.UseVisualStyleBackColor = true;
            this.dtpDOB.CustomFormat = "yyyy-MM-dd";
            this.dtpDOB.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpDOB.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpDOB.Location = new System.Drawing.Point(86, 30);
            this.dtpDOB.Name = "dtpDOB";
            this.dtpDOB.Size = new System.Drawing.Size(151, 21);
            this.dtpDOB.TabIndex = 0;
            this.label39.AutoSize = true;
            this.label39.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label39.Location = new System.Drawing.Point(8, 35);
            this.label39.Name = "label39";
            this.label39.Size = new System.Drawing.Size(70, 13);
            this.label39.TabIndex = 264;
            this.label39.Text = "Date Of Birth";
            this.label17.AutoSize = true;
            this.label17.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label17.Location = new System.Drawing.Point(8, 96);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(42, 13);
            this.label17.TabIndex = 242;
            this.label17.Text = "Gender";
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.Location = new System.Drawing.Point(8, 65);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(46, 13);
            this.label12.TabIndex = 238;
            this.label12.Text = "Country";
            this.nudNoOfDependances.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nudNoOfDependances.Location = new System.Drawing.Point(112, 107);
            this.nudNoOfDependances.Name = "nudNoOfDependances";
            this.nudNoOfDependances.Size = new System.Drawing.Size(212, 21);
            this.nudNoOfDependances.TabIndex = 3;
            this.label37.AutoSize = true;
            this.label37.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label37.Location = new System.Drawing.Point(12, 113);
            this.label37.Name = "label37";
            this.label37.Size = new System.Drawing.Size(89, 13);
            this.label37.TabIndex = 246;
            this.label37.Text = "No of Dependent";
            this.cmbMaritalStatus.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbMaritalStatus.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbMaritalStatus.FormattingEnabled = true;
            this.cmbMaritalStatus.Location = new System.Drawing.Point(112, 76);
            this.cmbMaritalStatus.Name = "cmbMaritalStatus";
            this.cmbMaritalStatus.Size = new System.Drawing.Size(212, 21);
            this.cmbMaritalStatus.TabIndex = 2;
            this.label36.AutoSize = true;
            this.label36.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label36.Location = new System.Drawing.Point(12, 80);
            this.label36.Name = "label36";
            this.label36.Size = new System.Drawing.Size(75, 13);
            this.label36.TabIndex = 243;
            this.label36.Text = "Maritial Status";
            this.txtIdentityNo.BackColor = System.Drawing.Color.LightYellow;
            this.txtIdentityNo.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtIdentityNo.Location = new System.Drawing.Point(112, 47);
            this.txtIdentityNo.MaxLength = 10;
            this.txtIdentityNo.Name = "txtIdentityNo";
            this.txtIdentityNo.Size = new System.Drawing.Size(212, 21);
            this.txtIdentityNo.TabIndex = 1;
            this.txtIdentityNo.Validating += new System.ComponentModel.CancelEventHandler(this.txtIdentityNo_Validating);
            this.cmbIdentityTypeID.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbIdentityTypeID.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbIdentityTypeID.FormattingEnabled = true;
            this.cmbIdentityTypeID.Location = new System.Drawing.Point(112, 19);
            this.cmbIdentityTypeID.Name = "cmbIdentityTypeID";
            this.cmbIdentityTypeID.Size = new System.Drawing.Size(212, 21);
            this.cmbIdentityTypeID.TabIndex = 0;
            this.cmbIdentityTypeID.SelectedIndexChanged += new System.EventHandler(this.cmbIdentityTypeID_SelectedIndexChanged);
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.Location = new System.Drawing.Point(12, 23);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(45, 13);
            this.label10.TabIndex = 234;
            this.label10.Text = "ID Type";
            this.groupBox2.BackColor = System.Drawing.Color.Transparent;
            this.groupBox2.Controls.Add(this.lblEmpPhoto);
            this.groupBox2.Controls.Add(this.btnClearLogo);
            this.groupBox2.Controls.Add(this.btnUploadLogo);
            this.groupBox2.Controls.Add(this.pbEmpPhoto);
            this.groupBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.Location = new System.Drawing.Point(505, 6);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(118, 181);
            this.groupBox2.TabIndex = 237;
            this.groupBox2.TabStop = false;
            this.lblEmpPhoto.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblEmpPhoto.Location = new System.Drawing.Point(15, 28);
            this.lblEmpPhoto.Name = "lblEmpPhoto";
            this.lblEmpPhoto.Size = new System.Drawing.Size(84, 83);
            this.lblEmpPhoto.TabIndex = 242;
            this.lblEmpPhoto.Text = "Upload Employee Photograph";
            this.lblEmpPhoto.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClearLogo.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClearLogo.Location = new System.Drawing.Point(58, 144);
            this.btnClearLogo.Name = "btnClearLogo";
            this.btnClearLogo.Size = new System.Drawing.Size(53, 21);
            this.btnClearLogo.TabIndex = 1;
            this.btnClearLogo.Text = "Clear";
            this.btnClearLogo.UseVisualStyleBackColor = true;
            this.btnClearLogo.Click += new System.EventHandler(this.btnClearLogo_Click);
            this.btnUploadLogo.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUploadLogo.Location = new System.Drawing.Point(6, 144);
            this.btnUploadLogo.Name = "btnUploadLogo";
            this.btnUploadLogo.Size = new System.Drawing.Size(53, 21);
            this.btnUploadLogo.TabIndex = 0;
            this.btnUploadLogo.Text = "Upload";
            this.btnUploadLogo.UseVisualStyleBackColor = true;
            this.btnUploadLogo.Click += new System.EventHandler(this.btnUploadLogo_Click);
            this.pbEmpPhoto.BackColor = System.Drawing.Color.Transparent;
            this.pbEmpPhoto.Location = new System.Drawing.Point(6, 19);
            this.pbEmpPhoto.Name = "pbEmpPhoto";
            this.pbEmpPhoto.Size = new System.Drawing.Size(102, 103);
            this.pbEmpPhoto.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbEmpPhoto.TabIndex = 3;
            this.pbEmpPhoto.TabStop = false;
            this.label38.AutoSize = true;
            this.label38.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label38.Location = new System.Drawing.Point(34, 362);
            this.label38.Name = "label38";
            this.label38.Size = new System.Drawing.Size(48, 13);
            this.label38.TabIndex = 263;
            this.label38.Text = "Remarks";
            this.txtRemarks.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtRemarks.Location = new System.Drawing.Point(135, 359);
            this.txtRemarks.Multiline = true;
            this.txtRemarks.Name = "txtRemarks";
            this.txtRemarks.Size = new System.Drawing.Size(488, 29);
            this.txtRemarks.TabIndex = 0;
            this.groupBox3.Controls.Add(this.cmbMr_Mrs);
            this.groupBox3.Controls.Add(this.label9);
            this.groupBox3.Controls.Add(this.txtFirstName);
            this.groupBox3.Controls.Add(this.label4);
            this.groupBox3.Controls.Add(this.txtNickName);
            this.groupBox3.Controls.Add(this.label3);
            this.groupBox3.Controls.Add(this.txtSurName);
            this.groupBox3.Controls.Add(this.label2);
            this.groupBox3.Controls.Add(this.txtNameWithIntials);
            this.groupBox3.Controls.Add(this.label1);
            this.groupBox3.Controls.Add(this.txtCode);
            this.groupBox3.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox3.Location = new System.Drawing.Point(21, 6);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(485, 181);
            this.groupBox3.TabIndex = 234;
            this.groupBox3.TabStop = false;
            this.cmbMr_Mrs.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbMr_Mrs.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbMr_Mrs.FormattingEnabled = true;
            this.cmbMr_Mrs.Location = new System.Drawing.Point(110, 48);
            this.cmbMr_Mrs.Name = "cmbMr_Mrs";
            this.cmbMr_Mrs.Size = new System.Drawing.Size(52, 21);
            this.cmbMr_Mrs.TabIndex = 63;
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(10, 52);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(63, 13);
            this.label9.TabIndex = 62;
            this.label9.Text = "First Names";
            this.txtFirstName.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFirstName.Location = new System.Drawing.Point(165, 49);
            this.txtFirstName.Name = "txtFirstName";
            this.txtFirstName.Size = new System.Drawing.Size(310, 21);
            this.txtFirstName.TabIndex = 1;
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(10, 147);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(52, 13);
            this.label4.TabIndex = 60;
            this.label4.Text = "Nickname";
            this.txtNickName.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNickName.Location = new System.Drawing.Point(110, 144);
            this.txtNickName.Name = "txtNickName";
            this.txtNickName.Size = new System.Drawing.Size(365, 21);
            this.txtNickName.TabIndex = 4;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(10, 115);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(49, 13);
            this.label3.TabIndex = 58;
            this.label3.Text = "Surname";
            this.txtSurName.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSurName.Location = new System.Drawing.Point(110, 112);
            this.txtSurName.Name = "txtSurName";
            this.txtSurName.Size = new System.Drawing.Size(365, 21);
            this.txtSurName.TabIndex = 3;
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(10, 83);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(71, 13);
            this.label2.TabIndex = 56;
            this.label2.Text = "Display Name";
            this.txtNameWithIntials.BackColor = System.Drawing.Color.LightYellow;
            this.txtNameWithIntials.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNameWithIntials.Location = new System.Drawing.Point(110, 80);
            this.txtNameWithIntials.Name = "txtNameWithIntials";
            this.txtNameWithIntials.Size = new System.Drawing.Size(365, 21);
            this.txtNameWithIntials.TabIndex = 2;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(10, 22);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(32, 13);
            this.label1.TabIndex = 54;
            this.label1.Text = "Code";
            this.txtCode.BackColor = System.Drawing.Color.LightYellow;
            this.txtCode.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCode.Location = new System.Drawing.Point(110, 19);
            this.txtCode.Name = "txtCode";
            this.txtCode.Size = new System.Drawing.Size(365, 21);
            this.txtCode.TabIndex = 0;
            this.lblID.AutoSize = true;
            this.lblID.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblID.Location = new System.Drawing.Point(49, 190);
            this.lblID.Name = "lblID";
            this.lblID.Size = new System.Drawing.Size(34, 13);
            this.lblID.TabIndex = 237;
            this.lblID.Text = "ID No";
            this.lblID.Visible = false;
            this.ContactDetails.Controls.Add(this.groupBox5);
            this.ContactDetails.Location = new System.Drawing.Point(4, 22);
            this.ContactDetails.Name = "ContactDetails";
            this.ContactDetails.Padding = new System.Windows.Forms.Padding(3);
            this.ContactDetails.Size = new System.Drawing.Size(649, 401);
            this.ContactDetails.TabIndex = 1;
            this.ContactDetails.Text = "Contact Details";
            this.ContactDetails.UseVisualStyleBackColor = true;
            this.groupBox5.Controls.Add(this.drpPOACountryID);
            this.groupBox5.Controls.Add(this.drpPMACountryID);
            this.groupBox5.Controls.Add(this.label49);
            this.groupBox5.Controls.Add(this.txtContEmail);
            this.groupBox5.Controls.Add(this.label53);
            this.groupBox5.Controls.Add(this.label52);
            this.groupBox5.Controls.Add(this.label51);
            this.groupBox5.Controls.Add(this.label50);
            this.groupBox5.Controls.Add(this.label42);
            this.groupBox5.Controls.Add(this.label43);
            this.groupBox5.Controls.Add(this.txtContEmployer);
            this.groupBox5.Controls.Add(this.txtContTel2);
            this.groupBox5.Controls.Add(this.label47);
            this.groupBox5.Controls.Add(this.label48);
            this.groupBox5.Controls.Add(this.txtContTel1);
            this.groupBox5.Controls.Add(this.txtContName);
            this.groupBox5.Controls.Add(this.panel4);
            this.groupBox5.Controls.Add(this.panel3);
            this.groupBox5.Controls.Add(this.cmbCity2);
            this.groupBox5.Controls.Add(this.cmbCity1);
            this.groupBox5.Controls.Add(this.label44);
            this.groupBox5.Controls.Add(this.label45);
            this.groupBox5.Controls.Add(this.txtEmail);
            this.groupBox5.Controls.Add(this.txtFaxNo);
            this.groupBox5.Controls.Add(this.label41);
            this.groupBox5.Controls.Add(this.label40);
            this.groupBox5.Controls.Add(this.txtTelMobile);
            this.groupBox5.Controls.Add(this.txtTelHome);
            this.groupBox5.Controls.Add(this.panel1);
            this.groupBox5.Controls.Add(this.label13);
            this.groupBox5.Controls.Add(this.label14);
            this.groupBox5.Controls.Add(this.label15);
            this.groupBox5.Controls.Add(this.txtPostalCode2);
            this.groupBox5.Controls.Add(this.label16);
            this.groupBox5.Controls.Add(this.txtPostalAdd);
            this.groupBox5.Controls.Add(this.label5);
            this.groupBox5.Controls.Add(this.label6);
            this.groupBox5.Controls.Add(this.label7);
            this.groupBox5.Controls.Add(this.txtPostalCode1);
            this.groupBox5.Controls.Add(this.label8);
            this.groupBox5.Controls.Add(this.txtPermanantAdd);
            this.groupBox5.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox5.Location = new System.Drawing.Point(22, 6);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(593, 379);
            this.groupBox5.TabIndex = 237;
            this.groupBox5.TabStop = false;
            this.drpPMACountryID.BackColor = System.Drawing.Color.Transparent;
            this.drpPMACountryID.DataSource = null;
            this.drpPMACountryID.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpPMACountryID.FormName = "";
            this.drpPMACountryID.Location = new System.Drawing.Point(117, 158);
            this.drpPMACountryID.Name = "drpPMACountryID";
            this.drpPMACountryID.SelectedText = "";
            this.drpPMACountryID.SelectedValue = "";
            this.drpPMACountryID.Size = new System.Drawing.Size(168, 23);
            this.drpPMACountryID.TabIndex = 3;
            this.drpPMACountryID.Click_Open += new System.EventHandler(this.drpPMACountryID_Click_Open);
            this.drpPOACountryID.BackColor = System.Drawing.Color.Transparent;
            this.drpPOACountryID.DataSource = null;
            this.drpPOACountryID.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpPOACountryID.FormName = "";
            this.drpPOACountryID.Location = new System.Drawing.Point(417, 160);
            this.drpPOACountryID.Name = "drpPOACountryID";
            this.drpPOACountryID.SelectedText = "";
            this.drpPOACountryID.SelectedValue = "";
            this.drpPOACountryID.Size = new System.Drawing.Size(168, 23);
            this.drpPOACountryID.TabIndex = 11;
            this.drpPOACountryID.Click_Open += new System.EventHandler(this.drpPOACountryID_Click_Open);
            this.label49.AutoSize = true;
            this.label49.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label49.Location = new System.Drawing.Point(310, 289);
            this.label49.Name = "label49";
            this.label49.Size = new System.Drawing.Size(51, 13);
            this.label49.TabIndex = 292;
            this.label49.Text = "E-Mail No";
            this.txtContEmail.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtContEmail.Location = new System.Drawing.Point(416, 286);
            this.txtContEmail.Name = "txtContEmail";
            this.txtContEmail.Size = new System.Drawing.Size(168, 21);
            this.txtContEmail.TabIndex = 14;
            this.label53.AutoSize = true;
            this.label53.Font = new System.Drawing.Font("Tahoma", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label53.Location = new System.Drawing.Point(310, 202);
            this.label53.Name = "label53";
            this.label53.Size = new System.Drawing.Size(199, 14);
            this.label53.TabIndex = 290;
            this.label53.Text = "Spouse/Contact Person Details";
            this.label52.AutoSize = true;
            this.label52.Font = new System.Drawing.Font("Tahoma", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label52.Location = new System.Drawing.Point(5, 204);
            this.label52.Name = "label52";
            this.label52.Size = new System.Drawing.Size(101, 14);
            this.label52.TabIndex = 289;
            this.label52.Text = "Contact Details";
            this.label51.AutoSize = true;
            this.label51.Font = new System.Drawing.Font("Tahoma", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label51.Location = new System.Drawing.Point(311, 8);
            this.label51.Name = "label51";
            this.label51.Size = new System.Drawing.Size(143, 14);
            this.label51.TabIndex = 288;
            this.label51.Text = "Postal Address Details";
            this.label50.AutoSize = true;
            this.label50.Font = new System.Drawing.Font("Tahoma", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label50.Location = new System.Drawing.Point(6, 11);
            this.label50.Name = "label50";
            this.label50.Size = new System.Drawing.Size(172, 14);
            this.label50.TabIndex = 287;
            this.label50.Text = "Permanant Address Details";
            this.label42.AutoSize = true;
            this.label42.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label42.Location = new System.Drawing.Point(310, 319);
            this.label42.Name = "label42";
            this.label42.Size = new System.Drawing.Size(51, 13);
            this.label42.TabIndex = 284;
            this.label42.Text = "Employer";
            this.label43.AutoSize = true;
            this.label43.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label43.Location = new System.Drawing.Point(310, 350);
            this.label43.Name = "label43";
            this.label43.Size = new System.Drawing.Size(72, 13);
            this.label43.TabIndex = 283;
            this.label43.Text = "Employer Tel.";
            this.txtContEmployer.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtContEmployer.Location = new System.Drawing.Point(416, 317);
            this.txtContEmployer.Name = "txtContEmployer";
            this.txtContEmployer.Size = new System.Drawing.Size(168, 21);
            this.txtContEmployer.TabIndex = 15;
            this.txtContTel2.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtContTel2.Location = new System.Drawing.Point(416, 344);
            this.txtContTel2.Name = "txtContTel2";
            this.txtContTel2.Size = new System.Drawing.Size(168, 21);
            this.txtContTel2.TabIndex = 16;
            this.label47.AutoSize = true;
            this.label47.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label47.Location = new System.Drawing.Point(310, 258);
            this.label47.Name = "label47";
            this.label47.Size = new System.Drawing.Size(66, 13);
            this.label47.TabIndex = 280;
            this.label47.Text = "Telephone 1";
            this.label48.AutoSize = true;
            this.label48.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label48.Location = new System.Drawing.Point(310, 233);
            this.label48.Name = "label48";
            this.label48.Size = new System.Drawing.Size(34, 13);
            this.label48.TabIndex = 279;
            this.label48.Text = "Name";
            this.txtContTel1.BackColor = System.Drawing.Color.LightYellow;
            this.txtContTel1.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtContTel1.Location = new System.Drawing.Point(416, 259);
            this.txtContTel1.Name = "txtContTel1";
            this.txtContTel1.Size = new System.Drawing.Size(168, 21);
            this.txtContTel1.TabIndex = 13;
            this.txtContTel1.Text = "Not Given";
            this.txtContName.BackColor = System.Drawing.Color.LightYellow;
            this.txtContName.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtContName.Location = new System.Drawing.Point(416, 231);
            this.txtContName.Name = "txtContName";
            this.txtContName.Size = new System.Drawing.Size(168, 21);
            this.txtContName.TabIndex = 12;
            this.txtContName.Text = "Not Given";
            this.panel4.BackColor = System.Drawing.Color.Silver;
            this.panel4.Location = new System.Drawing.Point(301, 207);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(1, 160);
            this.panel4.TabIndex = 261;
            this.panel3.BackColor = System.Drawing.Color.Silver;
            this.panel3.Location = new System.Drawing.Point(13, 194);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(571, 1);
            this.panel3.TabIndex = 261;
            this.cmbCity2.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCity2.FormattingEnabled = true;
            this.cmbCity2.Location = new System.Drawing.Point(417, 130);
            this.cmbCity2.Name = "cmbCity2";
            this.cmbCity2.Size = new System.Drawing.Size(170, 21);
            this.cmbCity2.TabIndex = 10;
            this.cmbCity1.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCity1.FormattingEnabled = true;
            this.cmbCity1.Location = new System.Drawing.Point(117, 127);
            this.cmbCity1.Name = "cmbCity1";
            this.cmbCity1.Size = new System.Drawing.Size(168, 21);
            this.cmbCity1.TabIndex = 2;
            this.label44.AutoSize = true;
            this.label44.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label44.Location = new System.Drawing.Point(5, 332);
            this.label44.Name = "label44";
            this.label44.Size = new System.Drawing.Size(51, 13);
            this.label44.TabIndex = 272;
            this.label44.Text = "E-Mail No";
            this.label45.AutoSize = true;
            this.label45.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label45.Location = new System.Drawing.Point(5, 298);
            this.label45.Name = "label45";
            this.label45.Size = new System.Drawing.Size(41, 13);
            this.label45.TabIndex = 271;
            this.label45.Text = "Fax No";
            this.txtEmail.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtEmail.Location = new System.Drawing.Point(117, 329);
            this.txtEmail.Name = "txtEmail";
            this.txtEmail.Size = new System.Drawing.Size(168, 21);
            this.txtEmail.TabIndex = 7;
            this.txtFaxNo.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFaxNo.Location = new System.Drawing.Point(117, 291);
            this.txtFaxNo.Name = "txtFaxNo";
            this.txtFaxNo.Size = new System.Drawing.Size(168, 21);
            this.txtFaxNo.TabIndex = 6;
            this.label41.AutoSize = true;
            this.label41.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label41.Location = new System.Drawing.Point(5, 265);
            this.label41.Name = "label41";
            this.label41.Size = new System.Drawing.Size(53, 13);
            this.label41.TabIndex = 264;
            this.label41.Text = "Mobile No";
            this.label40.AutoSize = true;
            this.label40.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label40.Location = new System.Drawing.Point(5, 235);
            this.label40.Name = "label40";
            this.label40.Size = new System.Drawing.Size(37, 13);
            this.label40.TabIndex = 263;
            this.label40.Text = "Tel No";
            this.txtTelMobile.BackColor = System.Drawing.Color.LightYellow;
            this.txtTelMobile.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTelMobile.Location = new System.Drawing.Point(117, 265);
            this.txtTelMobile.Name = "txtTelMobile";
            this.txtTelMobile.Size = new System.Drawing.Size(168, 21);
            this.txtTelMobile.TabIndex = 5;
            this.txtTelMobile.Text = "Not Given";
            this.txtTelHome.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTelHome.Location = new System.Drawing.Point(117, 232);
            this.txtTelHome.Name = "txtTelHome";
            this.txtTelHome.Size = new System.Drawing.Size(168, 21);
            this.txtTelHome.TabIndex = 4;
            this.panel1.BackColor = System.Drawing.Color.Silver;
            this.panel1.Location = new System.Drawing.Point(301, 30);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1, 155);
            this.panel1.TabIndex = 260;
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.Location = new System.Drawing.Point(311, 162);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(46, 13);
            this.label13.TabIndex = 257;
            this.label13.Text = "Country";
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label14.Location = new System.Drawing.Point(311, 136);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(26, 13);
            this.label14.TabIndex = 256;
            this.label14.Text = "City";
            this.label15.AutoSize = true;
            this.label15.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label15.Location = new System.Drawing.Point(311, 102);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(64, 13);
            this.label15.TabIndex = 255;
            this.label15.Text = "Postal Code";
            this.txtPostalCode2.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPostalCode2.Location = new System.Drawing.Point(417, 102);
            this.txtPostalCode2.Name = "txtPostalCode2";
            this.txtPostalCode2.Size = new System.Drawing.Size(168, 21);
            this.txtPostalCode2.TabIndex = 9;
            this.label16.AutoSize = true;
            this.label16.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label16.Location = new System.Drawing.Point(311, 40);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(78, 13);
            this.label16.TabIndex = 253;
            this.label16.Text = "Postal Address";
            this.txtPostalAdd.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPostalAdd.Location = new System.Drawing.Point(417, 37);
            this.txtPostalAdd.Multiline = true;
            this.txtPostalAdd.Name = "txtPostalAdd";
            this.txtPostalAdd.Size = new System.Drawing.Size(168, 57);
            this.txtPostalAdd.TabIndex = 8;
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(6, 158);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(46, 13);
            this.label5.TabIndex = 248;
            this.label5.Text = "Country";
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(6, 133);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(26, 13);
            this.label6.TabIndex = 247;
            this.label6.Text = "City";
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(6, 105);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(64, 13);
            this.label7.TabIndex = 246;
            this.label7.Text = "Postal Code";
            this.txtPostalCode1.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPostalCode1.Location = new System.Drawing.Point(117, 101);
            this.txtPostalCode1.Name = "txtPostalCode1";
            this.txtPostalCode1.Size = new System.Drawing.Size(168, 21);
            this.txtPostalCode1.TabIndex = 1;
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(6, 40);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(101, 13);
            this.label8.TabIndex = 244;
            this.label8.Text = "Permanant Address";
            this.txtPermanantAdd.BackColor = System.Drawing.Color.LightYellow;
            this.txtPermanantAdd.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPermanantAdd.Location = new System.Drawing.Point(117, 37);
            this.txtPermanantAdd.Multiline = true;
            this.txtPermanantAdd.Name = "txtPermanantAdd";
            this.txtPermanantAdd.Size = new System.Drawing.Size(168, 57);
            this.txtPermanantAdd.TabIndex = 0;
            this.txtPermanantAdd.Text = "Not Given";
            this.BankingDetails.Controls.Add(this.grdBNK);
            this.BankingDetails.Location = new System.Drawing.Point(4, 22);
            this.BankingDetails.Name = "BankingDetails";
            this.BankingDetails.Padding = new System.Windows.Forms.Padding(3);
            this.BankingDetails.Size = new System.Drawing.Size(649, 401);
            this.BankingDetails.TabIndex = 8;
            this.BankingDetails.Text = "Banking Details";
            this.BankingDetails.UseVisualStyleBackColor = true;
            this.grdBNK.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdBNK.Location = new System.Drawing.Point(1, 8);
            this.grdBNK.Name = "grdBNK";
            this.grdBNK.Size = new System.Drawing.Size(644, 392);
            this.grdBNK.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdBNK.Styles"));
            this.grdBNK.TabIndex = 0;
            this.grdBNK.KeyDown += new System.Windows.Forms.KeyEventHandler(this.grdBNK_KeyDown);
            this.grdBNK.CellButtonClick += new C1.Win.C1FlexGrid.RowColEventHandler(this.grdBNK_CellButtonClick);
            this.grdBNK.RowColChange += new System.EventHandler(this.grdBNK_RowColChange);
            this.ServiceDetails.Controls.Add(this.cmbStatus);
            this.ServiceDetails.Controls.Add(this.label19);
            this.ServiceDetails.Controls.Add(this.label56);
            this.ServiceDetails.Controls.Add(this.txtBasicSalary);
            this.ServiceDetails.Controls.Add(this.txtDesignation);
            this.ServiceDetails.Controls.Add(this.label11);
            this.ServiceDetails.Controls.Add(this.txtPrvEmployer);
            this.ServiceDetails.Controls.Add(this.dtpDischargeDate);
            this.ServiceDetails.Controls.Add(this.dtpEngageDate);
            this.ServiceDetails.Controls.Add(this.label67);
            this.ServiceDetails.Controls.Add(this.lblDischarge);
            this.ServiceDetails.Controls.Add(this.label64);
            this.ServiceDetails.Location = new System.Drawing.Point(4, 22);
            this.ServiceDetails.Name = "ServiceDetails";
            this.ServiceDetails.Padding = new System.Windows.Forms.Padding(3);
            this.ServiceDetails.Size = new System.Drawing.Size(649, 401);
            this.ServiceDetails.TabIndex = 2;
            this.ServiceDetails.Text = "Service Details";
            this.ServiceDetails.UseVisualStyleBackColor = true;
            this.cmbStatus.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbStatus.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbStatus.FormattingEnabled = true;
            this.cmbStatus.Location = new System.Drawing.Point(126, 168);
            this.cmbStatus.Name = "cmbStatus";
            this.cmbStatus.Size = new System.Drawing.Size(250, 21);
            this.cmbStatus.TabIndex = 4;
            this.label19.AutoSize = true;
            this.label19.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label19.Location = new System.Drawing.Point(8, 210);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(86, 13);
            this.label19.TabIndex = 239;
            this.label19.Text = "Basic Salary (lkr)";
            this.label56.AutoSize = true;
            this.label56.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label56.Location = new System.Drawing.Point(8, 168);
            this.label56.Name = "label56";
            this.label56.Size = new System.Drawing.Size(38, 13);
            this.label56.TabIndex = 239;
            this.label56.Text = "Status";
            this.txtBasicSalary.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtBasicSalary.Location = new System.Drawing.Point(126, 207);
            this.txtBasicSalary.Name = "txtBasicSalary";
            this.txtBasicSalary.Size = new System.Drawing.Size(250, 21);
            this.txtBasicSalary.TabIndex = 3;
            this.txtDesignation.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDesignation.Location = new System.Drawing.Point(126, 131);
            this.txtDesignation.Name = "txtDesignation";
            this.txtDesignation.Size = new System.Drawing.Size(250, 21);
            this.txtDesignation.TabIndex = 3;
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label11.Location = new System.Drawing.Point(8, 131);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(63, 13);
            this.label11.TabIndex = 237;
            this.label11.Text = "Designation";
            this.txtPrvEmployer.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPrvEmployer.Location = new System.Drawing.Point(126, 94);
            this.txtPrvEmployer.Name = "txtPrvEmployer";
            this.txtPrvEmployer.Size = new System.Drawing.Size(250, 21);
            this.txtPrvEmployer.TabIndex = 2;
            this.dtpDischargeDate.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpDischargeDate.Location = new System.Drawing.Point(126, 57);
            this.dtpDischargeDate.Name = "dtpDischargeDate";
            this.dtpDischargeDate.Size = new System.Drawing.Size(250, 21);
            this.dtpDischargeDate.TabIndex = 1;
            this.dtpEngageDate.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpEngageDate.Location = new System.Drawing.Point(126, 21);
            this.dtpEngageDate.Name = "dtpEngageDate";
            this.dtpEngageDate.Size = new System.Drawing.Size(250, 21);
            this.dtpEngageDate.TabIndex = 0;
            this.label67.AutoSize = true;
            this.label67.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label67.Location = new System.Drawing.Point(8, 94);
            this.label67.Name = "label67";
            this.label67.Size = new System.Drawing.Size(95, 13);
            this.label67.TabIndex = 232;
            this.label67.Text = "Previous Employer";
            this.lblDischarge.AutoSize = true;
            this.lblDischarge.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDischarge.Location = new System.Drawing.Point(8, 56);
            this.lblDischarge.Name = "lblDischarge";
            this.lblDischarge.Size = new System.Drawing.Size(93, 13);
            this.lblDischarge.TabIndex = 231;
            this.lblDischarge.Text = "Date of Discharge";
            this.label64.AutoSize = true;
            this.label64.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label64.Location = new System.Drawing.Point(8, 21);
            this.label64.Name = "label64";
            this.label64.Size = new System.Drawing.Size(106, 13);
            this.label64.TabIndex = 229;
            this.label64.Text = "Date of Engagement";
            this.chkActive.AutoSize = true;
            this.chkActive.Checked = true;
            this.chkActive.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkActive.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkActive.Location = new System.Drawing.Point(410, 449);
            this.chkActive.Name = "chkActive";
            this.chkActive.Size = new System.Drawing.Size(56, 17);
            this.chkActive.TabIndex = 225;
            this.chkActive.Text = "Active";
            this.chkActive.UseVisualStyleBackColor = true;
            this.chkActive.Click += new System.EventHandler(this.chkActive_Click);
            this.btnCancel.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Location = new System.Drawing.Point(555, 446);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(75, 23);
            this.btnCancel.TabIndex = 2;
            this.btnCancel.Text = "&Cancel";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnOk.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Location = new System.Drawing.Point(473, 446);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(75, 23);
            this.btnOk.TabIndex = 1;
            this.btnOk.Text = "&OK";
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(660, 476);
            this.Controls.Add(this.chkActive);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.tabEmployee);
            this.Name = "frmEmployee";
            this.Text = "Employee Details";
            this.Load += new System.EventHandler(this.frmEmployee_Load);
            this.tabEmployee.ResumeLayout(false);
            this.PersonalDetails.ResumeLayout(false);
            this.PersonalDetails.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox7.ResumeLayout(false);
            this.groupBox7.PerformLayout();
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nudNoOfDependances)).EndInit();
            this.groupBox2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbEmpPhoto)).EndInit();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.ContactDetails.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.BankingDetails.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdBNK)).EndInit();
            this.ServiceDetails.ResumeLayout(false);
            this.ServiceDetails.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.TabControl tabEmployee;
        private System.Windows.Forms.TabPage PersonalDetails;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.GroupBox groupBox7;
        private DropDowns.DropSearch drpCountryID;
        private System.Windows.Forms.GroupBox groupBox6;
        private System.Windows.Forms.RadioButton rdbIsMale;
        private System.Windows.Forms.RadioButton rdbIsFemale;
        private System.Windows.Forms.DateTimePicker dtpDOB;
        private System.Windows.Forms.Label label39;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.NumericUpDown nudNoOfDependances;
        private System.Windows.Forms.Label label37;
        private  Tourist_Management.User_Controls.ComboBox cmbMaritalStatus;
        private System.Windows.Forms.Label label36;
        private System.Windows.Forms.Label lblID;
        private System.Windows.Forms.TextBox txtIdentityNo;
        private  Tourist_Management.User_Controls.ComboBox cmbIdentityTypeID;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label lblEmpPhoto;
        private System.Windows.Forms.Button btnClearLogo;
        private System.Windows.Forms.Button btnUploadLogo;
        private System.Windows.Forms.PictureBox pbEmpPhoto;
        private System.Windows.Forms.Label label38;
        private System.Windows.Forms.TextBox txtRemarks;
        private System.Windows.Forms.GroupBox groupBox3;
        private  Tourist_Management.User_Controls.ComboBox cmbMr_Mrs;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.TextBox txtFirstName;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox txtNickName;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox txtSurName;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox txtNameWithIntials;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox txtCode;
        private System.Windows.Forms.TabPage ContactDetails;
        private System.Windows.Forms.GroupBox groupBox5;
        private DropDowns.DropSearch drpPMACountryID;
        private DropDowns.DropSearch drpPOACountryID;
        private System.Windows.Forms.Label label53;
        private System.Windows.Forms.Label label52;
        private System.Windows.Forms.Label label51;
        private System.Windows.Forms.Label label50;
        private System.Windows.Forms.Label label42;
        private System.Windows.Forms.Label label43;
        private System.Windows.Forms.TextBox txtContEmployer;
        private System.Windows.Forms.TextBox txtContTel2;
        private System.Windows.Forms.Label label47;
        private System.Windows.Forms.Label label48;
        private System.Windows.Forms.TextBox txtContTel1;
        private System.Windows.Forms.TextBox txtContName;
        private System.Windows.Forms.Panel panel4;
        private System.Windows.Forms.Panel panel3;
        private  Tourist_Management.User_Controls.ComboBox cmbCity2;
        private  Tourist_Management.User_Controls.ComboBox cmbCity1;
        private System.Windows.Forms.Label label44;
        private System.Windows.Forms.Label label45;
        private System.Windows.Forms.TextBox txtEmail;
        private System.Windows.Forms.TextBox txtFaxNo;
        private System.Windows.Forms.Label label41;
        private System.Windows.Forms.Label label40;
        private System.Windows.Forms.TextBox txtTelMobile;
        private System.Windows.Forms.TextBox txtTelHome;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.TextBox txtPostalCode2;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.TextBox txtPostalAdd;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TextBox txtPostalCode1;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox txtPermanantAdd;
        private System.Windows.Forms.TabPage BankingDetails;
        private C1.Win.C1FlexGrid.C1FlexGrid grdBNK;
        private System.Windows.Forms.TabPage ServiceDetails;
        private System.Windows.Forms.TextBox txtPrvEmployer;
        private System.Windows.Forms.DateTimePicker dtpDischargeDate;
        private System.Windows.Forms.DateTimePicker dtpEngageDate;
        private System.Windows.Forms.Label label67;
        private System.Windows.Forms.Label lblDischarge;
        private System.Windows.Forms.Label label64;
        private System.Windows.Forms.CheckBox chkActive;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.Label label49;
        private System.Windows.Forms.TextBox txtContEmail;
        private System.Windows.Forms.TextBox txtDesignation;
        private System.Windows.Forms.Label label11;
        private  Tourist_Management.User_Controls.ComboBox cmbStatus;
        private System.Windows.Forms.Label label56;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.TextBox txtBasicSalary;
    }
}