namespace Tourist_Management.Master
{
    partial class frmGuide
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmGuide));
            this.tcGuide = new System.Windows.Forms.TabControl();
            this.tpDetails = new System.Windows.Forms.TabPage();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.label5 = new System.Windows.Forms.Label();
            this.txtAddress = new System.Windows.Forms.TextBox();
            this.label13 = new System.Windows.Forms.Label();
            this.txtTel2 = new System.Windows.Forms.TextBox();
            this.label12 = new System.Windows.Forms.Label();
            this.txtTel1 = new System.Windows.Forms.TextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.txtSpouseNo = new System.Windows.Forms.TextBox();
            this.label10 = new System.Windows.Forms.Label();
            this.txtSpouseName = new System.Windows.Forms.TextBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.txtRemarks = new System.Windows.Forms.TextBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.drpEmpID = new DropDowns.DropSearch();
            this.chkIsDriver = new System.Windows.Forms.CheckBox();
            this.label3 = new System.Windows.Forms.Label();
            this.txtFee = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.txtCode = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.txtCompany = new System.Windows.Forms.TextBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.lblImage = new System.Windows.Forms.Label();
            this.btnClearLogo = new System.Windows.Forms.Button();
            this.btnUploadLogo = new System.Windows.Forms.Button();
            this.pbImage = new System.Windows.Forms.PictureBox();
            this.chkIsEmp = new System.Windows.Forms.CheckBox();
            this.dtpDateDisc = new System.Windows.Forms.DateTimePicker();
            this.dtpDateEngage = new System.Windows.Forms.DateTimePicker();
            this.lblDischarge = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.txtLicense = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.txtNIC = new System.Windows.Forms.TextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.txtName = new System.Windows.Forms.TextBox();
            this.tpLang = new System.Windows.Forms.TabPage();
            this.grdLang = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.tpAddPhotos = new System.Windows.Forms.TabPage();
            this.grdPhoto = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.tpViewPhotos = new System.Windows.Forms.TabPage();
            this.pbMultiPhotos = new System.Windows.Forms.PictureBox();
            this.tvPhotoDesc = new System.Windows.Forms.TreeView();
            this.tpReference = new System.Windows.Forms.TabPage();
            this.c1FlexGrid1 = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.chkActive = new System.Windows.Forms.CheckBox();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.tcGuide.SuspendLayout();
            this.tpDetails.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbImage)).BeginInit();
            this.tpLang.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdLang)).BeginInit();
            this.tpAddPhotos.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdPhoto)).BeginInit();
            this.tpViewPhotos.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbMultiPhotos)).BeginInit();
            this.tpReference.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.c1FlexGrid1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.SuspendLayout();
            this.tcGuide.Controls.Add(this.tpDetails);
            this.tcGuide.Controls.Add(this.tpLang);
            this.tcGuide.Controls.Add(this.tpAddPhotos);
            this.tcGuide.Controls.Add(this.tpViewPhotos);
            this.tcGuide.Controls.Add(this.tpReference);
            this.tcGuide.Location = new System.Drawing.Point(7, 5);
            this.tcGuide.Name = "tcGuide";
            this.tcGuide.SelectedIndex = 0;
            this.tcGuide.Size = new System.Drawing.Size(615, 374);
            this.tcGuide.TabIndex = 0;
            this.tpDetails.Controls.Add(this.groupBox5);
            this.tpDetails.Controls.Add(this.groupBox3);
            this.tpDetails.Controls.Add(this.groupBox4);
            this.tpDetails.Location = new System.Drawing.Point(4, 22);
            this.tpDetails.Name = "tpDetails";
            this.tpDetails.Padding = new System.Windows.Forms.Padding(3);
            this.tpDetails.Size = new System.Drawing.Size(607, 348);
            this.tpDetails.TabIndex = 0;
            this.tpDetails.Text = "Basic Detail";
            this.tpDetails.UseVisualStyleBackColor = true;
            this.groupBox5.Controls.Add(this.label5);
            this.groupBox5.Controls.Add(this.txtAddress);
            this.groupBox5.Controls.Add(this.label13);
            this.groupBox5.Controls.Add(this.txtTel2);
            this.groupBox5.Controls.Add(this.label12);
            this.groupBox5.Controls.Add(this.txtTel1);
            this.groupBox5.Controls.Add(this.label11);
            this.groupBox5.Controls.Add(this.txtSpouseNo);
            this.groupBox5.Controls.Add(this.label10);
            this.groupBox5.Controls.Add(this.txtSpouseName);
            this.groupBox5.Location = new System.Drawing.Point(363, 9);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(233, 220);
            this.groupBox5.TabIndex = 289;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Contacts";
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(6, 22);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(46, 13);
            this.label5.TabIndex = 290;
            this.label5.Text = "Address";
            this.txtAddress.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAddress.Location = new System.Drawing.Point(84, 22);
            this.txtAddress.MaxLength = 100;
            this.txtAddress.Multiline = true;
            this.txtAddress.Name = "txtAddress";
            this.txtAddress.Size = new System.Drawing.Size(135, 61);
            this.txtAddress.TabIndex = 0;
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.Location = new System.Drawing.Point(4, 127);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(66, 13);
            this.label13.TabIndex = 288;
            this.label13.Text = "Telephone 2";
            this.txtTel2.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTel2.Location = new System.Drawing.Point(84, 124);
            this.txtTel2.MaxLength = 100;
            this.txtTel2.Name = "txtTel2";
            this.txtTel2.Size = new System.Drawing.Size(135, 21);
            this.txtTel2.TabIndex = 2;
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.Location = new System.Drawing.Point(6, 96);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(66, 13);
            this.label12.TabIndex = 286;
            this.label12.Text = "Telephone 1";
            this.txtTel1.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTel1.Location = new System.Drawing.Point(84, 96);
            this.txtTel1.MaxLength = 100;
            this.txtTel1.Name = "txtTel1";
            this.txtTel1.Size = new System.Drawing.Size(135, 21);
            this.txtTel1.TabIndex = 1;
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label11.Location = new System.Drawing.Point(4, 189);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(58, 13);
            this.label11.TabIndex = 284;
            this.label11.Text = "Spouse No";
            this.txtSpouseNo.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSpouseNo.Location = new System.Drawing.Point(84, 186);
            this.txtSpouseNo.MaxLength = 100;
            this.txtSpouseNo.Name = "txtSpouseNo";
            this.txtSpouseNo.Size = new System.Drawing.Size(135, 21);
            this.txtSpouseNo.TabIndex = 4;
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.Location = new System.Drawing.Point(4, 162);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(72, 13);
            this.label10.TabIndex = 282;
            this.label10.Text = "Spouse Name";
            this.txtSpouseName.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSpouseName.Location = new System.Drawing.Point(84, 159);
            this.txtSpouseName.MaxLength = 100;
            this.txtSpouseName.Name = "txtSpouseName";
            this.txtSpouseName.Size = new System.Drawing.Size(135, 21);
            this.txtSpouseName.TabIndex = 3;
            this.groupBox3.Controls.Add(this.txtRemarks);
            this.groupBox3.Location = new System.Drawing.Point(364, 236);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(233, 96);
            this.groupBox3.TabIndex = 239;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Remarks";
            this.txtRemarks.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtRemarks.Location = new System.Drawing.Point(6, 24);
            this.txtRemarks.MaxLength = 100;
            this.txtRemarks.Multiline = true;
            this.txtRemarks.Name = "txtRemarks";
            this.txtRemarks.Size = new System.Drawing.Size(212, 61);
            this.txtRemarks.TabIndex = 0;
            this.groupBox4.Controls.Add(this.drpEmpID);
            this.groupBox4.Controls.Add(this.chkIsDriver);
            this.groupBox4.Controls.Add(this.label3);
            this.groupBox4.Controls.Add(this.txtFee);
            this.groupBox4.Controls.Add(this.label2);
            this.groupBox4.Controls.Add(this.txtCode);
            this.groupBox4.Controls.Add(this.label1);
            this.groupBox4.Controls.Add(this.txtCompany);
            this.groupBox4.Controls.Add(this.groupBox2);
            this.groupBox4.Controls.Add(this.chkIsEmp);
            this.groupBox4.Controls.Add(this.dtpDateDisc);
            this.groupBox4.Controls.Add(this.dtpDateEngage);
            this.groupBox4.Controls.Add(this.lblDischarge);
            this.groupBox4.Controls.Add(this.label4);
            this.groupBox4.Controls.Add(this.txtLicense);
            this.groupBox4.Controls.Add(this.label6);
            this.groupBox4.Controls.Add(this.label8);
            this.groupBox4.Controls.Add(this.txtNIC);
            this.groupBox4.Controls.Add(this.label9);
            this.groupBox4.Controls.Add(this.txtName);
            this.groupBox4.Location = new System.Drawing.Point(9, 9);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(348, 323);
            this.groupBox4.TabIndex = 1;
            this.groupBox4.TabStop = false;
            this.drpEmpID.BackColor = System.Drawing.Color.Transparent;
            this.drpEmpID.DataSource = null;
            this.drpEmpID.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpEmpID.FormName = "";
            this.drpEmpID.Location = new System.Drawing.Point(6, 60);
            this.drpEmpID.Name = "drpEmpID";
            this.drpEmpID.SelectedText = "";
            this.drpEmpID.SelectedValue = "";
            this.drpEmpID.Size = new System.Drawing.Size(189, 23);
            this.drpEmpID.TabIndex = 1;
            this.drpEmpID.Click_Open += new System.EventHandler(this.drpEmpID_Click_Open);
            this.drpEmpID.Selected_TextChanged += new System.EventHandler(this.drpEmpID_Selected_TextChanged);
            this.chkIsDriver.AutoSize = true;
            this.chkIsDriver.Location = new System.Drawing.Point(9, 37);
            this.chkIsDriver.Name = "chkIsDriver";
            this.chkIsDriver.Size = new System.Drawing.Size(93, 17);
            this.chkIsDriver.TabIndex = 309;
            this.chkIsDriver.Text = "Existing Driver";
            this.chkIsDriver.UseVisualStyleBackColor = true;
            this.chkIsDriver.CheckedChanged += new System.EventHandler(this.chkIsDriver_CheckedChanged);
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(8, 116);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(25, 13);
            this.label3.TabIndex = 308;
            this.label3.Text = "Fee";
            this.txtFee.BackColor = System.Drawing.SystemColors.Window;
            this.txtFee.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFee.Location = new System.Drawing.Point(66, 113);
            this.txtFee.MaxLength = 100;
            this.txtFee.Name = "txtFee";
            this.txtFee.Size = new System.Drawing.Size(148, 21);
            this.txtFee.TabIndex = 3;
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(8, 147);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(62, 13);
            this.label2.TabIndex = 306;
            this.label2.Text = "Guide Code";
            this.txtCode.BackColor = System.Drawing.Color.LightYellow;
            this.txtCode.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCode.Location = new System.Drawing.Point(122, 146);
            this.txtCode.MaxLength = 10;
            this.txtCode.Name = "txtCode";
            this.txtCode.Size = new System.Drawing.Size(92, 21);
            this.txtCode.TabIndex = 4;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(8, 89);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(52, 13);
            this.label1.TabIndex = 304;
            this.label1.Text = "Company";
            this.txtCompany.BackColor = System.Drawing.SystemColors.Window;
            this.txtCompany.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCompany.Location = new System.Drawing.Point(66, 86);
            this.txtCompany.MaxLength = 100;
            this.txtCompany.Name = "txtCompany";
            this.txtCompany.Size = new System.Drawing.Size(148, 21);
            this.txtCompany.TabIndex = 2;
            this.groupBox2.BackColor = System.Drawing.Color.Transparent;
            this.groupBox2.Controls.Add(this.lblImage);
            this.groupBox2.Controls.Add(this.btnClearLogo);
            this.groupBox2.Controls.Add(this.btnUploadLogo);
            this.groupBox2.Controls.Add(this.pbImage);
            this.groupBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.Location = new System.Drawing.Point(220, 11);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(116, 141);
            this.groupBox2.TabIndex = 302;
            this.groupBox2.TabStop = false;
            this.lblImage.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblImage.Location = new System.Drawing.Point(15, 28);
            this.lblImage.Name = "lblImage";
            this.lblImage.Size = new System.Drawing.Size(84, 81);
            this.lblImage.TabIndex = 242;
            this.lblImage.Text = "Upload Guide Image";
            this.lblImage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClearLogo.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClearLogo.Location = new System.Drawing.Point(60, 116);
            this.btnClearLogo.Name = "btnClearLogo";
            this.btnClearLogo.Size = new System.Drawing.Size(53, 21);
            this.btnClearLogo.TabIndex = 1;
            this.btnClearLogo.Text = "Clear";
            this.btnClearLogo.UseVisualStyleBackColor = true;
            this.btnClearLogo.Click += new System.EventHandler(this.btnClearLogo_Click);
            this.btnUploadLogo.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUploadLogo.Location = new System.Drawing.Point(6, 116);
            this.btnUploadLogo.Name = "btnUploadLogo";
            this.btnUploadLogo.Size = new System.Drawing.Size(53, 21);
            this.btnUploadLogo.TabIndex = 0;
            this.btnUploadLogo.Text = "Upload";
            this.btnUploadLogo.UseVisualStyleBackColor = true;
            this.btnUploadLogo.Click += new System.EventHandler(this.btnUploadLogo_Click);
            this.pbImage.BackColor = System.Drawing.Color.Transparent;
            this.pbImage.Location = new System.Drawing.Point(6, 11);
            this.pbImage.Name = "pbImage";
            this.pbImage.Size = new System.Drawing.Size(102, 101);
            this.pbImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbImage.TabIndex = 3;
            this.pbImage.TabStop = false;
            this.chkIsEmp.AutoSize = true;
            this.chkIsEmp.Location = new System.Drawing.Point(9, 14);
            this.chkIsEmp.Name = "chkIsEmp";
            this.chkIsEmp.Size = new System.Drawing.Size(111, 17);
            this.chkIsEmp.TabIndex = 0;
            this.chkIsEmp.Text = "Existing Employee";
            this.chkIsEmp.UseVisualStyleBackColor = true;
            this.chkIsEmp.CheckedChanged += new System.EventHandler(this.chkIsEmp_CheckedChanged);
            this.dtpDateDisc.Location = new System.Drawing.Point(122, 287);
            this.dtpDateDisc.Name = "dtpDateDisc";
            this.dtpDateDisc.Size = new System.Drawing.Size(205, 20);
            this.dtpDateDisc.TabIndex = 9;
            this.dtpDateEngage.Location = new System.Drawing.Point(122, 258);
            this.dtpDateEngage.Name = "dtpDateEngage";
            this.dtpDateEngage.Size = new System.Drawing.Size(205, 20);
            this.dtpDateEngage.TabIndex = 8;
            this.lblDischarge.AutoSize = true;
            this.lblDischarge.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDischarge.Location = new System.Drawing.Point(8, 290);
            this.lblDischarge.Name = "lblDischarge";
            this.lblDischarge.Size = new System.Drawing.Size(93, 13);
            this.lblDischarge.TabIndex = 291;
            this.lblDischarge.Text = "Date of Discharge";
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(8, 262);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(82, 13);
            this.label4.TabIndex = 290;
            this.label4.Text = "Date of Engage";
            this.txtLicense.BackColor = System.Drawing.SystemColors.Window;
            this.txtLicense.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtLicense.Location = new System.Drawing.Point(122, 227);
            this.txtLicense.MaxLength = 100;
            this.txtLicense.Name = "txtLicense";
            this.txtLicense.Size = new System.Drawing.Size(205, 21);
            this.txtLicense.TabIndex = 7;
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(8, 230);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(58, 13);
            this.label6.TabIndex = 288;
            this.label6.Text = "License No";
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(8, 201);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(41, 13);
            this.label8.TabIndex = 282;
            this.label8.Text = "NIC No";
            this.txtNIC.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNIC.Location = new System.Drawing.Point(122, 200);
            this.txtNIC.MaxLength = 100;
            this.txtNIC.Name = "txtNIC";
            this.txtNIC.Size = new System.Drawing.Size(205, 21);
            this.txtNIC.TabIndex = 6;
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(8, 174);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(34, 13);
            this.label9.TabIndex = 280;
            this.label9.Text = "Name";
            this.txtName.BackColor = System.Drawing.Color.LightYellow;
            this.txtName.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtName.Location = new System.Drawing.Point(122, 173);
            this.txtName.MaxLength = 100;
            this.txtName.Name = "txtName";
            this.txtName.Size = new System.Drawing.Size(205, 21);
            this.txtName.TabIndex = 5;
            this.txtName.TextChanged += new System.EventHandler(this.txtName_TextChanged);
            this.txtName.Leave += new System.EventHandler(this.txtName_Leave);
            this.tpLang.Controls.Add(this.grdLang);
            this.tpLang.Location = new System.Drawing.Point(4, 22);
            this.tpLang.Name = "tpLang";
            this.tpLang.Padding = new System.Windows.Forms.Padding(3);
            this.tpLang.Size = new System.Drawing.Size(607, 348);
            this.tpLang.TabIndex = 4;
            this.tpLang.Text = "Languages";
            this.tpLang.UseVisualStyleBackColor = true;
            this.grdLang.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdLang.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdLang.Location = new System.Drawing.Point(3, 3);
            this.grdLang.Name = "grdLang";
            this.grdLang.Size = new System.Drawing.Size(600, 342);
            this.grdLang.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdLang.Styles"));
            this.grdLang.TabIndex = 0;
            this.tpAddPhotos.Controls.Add(this.grdPhoto);
            this.tpAddPhotos.Location = new System.Drawing.Point(4, 22);
            this.tpAddPhotos.Name = "tpAddPhotos";
            this.tpAddPhotos.Padding = new System.Windows.Forms.Padding(3);
            this.tpAddPhotos.Size = new System.Drawing.Size(607, 348);
            this.tpAddPhotos.TabIndex = 2;
            this.tpAddPhotos.Text = "Add Photos";
            this.tpAddPhotos.UseVisualStyleBackColor = true;
            this.grdPhoto.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdPhoto.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdPhoto.Location = new System.Drawing.Point(3, 3);
            this.grdPhoto.Name = "grdPhoto";
            this.grdPhoto.Size = new System.Drawing.Size(600, 342);
            this.grdPhoto.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdPhoto.Styles"));
            this.grdPhoto.TabIndex = 7;
            this.grdPhoto.KeyDown += new System.Windows.Forms.KeyEventHandler(this.grdPhoto_KeyDown);
            this.grdPhoto.CellButtonClick += new C1.Win.C1FlexGrid.RowColEventHandler(this.grdPhoto_CellButtonClick);
            this.grdPhoto.RowColChange += new System.EventHandler(this.grdPhoto_RowColChange);
            this.tpViewPhotos.Controls.Add(this.pbMultiPhotos);
            this.tpViewPhotos.Controls.Add(this.tvPhotoDesc);
            this.tpViewPhotos.Location = new System.Drawing.Point(4, 22);
            this.tpViewPhotos.Name = "tpViewPhotos";
            this.tpViewPhotos.Padding = new System.Windows.Forms.Padding(3);
            this.tpViewPhotos.Size = new System.Drawing.Size(607, 348);
            this.tpViewPhotos.TabIndex = 3;
            this.tpViewPhotos.Text = "View Photos";
            this.tpViewPhotos.UseVisualStyleBackColor = true;
            this.pbMultiPhotos.Location = new System.Drawing.Point(161, 3);
            this.pbMultiPhotos.Name = "pbMultiPhotos";
            this.pbMultiPhotos.Size = new System.Drawing.Size(442, 339);
            this.pbMultiPhotos.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbMultiPhotos.TabIndex = 5;
            this.pbMultiPhotos.TabStop = false;
            this.tvPhotoDesc.Location = new System.Drawing.Point(6, 3);
            this.tvPhotoDesc.Name = "tvPhotoDesc";
            this.tvPhotoDesc.Size = new System.Drawing.Size(149, 339);
            this.tvPhotoDesc.TabIndex = 0;
            this.tvPhotoDesc.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.tvPhotoDesc_AfterSelect);
            this.tpReference.Controls.Add(this.c1FlexGrid1);
            this.tpReference.Location = new System.Drawing.Point(4, 22);
            this.tpReference.Name = "tpReference";
            this.tpReference.Padding = new System.Windows.Forms.Padding(3);
            this.tpReference.Size = new System.Drawing.Size(607, 348);
            this.tpReference.TabIndex = 1;
            this.tpReference.Text = "Reference";
            this.tpReference.UseVisualStyleBackColor = true;
            this.c1FlexGrid1.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.c1FlexGrid1.ColumnInfo = resources.GetString("c1FlexGrid1.ColumnInfo");
            this.c1FlexGrid1.Enabled = false;
            this.c1FlexGrid1.Location = new System.Drawing.Point(6, 4);
            this.c1FlexGrid1.Name = "c1FlexGrid1";
            this.c1FlexGrid1.Size = new System.Drawing.Size(594, 338);
            this.c1FlexGrid1.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("c1FlexGrid1.Styles"));
            this.c1FlexGrid1.TabIndex = 0;
            this.chkActive.AutoSize = true;
            this.chkActive.Checked = true;
            this.chkActive.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkActive.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkActive.Location = new System.Drawing.Point(394, 388);
            this.chkActive.Name = "chkActive";
            this.chkActive.Size = new System.Drawing.Size(56, 17);
            this.chkActive.TabIndex = 1;
            this.chkActive.Text = "Active";
            this.chkActive.UseVisualStyleBackColor = true;
            this.chkActive.Click += new System.EventHandler(this.chkActive_Click);
            this.btnCancel.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Location = new System.Drawing.Point(547, 385);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(75, 23);
            this.btnCancel.TabIndex = 3;
            this.btnCancel.Text = "&Cancel";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click_1);
            this.btnOk.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Location = new System.Drawing.Point(465, 385);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(75, 23);
            this.btnOk.TabIndex = 2;
            this.btnOk.Text = "&OK";
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.errorProvider1.ContainerControl = this;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(626, 418);
            this.Controls.Add(this.tcGuide);
            this.Controls.Add(this.chkActive);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOk);
            this.Name = "frmGuide";
            this.Text = "Guide Details";
            this.Load += new System.EventHandler(this.frmGuide_Load);
            this.tcGuide.ResumeLayout(false);
            this.tpDetails.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbImage)).EndInit();
            this.tpLang.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdLang)).EndInit();
            this.tpAddPhotos.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdPhoto)).EndInit();
            this.tpViewPhotos.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbMultiPhotos)).EndInit();
            this.tpReference.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.c1FlexGrid1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.TabControl tcGuide;
        private System.Windows.Forms.TabPage tpDetails;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox txtAddress;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.TextBox txtTel2;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.TextBox txtTel1;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.TextBox txtSpouseNo;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.TextBox txtSpouseName;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.TextBox txtRemarks;
        private System.Windows.Forms.GroupBox groupBox4;
        private DropDowns.DropSearch drpEmpID;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox txtCode;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox txtCompany;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label lblImage;
        private System.Windows.Forms.Button btnClearLogo;
        private System.Windows.Forms.Button btnUploadLogo;
        private System.Windows.Forms.PictureBox pbImage;
        private System.Windows.Forms.CheckBox chkIsEmp;
        private System.Windows.Forms.DateTimePicker dtpDateDisc;
        private System.Windows.Forms.DateTimePicker dtpDateEngage;
        private System.Windows.Forms.Label lblDischarge;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox txtLicense;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox txtNIC;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.TextBox txtName;
        private System.Windows.Forms.TabPage tpReference;
        private C1.Win.C1FlexGrid.C1FlexGrid c1FlexGrid1;
        private System.Windows.Forms.CheckBox chkActive;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.TabPage tpAddPhotos;
        private System.Windows.Forms.TabPage tpViewPhotos;
        private C1.Win.C1FlexGrid.C1FlexGrid grdPhoto;
        private System.Windows.Forms.PictureBox pbMultiPhotos;
        private System.Windows.Forms.TreeView tvPhotoDesc;
        private System.Windows.Forms.TabPage tpLang;
        private C1.Win.C1FlexGrid.C1FlexGrid grdLang;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox txtFee;
        private System.Windows.Forms.CheckBox chkIsDriver;
        private System.Windows.Forms.ErrorProvider errorProvider1;
    }
}