namespace Tourist_Management.Master
{
    partial class frmTRDetails
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmTRDetails));
            this.tcTransportation = new System.Windows.Forms.TabControl();
            this.tpDriver = new System.Windows.Forms.TabPage();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.txtTel1 = new System.Windows.Forms.TextBox();
            this.label14 = new System.Windows.Forms.Label();
            this.txtTel3 = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.txtEmail = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.txtAddress = new System.Windows.Forms.TextBox();
            this.label13 = new System.Windows.Forms.Label();
            this.txtTel2 = new System.Windows.Forms.TextBox();
            this.label12 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.txtSpouseNo = new System.Windows.Forms.TextBox();
            this.label10 = new System.Windows.Forms.Label();
            this.txtSpouseName = new System.Windows.Forms.TextBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.txtRemarks = new System.Windows.Forms.TextBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.drpOwnerID = new Tourist_Management.DropDowns.DropSearch();
            this.drpEmpID = new Tourist_Management.DropDowns.DropSearch();
            this.btnTakeaPic = new System.Windows.Forms.Button();
            this.txtOwnerName = new System.Windows.Forms.TextBox();
            this.label21 = new System.Windows.Forms.Label();
            this.txtDriverName = new System.Windows.Forms.TextBox();
            this.srcPriority = new RatingControls.StarRatingControl();
            this.label17 = new System.Windows.Forms.Label();
            this.chkEngageDate = new System.Windows.Forms.CheckBox();
            this.txtGuideLicense = new System.Windows.Forms.TextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.txtCode = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.gbImage = new System.Windows.Forms.GroupBox();
            this.lblImage = new System.Windows.Forms.Label();
            this.btnClearLogo = new System.Windows.Forms.Button();
            this.btnUploadLogo = new System.Windows.Forms.Button();
            this.pbImage = new System.Windows.Forms.PictureBox();
            this.chkIsEmp = new System.Windows.Forms.CheckBox();
            this.dtpDateDisc = new System.Windows.Forms.DateTimePicker();
            this.dtpDateEngage = new System.Windows.Forms.DateTimePicker();
            this.lblDischarge = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.txtLicense = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.txtNIC = new System.Windows.Forms.TextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.tpLanguages = new System.Windows.Forms.TabPage();
            this.grdLang = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.tpVehicle = new System.Windows.Forms.TabPage();
            this.groupBox9 = new System.Windows.Forms.GroupBox();
            this.txtLeasePayment = new System.Windows.Forms.TextBox();
            this.label32 = new System.Windows.Forms.Label();
            this.label33 = new System.Windows.Forms.Label();
            this.txtInsurance = new System.Windows.Forms.TextBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.drpBrand = new Tourist_Management.DropDowns.DropSearch();
            this.drpCountry = new Tourist_Management.DropDowns.DropSearch();
            this.label29 = new System.Windows.Forms.Label();
            this.label26 = new System.Windows.Forms.Label();
            this.groupBox8 = new System.Windows.Forms.GroupBox();
            this.drpTypeID = new Tourist_Management.DropDowns.DropSearch();
            this.txtModelNo = new System.Windows.Forms.TextBox();
            this.label23 = new System.Windows.Forms.Label();
            this.txtModel = new System.Windows.Forms.TextBox();
            this.label28 = new System.Windows.Forms.Label();
            this.label24 = new System.Windows.Forms.Label();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.txtVehiRemarks = new System.Windows.Forms.TextBox();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.txtCharg = new System.Windows.Forms.TextBox();
            this.nudMaxPas = new System.Windows.Forms.NumericUpDown();
            this.label25 = new System.Windows.Forms.Label();
            this.label27 = new System.Windows.Forms.Label();
            this.chkManuYear = new System.Windows.Forms.CheckBox();
            this.chkRegYear = new System.Windows.Forms.CheckBox();
            this.dtpManuYear = new System.Windows.Forms.DateTimePicker();
            this.dtpRegYear = new System.Windows.Forms.DateTimePicker();
            this.label19 = new System.Windows.Forms.Label();
            this.label20 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.drpCity = new Tourist_Management.DropDowns.DropSearch();
            this.txtInsNo = new System.Windows.Forms.TextBox();
            this.label15 = new System.Windows.Forms.Label();
            this.txtVehNo = new System.Windows.Forms.TextBox();
            this.label18 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.tpAccessCat = new System.Windows.Forms.TabPage();
            this.grdACC = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.tpAddPhotos = new System.Windows.Forms.TabPage();
            this.grdPhoto = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.tpViewPhotos = new System.Windows.Forms.TabPage();
            this.pbMultiPhotos = new System.Windows.Forms.PictureBox();
            this.tvPhotoDesc = new System.Windows.Forms.TreeView();
            this.tpReference = new System.Windows.Forms.TabPage();
            this.grdRef = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.chkExSum = new System.Windows.Forms.CheckBox();
            this.btnEmail = new System.Windows.Forms.Button();
            this.groupBox16 = new System.Windows.Forms.GroupBox();
            this.rtbBody = new System.Windows.Forms.RichTextBox();
            this.groupBox15 = new System.Windows.Forms.GroupBox();
            this.txtCC = new System.Windows.Forms.TextBox();
            this.label22 = new System.Windows.Forms.Label();
            this.btnEmailConts = new System.Windows.Forms.Button();
            this.txtSubject = new System.Windows.Forms.TextBox();
            this.txtTo = new System.Windows.Forms.TextBox();
            this.label30 = new System.Windows.Forms.Label();
            this.label31 = new System.Windows.Forms.Label();
            this.chkActive = new System.Windows.Forms.CheckBox();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.comboBoxCameras = new  Tourist_Management.User_Controls.ComboBox();
            this.btnPrint = new System.Windows.Forms.Button();
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.tcTransportation.SuspendLayout();
            this.tpDriver.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.gbImage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbImage)).BeginInit();
            this.tpLanguages.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdLang)).BeginInit();
            this.tpVehicle.SuspendLayout();
            this.groupBox9.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox8.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.groupBox6.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nudMaxPas)).BeginInit();
            this.groupBox1.SuspendLayout();
            this.tpAccessCat.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdACC)).BeginInit();
            this.tpAddPhotos.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdPhoto)).BeginInit();
            this.tpViewPhotos.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbMultiPhotos)).BeginInit();
            this.tpReference.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdRef)).BeginInit();
            this.tabPage1.SuspendLayout();
            this.groupBox16.SuspendLayout();
            this.groupBox15.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.SuspendLayout();
            this.tcTransportation.Appearance = System.Windows.Forms.TabAppearance.Buttons;
            this.tcTransportation.Controls.Add(this.tpDriver);
            this.tcTransportation.Controls.Add(this.tpLanguages);
            this.tcTransportation.Controls.Add(this.tpVehicle);
            this.tcTransportation.Controls.Add(this.tpAccessCat);
            this.tcTransportation.Controls.Add(this.tpAddPhotos);
            this.tcTransportation.Controls.Add(this.tpViewPhotos);
            this.tcTransportation.Controls.Add(this.tpReference);
            this.tcTransportation.Controls.Add(this.tabPage1);
            this.tcTransportation.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tcTransportation.Location = new System.Drawing.Point(3, 4);
            this.tcTransportation.Name = "tcTransportation";
            this.tcTransportation.SelectedIndex = 0;
            this.tcTransportation.Size = new System.Drawing.Size(665, 413);
            this.tcTransportation.TabIndex = 0;
            this.tpDriver.BackColor = System.Drawing.Color.Transparent;
            this.tpDriver.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tpDriver.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tpDriver.Controls.Add(this.groupBox5);
            this.tpDriver.Controls.Add(this.groupBox3);
            this.tpDriver.Controls.Add(this.groupBox4);
            this.tpDriver.Location = new System.Drawing.Point(4, 25);
            this.tpDriver.Name = "tpDriver";
            this.tpDriver.Padding = new System.Windows.Forms.Padding(3);
            this.tpDriver.Size = new System.Drawing.Size(657, 384);
            this.tpDriver.TabIndex = 0;
            this.tpDriver.Text = "Basics";
            this.groupBox5.Controls.Add(this.txtTel1);
            this.groupBox5.Controls.Add(this.label14);
            this.groupBox5.Controls.Add(this.txtTel3);
            this.groupBox5.Controls.Add(this.label3);
            this.groupBox5.Controls.Add(this.txtEmail);
            this.groupBox5.Controls.Add(this.label5);
            this.groupBox5.Controls.Add(this.txtAddress);
            this.groupBox5.Controls.Add(this.label13);
            this.groupBox5.Controls.Add(this.txtTel2);
            this.groupBox5.Controls.Add(this.label12);
            this.groupBox5.Controls.Add(this.label11);
            this.groupBox5.Controls.Add(this.txtSpouseNo);
            this.groupBox5.Controls.Add(this.label10);
            this.groupBox5.Controls.Add(this.txtSpouseName);
            this.groupBox5.Location = new System.Drawing.Point(363, 9);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(233, 276);
            this.groupBox5.TabIndex = 0;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Contacts";
            this.txtTel1.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTel1.Location = new System.Drawing.Point(84, 93);
            this.txtTel1.MaxLength = 100;
            this.txtTel1.Name = "txtTel1";
            this.txtTel1.Size = new System.Drawing.Size(135, 21);
            this.txtTel1.TabIndex = 1;
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label14.Location = new System.Drawing.Point(8, 158);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(66, 13);
            this.label14.TabIndex = 294;
            this.label14.Text = "Telephone 3";
            this.txtTel3.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTel3.Location = new System.Drawing.Point(85, 155);
            this.txtTel3.MaxLength = 100;
            this.txtTel3.Name = "txtTel3";
            this.txtTel3.Size = new System.Drawing.Size(135, 21);
            this.txtTel3.TabIndex = 3;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(7, 188);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(31, 13);
            this.label3.TabIndex = 292;
            this.label3.Text = "Email";
            this.txtEmail.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtEmail.Location = new System.Drawing.Point(84, 185);
            this.txtEmail.MaxLength = 100;
            this.txtEmail.Name = "txtEmail";
            this.txtEmail.Size = new System.Drawing.Size(135, 21);
            this.txtEmail.TabIndex = 4;
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(6, 22);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(46, 13);
            this.label5.TabIndex = 290;
            this.label5.Text = "Address";
            this.txtAddress.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAddress.Location = new System.Drawing.Point(84, 22);
            this.txtAddress.MaxLength = 100;
            this.txtAddress.Multiline = true;
            this.txtAddress.Name = "txtAddress";
            this.txtAddress.Size = new System.Drawing.Size(135, 61);
            this.txtAddress.TabIndex = 0;
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.Location = new System.Drawing.Point(7, 127);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(66, 13);
            this.label13.TabIndex = 288;
            this.label13.Text = "Telephone 2";
            this.txtTel2.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTel2.Location = new System.Drawing.Point(84, 124);
            this.txtTel2.MaxLength = 100;
            this.txtTel2.Name = "txtTel2";
            this.txtTel2.Size = new System.Drawing.Size(135, 21);
            this.txtTel2.TabIndex = 2;
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.Location = new System.Drawing.Point(7, 96);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(66, 13);
            this.label12.TabIndex = 286;
            this.label12.Text = "Telephone 1";
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label11.Location = new System.Drawing.Point(7, 246);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(58, 13);
            this.label11.TabIndex = 284;
            this.label11.Text = "Spouse No";
            this.txtSpouseNo.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSpouseNo.Location = new System.Drawing.Point(84, 243);
            this.txtSpouseNo.MaxLength = 100;
            this.txtSpouseNo.Name = "txtSpouseNo";
            this.txtSpouseNo.Size = new System.Drawing.Size(135, 21);
            this.txtSpouseNo.TabIndex = 5;
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.Location = new System.Drawing.Point(7, 215);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(72, 13);
            this.label10.TabIndex = 282;
            this.label10.Text = "Spouse Name";
            this.txtSpouseName.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSpouseName.Location = new System.Drawing.Point(84, 212);
            this.txtSpouseName.MaxLength = 100;
            this.txtSpouseName.Name = "txtSpouseName";
            this.txtSpouseName.Size = new System.Drawing.Size(135, 21);
            this.txtSpouseName.TabIndex = 5;
            this.groupBox3.Controls.Add(this.txtRemarks);
            this.groupBox3.Location = new System.Drawing.Point(364, 287);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(233, 91);
            this.groupBox3.TabIndex = 239;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Remarks";
            this.txtRemarks.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtRemarks.Location = new System.Drawing.Point(6, 21);
            this.txtRemarks.MaxLength = 100;
            this.txtRemarks.Multiline = true;
            this.txtRemarks.Name = "txtRemarks";
            this.txtRemarks.Size = new System.Drawing.Size(216, 60);
            this.txtRemarks.TabIndex = 0;
            this.groupBox4.Controls.Add(this.drpOwnerID);
            this.groupBox4.Controls.Add(this.drpEmpID);
            this.groupBox4.Controls.Add(this.btnTakeaPic);
            this.groupBox4.Controls.Add(this.txtOwnerName);
            this.groupBox4.Controls.Add(this.label21);
            this.groupBox4.Controls.Add(this.txtDriverName);
            this.groupBox4.Controls.Add(this.srcPriority);
            this.groupBox4.Controls.Add(this.label17);
            this.groupBox4.Controls.Add(this.chkEngageDate);
            this.groupBox4.Controls.Add(this.txtGuideLicense);
            this.groupBox4.Controls.Add(this.label7);
            this.groupBox4.Controls.Add(this.label2);
            this.groupBox4.Controls.Add(this.txtCode);
            this.groupBox4.Controls.Add(this.label1);
            this.groupBox4.Controls.Add(this.gbImage);
            this.groupBox4.Controls.Add(this.chkIsEmp);
            this.groupBox4.Controls.Add(this.dtpDateDisc);
            this.groupBox4.Controls.Add(this.dtpDateEngage);
            this.groupBox4.Controls.Add(this.lblDischarge);
            this.groupBox4.Controls.Add(this.label4);
            this.groupBox4.Controls.Add(this.txtLicense);
            this.groupBox4.Controls.Add(this.label6);
            this.groupBox4.Controls.Add(this.label8);
            this.groupBox4.Controls.Add(this.txtNIC);
            this.groupBox4.Controls.Add(this.label9);
            this.groupBox4.Location = new System.Drawing.Point(9, 9);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(348, 372);
            this.groupBox4.TabIndex = 0;
            this.groupBox4.TabStop = false;
            this.drpOwnerID.BackColor = System.Drawing.Color.Transparent;
            this.drpOwnerID.DataSource = null;
            this.drpOwnerID.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpOwnerID.Location = new System.Drawing.Point(73, 125);
            this.drpOwnerID.Name = "drpOwnerID";
            this.drpOwnerID.SelectedText = "";
            this.drpOwnerID.SelectedValue = "";
            this.drpOwnerID.Size = new System.Drawing.Size(122, 20);
            this.drpOwnerID.TabIndex = 3;
            this.drpOwnerID.Click_Open += new System.EventHandler(this.drpOwnerID_Click_Open);
            this.drpEmpID.BackColor = System.Drawing.Color.Transparent;
            this.drpEmpID.DataSource = null;
            this.drpEmpID.Enabled = false;
            this.drpEmpID.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpEmpID.Location = new System.Drawing.Point(6, 69);
            this.drpEmpID.Name = "drpEmpID";
            this.drpEmpID.SelectedText = "";
            this.drpEmpID.SelectedValue = "";
            this.drpEmpID.Size = new System.Drawing.Size(189, 20);
            this.drpEmpID.TabIndex = 1;
            this.drpEmpID.Click_Open += new System.EventHandler(this.drpEmpID_Click_Open);
            this.drpEmpID.Selected_TextChanged += new System.EventHandler(this.drpEmpID_Selected_TextChanged);
            this.btnTakeaPic.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTakeaPic.Location = new System.Drawing.Point(6, 150);
            this.btnTakeaPic.Name = "btnTakeaPic";
            this.btnTakeaPic.Size = new System.Drawing.Size(81, 21);
            this.btnTakeaPic.TabIndex = 4;
            this.btnTakeaPic.Text = "Take a Pic";
            this.btnTakeaPic.UseVisualStyleBackColor = true;
            this.btnTakeaPic.Visible = false;
            this.txtOwnerName.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtOwnerName.Location = new System.Drawing.Point(122, 171);
            this.txtOwnerName.MaxLength = 100;
            this.txtOwnerName.Name = "txtOwnerName";
            this.txtOwnerName.Size = new System.Drawing.Size(203, 21);
            this.txtOwnerName.TabIndex = 5;
            this.txtOwnerName.TextChanged += new System.EventHandler(this.txtOwnerName_TextChanged);
            this.txtOwnerName.Leave += new System.EventHandler(this.txtOwnerName_Leave);
            this.label21.AutoSize = true;
            this.label21.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label21.Location = new System.Drawing.Point(9, 129);
            this.label21.Name = "label21";
            this.label21.Size = new System.Drawing.Size(52, 13);
            this.label21.TabIndex = 313;
            this.label21.Text = "Company";
            this.txtDriverName.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDriverName.Location = new System.Drawing.Point(122, 201);
            this.txtDriverName.MaxLength = 100;
            this.txtDriverName.Name = "txtDriverName";
            this.txtDriverName.Size = new System.Drawing.Size(203, 21);
            this.txtDriverName.TabIndex = 6;
            this.txtDriverName.TextChanged += new System.EventHandler(this.txtDriverName_TextChanged);
            this.txtDriverName.Leave += new System.EventHandler(this.txtDriverName_Leave);
            this.srcPriority.BackColor = System.Drawing.Color.White;
            this.srcPriority.BottomMargin = 2;
            this.srcPriority.HoverColor = System.Drawing.Color.Yellow;
            this.srcPriority.LeftMargin = 2;
            this.srcPriority.Location = new System.Drawing.Point(48, 12);
            this.srcPriority.Name = "srcPriority";
            this.srcPriority.OutlineColor = System.Drawing.Color.DarkGray;
            this.srcPriority.OutlineThickness = 1;
            this.srcPriority.RightMargin = 2;
            this.srcPriority.SelectedColor = System.Drawing.Color.RoyalBlue;
            this.srcPriority.SelectedStar = 0;
            this.srcPriority.Size = new System.Drawing.Size(149, 18);
            this.srcPriority.StarCount = 7;
            this.srcPriority.StarSpacing = 8;
            this.srcPriority.TabIndex = 0;
            this.srcPriority.Text = "starRatingControl1";
            this.srcPriority.TopMargin = 2;
            this.label17.AutoSize = true;
            this.label17.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label17.Location = new System.Drawing.Point(10, 15);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(30, 13);
            this.label17.TabIndex = 0;
            this.label17.Text = "Rate";
            this.chkEngageDate.AutoSize = true;
            this.chkEngageDate.Location = new System.Drawing.Point(124, 314);
            this.chkEngageDate.Name = "chkEngageDate";
            this.chkEngageDate.Size = new System.Drawing.Size(15, 14);
            this.chkEngageDate.TabIndex = 309;
            this.chkEngageDate.UseVisualStyleBackColor = true;
            this.chkEngageDate.CheckedChanged += new System.EventHandler(this.chkEngageDate_CheckedChanged);
            this.txtGuideLicense.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtGuideLicense.Location = new System.Drawing.Point(122, 284);
            this.txtGuideLicense.MaxLength = 100;
            this.txtGuideLicense.Name = "txtGuideLicense";
            this.txtGuideLicense.Size = new System.Drawing.Size(205, 21);
            this.txtGuideLicense.TabIndex = 9;
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(8, 287);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(88, 13);
            this.label7.TabIndex = 307;
            this.label7.Text = "Guide License No";
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(11, 101);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(64, 13);
            this.label2.TabIndex = 306;
            this.label2.Text = "Driver Code";
            this.txtCode.BackColor = System.Drawing.Color.LightYellow;
            this.txtCode.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCode.Location = new System.Drawing.Point(75, 98);
            this.txtCode.MaxLength = 10;
            this.txtCode.Name = "txtCode";
            this.txtCode.Size = new System.Drawing.Size(118, 21);
            this.txtCode.TabIndex = 2;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(8, 174);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(69, 13);
            this.label1.TabIndex = 304;
            this.label1.Text = "Owner Name";
            this.gbImage.BackColor = System.Drawing.Color.Transparent;
            this.gbImage.Controls.Add(this.lblImage);
            this.gbImage.Controls.Add(this.btnClearLogo);
            this.gbImage.Controls.Add(this.btnUploadLogo);
            this.gbImage.Controls.Add(this.pbImage);
            this.gbImage.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbImage.Location = new System.Drawing.Point(199, 5);
            this.gbImage.Name = "gbImage";
            this.gbImage.Size = new System.Drawing.Size(141, 162);
            this.gbImage.TabIndex = 302;
            this.gbImage.TabStop = false;
            this.lblImage.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblImage.Location = new System.Drawing.Point(15, 20);
            this.lblImage.Name = "lblImage";
            this.lblImage.Size = new System.Drawing.Size(109, 98);
            this.lblImage.TabIndex = 242;
            this.lblImage.Text = "Upload Driver Image";
            this.lblImage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClearLogo.BackColor = System.Drawing.SystemColors.Control;
            this.btnClearLogo.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnClearLogo.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClearLogo.Location = new System.Drawing.Point(70, 136);
            this.btnClearLogo.Name = "btnClearLogo";
            this.btnClearLogo.Size = new System.Drawing.Size(59, 21);
            this.btnClearLogo.TabIndex = 1;
            this.btnClearLogo.Text = "Clear";
            this.btnClearLogo.UseVisualStyleBackColor = false;
            this.btnClearLogo.Click += new System.EventHandler(this.btnClearLogo_Click);
            this.btnUploadLogo.BackColor = System.Drawing.SystemColors.Control;
            this.btnUploadLogo.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnUploadLogo.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUploadLogo.Location = new System.Drawing.Point(8, 136);
            this.btnUploadLogo.Name = "btnUploadLogo";
            this.btnUploadLogo.Size = new System.Drawing.Size(59, 21);
            this.btnUploadLogo.TabIndex = 0;
            this.btnUploadLogo.Text = "Upload";
            this.btnUploadLogo.UseVisualStyleBackColor = false;
            this.btnUploadLogo.Click += new System.EventHandler(this.btnUploadLogo_Click);
            this.pbImage.BackColor = System.Drawing.Color.Transparent;
            this.pbImage.Location = new System.Drawing.Point(6, 11);
            this.pbImage.Name = "pbImage";
            this.pbImage.Size = new System.Drawing.Size(127, 118);
            this.pbImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbImage.TabIndex = 3;
            this.pbImage.TabStop = false;
            this.chkIsEmp.AutoSize = true;
            this.chkIsEmp.Location = new System.Drawing.Point(9, 46);
            this.chkIsEmp.Name = "chkIsEmp";
            this.chkIsEmp.Size = new System.Drawing.Size(130, 17);
            this.chkIsEmp.TabIndex = 300;
            this.chkIsEmp.Text = "Existing Employee";
            this.chkIsEmp.UseVisualStyleBackColor = true;
            this.chkIsEmp.CheckedChanged += new System.EventHandler(this.chkIsEmp_CheckedChanged);
            this.dtpDateDisc.Location = new System.Drawing.Point(122, 340);
            this.dtpDateDisc.Name = "dtpDateDisc";
            this.dtpDateDisc.Size = new System.Drawing.Size(205, 21);
            this.dtpDateDisc.TabIndex = 11;
            this.dtpDateEngage.Location = new System.Drawing.Point(144, 311);
            this.dtpDateEngage.Name = "dtpDateEngage";
            this.dtpDateEngage.Size = new System.Drawing.Size(183, 21);
            this.dtpDateEngage.TabIndex = 10;
            this.dtpDateEngage.Value = new System.DateTime(2012, 4, 30, 12, 26, 15, 0);
            this.dtpDateEngage.Visible = false;
            this.lblDischarge.AutoSize = true;
            this.lblDischarge.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDischarge.Location = new System.Drawing.Point(8, 343);
            this.lblDischarge.Name = "lblDischarge";
            this.lblDischarge.Size = new System.Drawing.Size(93, 13);
            this.lblDischarge.TabIndex = 291;
            this.lblDischarge.Text = "Date of Discharge";
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(8, 315);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(82, 13);
            this.label4.TabIndex = 290;
            this.label4.Text = "Date of Engage";
            this.txtLicense.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtLicense.Location = new System.Drawing.Point(122, 257);
            this.txtLicense.MaxLength = 100;
            this.txtLicense.Name = "txtLicense";
            this.txtLicense.Size = new System.Drawing.Size(205, 21);
            this.txtLicense.TabIndex = 8;
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(8, 260);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(94, 13);
            this.label6.TabIndex = 288;
            this.label6.Text = "Driving License No";
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(8, 231);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(41, 13);
            this.label8.TabIndex = 282;
            this.label8.Text = "NIC No";
            this.txtNIC.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNIC.Location = new System.Drawing.Point(122, 230);
            this.txtNIC.MaxLength = 100;
            this.txtNIC.Name = "txtNIC";
            this.txtNIC.Size = new System.Drawing.Size(205, 21);
            this.txtNIC.TabIndex = 7;
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(8, 204);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(66, 13);
            this.label9.TabIndex = 280;
            this.label9.Text = "Driver Name";
            this.tpLanguages.BackColor = System.Drawing.Color.Transparent;
            this.tpLanguages.Controls.Add(this.grdLang);
            this.tpLanguages.Location = new System.Drawing.Point(4, 25);
            this.tpLanguages.Name = "tpLanguages";
            this.tpLanguages.Padding = new System.Windows.Forms.Padding(3);
            this.tpLanguages.Size = new System.Drawing.Size(657, 384);
            this.tpLanguages.TabIndex = 2;
            this.tpLanguages.Text = "Languages";
            this.grdLang.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.grdLang.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.grdLang.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdLang.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdLang.Cursor = System.Windows.Forms.Cursors.Default;
            this.grdLang.Location = new System.Drawing.Point(3, 4);
            this.grdLang.Name = "grdLang";
            this.grdLang.Size = new System.Drawing.Size(600, 378);
            this.grdLang.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdLang.Styles"));
            this.grdLang.TabIndex = 9;
            this.tpVehicle.BackColor = System.Drawing.Color.Transparent;
            this.tpVehicle.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tpVehicle.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tpVehicle.Controls.Add(this.groupBox9);
            this.tpVehicle.Controls.Add(this.groupBox2);
            this.tpVehicle.Controls.Add(this.groupBox8);
            this.tpVehicle.Controls.Add(this.groupBox7);
            this.tpVehicle.Controls.Add(this.groupBox6);
            this.tpVehicle.Controls.Add(this.groupBox1);
            this.tpVehicle.Location = new System.Drawing.Point(4, 25);
            this.tpVehicle.Name = "tpVehicle";
            this.tpVehicle.Padding = new System.Windows.Forms.Padding(3);
            this.tpVehicle.Size = new System.Drawing.Size(657, 384);
            this.tpVehicle.TabIndex = 3;
            this.tpVehicle.Text = "Vehicle Details";
            this.groupBox9.Controls.Add(this.txtLeasePayment);
            this.groupBox9.Controls.Add(this.label32);
            this.groupBox9.Controls.Add(this.label33);
            this.groupBox9.Controls.Add(this.txtInsurance);
            this.groupBox9.Location = new System.Drawing.Point(351, 106);
            this.groupBox9.Name = "groupBox9";
            this.groupBox9.Size = new System.Drawing.Size(300, 108);
            this.groupBox9.TabIndex = 313;
            this.groupBox9.TabStop = false;
            this.groupBox9.Text = "Payment Details";
            this.txtLeasePayment.BackColor = System.Drawing.SystemColors.Window;
            this.txtLeasePayment.Location = new System.Drawing.Point(139, 61);
            this.txtLeasePayment.Name = "txtLeasePayment";
            this.txtLeasePayment.Size = new System.Drawing.Size(145, 21);
            this.txtLeasePayment.TabIndex = 0;
            this.label32.AutoSize = true;
            this.label32.Location = new System.Drawing.Point(11, 64);
            this.label32.Name = "label32";
            this.label32.Size = new System.Drawing.Size(123, 13);
            this.label32.TabIndex = 312;
            this.label32.Text = "Lease Payment (lkr)";
            this.label33.AutoSize = true;
            this.label33.Location = new System.Drawing.Point(11, 29);
            this.label33.Name = "label33";
            this.label33.Size = new System.Drawing.Size(93, 13);
            this.label33.TabIndex = 310;
            this.label33.Text = "Insurance (lkr)";
            this.txtInsurance.BackColor = System.Drawing.SystemColors.Window;
            this.txtInsurance.Location = new System.Drawing.Point(139, 26);
            this.txtInsurance.Name = "txtInsurance";
            this.txtInsurance.Size = new System.Drawing.Size(145, 21);
            this.txtInsurance.TabIndex = 0;
            this.groupBox2.Controls.Add(this.drpBrand);
            this.groupBox2.Controls.Add(this.drpCountry);
            this.groupBox2.Controls.Add(this.label29);
            this.groupBox2.Controls.Add(this.label26);
            this.groupBox2.Location = new System.Drawing.Point(351, 6);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(300, 97);
            this.groupBox2.TabIndex = 312;
            this.groupBox2.TabStop = false;
            this.drpBrand.BackColor = System.Drawing.Color.Transparent;
            this.drpBrand.DataSource = null;
            this.drpBrand.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpBrand.Location = new System.Drawing.Point(77, 18);
            this.drpBrand.Name = "drpBrand";
            this.drpBrand.SelectedText = "";
            this.drpBrand.SelectedValue = "";
            this.drpBrand.Size = new System.Drawing.Size(192, 20);
            this.drpBrand.TabIndex = 0;
            this.drpBrand.Click_Open += new System.EventHandler(this.drpBrand_Click_Open);
            this.drpCountry.BackColor = System.Drawing.Color.Transparent;
            this.drpCountry.DataSource = null;
            this.drpCountry.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpCountry.Location = new System.Drawing.Point(77, 47);
            this.drpCountry.Name = "drpCountry";
            this.drpCountry.SelectedText = "";
            this.drpCountry.SelectedValue = "";
            this.drpCountry.Size = new System.Drawing.Size(192, 20);
            this.drpCountry.TabIndex = 1;
            this.drpCountry.Click_Open += new System.EventHandler(this.drpCountry_Click_Open);
            this.label29.AutoSize = true;
            this.label29.Location = new System.Drawing.Point(11, 51);
            this.label29.Name = "label29";
            this.label29.Size = new System.Drawing.Size(53, 13);
            this.label29.TabIndex = 312;
            this.label29.Text = "Country";
            this.label26.AutoSize = true;
            this.label26.Location = new System.Drawing.Point(11, 21);
            this.label26.Name = "label26";
            this.label26.Size = new System.Drawing.Size(41, 13);
            this.label26.TabIndex = 310;
            this.label26.Text = "Brand";
            this.groupBox8.Controls.Add(this.drpTypeID);
            this.groupBox8.Controls.Add(this.txtModelNo);
            this.groupBox8.Controls.Add(this.label23);
            this.groupBox8.Controls.Add(this.txtModel);
            this.groupBox8.Controls.Add(this.label28);
            this.groupBox8.Controls.Add(this.label24);
            this.groupBox8.Location = new System.Drawing.Point(5, 6);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new System.Drawing.Size(332, 97);
            this.groupBox8.TabIndex = 242;
            this.groupBox8.TabStop = false;
            this.drpTypeID.BackColor = System.Drawing.Color.Transparent;
            this.drpTypeID.DataSource = null;
            this.drpTypeID.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpTypeID.Location = new System.Drawing.Point(101, 12);
            this.drpTypeID.Name = "drpTypeID";
            this.drpTypeID.SelectedText = "";
            this.drpTypeID.SelectedValue = "";
            this.drpTypeID.Size = new System.Drawing.Size(194, 20);
            this.drpTypeID.TabIndex = 0;
            this.drpTypeID.Click_Open += new System.EventHandler(this.drpTypeID_Click_Open);
            this.txtModelNo.BackColor = System.Drawing.SystemColors.Window;
            this.txtModelNo.Location = new System.Drawing.Point(101, 67);
            this.txtModelNo.Name = "txtModelNo";
            this.txtModelNo.Size = new System.Drawing.Size(225, 21);
            this.txtModelNo.TabIndex = 2;
            this.label23.AutoSize = true;
            this.label23.Location = new System.Drawing.Point(6, 68);
            this.label23.Name = "label23";
            this.label23.Size = new System.Drawing.Size(59, 13);
            this.label23.TabIndex = 321;
            this.label23.Text = "Model No";
            this.txtModel.BackColor = System.Drawing.SystemColors.Window;
            this.txtModel.Location = new System.Drawing.Point(101, 41);
            this.txtModel.Name = "txtModel";
            this.txtModel.Size = new System.Drawing.Size(225, 21);
            this.txtModel.TabIndex = 1;
            this.label28.AutoSize = true;
            this.label28.Location = new System.Drawing.Point(6, 41);
            this.label28.Name = "label28";
            this.label28.Size = new System.Drawing.Size(40, 13);
            this.label28.TabIndex = 319;
            this.label28.Text = "Model";
            this.label24.AutoSize = true;
            this.label24.Location = new System.Drawing.Point(6, 12);
            this.label24.Name = "label24";
            this.label24.Size = new System.Drawing.Size(35, 13);
            this.label24.TabIndex = 313;
            this.label24.Text = "Type";
            this.groupBox7.Controls.Add(this.txtVehiRemarks);
            this.groupBox7.Location = new System.Drawing.Point(351, 220);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(300, 153);
            this.groupBox7.TabIndex = 240;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "Remarks";
            this.txtVehiRemarks.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtVehiRemarks.Location = new System.Drawing.Point(9, 18);
            this.txtVehiRemarks.MaxLength = 100;
            this.txtVehiRemarks.Multiline = true;
            this.txtVehiRemarks.Name = "txtVehiRemarks";
            this.txtVehiRemarks.Size = new System.Drawing.Size(285, 121);
            this.txtVehiRemarks.TabIndex = 0;
            this.groupBox6.Controls.Add(this.txtCharg);
            this.groupBox6.Controls.Add(this.nudMaxPas);
            this.groupBox6.Controls.Add(this.label25);
            this.groupBox6.Controls.Add(this.label27);
            this.groupBox6.Controls.Add(this.chkManuYear);
            this.groupBox6.Controls.Add(this.chkRegYear);
            this.groupBox6.Controls.Add(this.dtpManuYear);
            this.groupBox6.Controls.Add(this.dtpRegYear);
            this.groupBox6.Controls.Add(this.label19);
            this.groupBox6.Controls.Add(this.label20);
            this.groupBox6.Location = new System.Drawing.Point(6, 220);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(331, 153);
            this.groupBox6.TabIndex = 11;
            this.groupBox6.TabStop = false;
            this.txtCharg.BackColor = System.Drawing.SystemColors.Window;
            this.txtCharg.Location = new System.Drawing.Point(114, 53);
            this.txtCharg.Name = "txtCharg";
            this.txtCharg.Size = new System.Drawing.Size(184, 21);
            this.txtCharg.TabIndex = 1;
            this.txtCharg.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.nudMaxPas.Location = new System.Drawing.Point(114, 24);
            this.nudMaxPas.Name = "nudMaxPas";
            this.nudMaxPas.Size = new System.Drawing.Size(197, 21);
            this.nudMaxPas.TabIndex = 0;
            this.label25.AutoSize = true;
            this.label25.Location = new System.Drawing.Point(4, 55);
            this.label25.Name = "label25";
            this.label25.Size = new System.Drawing.Size(106, 13);
            this.label25.TabIndex = 316;
            this.label25.Text = "Chargers Per Km";
            this.label27.AutoSize = true;
            this.label27.Location = new System.Drawing.Point(4, 26);
            this.label27.Name = "label27";
            this.label27.Size = new System.Drawing.Size(99, 13);
            this.label27.TabIndex = 315;
            this.label27.Text = "Max Passengers";
            this.chkManuYear.AutoSize = true;
            this.chkManuYear.Location = new System.Drawing.Point(113, 120);
            this.chkManuYear.Name = "chkManuYear";
            this.chkManuYear.Size = new System.Drawing.Size(15, 14);
            this.chkManuYear.TabIndex = 314;
            this.chkManuYear.UseVisualStyleBackColor = true;
            this.chkManuYear.CheckedChanged += new System.EventHandler(this.chkManuYear_CheckedChanged);
            this.chkRegYear.AutoSize = true;
            this.chkRegYear.Location = new System.Drawing.Point(113, 86);
            this.chkRegYear.Name = "chkRegYear";
            this.chkRegYear.Size = new System.Drawing.Size(15, 14);
            this.chkRegYear.TabIndex = 313;
            this.chkRegYear.UseVisualStyleBackColor = true;
            this.chkRegYear.CheckedChanged += new System.EventHandler(this.chkRegYear_CheckedChanged);
            this.dtpManuYear.Location = new System.Drawing.Point(134, 118);
            this.dtpManuYear.Name = "dtpManuYear";
            this.dtpManuYear.Size = new System.Drawing.Size(162, 21);
            this.dtpManuYear.TabIndex = 3;
            this.dtpManuYear.Visible = false;
            this.dtpRegYear.Checked = false;
            this.dtpRegYear.Location = new System.Drawing.Point(134, 83);
            this.dtpRegYear.Name = "dtpRegYear";
            this.dtpRegYear.Size = new System.Drawing.Size(162, 21);
            this.dtpRegYear.TabIndex = 2;
            this.dtpRegYear.Visible = false;
            this.label19.AutoSize = true;
            this.label19.Location = new System.Drawing.Point(4, 123);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(88, 13);
            this.label19.TabIndex = 248;
            this.label19.Text = "Manufac. Year";
            this.label20.AutoSize = true;
            this.label20.Location = new System.Drawing.Point(4, 89);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(98, 13);
            this.label20.TabIndex = 247;
            this.label20.Text = "Registered Year";
            this.groupBox1.Controls.Add(this.drpCity);
            this.groupBox1.Controls.Add(this.txtInsNo);
            this.groupBox1.Controls.Add(this.label15);
            this.groupBox1.Controls.Add(this.txtVehNo);
            this.groupBox1.Controls.Add(this.label18);
            this.groupBox1.Controls.Add(this.label16);
            this.groupBox1.Location = new System.Drawing.Point(6, 106);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(331, 108);
            this.groupBox1.TabIndex = 4;
            this.groupBox1.TabStop = false;
            this.drpCity.BackColor = System.Drawing.Color.Transparent;
            this.drpCity.DataSource = null;
            this.drpCity.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpCity.Location = new System.Drawing.Point(98, 69);
            this.drpCity.Name = "drpCity";
            this.drpCity.SelectedText = "";
            this.drpCity.SelectedValue = "";
            this.drpCity.Size = new System.Drawing.Size(192, 20);
            this.drpCity.TabIndex = 2;
            this.drpCity.Click_Open += new System.EventHandler(this.drpCity_Click_Open);
            this.txtInsNo.BackColor = System.Drawing.SystemColors.Window;
            this.txtInsNo.Location = new System.Drawing.Point(98, 43);
            this.txtInsNo.Name = "txtInsNo";
            this.txtInsNo.Size = new System.Drawing.Size(192, 21);
            this.txtInsNo.TabIndex = 1;
            this.label15.AutoSize = true;
            this.label15.Location = new System.Drawing.Point(5, 46);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(83, 13);
            this.label15.TabIndex = 7;
            this.label15.Text = "Insurance No";
            this.txtVehNo.BackColor = System.Drawing.SystemColors.Window;
            this.txtVehNo.Location = new System.Drawing.Point(98, 16);
            this.txtVehNo.Name = "txtVehNo";
            this.txtVehNo.Size = new System.Drawing.Size(192, 21);
            this.txtVehNo.TabIndex = 0;
            this.label18.AutoSize = true;
            this.label18.Location = new System.Drawing.Point(5, 73);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(54, 13);
            this.label18.TabIndex = 310;
            this.label18.Text = "Location";
            this.label16.AutoSize = true;
            this.label16.Location = new System.Drawing.Point(5, 19);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(67, 13);
            this.label16.TabIndex = 4;
            this.label16.Text = "Vehicle No";
            this.tpAccessCat.BackColor = System.Drawing.Color.Transparent;
            this.tpAccessCat.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tpAccessCat.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tpAccessCat.Controls.Add(this.grdACC);
            this.tpAccessCat.Location = new System.Drawing.Point(4, 25);
            this.tpAccessCat.Name = "tpAccessCat";
            this.tpAccessCat.Padding = new System.Windows.Forms.Padding(3);
            this.tpAccessCat.Size = new System.Drawing.Size(657, 384);
            this.tpAccessCat.TabIndex = 4;
            this.tpAccessCat.Text = "Access Categories";
            this.grdACC.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.grdACC.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.grdACC.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdACC.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdACC.Cursor = System.Windows.Forms.Cursors.Default;
            this.grdACC.Location = new System.Drawing.Point(3, 3);
            this.grdACC.Name = "grdACC";
            this.grdACC.Size = new System.Drawing.Size(648, 381);
            this.grdACC.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdACC.Styles"));
            this.grdACC.TabIndex = 8;
            this.tpAddPhotos.BackColor = System.Drawing.Color.Transparent;
            this.tpAddPhotos.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tpAddPhotos.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tpAddPhotos.Controls.Add(this.grdPhoto);
            this.tpAddPhotos.Location = new System.Drawing.Point(4, 25);
            this.tpAddPhotos.Name = "tpAddPhotos";
            this.tpAddPhotos.Padding = new System.Windows.Forms.Padding(3);
            this.tpAddPhotos.Size = new System.Drawing.Size(657, 384);
            this.tpAddPhotos.TabIndex = 5;
            this.tpAddPhotos.Text = "Add Photos";
            this.grdPhoto.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.grdPhoto.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.grdPhoto.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdPhoto.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdPhoto.Cursor = System.Windows.Forms.Cursors.Default;
            this.grdPhoto.Location = new System.Drawing.Point(3, 3);
            this.grdPhoto.Name = "grdPhoto";
            this.grdPhoto.Size = new System.Drawing.Size(648, 381);
            this.grdPhoto.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdPhoto.Styles"));
            this.grdPhoto.TabIndex = 7;
            this.grdPhoto.RowColChange += new System.EventHandler(this.grdPhoto_RowColChange);
            this.grdPhoto.CellButtonClick += new C1.Win.C1FlexGrid.RowColEventHandler(this.grdPhoto_CellButtonClick);
            this.grdPhoto.KeyDown += new System.Windows.Forms.KeyEventHandler(this.grdPhoto_KeyDown);
            this.tpViewPhotos.BackColor = System.Drawing.Color.Transparent;
            this.tpViewPhotos.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tpViewPhotos.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tpViewPhotos.Controls.Add(this.pbMultiPhotos);
            this.tpViewPhotos.Controls.Add(this.tvPhotoDesc);
            this.tpViewPhotos.Location = new System.Drawing.Point(4, 25);
            this.tpViewPhotos.Name = "tpViewPhotos";
            this.tpViewPhotos.Padding = new System.Windows.Forms.Padding(3);
            this.tpViewPhotos.Size = new System.Drawing.Size(657, 384);
            this.tpViewPhotos.TabIndex = 6;
            this.tpViewPhotos.Text = "View Photos";
            this.pbMultiPhotos.Location = new System.Drawing.Point(157, 6);
            this.pbMultiPhotos.Name = "pbMultiPhotos";
            this.pbMultiPhotos.Size = new System.Drawing.Size(494, 375);
            this.pbMultiPhotos.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbMultiPhotos.TabIndex = 5;
            this.pbMultiPhotos.TabStop = false;
            this.tvPhotoDesc.Location = new System.Drawing.Point(6, 6);
            this.tvPhotoDesc.Name = "tvPhotoDesc";
            this.tvPhotoDesc.Size = new System.Drawing.Size(145, 375);
            this.tvPhotoDesc.TabIndex = 4;
            this.tvPhotoDesc.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.tvPhotoDesc_AfterSelect);
            this.tpReference.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tpReference.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tpReference.Controls.Add(this.grdRef);
            this.tpReference.Location = new System.Drawing.Point(4, 25);
            this.tpReference.Name = "tpReference";
            this.tpReference.Padding = new System.Windows.Forms.Padding(3);
            this.tpReference.Size = new System.Drawing.Size(657, 384);
            this.tpReference.TabIndex = 1;
            this.tpReference.Text = "Reference";
            this.tpReference.UseVisualStyleBackColor = true;
            this.grdRef.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.grdRef.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.grdRef.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdRef.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdRef.Cursor = System.Windows.Forms.Cursors.Default;
            this.grdRef.Location = new System.Drawing.Point(6, 4);
            this.grdRef.Name = "grdRef";
            this.grdRef.Size = new System.Drawing.Size(645, 375);
            this.grdRef.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdRef.Styles"));
            this.grdRef.TabIndex = 2;
            this.tabPage1.Controls.Add(this.chkExSum);
            this.tabPage1.Controls.Add(this.btnEmail);
            this.tabPage1.Controls.Add(this.groupBox16);
            this.tabPage1.Controls.Add(this.groupBox15);
            this.tabPage1.Location = new System.Drawing.Point(4, 25);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(657, 384);
            this.tabPage1.TabIndex = 7;
            this.tabPage1.Text = "Email";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.chkExSum.AutoSize = true;
            this.chkExSum.Checked = true;
            this.chkExSum.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkExSum.Location = new System.Drawing.Point(444, 324);
            this.chkExSum.Name = "chkExSum";
            this.chkExSum.Size = new System.Drawing.Size(104, 17);
            this.chkExSum.TabIndex = 1;
            this.chkExSum.Text = "Attach Report";
            this.chkExSum.UseVisualStyleBackColor = true;
            this.btnEmail.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnEmail.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEmail.Location = new System.Drawing.Point(554, 321);
            this.btnEmail.Name = "btnEmail";
            this.btnEmail.Size = new System.Drawing.Size(87, 22);
            this.btnEmail.TabIndex = 2;
            this.btnEmail.Text = "&Email This";
            this.btnEmail.UseVisualStyleBackColor = true;
            this.btnEmail.Click += new System.EventHandler(this.btnEmail_Click);
            this.groupBox16.BackColor = System.Drawing.Color.Transparent;
            this.groupBox16.Controls.Add(this.rtbBody);
            this.groupBox16.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox16.Location = new System.Drawing.Point(14, 163);
            this.groupBox16.Name = "groupBox16";
            this.groupBox16.Size = new System.Drawing.Size(628, 141);
            this.groupBox16.TabIndex = 250;
            this.groupBox16.TabStop = false;
            this.groupBox16.Text = "Email Body";
            this.rtbBody.AccessibleRole = System.Windows.Forms.AccessibleRole.None;
            this.rtbBody.Location = new System.Drawing.Point(9, 19);
            this.rtbBody.Name = "rtbBody";
            this.rtbBody.Size = new System.Drawing.Size(608, 110);
            this.rtbBody.TabIndex = 0;
            this.rtbBody.Text = "";
            this.groupBox15.BackColor = System.Drawing.Color.Transparent;
            this.groupBox15.Controls.Add(this.txtCC);
            this.groupBox15.Controls.Add(this.label22);
            this.groupBox15.Controls.Add(this.btnEmailConts);
            this.groupBox15.Controls.Add(this.txtSubject);
            this.groupBox15.Controls.Add(this.txtTo);
            this.groupBox15.Controls.Add(this.label30);
            this.groupBox15.Controls.Add(this.label31);
            this.groupBox15.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox15.Location = new System.Drawing.Point(14, 42);
            this.groupBox15.Name = "groupBox15";
            this.groupBox15.Size = new System.Drawing.Size(627, 115);
            this.groupBox15.TabIndex = 0;
            this.groupBox15.TabStop = false;
            this.groupBox15.Text = "General Details";
            this.txtCC.Location = new System.Drawing.Point(68, 51);
            this.txtCC.Name = "txtCC";
            this.txtCC.Size = new System.Drawing.Size(549, 21);
            this.txtCC.TabIndex = 2;
            this.label22.AutoSize = true;
            this.label22.Location = new System.Drawing.Point(7, 54);
            this.label22.Name = "label22";
            this.label22.Size = new System.Drawing.Size(25, 13);
            this.label22.TabIndex = 8;
            this.label22.Text = "CC";
            this.btnEmailConts.BackColor = System.Drawing.SystemColors.Control;
            this.btnEmailConts.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnEmailConts.Location = new System.Drawing.Point(584, 22);
            this.btnEmailConts.Name = "btnEmailConts";
            this.btnEmailConts.Size = new System.Drawing.Size(33, 23);
            this.btnEmailConts.TabIndex = 1;
            this.btnEmailConts.Text = "...";
            this.btnEmailConts.UseVisualStyleBackColor = false;
            this.txtSubject.Location = new System.Drawing.Point(68, 77);
            this.txtSubject.Name = "txtSubject";
            this.txtSubject.Size = new System.Drawing.Size(549, 21);
            this.txtSubject.TabIndex = 5;
            this.txtTo.Location = new System.Drawing.Point(68, 24);
            this.txtTo.Name = "txtTo";
            this.txtTo.Size = new System.Drawing.Size(510, 21);
            this.txtTo.TabIndex = 0;
            this.label30.AutoSize = true;
            this.label30.Location = new System.Drawing.Point(7, 80);
            this.label30.Name = "label30";
            this.label30.Size = new System.Drawing.Size(50, 13);
            this.label30.TabIndex = 2;
            this.label30.Text = "Subject";
            this.label31.AutoSize = true;
            this.label31.Location = new System.Drawing.Point(7, 27);
            this.label31.Name = "label31";
            this.label31.Size = new System.Drawing.Size(21, 13);
            this.label31.TabIndex = 1;
            this.label31.Text = "To";
            this.chkActive.AutoSize = true;
            this.chkActive.BackColor = System.Drawing.Color.Transparent;
            this.chkActive.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkActive.Location = new System.Drawing.Point(288, 431);
            this.chkActive.Name = "chkActive";
            this.chkActive.Size = new System.Drawing.Size(56, 17);
            this.chkActive.TabIndex = 1;
            this.chkActive.Text = "Active";
            this.chkActive.UseVisualStyleBackColor = false;
            this.chkActive.Click += new System.EventHandler(this.chkActive_Click);
            this.btnCancel.BackColor = System.Drawing.SystemColors.Control;
            this.btnCancel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCancel.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Location = new System.Drawing.Point(534, 424);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(75, 29);
            this.btnCancel.TabIndex = 3;
            this.btnCancel.Text = "&Cancel";
            this.btnCancel.UseVisualStyleBackColor = false;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnOk.BackColor = System.Drawing.SystemColors.Control;
            this.btnOk.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnOk.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Location = new System.Drawing.Point(452, 424);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(75, 29);
            this.btnOk.TabIndex = 2;
            this.btnOk.Text = "&OK";
            this.btnOk.UseVisualStyleBackColor = false;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.comboBoxCameras.FormattingEnabled = true;
            this.comboBoxCameras.Location = new System.Drawing.Point(10, 427);
            this.comboBoxCameras.Name = "comboBoxCameras";
            this.comboBoxCameras.Size = new System.Drawing.Size(121, 21);
            this.comboBoxCameras.TabIndex = 0;
            this.comboBoxCameras.Visible = false;
            this.btnPrint.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPrint.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPrint.Image = global::Tourist_Management.Properties.Resources.search;
            this.btnPrint.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPrint.Location = new System.Drawing.Point(360, 424);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.Size = new System.Drawing.Size(76, 29);
            this.btnPrint.TabIndex = 3;
            this.btnPrint.Text = "&Preview";
            this.btnPrint.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPrint.UseVisualStyleBackColor = true;
            this.btnPrint.Click += new System.EventHandler(this.btnPrint_Click);
            this.errorProvider1.ContainerControl = this;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(680, 463);
            this.ControlBox = false;
            this.Controls.Add(this.btnPrint);
            this.Controls.Add(this.comboBoxCameras);
            this.Controls.Add(this.tcTransportation);
            this.Controls.Add(this.chkActive);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOk);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "frmTRDetails";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmTRDetails_Load);
            this.tcTransportation.ResumeLayout(false);
            this.tpDriver.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.gbImage.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbImage)).EndInit();
            this.tpLanguages.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdLang)).EndInit();
            this.tpVehicle.ResumeLayout(false);
            this.groupBox9.ResumeLayout(false);
            this.groupBox9.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox8.ResumeLayout(false);
            this.groupBox8.PerformLayout();
            this.groupBox7.ResumeLayout(false);
            this.groupBox7.PerformLayout();
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nudMaxPas)).EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.tpAccessCat.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdACC)).EndInit();
            this.tpAddPhotos.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdPhoto)).EndInit();
            this.tpViewPhotos.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbMultiPhotos)).EndInit();
            this.tpReference.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdRef)).EndInit();
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.groupBox16.ResumeLayout(false);
            this.groupBox15.ResumeLayout(false);
            this.groupBox15.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.TabControl tcTransportation;
        private System.Windows.Forms.TabPage tpDriver;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox txtEmail;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox txtAddress;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.TextBox txtTel2;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.TextBox txtSpouseNo;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.TextBox txtSpouseName;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.TextBox txtRemarks;
        private System.Windows.Forms.GroupBox groupBox4;
        private DropDowns.DropSearch drpEmpID;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox txtCode;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.GroupBox gbImage;
        private System.Windows.Forms.Label lblImage;
        private System.Windows.Forms.Button btnClearLogo;
        private System.Windows.Forms.Button btnUploadLogo;
        private System.Windows.Forms.PictureBox pbImage;
        private System.Windows.Forms.CheckBox chkIsEmp;
        private System.Windows.Forms.DateTimePicker dtpDateDisc;
        private System.Windows.Forms.DateTimePicker dtpDateEngage;
        private System.Windows.Forms.Label lblDischarge;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox txtLicense;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox txtNIC;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.TabPage tpReference;
        private C1.Win.C1FlexGrid.C1FlexGrid grdRef;
        private System.Windows.Forms.CheckBox chkActive;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.TextBox txtGuideLicense;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.TextBox txtTel3;
        private System.Windows.Forms.CheckBox chkEngageDate;
        private System.Windows.Forms.TabPage tpLanguages;
        private C1.Win.C1FlexGrid.C1FlexGrid grdLang;
        private System.Windows.Forms.TabPage tpVehicle;
        private System.Windows.Forms.TabPage tpAccessCat;
        private System.Windows.Forms.TabPage tpAddPhotos;
        private System.Windows.Forms.TabPage tpViewPhotos;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.TextBox txtInsNo;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.TextBox txtVehNo;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.GroupBox groupBox6;
        private System.Windows.Forms.DateTimePicker dtpManuYear;
        private System.Windows.Forms.DateTimePicker dtpRegYear;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label20;
        private DropDowns.DropSearch drpCity;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.CheckBox chkManuYear;
        private System.Windows.Forms.CheckBox chkRegYear;
        private C1.Win.C1FlexGrid.C1FlexGrid grdACC;
        private C1.Win.C1FlexGrid.C1FlexGrid grdPhoto;
        private System.Windows.Forms.PictureBox pbMultiPhotos;
        private System.Windows.Forms.TreeView tvPhotoDesc;
        private System.Windows.Forms.TextBox txtCharg;
        private System.Windows.Forms.NumericUpDown nudMaxPas;
        private System.Windows.Forms.Label label25;
        private System.Windows.Forms.Label label27;
        private System.Windows.Forms.GroupBox groupBox7;
        private System.Windows.Forms.TextBox txtVehiRemarks;
        private System.Windows.Forms.GroupBox groupBox8;
        private DropDowns.DropSearch drpTypeID;
        private System.Windows.Forms.Label label24;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.TextBox txtTel1;
        private System.Windows.Forms.TextBox txtDriverName;
        public RatingControls.StarRatingControl srcPriority;
        private DropDowns.DropSearch drpOwnerID;
        private System.Windows.Forms.Label label21;
        private System.Windows.Forms.TextBox txtOwnerName;
        private  Tourist_Management.User_Controls.ComboBox comboBoxCameras;
        private System.Windows.Forms.Button btnTakeaPic;
        private System.Windows.Forms.GroupBox groupBox2;
        private DropDowns.DropSearch drpCountry;
        private System.Windows.Forms.Label label29;
        private DropDowns.DropSearch drpBrand;
        private System.Windows.Forms.Label label26;
        private System.Windows.Forms.TextBox txtModelNo;
        private System.Windows.Forms.Label label23;
        private System.Windows.Forms.TextBox txtModel;
        private System.Windows.Forms.Label label28;
        private System.Windows.Forms.Button btnPrint;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.CheckBox chkExSum;
        private System.Windows.Forms.Button btnEmail;
        private System.Windows.Forms.GroupBox groupBox16;
        private System.Windows.Forms.RichTextBox rtbBody;
        private System.Windows.Forms.GroupBox groupBox15;
        private System.Windows.Forms.TextBox txtCC;
        private System.Windows.Forms.Label label22;
        private System.Windows.Forms.Button btnEmailConts;
        private System.Windows.Forms.TextBox txtSubject;
        private System.Windows.Forms.TextBox txtTo;
        private System.Windows.Forms.Label label30;
        private System.Windows.Forms.Label label31;
        private System.Windows.Forms.ErrorProvider errorProvider1;
        private System.Windows.Forms.GroupBox groupBox9;
        private System.Windows.Forms.Label label32;
        private System.Windows.Forms.Label label33;
        private System.Windows.Forms.TextBox txtLeasePayment;
        private System.Windows.Forms.TextBox txtInsurance;
    }
}