namespace Tourist_Management.Master
{
    partial class frmVehicle
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmVehicle));
            this.tcVehicle = new System.Windows.Forms.TabControl();
            this.tpDetailView = new System.Windows.Forms.TabPage();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.drpTypeID = new DropDowns.DropSearch();
            this.drpStatusID = new DropDowns.DropSearch();
            this.drpDriverID = new DropDowns.DropSearch();
            this.drpCity = new DropDowns.DropSearch();
            this.label13 = new System.Windows.Forms.Label();
            this.dtpManudate = new System.Windows.Forms.DateTimePicker();
            this.dtpPurchDate = new System.Windows.Forms.DateTimePicker();
            this.label11 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.txtRemarks = new System.Windows.Forms.TextBox();
            this.label10 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.cmbCurrency = new  Tourist_Management.User_Controls.ComboBox();
            this.txtCharg = new System.Windows.Forms.TextBox();
            this.nudMaxDis = new System.Windows.Forms.NumericUpDown();
            this.nudMaxPas = new System.Windows.Forms.NumericUpDown();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.txtInsNo = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.txtVehNo = new System.Windows.Forms.TextBox();
            this.txtCode = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.tpAccCat = new System.Windows.Forms.TabPage();
            this.grdACC = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.tpAddPhotos = new System.Windows.Forms.TabPage();
            this.grdPhoto = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.tpPhotoView = new System.Windows.Forms.TabPage();
            this.pbMultiPhotos = new System.Windows.Forms.PictureBox();
            this.tvPhotoDesc = new System.Windows.Forms.TreeView();
            this.chkActive = new System.Windows.Forms.CheckBox();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.tcVehicle.SuspendLayout();
            this.tpDetailView.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nudMaxDis)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudMaxPas)).BeginInit();
            this.groupBox1.SuspendLayout();
            this.tpAccCat.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdACC)).BeginInit();
            this.tpAddPhotos.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdPhoto)).BeginInit();
            this.tpPhotoView.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbMultiPhotos)).BeginInit();
            this.SuspendLayout();
            this.tcVehicle.Controls.Add(this.tpDetailView);
            this.tcVehicle.Controls.Add(this.tpAccCat);
            this.tcVehicle.Controls.Add(this.tpAddPhotos);
            this.tcVehicle.Controls.Add(this.tpPhotoView);
            this.tcVehicle.Location = new System.Drawing.Point(2, 6);
            this.tcVehicle.Name = "tcVehicle";
            this.tcVehicle.SelectedIndex = 0;
            this.tcVehicle.Size = new System.Drawing.Size(565, 349);
            this.tcVehicle.TabIndex = 0;
            this.tpDetailView.Controls.Add(this.groupBox3);
            this.tpDetailView.Controls.Add(this.groupBox2);
            this.tpDetailView.Controls.Add(this.groupBox1);
            this.tpDetailView.Location = new System.Drawing.Point(4, 22);
            this.tpDetailView.Name = "tpDetailView";
            this.tpDetailView.Padding = new System.Windows.Forms.Padding(3);
            this.tpDetailView.Size = new System.Drawing.Size(557, 323);
            this.tpDetailView.TabIndex = 0;
            this.tpDetailView.Text = "Detail View";
            this.tpDetailView.UseVisualStyleBackColor = true;
            this.groupBox3.Controls.Add(this.drpCity);
            this.groupBox3.Controls.Add(this.drpDriverID);
            this.groupBox3.Controls.Add(this.drpStatusID);
            this.groupBox3.Controls.Add(this.drpTypeID);
            this.groupBox3.Controls.Add(this.label13);
            this.groupBox3.Controls.Add(this.dtpManudate);
            this.groupBox3.Controls.Add(this.dtpPurchDate);
            this.groupBox3.Controls.Add(this.label11);
            this.groupBox3.Controls.Add(this.label12);
            this.groupBox3.Controls.Add(this.txtRemarks);
            this.groupBox3.Controls.Add(this.label10);
            this.groupBox3.Controls.Add(this.label7);
            this.groupBox3.Controls.Add(this.label8);
            this.groupBox3.Controls.Add(this.label9);
            this.groupBox3.Location = new System.Drawing.Point(6, 126);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(539, 191);
            this.groupBox3.TabIndex = 9;
            this.groupBox3.TabStop = false;
            this.drpTypeID.BackColor = System.Drawing.Color.Transparent;
            this.drpTypeID.DataSource = null;
            this.drpTypeID.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpTypeID.FormName = "";
            this.drpTypeID.Location = new System.Drawing.Point(98, 19);
            this.drpTypeID.Name = "drpTypeID";
            this.drpTypeID.SelectedText = "";
            this.drpTypeID.SelectedValue = "";
            this.drpTypeID.Size = new System.Drawing.Size(194, 23);
            this.drpTypeID.TabIndex = 0;
            this.drpTypeID.Click_Open += new System.EventHandler(this.drpTypeID_Click_Open);
            this.drpStatusID.BackColor = System.Drawing.Color.Transparent;
            this.drpStatusID.DataSource = null;
            this.drpStatusID.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpStatusID.FormName = "";
            this.drpStatusID.Location = new System.Drawing.Point(98, 48);
            this.drpStatusID.Name = "drpStatusID";
            this.drpStatusID.SelectedText = "";
            this.drpStatusID.SelectedValue = "";
            this.drpStatusID.Size = new System.Drawing.Size(194, 23);
            this.drpStatusID.TabIndex = 1;
            this.drpStatusID.Click_Open += new System.EventHandler(this.drpStatusID_Click_Open);
            this.drpDriverID.BackColor = System.Drawing.Color.Transparent;
            this.drpDriverID.DataSource = null;
            this.drpDriverID.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpDriverID.FormName = "";
            this.drpDriverID.Location = new System.Drawing.Point(98, 77);
            this.drpDriverID.Name = "drpDriverID";
            this.drpDriverID.SelectedText = "";
            this.drpDriverID.SelectedValue = "";
            this.drpDriverID.Size = new System.Drawing.Size(194, 23);
            this.drpDriverID.TabIndex = 2;
            this.drpDriverID.Click_Open += new System.EventHandler(this.drpDriverID_Click_Open);
            this.drpCity.BackColor = System.Drawing.Color.Transparent;
            this.drpCity.DataSource = null;
            this.drpCity.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpCity.FormName = "";
            this.drpCity.Location = new System.Drawing.Point(357, 19);
            this.drpCity.Name = "drpCity";
            this.drpCity.SelectedText = "";
            this.drpCity.SelectedValue = "";
            this.drpCity.Size = new System.Drawing.Size(169, 23);
            this.drpCity.TabIndex = 5;
            this.drpCity.Click_Open += new System.EventHandler(this.drpCity_Click_Open);
            this.label13.AutoSize = true;
            this.label13.Location = new System.Drawing.Point(304, 24);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(48, 13);
            this.label13.TabIndex = 310;
            this.label13.Text = "Location";
            this.dtpManudate.Location = new System.Drawing.Point(98, 141);
            this.dtpManudate.Name = "dtpManudate";
            this.dtpManudate.Size = new System.Drawing.Size(192, 20);
            this.dtpManudate.TabIndex = 4;
            this.dtpPurchDate.Checked = false;
            this.dtpPurchDate.Location = new System.Drawing.Point(98, 112);
            this.dtpPurchDate.Name = "dtpPurchDate";
            this.dtpPurchDate.Size = new System.Drawing.Size(192, 20);
            this.dtpPurchDate.TabIndex = 3;
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(7, 146);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(78, 13);
            this.label11.TabIndex = 248;
            this.label11.Text = "Manufac. Date";
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(7, 118);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(78, 13);
            this.label12.TabIndex = 247;
            this.label12.Text = "Purchase Date";
            this.txtRemarks.Location = new System.Drawing.Point(316, 80);
            this.txtRemarks.Multiline = true;
            this.txtRemarks.Name = "txtRemarks";
            this.txtRemarks.Size = new System.Drawing.Size(215, 79);
            this.txtRemarks.TabIndex = 6;
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(391, 58);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(49, 13);
            this.label10.TabIndex = 245;
            this.label10.Text = "Remarks";
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(7, 80);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(35, 13);
            this.label7.TabIndex = 243;
            this.label7.Text = "Driver";
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(7, 52);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(37, 13);
            this.label8.TabIndex = 4;
            this.label8.Text = "Status";
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(7, 19);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(31, 13);
            this.label9.TabIndex = 3;
            this.label9.Text = "Type";
            this.groupBox2.Controls.Add(this.cmbCurrency);
            this.groupBox2.Controls.Add(this.txtCharg);
            this.groupBox2.Controls.Add(this.nudMaxDis);
            this.groupBox2.Controls.Add(this.nudMaxPas);
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.label6);
            this.groupBox2.Location = new System.Drawing.Point(278, 12);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(267, 108);
            this.groupBox2.TabIndex = 9;
            this.groupBox2.TabStop = false;
            this.cmbCurrency.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCurrency.FormattingEnabled = true;
            this.cmbCurrency.Location = new System.Drawing.Point(207, 72);
            this.cmbCurrency.Name = "cmbCurrency";
            this.cmbCurrency.Size = new System.Drawing.Size(52, 21);
            this.cmbCurrency.TabIndex = 3;
            this.txtCharg.BackColor = System.Drawing.Color.LightYellow;
            this.txtCharg.Location = new System.Drawing.Point(119, 72);
            this.txtCharg.Name = "txtCharg";
            this.txtCharg.Size = new System.Drawing.Size(83, 20);
            this.txtCharg.TabIndex = 2;
            this.nudMaxDis.Location = new System.Drawing.Point(119, 46);
            this.nudMaxDis.Name = "nudMaxDis";
            this.nudMaxDis.Size = new System.Drawing.Size(141, 20);
            this.nudMaxDis.TabIndex = 1;
            this.nudMaxPas.Location = new System.Drawing.Point(119, 17);
            this.nudMaxPas.Name = "nudMaxPas";
            this.nudMaxPas.Size = new System.Drawing.Size(141, 20);
            this.nudMaxPas.TabIndex = 0;
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(7, 73);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(86, 13);
            this.label4.TabIndex = 7;
            this.label4.Text = "Chargers Per Km";
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(7, 47);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(96, 13);
            this.label5.TabIndex = 4;
            this.label5.Text = "Max Distance (Km)";
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(7, 19);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(85, 13);
            this.label6.TabIndex = 3;
            this.label6.Text = "Max Passengers";
            this.groupBox1.Controls.Add(this.txtInsNo);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.txtVehNo);
            this.groupBox1.Controls.Add(this.txtCode);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Location = new System.Drawing.Point(6, 12);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(262, 108);
            this.groupBox1.TabIndex = 3;
            this.groupBox1.TabStop = false;
            this.txtInsNo.BackColor = System.Drawing.Color.LightYellow;
            this.txtInsNo.Location = new System.Drawing.Point(100, 69);
            this.txtInsNo.Name = "txtInsNo";
            this.txtInsNo.Size = new System.Drawing.Size(152, 20);
            this.txtInsNo.TabIndex = 2;
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(7, 72);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(71, 13);
            this.label3.TabIndex = 7;
            this.label3.Text = "Insurance No";
            this.txtVehNo.BackColor = System.Drawing.Color.LightYellow;
            this.txtVehNo.Location = new System.Drawing.Point(100, 42);
            this.txtVehNo.Name = "txtVehNo";
            this.txtVehNo.Size = new System.Drawing.Size(152, 20);
            this.txtVehNo.TabIndex = 1;
            this.txtCode.BackColor = System.Drawing.Color.LightYellow;
            this.txtCode.Location = new System.Drawing.Point(100, 16);
            this.txtCode.Name = "txtCode";
            this.txtCode.Size = new System.Drawing.Size(152, 20);
            this.txtCode.TabIndex = 0;
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(7, 45);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(59, 13);
            this.label2.TabIndex = 4;
            this.label2.Text = "Vehicle No";
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(7, 18);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(32, 13);
            this.label1.TabIndex = 3;
            this.label1.Text = "Code";
            this.tpAccCat.Controls.Add(this.grdACC);
            this.tpAccCat.Location = new System.Drawing.Point(4, 22);
            this.tpAccCat.Name = "tpAccCat";
            this.tpAccCat.Padding = new System.Windows.Forms.Padding(3);
            this.tpAccCat.Size = new System.Drawing.Size(557, 323);
            this.tpAccCat.TabIndex = 3;
            this.tpAccCat.Text = "Access Categories";
            this.tpAccCat.UseVisualStyleBackColor = true;
            this.grdACC.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdACC.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdACC.Cursor = System.Windows.Forms.Cursors.Default;
            this.grdACC.Location = new System.Drawing.Point(3, 3);
            this.grdACC.Name = "grdACC";
            this.grdACC.Size = new System.Drawing.Size(550, 314);
            this.grdACC.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdACC.Styles"));
            this.grdACC.TabIndex = 7;
            this.tpAddPhotos.Controls.Add(this.grdPhoto);
            this.tpAddPhotos.Location = new System.Drawing.Point(4, 22);
            this.tpAddPhotos.Name = "tpAddPhotos";
            this.tpAddPhotos.Padding = new System.Windows.Forms.Padding(3);
            this.tpAddPhotos.Size = new System.Drawing.Size(557, 323);
            this.tpAddPhotos.TabIndex = 1;
            this.tpAddPhotos.Text = "Add Photos";
            this.tpAddPhotos.UseVisualStyleBackColor = true;
            this.grdPhoto.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdPhoto.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdPhoto.Cursor = System.Windows.Forms.Cursors.Default;
            this.grdPhoto.Location = new System.Drawing.Point(3, 3);
            this.grdPhoto.Name = "grdPhoto";
            this.grdPhoto.Size = new System.Drawing.Size(550, 314);
            this.grdPhoto.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdPhoto.Styles"));
            this.grdPhoto.TabIndex = 6;
            this.grdPhoto.KeyDown += new System.Windows.Forms.KeyEventHandler(this.grdPhoto_KeyDown);
            this.grdPhoto.CellButtonClick += new C1.Win.C1FlexGrid.RowColEventHandler(this.grdPhoto_CellButtonClick);
            this.grdPhoto.RowColChange += new System.EventHandler(this.grdPhoto_RowColChange);
            this.tpPhotoView.Controls.Add(this.pbMultiPhotos);
            this.tpPhotoView.Controls.Add(this.tvPhotoDesc);
            this.tpPhotoView.Location = new System.Drawing.Point(4, 22);
            this.tpPhotoView.Name = "tpPhotoView";
            this.tpPhotoView.Padding = new System.Windows.Forms.Padding(3);
            this.tpPhotoView.Size = new System.Drawing.Size(557, 323);
            this.tpPhotoView.TabIndex = 2;
            this.tpPhotoView.Text = "View Photos";
            this.tpPhotoView.UseVisualStyleBackColor = true;
            this.pbMultiPhotos.Location = new System.Drawing.Point(158, 6);
            this.pbMultiPhotos.Name = "pbMultiPhotos";
            this.pbMultiPhotos.Size = new System.Drawing.Size(393, 311);
            this.pbMultiPhotos.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbMultiPhotos.TabIndex = 3;
            this.pbMultiPhotos.TabStop = false;
            this.tvPhotoDesc.Location = new System.Drawing.Point(3, 6);
            this.tvPhotoDesc.Name = "tvPhotoDesc";
            this.tvPhotoDesc.Size = new System.Drawing.Size(149, 311);
            this.tvPhotoDesc.TabIndex = 2;
            this.tvPhotoDesc.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.tvPhotoDesc_AfterSelect);
            this.chkActive.AutoSize = true;
            this.chkActive.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkActive.Location = new System.Drawing.Point(335, 374);
            this.chkActive.Name = "chkActive";
            this.chkActive.Size = new System.Drawing.Size(56, 17);
            this.chkActive.TabIndex = 232;
            this.chkActive.Text = "Active";
            this.chkActive.UseVisualStyleBackColor = true;
            this.chkActive.Click += new System.EventHandler(this.chkActive_Click);
            this.btnCancel.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Location = new System.Drawing.Point(488, 371);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(75, 23);
            this.btnCancel.TabIndex = 234;
            this.btnCancel.Text = "&Cancel";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnOk.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Location = new System.Drawing.Point(406, 371);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(75, 23);
            this.btnOk.TabIndex = 233;
            this.btnOk.Text = "&OK";
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(569, 406);
            this.Controls.Add(this.chkActive);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.tcVehicle);
            this.Name = "frmVehicle";
            this.Text = "Vehicle Details";
            this.Load += new System.EventHandler(this.frmVehicle_Load);
            this.tcVehicle.ResumeLayout(false);
            this.tpDetailView.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nudMaxDis)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudMaxPas)).EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.tpAccCat.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdACC)).EndInit();
            this.tpAddPhotos.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdPhoto)).EndInit();
            this.tpPhotoView.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbMultiPhotos)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.TabControl tcVehicle;
        private System.Windows.Forms.TabPage tpDetailView;
        private System.Windows.Forms.TabPage tpAddPhotos;
        private System.Windows.Forms.CheckBox chkActive;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.TextBox txtCode;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox txtVehNo;
        private System.Windows.Forms.TextBox txtInsNo;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.NumericUpDown nudMaxPas;
        private  Tourist_Management.User_Controls.ComboBox cmbCurrency;
        private System.Windows.Forms.TextBox txtCharg;
        private System.Windows.Forms.NumericUpDown nudMaxDis;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private DropDowns.DropSearch drpStatusID;
        private DropDowns.DropSearch drpTypeID;
        private DropDowns.DropSearch drpDriverID;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TextBox txtRemarks;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.TabPage tpPhotoView;
        private C1.Win.C1FlexGrid.C1FlexGrid grdPhoto;
        private System.Windows.Forms.PictureBox pbMultiPhotos;
        private System.Windows.Forms.TreeView tvPhotoDesc;
        private System.Windows.Forms.TabPage tpAccCat;
        private C1.Win.C1FlexGrid.C1FlexGrid grdACC;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.DateTimePicker dtpPurchDate;
        private System.Windows.Forms.DateTimePicker dtpManudate;
        private DropDowns.DropSearch drpCity;
        private System.Windows.Forms.Label label13;
    }
}