namespace Tourist_Management.Accounts
{
    partial class frmChartOfAccount
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.tc = new System.Windows.Forms.TabControl();
            this.tp1 = new System.Windows.Forms.TabPage();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.drpOtherAccType = new Tourist_Management.DropDowns.DropSearch();
            this.lblAccName = new System.Windows.Forms.Label();
            this.lblDescription = new System.Windows.Forms.Label();
            this.btnCancel1 = new System.Windows.Forms.Button();
            this.btnContinue = new System.Windows.Forms.Button();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.rdbOther = new System.Windows.Forms.RadioButton();
            this.rdbEquity = new System.Windows.Forms.RadioButton();
            this.rdbCCard = new System.Windows.Forms.RadioButton();
            this.rdbLoan = new System.Windows.Forms.RadioButton();
            this.rdbBank = new System.Windows.Forms.RadioButton();
            this.rdbFAsset = new System.Windows.Forms.RadioButton();
            this.rdbExpense = new System.Windows.Forms.RadioButton();
            this.rdbIncome = new System.Windows.Forms.RadioButton();
            this.label2 = new System.Windows.Forms.Label();
            this.tp2 = new System.Windows.Forms.TabPage();
            this.chkAllComp = new System.Windows.Forms.CheckBox();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.chkComp = new System.Windows.Forms.CheckBox();
            this.cmbCompany = new  Tourist_Management.User_Controls.ComboBox();
            this.chkActive = new System.Windows.Forms.CheckBox();
            this.btnSaveClose = new System.Windows.Forms.Button();
            this.btnCancel2 = new System.Windows.Forms.Button();
            this.btnSaveNew = new System.Windows.Forms.Button();
            this.gbOpenBal = new System.Windows.Forms.GroupBox();
            this.dtpOB = new System.Windows.Forms.DateTimePicker();
            this.txtAmount = new System.Windows.Forms.TextBox();
            this.label13 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.drpTLM = new Tourist_Management.DropDowns.DropSearch();
            this.label11 = new System.Windows.Forms.Label();
            this.txtNote = new System.Windows.Forms.TextBox();
            this.label10 = new System.Windows.Forms.Label();
            this.txtDescription = new System.Windows.Forms.TextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.drpSubOf = new Tourist_Management.DropDowns.DropSearch();
            this.txtAccIden = new System.Windows.Forms.TextBox();
            this.label15 = new System.Windows.Forms.Label();
            this.txtAccNo = new System.Windows.Forms.TextBox();
            this.label14 = new System.Windows.Forms.Label();
            this.txtAccName = new System.Windows.Forms.TextBox();
            this.chkSubAccOf = new System.Windows.Forms.CheckBox();
            this.label8 = new System.Windows.Forms.Label();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.drpAccType = new Tourist_Management.DropDowns.DropSearch();
            this.label7 = new System.Windows.Forms.Label();
            this.tc.SuspendLayout();
            this.tp1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.tp2.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.gbOpenBal.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Lucida Bright", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(6, 3);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(303, 15);
            this.label1.TabIndex = 0;
            this.label1.Text = "Choose ONE account type and click continue";
            this.tc.Controls.Add(this.tp1);
            this.tc.Controls.Add(this.tp2);
            this.tc.Location = new System.Drawing.Point(4, 3);
            this.tc.Name = "tc";
            this.tc.SelectedIndex = 0;
            this.tc.Size = new System.Drawing.Size(557, 386);
            this.tc.TabIndex = 1;
            this.tc.Click += new System.EventHandler(this.tc_Click);
            this.tp1.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tp1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tp1.Controls.Add(this.groupBox1);
            this.tp1.Controls.Add(this.label1);
            this.tp1.Location = new System.Drawing.Point(4, 23);
            this.tp1.Name = "tp1";
            this.tp1.Padding = new System.Windows.Forms.Padding(3);
            this.tp1.Size = new System.Drawing.Size(549, 359);
            this.tp1.TabIndex = 0;
            this.tp1.UseVisualStyleBackColor = true;
            this.groupBox1.Controls.Add(this.drpOtherAccType);
            this.groupBox1.Controls.Add(this.lblAccName);
            this.groupBox1.Controls.Add(this.lblDescription);
            this.groupBox1.Controls.Add(this.btnCancel1);
            this.groupBox1.Controls.Add(this.btnContinue);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.rdbOther);
            this.groupBox1.Controls.Add(this.rdbEquity);
            this.groupBox1.Controls.Add(this.rdbCCard);
            this.groupBox1.Controls.Add(this.rdbLoan);
            this.groupBox1.Controls.Add(this.rdbBank);
            this.groupBox1.Controls.Add(this.rdbFAsset);
            this.groupBox1.Controls.Add(this.rdbExpense);
            this.groupBox1.Controls.Add(this.rdbIncome);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Location = new System.Drawing.Point(9, 21);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(534, 328);
            this.groupBox1.TabIndex = 2;
            this.groupBox1.TabStop = false;
            this.drpOtherAccType.BackColor = System.Drawing.Color.Transparent;
            this.drpOtherAccType.DataSource = null;
            this.drpOtherAccType.Enabled = false;
            this.drpOtherAccType.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpOtherAccType.Location = new System.Drawing.Point(152, 253);
            this.drpOtherAccType.Name = "drpOtherAccType";
            this.drpOtherAccType.SelectedText = "";
            this.drpOtherAccType.SelectedValue = "";
            this.drpOtherAccType.Size = new System.Drawing.Size(170, 20);
            this.drpOtherAccType.TabIndex = 376;
            this.drpOtherAccType.Selected_TextChanged += new System.EventHandler(this.drpOtherAccType_Selected_TextChanged);
            this.lblAccName.Font = new System.Drawing.Font("Lucida Bright", 8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))));
            this.lblAccName.ForeColor = System.Drawing.Color.Blue;
            this.lblAccName.Location = new System.Drawing.Point(333, 16);
            this.lblAccName.Name = "lblAccName";
            this.lblAccName.Size = new System.Drawing.Size(187, 24);
            this.lblAccName.TabIndex = 377;
            this.lblAccName.Text = "Income Account";
            this.lblAccName.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblDescription.BackColor = System.Drawing.Color.Gainsboro;
            this.lblDescription.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDescription.Location = new System.Drawing.Point(330, 43);
            this.lblDescription.Name = "lblDescription";
            this.lblDescription.Size = new System.Drawing.Size(190, 235);
            this.lblDescription.TabIndex = 375;
            this.lblDescription.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCancel1.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel1.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnCancel1.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel1.Location = new System.Drawing.Point(438, 295);
            this.btnCancel1.Name = "btnCancel1";
            this.btnCancel1.Size = new System.Drawing.Size(84, 26);
            this.btnCancel1.TabIndex = 374;
            this.btnCancel1.Text = "&Close";
            this.btnCancel1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel1.UseVisualStyleBackColor = true;
            this.btnCancel1.Click += new System.EventHandler(this.btnCancel1_Click);
            this.btnContinue.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnContinue.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnContinue.Image = global::Tourist_Management.Properties.Resources.next;
            this.btnContinue.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnContinue.Location = new System.Drawing.Point(349, 295);
            this.btnContinue.Name = "btnContinue";
            this.btnContinue.Size = new System.Drawing.Size(84, 26);
            this.btnContinue.TabIndex = 373;
            this.btnContinue.Text = "C&ontinue";
            this.btnContinue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnContinue.UseVisualStyleBackColor = true;
            this.btnContinue.Click += new System.EventHandler(this.btnContinue_Click);
            this.label6.BackColor = System.Drawing.Color.Gray;
            this.label6.Location = new System.Drawing.Point(11, 110);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(307, 2);
            this.label6.TabIndex = 13;
            this.label5.BackColor = System.Drawing.Color.Gray;
            this.label5.Location = new System.Drawing.Point(8, 36);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(307, 2);
            this.label5.TabIndex = 12;
            this.label4.BackColor = System.Drawing.Color.Gray;
            this.label4.Location = new System.Drawing.Point(11, 247);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(307, 2);
            this.label4.TabIndex = 11;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(11, 96);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(258, 14);
            this.label3.TabIndex = 10;
            this.label3.Text = "Or track the value of your assets and liabilities";
            this.rdbOther.AutoSize = true;
            this.rdbOther.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbOther.Location = new System.Drawing.Point(13, 254);
            this.rdbOther.Name = "rdbOther";
            this.rdbOther.Size = new System.Drawing.Size(138, 18);
            this.rdbOther.TabIndex = 9;
            this.rdbOther.Text = "Other account ty&pes";
            this.rdbOther.UseVisualStyleBackColor = true;
            this.rdbOther.CheckedChanged += new System.EventHandler(this.rdbOther_CheckedChanged);
            this.rdbEquity.AutoSize = true;
            this.rdbEquity.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbEquity.Location = new System.Drawing.Point(11, 214);
            this.rdbEquity.Name = "rdbEquity";
            this.rdbEquity.Size = new System.Drawing.Size(60, 18);
            this.rdbEquity.TabIndex = 8;
            this.rdbEquity.Text = "E&quity";
            this.rdbEquity.UseVisualStyleBackColor = true;
            this.rdbEquity.CheckedChanged += new System.EventHandler(this.rdbEquity_CheckedChanged);
            this.rdbCCard.AutoSize = true;
            this.rdbCCard.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbCCard.Location = new System.Drawing.Point(11, 190);
            this.rdbCCard.Name = "rdbCCard";
            this.rdbCCard.Size = new System.Drawing.Size(91, 18);
            this.rdbCCard.TabIndex = 7;
            this.rdbCCard.Text = "Credit Car&d";
            this.rdbCCard.UseVisualStyleBackColor = true;
            this.rdbCCard.CheckedChanged += new System.EventHandler(this.rdbCCard_CheckedChanged);
            this.rdbLoan.AutoSize = true;
            this.rdbLoan.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbLoan.Location = new System.Drawing.Point(11, 166);
            this.rdbLoan.Name = "rdbLoan";
            this.rdbLoan.Size = new System.Drawing.Size(52, 18);
            this.rdbLoan.TabIndex = 6;
            this.rdbLoan.Text = "Loa&n";
            this.rdbLoan.UseVisualStyleBackColor = true;
            this.rdbLoan.CheckedChanged += new System.EventHandler(this.rdbLoan_CheckedChanged);
            this.rdbBank.AutoSize = true;
            this.rdbBank.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbBank.Location = new System.Drawing.Point(11, 142);
            this.rdbBank.Name = "rdbBank";
            this.rdbBank.Size = new System.Drawing.Size(52, 18);
            this.rdbBank.TabIndex = 5;
            this.rdbBank.Text = "Ban&k";
            this.rdbBank.UseVisualStyleBackColor = true;
            this.rdbBank.CheckedChanged += new System.EventHandler(this.rdbBank_CheckedChanged);
            this.rdbFAsset.AutoSize = true;
            this.rdbFAsset.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbFAsset.Location = new System.Drawing.Point(11, 118);
            this.rdbFAsset.Name = "rdbFAsset";
            this.rdbFAsset.Size = new System.Drawing.Size(196, 18);
            this.rdbFAsset.TabIndex = 4;
            this.rdbFAsset.Text = "Fixed &Asset (major purchases)";
            this.rdbFAsset.UseVisualStyleBackColor = true;
            this.rdbFAsset.CheckedChanged += new System.EventHandler(this.rdbFAsset_CheckedChanged);
            this.rdbExpense.AutoSize = true;
            this.rdbExpense.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbExpense.Location = new System.Drawing.Point(11, 67);
            this.rdbExpense.Name = "rdbExpense";
            this.rdbExpense.Size = new System.Drawing.Size(73, 18);
            this.rdbExpense.TabIndex = 3;
            this.rdbExpense.Text = "E&xpense";
            this.rdbExpense.UseVisualStyleBackColor = true;
            this.rdbExpense.CheckedChanged += new System.EventHandler(this.rdbExpense_CheckedChanged);
            this.rdbIncome.AutoSize = true;
            this.rdbIncome.Checked = true;
            this.rdbIncome.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdbIncome.Location = new System.Drawing.Point(11, 43);
            this.rdbIncome.Name = "rdbIncome";
            this.rdbIncome.Size = new System.Drawing.Size(67, 18);
            this.rdbIncome.TabIndex = 2;
            this.rdbIncome.TabStop = true;
            this.rdbIncome.Text = "&Income";
            this.rdbIncome.UseVisualStyleBackColor = true;
            this.rdbIncome.CheckedChanged += new System.EventHandler(this.rdbIncome_CheckedChanged);
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(8, 16);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(276, 14);
            this.label2.TabIndex = 1;
            this.label2.Text = "Categorize money your business earns or spends";
            this.tp2.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tp2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tp2.Controls.Add(this.chkAllComp);
            this.tp2.Controls.Add(this.groupBox5);
            this.tp2.Controls.Add(this.chkActive);
            this.tp2.Controls.Add(this.btnSaveClose);
            this.tp2.Controls.Add(this.btnCancel2);
            this.tp2.Controls.Add(this.btnSaveNew);
            this.tp2.Controls.Add(this.gbOpenBal);
            this.tp2.Controls.Add(this.groupBox4);
            this.tp2.Controls.Add(this.groupBox3);
            this.tp2.Controls.Add(this.groupBox2);
            this.tp2.Location = new System.Drawing.Point(4, 23);
            this.tp2.Name = "tp2";
            this.tp2.Padding = new System.Windows.Forms.Padding(3);
            this.tp2.Size = new System.Drawing.Size(549, 359);
            this.tp2.TabIndex = 1;
            this.tp2.UseVisualStyleBackColor = true;
            this.chkAllComp.AutoSize = true;
            this.chkAllComp.Enabled = false;
            this.chkAllComp.Location = new System.Drawing.Point(363, 100);
            this.chkAllComp.Name = "chkAllComp";
            this.chkAllComp.Size = new System.Drawing.Size(116, 18);
            this.chkAllComp.TabIndex = 386;
            this.chkAllComp.Text = "For All Company";
            this.chkAllComp.UseVisualStyleBackColor = true;
            this.chkAllComp.CheckedChanged += new System.EventHandler(this.chkAllComp_CheckedChanged);
            this.groupBox5.BackColor = System.Drawing.Color.Transparent;
            this.groupBox5.Controls.Add(this.chkComp);
            this.groupBox5.Controls.Add(this.cmbCompany);
            this.groupBox5.Location = new System.Drawing.Point(359, 130);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(175, 52);
            this.groupBox5.TabIndex = 385;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Company";
            this.chkComp.AutoSize = true;
            this.chkComp.Location = new System.Drawing.Point(63, 1);
            this.chkComp.Name = "chkComp";
            this.chkComp.Size = new System.Drawing.Size(15, 14);
            this.chkComp.TabIndex = 0;
            this.chkComp.UseVisualStyleBackColor = true;
            this.chkComp.CheckedChanged += new System.EventHandler(this.chkComp_CheckedChanged);
            this.cmbCompany.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCompany.Enabled = false;
            this.cmbCompany.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCompany.FormattingEnabled = true;
            this.cmbCompany.Location = new System.Drawing.Point(9, 21);
            this.cmbCompany.Name = "cmbCompany";
            this.cmbCompany.Size = new System.Drawing.Size(160, 21);
            this.cmbCompany.TabIndex = 1;
            this.chkActive.AutoSize = true;
            this.chkActive.Checked = true;
            this.chkActive.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkActive.Location = new System.Drawing.Point(21, 310);
            this.chkActive.Name = "chkActive";
            this.chkActive.Size = new System.Drawing.Size(74, 18);
            this.chkActive.TabIndex = 384;
            this.chkActive.Text = "Is Active";
            this.chkActive.UseVisualStyleBackColor = true;
            this.btnSaveClose.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnSaveClose.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSaveClose.Image = global::Tourist_Management.Properties.Resources.floppy;
            this.btnSaveClose.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSaveClose.Location = new System.Drawing.Point(208, 327);
            this.btnSaveClose.Name = "btnSaveClose";
            this.btnSaveClose.Size = new System.Drawing.Size(116, 26);
            this.btnSaveClose.TabIndex = 0;
            this.btnSaveClose.Text = "&Save && Close";
            this.btnSaveClose.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSaveClose.UseVisualStyleBackColor = true;
            this.btnSaveClose.Click += new System.EventHandler(this.btnSaveClose_Click);
            this.btnCancel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCancel2.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel2.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnCancel2.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel2.Location = new System.Drawing.Point(434, 327);
            this.btnCancel2.Name = "btnCancel2";
            this.btnCancel2.Size = new System.Drawing.Size(84, 26);
            this.btnCancel2.TabIndex = 2;
            this.btnCancel2.Text = "&Close";
            this.btnCancel2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel2.UseVisualStyleBackColor = true;
            this.btnCancel2.Click += new System.EventHandler(this.btnCancel2_Click);
            this.btnSaveNew.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnSaveNew.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSaveNew.Image = global::Tourist_Management.Properties.Resources.copy;
            this.btnSaveNew.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSaveNew.Location = new System.Drawing.Point(331, 327);
            this.btnSaveNew.Name = "btnSaveNew";
            this.btnSaveNew.Size = new System.Drawing.Size(100, 26);
            this.btnSaveNew.TabIndex = 1;
            this.btnSaveNew.Text = "Save && &New";
            this.btnSaveNew.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSaveNew.UseVisualStyleBackColor = true;
            this.btnSaveNew.Click += new System.EventHandler(this.btnSaveNew_Click);
            this.gbOpenBal.Controls.Add(this.dtpOB);
            this.gbOpenBal.Controls.Add(this.txtAmount);
            this.gbOpenBal.Controls.Add(this.label13);
            this.gbOpenBal.Controls.Add(this.label12);
            this.gbOpenBal.Location = new System.Drawing.Point(359, 7);
            this.gbOpenBal.Name = "gbOpenBal";
            this.gbOpenBal.Size = new System.Drawing.Size(175, 77);
            this.gbOpenBal.TabIndex = 380;
            this.gbOpenBal.TabStop = false;
            this.gbOpenBal.Text = "Opening Balanace";
            this.dtpOB.Location = new System.Drawing.Point(64, 47);
            this.dtpOB.Name = "dtpOB";
            this.dtpOB.Size = new System.Drawing.Size(105, 20);
            this.dtpOB.TabIndex = 1;
            this.txtAmount.Location = new System.Drawing.Point(64, 21);
            this.txtAmount.Name = "txtAmount";
            this.txtAmount.Size = new System.Drawing.Size(105, 20);
            this.txtAmount.TabIndex = 0;
            this.txtAmount.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.label13.AutoSize = true;
            this.label13.Location = new System.Drawing.Point(6, 47);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(37, 14);
            this.label13.TabIndex = 4;
            this.label13.Text = "As of";
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(6, 23);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(52, 14);
            this.label12.TabIndex = 3;
            this.label12.Text = "Amount";
            this.groupBox4.Controls.Add(this.drpTLM);
            this.groupBox4.Controls.Add(this.label11);
            this.groupBox4.Controls.Add(this.txtNote);
            this.groupBox4.Controls.Add(this.label10);
            this.groupBox4.Controls.Add(this.txtDescription);
            this.groupBox4.Controls.Add(this.label9);
            this.groupBox4.Location = new System.Drawing.Point(12, 185);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(522, 116);
            this.groupBox4.TabIndex = 379;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Optional";
            this.drpTLM.BackColor = System.Drawing.Color.Transparent;
            this.drpTLM.DataSource = null;
            this.drpTLM.Enabled = false;
            this.drpTLM.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpTLM.Location = new System.Drawing.Point(115, 85);
            this.drpTLM.Name = "drpTLM";
            this.drpTLM.SelectedText = "";
            this.drpTLM.SelectedValue = "";
            this.drpTLM.Size = new System.Drawing.Size(223, 20);
            this.drpTLM.TabIndex = 2;
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(6, 88);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(101, 14);
            this.label11.TabIndex = 381;
            this.label11.Text = "Tax-Line Mapping";
            this.txtNote.Location = new System.Drawing.Point(115, 57);
            this.txtNote.Multiline = true;
            this.txtNote.Name = "txtNote";
            this.txtNote.Size = new System.Drawing.Size(391, 21);
            this.txtNote.TabIndex = 1;
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(8, 60);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(33, 14);
            this.label10.TabIndex = 379;
            this.label10.Text = "Note";
            this.txtDescription.Location = new System.Drawing.Point(115, 19);
            this.txtDescription.Multiline = true;
            this.txtDescription.Name = "txtDescription";
            this.txtDescription.Size = new System.Drawing.Size(391, 32);
            this.txtDescription.TabIndex = 0;
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(6, 22);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(71, 14);
            this.label9.TabIndex = 3;
            this.label9.Text = "Description";
            this.groupBox3.Controls.Add(this.drpSubOf);
            this.groupBox3.Controls.Add(this.txtAccIden);
            this.groupBox3.Controls.Add(this.label15);
            this.groupBox3.Controls.Add(this.txtAccNo);
            this.groupBox3.Controls.Add(this.label14);
            this.groupBox3.Controls.Add(this.txtAccName);
            this.groupBox3.Controls.Add(this.chkSubAccOf);
            this.groupBox3.Controls.Add(this.label8);
            this.groupBox3.Location = new System.Drawing.Point(12, 54);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(340, 129);
            this.groupBox3.TabIndex = 2;
            this.groupBox3.TabStop = false;
            this.drpSubOf.BackColor = System.Drawing.Color.Transparent;
            this.drpSubOf.DataSource = null;
            this.drpSubOf.Enabled = false;
            this.drpSubOf.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpSubOf.Location = new System.Drawing.Point(117, 40);
            this.drpSubOf.Name = "drpSubOf";
            this.drpSubOf.SelectedText = "";
            this.drpSubOf.SelectedValue = "";
            this.drpSubOf.Size = new System.Drawing.Size(208, 20);
            this.drpSubOf.TabIndex = 1;
            this.txtAccIden.Location = new System.Drawing.Point(117, 96);
            this.txtAccIden.Name = "txtAccIden";
            this.txtAccIden.Size = new System.Drawing.Size(208, 20);
            this.txtAccIden.TabIndex = 7;
            this.label15.AutoSize = true;
            this.label15.Location = new System.Drawing.Point(6, 97);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(108, 14);
            this.label15.TabIndex = 8;
            this.label15.Text = "Account Identifier";
            this.txtAccNo.Location = new System.Drawing.Point(117, 70);
            this.txtAccNo.Name = "txtAccNo";
            this.txtAccNo.Size = new System.Drawing.Size(208, 20);
            this.txtAccNo.TabIndex = 5;
            this.label14.AutoSize = true;
            this.label14.Location = new System.Drawing.Point(6, 70);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(73, 14);
            this.label14.TabIndex = 6;
            this.label14.Text = "Account No";
            this.txtAccName.Location = new System.Drawing.Point(117, 16);
            this.txtAccName.Name = "txtAccName";
            this.txtAccName.Size = new System.Drawing.Size(208, 20);
            this.txtAccName.TabIndex = 0;
            this.chkSubAccOf.AutoSize = true;
            this.chkSubAccOf.Location = new System.Drawing.Point(7, 42);
            this.chkSubAccOf.Name = "chkSubAccOf";
            this.chkSubAccOf.Size = new System.Drawing.Size(96, 17);
            this.chkSubAccOf.TabIndex = 4;
            this.chkSubAccOf.Text = "Subaccount of";
            this.chkSubAccOf.UseVisualStyleBackColor = true;
            this.chkSubAccOf.CheckedChanged += new System.EventHandler(this.chkSubAccOf_CheckedChanged);
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(6, 16);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(90, 14);
            this.label8.TabIndex = 3;
            this.label8.Text = "Account Name";
            this.groupBox2.Controls.Add(this.drpAccType);
            this.groupBox2.Controls.Add(this.label7);
            this.groupBox2.Location = new System.Drawing.Point(12, 5);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(340, 48);
            this.groupBox2.TabIndex = 1;
            this.groupBox2.TabStop = false;
            this.drpAccType.BackColor = System.Drawing.Color.Transparent;
            this.drpAccType.DataSource = null;
            this.drpAccType.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpAccType.Location = new System.Drawing.Point(103, 16);
            this.drpAccType.Name = "drpAccType";
            this.drpAccType.SelectedText = "";
            this.drpAccType.SelectedValue = "";
            this.drpAccType.Size = new System.Drawing.Size(222, 20);
            this.drpAccType.TabIndex = 0;
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(12, 19);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(85, 14);
            this.label7.TabIndex = 2;
            this.label7.Text = "Account Type";
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(575, 401);
            this.ControlBox = false;
            this.Controls.Add(this.tc);
            this.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmChartOfAccount";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmChartOfAccount_Load);
            this.tc.ResumeLayout(false);
            this.tp1.ResumeLayout(false);
            this.tp1.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.tp2.ResumeLayout(false);
            this.tp2.PerformLayout();
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.gbOpenBal.ResumeLayout(false);
            this.gbOpenBal.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.ResumeLayout(false);
        }
        #endregion
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TabControl tc;
        private System.Windows.Forms.TabPage tp1;
        private System.Windows.Forms.TabPage tp2;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.RadioButton rdbBank;
        private System.Windows.Forms.RadioButton rdbFAsset;
        private System.Windows.Forms.RadioButton rdbExpense;
        private System.Windows.Forms.RadioButton rdbIncome;
        private System.Windows.Forms.RadioButton rdbOther;
        private System.Windows.Forms.RadioButton rdbEquity;
        private System.Windows.Forms.RadioButton rdbCCard;
        private System.Windows.Forms.RadioButton rdbLoan;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Button btnCancel1;
        private System.Windows.Forms.Button btnContinue;
        private System.Windows.Forms.Label lblDescription;
        private DropDowns.DropSearch drpOtherAccType;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label label7;
        private DropDowns.DropSearch drpTLM;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.CheckBox chkSubAccOf;
        private DropDowns.DropSearch drpAccType;
        private System.Windows.Forms.TextBox txtAccName;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.TextBox txtDescription;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.TextBox txtNote;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label11;
        private DropDowns.DropSearch drpSubOf;
        private System.Windows.Forms.GroupBox gbOpenBal;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.DateTimePicker dtpOB;
        private System.Windows.Forms.TextBox txtAmount;
        private System.Windows.Forms.Button btnSaveClose;
        private System.Windows.Forms.Button btnCancel2;
        private System.Windows.Forms.Button btnSaveNew;
        private System.Windows.Forms.Label lblAccName;
        private System.Windows.Forms.CheckBox chkActive;
        private System.Windows.Forms.TextBox txtAccIden;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.TextBox txtAccNo;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.CheckBox chkComp;
        private  Tourist_Management.User_Controls.ComboBox cmbCompany;
        private System.Windows.Forms.CheckBox chkAllComp;
    }
}