namespace Tourist_Management.Accounts
{
    partial class frmDirectBooking
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmDirectBooking));
            this.ucFilterByCompany1 = new Tourist_Management.User_Controls.ucFilterByCompany();
            this.ucFilterByDate1 = new Tourist_Management.User_Controls.ucFilterByDate();
            this.ucFilterByOther1 = new Tourist_Management.User_Controls.ucFilterByOther();
            this.label39 = new System.Windows.Forms.Label();
            this.btnFilter = new System.Windows.Forms.Button();
            this.grdViewer = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.btnICancel = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.chkDirect = new System.Windows.Forms.CheckBox();
            this.label1 = new System.Windows.Forms.Label();
            this.ucFilterByOther2 = new Tourist_Management.User_Controls.ucFilterByOther();
            this.cmbOp = new  Tourist_Management.User_Controls.ComboBox();
            this.cmbFld = new  Tourist_Management.User_Controls.ComboBox();
            this.btnClearSearch = new System.Windows.Forms.Button();
            this.txtAccountName = new System.Windows.Forms.TextBox();
            ((System.ComponentModel.ISupportInitialize)(this.grdViewer)).BeginInit();
            this.SuspendLayout();
            this.ucFilterByCompany1.BackColor = System.Drawing.Color.Transparent;
            this.ucFilterByCompany1.Location = new System.Drawing.Point(454, 14);
            this.ucFilterByCompany1.Name = "ucFilterByCompany1";
            this.ucFilterByCompany1.Size = new System.Drawing.Size(231, 60);
            this.ucFilterByCompany1.TabIndex = 387;
            this.ucFilterByDate1.BackColor = System.Drawing.Color.Transparent;
            this.ucFilterByDate1.Location = new System.Drawing.Point(5, 5);
            this.ucFilterByDate1.Name = "ucFilterByDate1";
            this.ucFilterByDate1.Size = new System.Drawing.Size(453, 65);
            this.ucFilterByDate1.TabIndex = 386;
            this.ucFilterByOther1.BackColor = System.Drawing.Color.Transparent;
            this.ucFilterByOther1.Location = new System.Drawing.Point(10, 73);
            this.ucFilterByOther1.Name = "ucFilterByOther1";
            this.ucFilterByOther1.Query = null;
            this.ucFilterByOther1.Size = new System.Drawing.Size(185, 50);
            this.ucFilterByOther1.TabIndex = 388;
            this.label39.AutoSize = true;
            this.label39.BackColor = System.Drawing.Color.Transparent;
            this.label39.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label39.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label39.Location = new System.Drawing.Point(9, 73);
            this.label39.Name = "label39";
            this.label39.Size = new System.Drawing.Size(72, 14);
            this.label39.TabIndex = 389;
            this.label39.Text = "HANDLED";
            this.btnFilter.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnFilter.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFilter.Image = global::Tourist_Management.Properties.Resources.filter;
            this.btnFilter.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFilter.Location = new System.Drawing.Point(564, 82);
            this.btnFilter.Name = "btnFilter";
            this.btnFilter.Size = new System.Drawing.Size(71, 37);
            this.btnFilter.TabIndex = 390;
            this.btnFilter.Text = "&Filter";
            this.btnFilter.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFilter.UseVisualStyleBackColor = true;
            this.btnFilter.Click += new System.EventHandler(this.btnFilter_Click);
            this.grdViewer.BackColor = System.Drawing.Color.Transparent;
            this.grdViewer.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.grdViewer.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.grdViewer.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdViewer.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdViewer.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grdViewer.Location = new System.Drawing.Point(14, 164);
            this.grdViewer.Name = "grdViewer";
            this.grdViewer.Size = new System.Drawing.Size(671, 317);
            this.grdViewer.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdViewer.Styles"));
            this.grdViewer.TabIndex = 392;
            this.btnICancel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnICancel.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnICancel.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnICancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnICancel.Location = new System.Drawing.Point(613, 491);
            this.btnICancel.Name = "btnICancel";
            this.btnICancel.Size = new System.Drawing.Size(72, 30);
            this.btnICancel.TabIndex = 391;
            this.btnICancel.Text = "&Cancel";
            this.btnICancel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnICancel.UseVisualStyleBackColor = true;
            this.btnICancel.Click += new System.EventHandler(this.btnICancel_Click);
            this.btnOk.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnOk.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Image = global::Tourist_Management.Properties.Resources.floppy;
            this.btnOk.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOk.Location = new System.Drawing.Point(535, 491);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(72, 30);
            this.btnOk.TabIndex = 407;
            this.btnOk.Text = "&Save";
            this.btnOk.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.chkDirect.AutoSize = true;
            this.chkDirect.BackColor = System.Drawing.Color.Transparent;
            this.chkDirect.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkDirect.ForeColor = System.Drawing.Color.Green;
            this.chkDirect.Location = new System.Drawing.Point(392, 99);
            this.chkDirect.Name = "chkDirect";
            this.chkDirect.Size = new System.Drawing.Size(166, 19);
            this.chkDirect.TabIndex = 408;
            this.chkDirect.Text = "Show Direct Bookings";
            this.chkDirect.UseVisualStyleBackColor = false;
            this.chkDirect.CheckedChanged += new System.EventHandler(this.chkDirect_CheckedChanged);
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label1.Location = new System.Drawing.Point(203, 74);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(52, 14);
            this.label1.TabIndex = 410;
            this.label1.Text = "AGENT";
            this.ucFilterByOther2.BackColor = System.Drawing.Color.Transparent;
            this.ucFilterByOther2.Location = new System.Drawing.Point(200, 73);
            this.ucFilterByOther2.Name = "ucFilterByOther2";
            this.ucFilterByOther2.Query = null;
            this.ucFilterByOther2.Size = new System.Drawing.Size(185, 50);
            this.ucFilterByOther2.TabIndex = 409;
            this.cmbOp.BackColor = System.Drawing.Color.White;
            this.cmbOp.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbOp.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbOp.ForeColor = System.Drawing.Color.Black;
            this.cmbOp.FormattingEnabled = true;
            this.cmbOp.Location = new System.Drawing.Point(252, 136);
            this.cmbOp.Name = "cmbOp";
            this.cmbOp.Size = new System.Drawing.Size(158, 21);
            this.cmbOp.TabIndex = 414;
            this.cmbFld.BackColor = System.Drawing.Color.White;
            this.cmbFld.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFld.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbFld.ForeColor = System.Drawing.Color.Black;
            this.cmbFld.FormattingEnabled = true;
            this.cmbFld.Location = new System.Drawing.Point(93, 136);
            this.cmbFld.Name = "cmbFld";
            this.cmbFld.Size = new System.Drawing.Size(153, 21);
            this.cmbFld.TabIndex = 413;
            this.btnClearSearch.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnClearSearch.Image = global::Tourist_Management.Properties.Resources.cancel;
            this.btnClearSearch.Location = new System.Drawing.Point(538, 135);
            this.btnClearSearch.Name = "btnClearSearch";
            this.btnClearSearch.Size = new System.Drawing.Size(24, 22);
            this.btnClearSearch.TabIndex = 412;
            this.btnClearSearch.UseVisualStyleBackColor = true;
            this.btnClearSearch.Click += new System.EventHandler(this.btnClearSearch_Click);
            this.txtAccountName.BackColor = System.Drawing.Color.LightYellow;
            this.txtAccountName.Location = new System.Drawing.Point(416, 136);
            this.txtAccountName.MaxLength = 0;
            this.txtAccountName.Name = "txtAccountName";
            this.txtAccountName.Size = new System.Drawing.Size(120, 20);
            this.txtAccountName.TabIndex = 411;
            this.txtAccountName.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txtAccountName.TextChanged += new System.EventHandler(this.txtAccountName_TextChanged);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(696, 527);
            this.ControlBox = false;
            this.Controls.Add(this.cmbOp);
            this.Controls.Add(this.cmbFld);
            this.Controls.Add(this.btnClearSearch);
            this.Controls.Add(this.txtAccountName);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.ucFilterByOther2);
            this.Controls.Add(this.chkDirect);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.grdViewer);
            this.Controls.Add(this.btnICancel);
            this.Controls.Add(this.btnFilter);
            this.Controls.Add(this.label39);
            this.Controls.Add(this.ucFilterByOther1);
            this.Controls.Add(this.ucFilterByCompany1);
            this.Controls.Add(this.ucFilterByDate1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmDirectBooking";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmDirectBooking_Load);
            ((System.ComponentModel.ISupportInitialize)(this.grdViewer)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private Tourist_Management.User_Controls.ucFilterByCompany ucFilterByCompany1;
        private Tourist_Management.User_Controls.ucFilterByDate ucFilterByDate1;
        private Tourist_Management.User_Controls.ucFilterByOther ucFilterByOther1;
        private System.Windows.Forms.Label label39;
        private System.Windows.Forms.Button btnFilter;
        private C1.Win.C1FlexGrid.C1FlexGrid grdViewer;
        private System.Windows.Forms.Button btnICancel;
        public System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.CheckBox chkDirect;
        private System.Windows.Forms.Label label1;
        private Tourist_Management.User_Controls.ucFilterByOther ucFilterByOther2;
        internal  Tourist_Management.User_Controls.ComboBox cmbOp;
        internal  Tourist_Management.User_Controls.ComboBox cmbFld;
        private System.Windows.Forms.Button btnClearSearch;
        private System.Windows.Forms.TextBox txtAccountName;
    }
}