namespace Tourist_Management.Accounts
{
    partial class frmHotelMonthlyPay
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmHotelMonthlyPay));
            this.chkTodayPay = new System.Windows.Forms.CheckBox();
            this.chkAllPaid = new System.Windows.Forms.CheckBox();
            this.btnUpdate = new System.Windows.Forms.Button();
            this.btnDefRate = new System.Windows.Forms.Button();
            this.label3 = new System.Windows.Forms.Label();
            this.txtConRate = new System.Windows.Forms.TextBox();
            this.dtpConfirmDate = new System.Windows.Forms.DateTimePicker();
            this.chkGuide = new System.Windows.Forms.CheckBox();
            this.checkBox1 = new System.Windows.Forms.CheckBox();
            this.groupBox10 = new System.Windows.Forms.GroupBox();
            this.label7 = new System.Windows.Forms.Label();
            this.groupBox9 = new System.Windows.Forms.GroupBox();
            this.grdMealPay = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.grdRoomPay = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.label6 = new System.Windows.Forms.Label();
            this.groupBox8 = new System.Windows.Forms.GroupBox();
            this.label5 = new System.Windows.Forms.Label();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.chkEbed = new System.Windows.Forms.CheckBox();
            this.chkOther = new System.Windows.Forms.CheckBox();
            this.label4 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.groupBox19 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label23 = new System.Windows.Forms.Label();
            this.dtpFromDate = new System.Windows.Forms.DateTimePicker();
            this.label9 = new System.Windows.Forms.Label();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.label2 = new System.Windows.Forms.Label();
            this.dtpPaidDate = new System.Windows.Forms.DateTimePicker();
            this.btnGetTot = new System.Windows.Forms.Button();
            this.dtpToDate = new System.Windows.Forms.DateTimePicker();
            this.pbCompLogo = new System.Windows.Forms.PictureBox();
            this.chkPrint = new System.Windows.Forms.CheckBox();
            this.btnCancel = new System.Windows.Forms.Button();
            this.gbDateRange = new System.Windows.Forms.GroupBox();
            this.btnPrint = new System.Windows.Forms.Button();
            this.grdDuePayDaily = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.btnOk = new System.Windows.Forms.Button();
            this.drpHotel = new Tourist_Management.DropDowns.DropSearch();
            this.label8 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.txtChkNo = new System.Windows.Forms.TextBox();
            this.btnTour = new System.Windows.Forms.Button();
            this.txtTourNo = new System.Windows.Forms.TextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.btnClear = new System.Windows.Forms.Button();
            this.lblClient = new System.Windows.Forms.Label();
            this.pbPaySum = new System.Windows.Forms.ProgressBar();
            this.cmbCompany = new  Tourist_Management.User_Controls.ComboBox();
            this.label36 = new System.Windows.Forms.Label();
            this.lblCompLogo = new System.Windows.Forms.Label();
            this.btnEmail = new System.Windows.Forms.Button();
            this.lblPrePaid = new System.Windows.Forms.Label();
            this.chkCmpny = new System.Windows.Forms.CheckBox();
            this.label13 = new System.Windows.Forms.Label();
            this.grpPayMethod = new System.Windows.Forms.GroupBox();
            this.rdbCash = new System.Windows.Forms.RadioButton();
            this.rdbBank = new System.Windows.Forms.RadioButton();
            ((System.ComponentModel.ISupportInitialize)(this.grdMealPay)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdRoomPay)).BeginInit();
            this.groupBox4.SuspendLayout();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbCompLogo)).BeginInit();
            this.gbDateRange.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdDuePayDaily)).BeginInit();
            this.grpPayMethod.SuspendLayout();
            this.SuspendLayout();
            this.chkTodayPay.AutoSize = true;
            this.chkTodayPay.BackColor = System.Drawing.Color.Transparent;
            this.chkTodayPay.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkTodayPay.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkTodayPay.Location = new System.Drawing.Point(13, 13);
            this.chkTodayPay.Name = "chkTodayPay";
            this.chkTodayPay.Size = new System.Drawing.Size(87, 17);
            this.chkTodayPay.TabIndex = 345;
            this.chkTodayPay.Text = "Paid Only";
            this.chkTodayPay.UseVisualStyleBackColor = false;
            this.chkTodayPay.CheckedChanged += new System.EventHandler(this.chkTodayPay_CheckedChanged);
            this.chkAllPaid.AutoSize = true;
            this.chkAllPaid.BackColor = System.Drawing.Color.Transparent;
            this.chkAllPaid.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkAllPaid.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkAllPaid.Location = new System.Drawing.Point(13, 34);
            this.chkAllPaid.Name = "chkAllPaid";
            this.chkAllPaid.Size = new System.Drawing.Size(131, 17);
            this.chkAllPaid.TabIndex = 344;
            this.chkAllPaid.Text = "Mark All As Paid";
            this.chkAllPaid.UseVisualStyleBackColor = false;
            this.chkAllPaid.Click += new System.EventHandler(this.chkAllPaid_CheckedChanged);
            this.btnUpdate.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnUpdate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUpdate.Image = global::Tourist_Management.Properties.Resources.upload;
            this.btnUpdate.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUpdate.Location = new System.Drawing.Point(15, 613);
            this.btnUpdate.Name = "btnUpdate";
            this.btnUpdate.Size = new System.Drawing.Size(130, 50);
            this.btnUpdate.TabIndex = 399;
            this.btnUpdate.Text = "&Update Above Rates To Hotels";
            this.btnUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUpdate.UseVisualStyleBackColor = true;
            this.btnUpdate.Click += new System.EventHandler(this.btnUpdate_Click);
            this.btnDefRate.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnDefRate.Location = new System.Drawing.Point(865, 64);
            this.btnDefRate.Name = "btnDefRate";
            this.btnDefRate.Size = new System.Drawing.Size(148, 23);
            this.btnDefRate.TabIndex = 398;
            this.btnDefRate.Text = "Set Default Conv.Rate";
            this.btnDefRate.UseVisualStyleBackColor = true;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(740, 106);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(53, 13);
            this.label3.TabIndex = 379;
            this.label3.Text = "Confirm";
            this.label3.Visible = false;
            this.txtConRate.BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            this.txtConRate.Location = new System.Drawing.Point(726, 65);
            this.txtConRate.Name = "txtConRate";
            this.txtConRate.Size = new System.Drawing.Size(135, 21);
            this.txtConRate.TabIndex = 397;
            this.txtConRate.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.dtpConfirmDate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpConfirmDate.Location = new System.Drawing.Point(799, 103);
            this.dtpConfirmDate.Name = "dtpConfirmDate";
            this.dtpConfirmDate.Size = new System.Drawing.Size(212, 20);
            this.dtpConfirmDate.TabIndex = 380;
            this.dtpConfirmDate.Visible = false;
            this.chkGuide.AutoSize = true;
            this.chkGuide.BackColor = System.Drawing.Color.Transparent;
            this.chkGuide.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkGuide.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkGuide.Location = new System.Drawing.Point(13, 54);
            this.chkGuide.Name = "chkGuide";
            this.chkGuide.Size = new System.Drawing.Size(159, 17);
            this.chkGuide.TabIndex = 347;
            this.chkGuide.Text = "Separate Guide Rate";
            this.chkGuide.UseVisualStyleBackColor = false;
            this.chkGuide.Click += new System.EventHandler(this.chkGuide_CheckedChanged);
            this.checkBox1.AutoSize = true;
            this.checkBox1.BackColor = System.Drawing.Color.Transparent;
            this.checkBox1.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.checkBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.checkBox1.Location = new System.Drawing.Point(822, 91);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Size = new System.Drawing.Size(130, 17);
            this.checkBox1.TabIndex = 378;
            this.checkBox1.Text = "Confirm All Paid";
            this.checkBox1.UseVisualStyleBackColor = false;
            this.checkBox1.Visible = false;
            this.groupBox10.BackColor = System.Drawing.Color.Gray;
            this.groupBox10.Location = new System.Drawing.Point(715, 395);
            this.groupBox10.Name = "groupBox10";
            this.groupBox10.Size = new System.Drawing.Size(2, 218);
            this.groupBox10.TabIndex = 396;
            this.groupBox10.TabStop = false;
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.Transparent;
            this.label7.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label7.Location = new System.Drawing.Point(727, 393);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(125, 14);
            this.label7.TabIndex = 395;
            this.label7.Text = "MEAL PAYMENTS ";
            this.groupBox9.BackColor = System.Drawing.Color.Gray;
            this.groupBox9.Location = new System.Drawing.Point(766, 402);
            this.groupBox9.Name = "groupBox9";
            this.groupBox9.Size = new System.Drawing.Size(457, 5);
            this.groupBox9.TabIndex = 394;
            this.groupBox9.TabStop = false;
            this.grdMealPay.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdMealPay.ColumnInfo = "0,0,0,0,0,85,Columns:";
            this.grdMealPay.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grdMealPay.Location = new System.Drawing.Point(724, 413);
            this.grdMealPay.Name = "grdMealPay";
            this.grdMealPay.Size = new System.Drawing.Size(499, 198);
            this.grdMealPay.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdMealPay.Styles"));
            this.grdMealPay.TabIndex = 393;
            this.grdMealPay.AfterSelChange += new C1.Win.C1FlexGrid.RangeEventHandler(this.grdMealPay_AfterSelChange);
            this.grdRoomPay.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdRoomPay.ColumnInfo = "0,0,0,0,0,85,Columns:";
            this.grdRoomPay.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grdRoomPay.Location = new System.Drawing.Point(15, 413);
            this.grdRoomPay.Name = "grdRoomPay";
            this.grdRoomPay.Size = new System.Drawing.Size(688, 198);
            this.grdRoomPay.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdRoomPay.Styles"));
            this.grdRoomPay.TabIndex = 392;
            this.grdRoomPay.AfterSelChange += new C1.Win.C1FlexGrid.RangeEventHandler(this.grdRoomPay_AfterSelChange);
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label6.Location = new System.Drawing.Point(12, 393);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(131, 14);
            this.label6.TabIndex = 391;
            this.label6.Text = "ROOM PAYMENTS ";
            this.groupBox8.BackColor = System.Drawing.Color.Gray;
            this.groupBox8.Location = new System.Drawing.Point(109, 402);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new System.Drawing.Size(592, 5);
            this.groupBox8.TabIndex = 390;
            this.groupBox8.TabStop = false;
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label5.Location = new System.Drawing.Point(12, 129);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(145, 14);
            this.label5.TabIndex = 389;
            this.label5.Text = "PAYMENT SUMMARY";
            this.groupBox6.BackColor = System.Drawing.Color.Gray;
            this.groupBox6.Location = new System.Drawing.Point(1019, 7);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(4, 83);
            this.groupBox6.TabIndex = 387;
            this.groupBox6.TabStop = false;
            this.groupBox5.BackColor = System.Drawing.Color.Gray;
            this.groupBox5.Location = new System.Drawing.Point(713, 7);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(4, 83);
            this.groupBox5.TabIndex = 386;
            this.groupBox5.TabStop = false;
            this.groupBox3.BackColor = System.Drawing.Color.Gray;
            this.groupBox3.Location = new System.Drawing.Point(382, 7);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(4, 83);
            this.groupBox3.TabIndex = 384;
            this.groupBox3.TabStop = false;
            this.groupBox4.BackColor = System.Drawing.Color.Transparent;
            this.groupBox4.Controls.Add(this.chkEbed);
            this.groupBox4.Controls.Add(this.chkOther);
            this.groupBox4.Controls.Add(this.chkGuide);
            this.groupBox4.Controls.Add(this.chkTodayPay);
            this.groupBox4.Controls.Add(this.chkAllPaid);
            this.groupBox4.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox4.Location = new System.Drawing.Point(1039, -3);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(184, 113);
            this.groupBox4.TabIndex = 383;
            this.groupBox4.TabStop = false;
            this.chkEbed.AutoSize = true;
            this.chkEbed.BackColor = System.Drawing.Color.Transparent;
            this.chkEbed.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkEbed.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkEbed.Location = new System.Drawing.Point(13, 92);
            this.chkEbed.Name = "chkEbed";
            this.chkEbed.Size = new System.Drawing.Size(89, 17);
            this.chkEbed.TabIndex = 350;
            this.chkEbed.Text = "Extra Bed";
            this.chkEbed.UseVisualStyleBackColor = false;
            this.chkEbed.CheckedChanged += new System.EventHandler(this.chkEbed_CheckedChanged);
            this.chkOther.AutoSize = true;
            this.chkOther.BackColor = System.Drawing.Color.Transparent;
            this.chkOther.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkOther.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkOther.Location = new System.Drawing.Point(13, 74);
            this.chkOther.Name = "chkOther";
            this.chkOther.Size = new System.Drawing.Size(130, 17);
            this.chkOther.TabIndex = 348;
            this.chkOther.Text = "Other Payments";
            this.chkOther.UseVisualStyleBackColor = false;
            this.chkOther.Click += new System.EventHandler(this.chkOther_CheckedChanged);
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label4.Location = new System.Drawing.Point(728, 5);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(190, 14);
            this.label4.TabIndex = 385;
            this.label4.Text = "SET PAID/CONFIRM DATES";
            this.groupBox1.BackColor = System.Drawing.Color.Gray;
            this.groupBox1.Location = new System.Drawing.Point(822, 17);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(189, 2);
            this.groupBox1.TabIndex = 382;
            this.groupBox1.TabStop = false;
            this.groupBox19.BackColor = System.Drawing.Color.Gray;
            this.groupBox19.Location = new System.Drawing.Point(496, 16);
            this.groupBox19.Name = "groupBox19";
            this.groupBox19.Size = new System.Drawing.Size(207, 2);
            this.groupBox19.TabIndex = 376;
            this.groupBox19.TabStop = false;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(8, 46);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(52, 13);
            this.label1.TabIndex = 248;
            this.label1.Text = "Date To";
            this.label12.AutoSize = true;
            this.label12.BackColor = System.Drawing.Color.Transparent;
            this.label12.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label12.Location = new System.Drawing.Point(399, 4);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(116, 14);
            this.label12.TabIndex = 377;
            this.label12.Text = "FILTER BY DATE";
            this.label23.BackColor = System.Drawing.Color.Transparent;
            this.label23.Font = new System.Drawing.Font("Verdana", 12.75F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label23.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.label23.Location = new System.Drawing.Point(0, 320);
            this.label23.Name = "label23";
            this.label23.Size = new System.Drawing.Size(257, 46);
            this.label23.TabIndex = 368;
            this.label23.Text = "HOTEL DUE PAYMENTS  MONTHLY";
            this.label23.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.label23.UseCompatibleTextRendering = true;
            this.label23.Visible = false;
            this.dtpFromDate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpFromDate.Location = new System.Drawing.Point(80, 20);
            this.dtpFromDate.Name = "dtpFromDate";
            this.dtpFromDate.Size = new System.Drawing.Size(212, 20);
            this.dtpFromDate.TabIndex = 247;
            this.dtpFromDate.ValueChanged += new System.EventHandler(this.dtpFromDate_ValueChanged);
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(8, 23);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(67, 13);
            this.label9.TabIndex = 246;
            this.label9.Text = "Date From";
            this.groupBox2.BackColor = System.Drawing.Color.Transparent;
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Controls.Add(this.dtpPaidDate);
            this.groupBox2.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.Location = new System.Drawing.Point(726, 11);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(287, 48);
            this.groupBox2.TabIndex = 381;
            this.groupBox2.TabStop = false;
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(7, 17);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(31, 13);
            this.label2.TabIndex = 346;
            this.label2.Text = "Paid";
            this.dtpPaidDate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpPaidDate.Location = new System.Drawing.Point(65, 16);
            this.dtpPaidDate.Name = "dtpPaidDate";
            this.dtpPaidDate.Size = new System.Drawing.Size(212, 20);
            this.dtpPaidDate.TabIndex = 347;
            this.dtpPaidDate.ValueChanged += new System.EventHandler(this.dtpPaidDate_ValueChanged);
            this.btnGetTot.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnGetTot.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGetTot.Image = global::Tourist_Management.Properties.Resources.sum;
            this.btnGetTot.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGetTot.Location = new System.Drawing.Point(970, 631);
            this.btnGetTot.Name = "btnGetTot";
            this.btnGetTot.Size = new System.Drawing.Size(87, 33);
            this.btnGetTot.TabIndex = 375;
            this.btnGetTot.Text = "&Get Total";
            this.btnGetTot.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGetTot.UseVisualStyleBackColor = true;
            this.btnGetTot.Click += new System.EventHandler(this.btnGetTot_Click);
            this.dtpToDate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpToDate.Location = new System.Drawing.Point(80, 46);
            this.dtpToDate.Name = "dtpToDate";
            this.dtpToDate.Size = new System.Drawing.Size(212, 20);
            this.dtpToDate.TabIndex = 249;
            this.dtpToDate.ValueChanged += new System.EventHandler(this.dtpToDate_ValueChanged_1);
            this.pbCompLogo.Location = new System.Drawing.Point(11, 7);
            this.pbCompLogo.Name = "pbCompLogo";
            this.pbCompLogo.Size = new System.Drawing.Size(110, 107);
            this.pbCompLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbCompLogo.TabIndex = 374;
            this.pbCompLogo.TabStop = false;
            this.chkPrint.AutoSize = true;
            this.chkPrint.BackColor = System.Drawing.Color.Transparent;
            this.chkPrint.Checked = true;
            this.chkPrint.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkPrint.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkPrint.Location = new System.Drawing.Point(656, 638);
            this.chkPrint.Name = "chkPrint";
            this.chkPrint.Size = new System.Drawing.Size(136, 17);
            this.chkPrint.TabIndex = 373;
            this.chkPrint.Text = "Preview After Save";
            this.chkPrint.UseVisualStyleBackColor = false;
            this.btnCancel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCancel.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.Location = new System.Drawing.Point(1144, 631);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(79, 33);
            this.btnCancel.TabIndex = 372;
            this.btnCancel.Text = "&Close";
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.gbDateRange.BackColor = System.Drawing.Color.Transparent;
            this.gbDateRange.Controls.Add(this.dtpToDate);
            this.gbDateRange.Controls.Add(this.label1);
            this.gbDateRange.Controls.Add(this.dtpFromDate);
            this.gbDateRange.Controls.Add(this.label9);
            this.gbDateRange.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbDateRange.Location = new System.Drawing.Point(399, 11);
            this.gbDateRange.Name = "gbDateRange";
            this.gbDateRange.Size = new System.Drawing.Size(304, 76);
            this.gbDateRange.TabIndex = 367;
            this.gbDateRange.TabStop = false;
            this.btnPrint.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPrint.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPrint.Image = global::Tourist_Management.Properties.Resources.search;
            this.btnPrint.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPrint.Location = new System.Drawing.Point(800, 631);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.Size = new System.Drawing.Size(79, 33);
            this.btnPrint.TabIndex = 370;
            this.btnPrint.Text = "&Preview";
            this.btnPrint.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPrint.UseVisualStyleBackColor = true;
            this.btnPrint.Click += new System.EventHandler(this.btnPrint_Click);
            this.grdDuePayDaily.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdDuePayDaily.ColumnInfo = "0,0,0,0,0,85,Columns:";
            this.grdDuePayDaily.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grdDuePayDaily.Location = new System.Drawing.Point(15, 151);
            this.grdDuePayDaily.Name = "grdDuePayDaily";
            this.grdDuePayDaily.Size = new System.Drawing.Size(1208, 230);
            this.grdDuePayDaily.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdDuePayDaily.Styles"));
            this.grdDuePayDaily.TabIndex = 371;
            this.grdDuePayDaily.AfterSelChange += new C1.Win.C1FlexGrid.RangeEventHandler(this.grdDuePayDaily_AfterSelChange);
            this.grdDuePayDaily.CellButtonClick += new C1.Win.C1FlexGrid.RowColEventHandler(this.grdDuePayDaily_CellButtonClick);
            this.btnOk.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnOk.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Image = global::Tourist_Management.Properties.Resources.floppy;
            this.btnOk.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOk.Location = new System.Drawing.Point(1061, 631);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(79, 33);
            this.btnOk.TabIndex = 369;
            this.btnOk.Text = "&Save";
            this.btnOk.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.drpHotel.BackColor = System.Drawing.Color.Transparent;
            this.drpHotel.DataSource = null;
            this.drpHotel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpHotel.Location = new System.Drawing.Point(198, 37);
            this.drpHotel.Name = "drpHotel";
            this.drpHotel.SelectedText = "";
            this.drpHotel.SelectedValue = "";
            this.drpHotel.Size = new System.Drawing.Size(178, 20);
            this.drpHotel.TabIndex = 400;
            this.drpHotel.Selected_TextChanged += new System.EventHandler(this.drpHotel_Selected_TextChanged);
            this.label8.AutoSize = true;
            this.label8.BackColor = System.Drawing.Color.Transparent;
            this.label8.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(125, 40);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(36, 13);
            this.label8.TabIndex = 401;
            this.label8.Text = "Hotel";
            this.label10.AutoSize = true;
            this.label10.BackColor = System.Drawing.Color.Transparent;
            this.label10.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.Location = new System.Drawing.Point(125, 65);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(49, 13);
            this.label10.TabIndex = 402;
            this.label10.Text = "Chk No";
            this.txtChkNo.BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            this.txtChkNo.Location = new System.Drawing.Point(198, 63);
            this.txtChkNo.Name = "txtChkNo";
            this.txtChkNo.Size = new System.Drawing.Size(178, 21);
            this.txtChkNo.TabIndex = 403;
            this.txtChkNo.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.btnTour.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTour.Location = new System.Drawing.Point(625, 99);
            this.btnTour.Name = "btnTour";
            this.btnTour.Size = new System.Drawing.Size(33, 23);
            this.btnTour.TabIndex = 405;
            this.btnTour.Text = "...";
            this.btnTour.UseVisualStyleBackColor = true;
            this.btnTour.Click += new System.EventHandler(this.btnTour_Click);
            this.txtTourNo.Enabled = false;
            this.txtTourNo.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTourNo.ForeColor = System.Drawing.Color.Blue;
            this.txtTourNo.Location = new System.Drawing.Point(472, 100);
            this.txtTourNo.Name = "txtTourNo";
            this.txtTourNo.ReadOnly = true;
            this.txtTourNo.Size = new System.Drawing.Size(150, 21);
            this.txtTourNo.TabIndex = 404;
            this.label11.AutoSize = true;
            this.label11.BackColor = System.Drawing.Color.Transparent;
            this.label11.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label11.Location = new System.Drawing.Point(404, 103);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(57, 13);
            this.label11.TabIndex = 406;
            this.label11.Text = "Get Tour";
            this.btnClear.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClear.Location = new System.Drawing.Point(660, 98);
            this.btnClear.Name = "btnClear";
            this.btnClear.Size = new System.Drawing.Size(50, 23);
            this.btnClear.TabIndex = 407;
            this.btnClear.Text = "Clear";
            this.btnClear.UseVisualStyleBackColor = true;
            this.btnClear.Click += new System.EventHandler(this.btnClear_Click);
            this.lblClient.AutoSize = true;
            this.lblClient.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.lblClient.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblClient.ForeColor = System.Drawing.Color.Blue;
            this.lblClient.Location = new System.Drawing.Point(718, 103);
            this.lblClient.Name = "lblClient";
            this.lblClient.Size = new System.Drawing.Size(21, 14);
            this.lblClient.TabIndex = 408;
            this.lblClient.Text = "\"\"";
            this.pbPaySum.Location = new System.Drawing.Point(154, 140);
            this.pbPaySum.Maximum = 1000;
            this.pbPaySum.Name = "pbPaySum";
            this.pbPaySum.Size = new System.Drawing.Size(1068, 3);
            this.pbPaySum.TabIndex = 409;
            this.cmbCompany.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCompany.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCompany.FormattingEnabled = true;
            this.cmbCompany.Location = new System.Drawing.Point(213, 7);
            this.cmbCompany.Name = "cmbCompany";
            this.cmbCompany.Size = new System.Drawing.Size(163, 21);
            this.cmbCompany.TabIndex = 411;
            this.cmbCompany.SelectedIndexChanged += new System.EventHandler(this.cmbCompany_SelectedIndexChanged);
            this.label36.AutoSize = true;
            this.label36.BackColor = System.Drawing.Color.Transparent;
            this.label36.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label36.Location = new System.Drawing.Point(125, 10);
            this.label36.Name = "label36";
            this.label36.Size = new System.Drawing.Size(62, 13);
            this.label36.TabIndex = 410;
            this.label36.Text = "Company";
            this.lblCompLogo.Location = new System.Drawing.Point(30, 36);
            this.lblCompLogo.Name = "lblCompLogo";
            this.lblCompLogo.Size = new System.Drawing.Size(67, 42);
            this.lblCompLogo.TabIndex = 412;
            this.lblCompLogo.Text = "Company Logo";
            this.lblCompLogo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEmail.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnEmail.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEmail.Location = new System.Drawing.Point(885, 631);
            this.btnEmail.Name = "btnEmail";
            this.btnEmail.Size = new System.Drawing.Size(79, 33);
            this.btnEmail.TabIndex = 415;
            this.btnEmail.Text = "&Email This";
            this.btnEmail.UseVisualStyleBackColor = true;
            this.btnEmail.Click += new System.EventHandler(this.btnEmail_Click);
            this.lblPrePaid.BackColor = System.Drawing.Color.Transparent;
            this.lblPrePaid.Font = new System.Drawing.Font("Lucida Bright", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPrePaid.ForeColor = System.Drawing.Color.Red;
            this.lblPrePaid.Location = new System.Drawing.Point(150, 614);
            this.lblPrePaid.Name = "lblPrePaid";
            this.lblPrePaid.Size = new System.Drawing.Size(483, 41);
            this.lblPrePaid.TabIndex = 416;
            this.lblPrePaid.Text = "\"\"";
            this.chkCmpny.AutoSize = true;
            this.chkCmpny.Checked = true;
            this.chkCmpny.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkCmpny.Location = new System.Drawing.Point(197, 11);
            this.chkCmpny.Name = "chkCmpny";
            this.chkCmpny.Size = new System.Drawing.Size(15, 14);
            this.chkCmpny.TabIndex = 417;
            this.chkCmpny.UseVisualStyleBackColor = true;
            this.chkCmpny.CheckedChanged += new System.EventHandler(this.chkCmpny_CheckedChanged);
            this.label13.AutoSize = true;
            this.label13.BackColor = System.Drawing.Color.Transparent;
            this.label13.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.Location = new System.Drawing.Point(125, 94);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(73, 13);
            this.label13.TabIndex = 418;
            this.label13.Text = "Pay Method";
            this.grpPayMethod.BackColor = System.Drawing.Color.Transparent;
            this.grpPayMethod.Controls.Add(this.rdbCash);
            this.grpPayMethod.Controls.Add(this.rdbBank);
            this.grpPayMethod.Location = new System.Drawing.Point(198, 84);
            this.grpPayMethod.Name = "grpPayMethod";
            this.grpPayMethod.Size = new System.Drawing.Size(178, 32);
            this.grpPayMethod.TabIndex = 419;
            this.grpPayMethod.TabStop = false;
            this.rdbCash.AutoSize = true;
            this.rdbCash.Location = new System.Drawing.Point(65, 10);
            this.rdbCash.Name = "rdbCash";
            this.rdbCash.Size = new System.Drawing.Size(49, 17);
            this.rdbCash.TabIndex = 1;
            this.rdbCash.TabStop = true;
            this.rdbCash.Text = "Cash";
            this.rdbCash.UseVisualStyleBackColor = true;
            this.rdbBank.AutoSize = true;
            this.rdbBank.Location = new System.Drawing.Point(5, 10);
            this.rdbBank.Name = "rdbBank";
            this.rdbBank.Size = new System.Drawing.Size(50, 17);
            this.rdbBank.TabIndex = 0;
            this.rdbBank.TabStop = true;
            this.rdbBank.Text = "Bank";
            this.rdbBank.UseVisualStyleBackColor = true;
            this.rdbBank.CheckedChanged += new System.EventHandler(this.rdbBank_CheckedChanged);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(1234, 670);
            this.ControlBox = false;
            this.Controls.Add(this.drpHotel);
            this.Controls.Add(this.grpPayMethod);
            this.Controls.Add(this.label13);
            this.Controls.Add(this.chkCmpny);
            this.Controls.Add(this.lblPrePaid);
            this.Controls.Add(this.btnEmail);
            this.Controls.Add(this.lblCompLogo);
            this.Controls.Add(this.cmbCompany);
            this.Controls.Add(this.label36);
            this.Controls.Add(this.pbPaySum);
            this.Controls.Add(this.lblClient);
            this.Controls.Add(this.btnClear);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.btnTour);
            this.Controls.Add(this.txtTourNo);
            this.Controls.Add(this.txtChkNo);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.btnUpdate);
            this.Controls.Add(this.btnDefRate);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.txtConRate);
            this.Controls.Add(this.dtpConfirmDate);
            this.Controls.Add(this.checkBox1);
            this.Controls.Add(this.groupBox10);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.groupBox9);
            this.Controls.Add(this.grdMealPay);
            this.Controls.Add(this.grdRoomPay);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.groupBox8);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.groupBox6);
            this.Controls.Add(this.groupBox5);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox4);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.groupBox19);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.label23);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.btnGetTot);
            this.Controls.Add(this.pbCompLogo);
            this.Controls.Add(this.chkPrint);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.gbDateRange);
            this.Controls.Add(this.btnPrint);
            this.Controls.Add(this.grdDuePayDaily);
            this.Controls.Add(this.btnOk);
            this.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.Name = "frmHotelMonthlyPay";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmHotelMonthlyPay_Load);
            ((System.ComponentModel.ISupportInitialize)(this.grdMealPay)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdRoomPay)).EndInit();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbCompLogo)).EndInit();
            this.gbDateRange.ResumeLayout(false);
            this.gbDateRange.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdDuePayDaily)).EndInit();
            this.grpPayMethod.ResumeLayout(false);
            this.grpPayMethod.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.CheckBox chkTodayPay;
        private System.Windows.Forms.CheckBox chkAllPaid;
        private System.Windows.Forms.Button btnUpdate;
        private System.Windows.Forms.Button btnDefRate;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox txtConRate;
        private System.Windows.Forms.DateTimePicker dtpConfirmDate;
        private System.Windows.Forms.CheckBox chkGuide;
        private System.Windows.Forms.CheckBox checkBox1;
        private System.Windows.Forms.GroupBox groupBox10;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.GroupBox groupBox9;
        private C1.Win.C1FlexGrid.C1FlexGrid grdMealPay;
        private C1.Win.C1FlexGrid.C1FlexGrid grdRoomPay;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.GroupBox groupBox8;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.GroupBox groupBox6;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.CheckBox chkOther;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox groupBox19;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label23;
        private System.Windows.Forms.DateTimePicker dtpFromDate;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.DateTimePicker dtpPaidDate;
        private System.Windows.Forms.Button btnGetTot;
        private System.Windows.Forms.DateTimePicker dtpToDate;
        private System.Windows.Forms.PictureBox pbCompLogo;
        private System.Windows.Forms.CheckBox chkPrint;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.GroupBox gbDateRange;
        private System.Windows.Forms.Button btnPrint;
        private C1.Win.C1FlexGrid.C1FlexGrid grdDuePayDaily;
        private System.Windows.Forms.Button btnOk;
        private DropDowns.DropSearch drpHotel;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.TextBox txtChkNo;
        private System.Windows.Forms.Button btnTour;
        private System.Windows.Forms.TextBox txtTourNo;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Button btnClear;
        private System.Windows.Forms.Label lblClient;
        private System.Windows.Forms.ProgressBar pbPaySum;
        private  Tourist_Management.User_Controls.ComboBox cmbCompany;
        private System.Windows.Forms.Label label36;
        private System.Windows.Forms.Label lblCompLogo;
        private System.Windows.Forms.Button btnEmail;
        private System.Windows.Forms.CheckBox chkEbed;
        private System.Windows.Forms.Label lblPrePaid;
        private System.Windows.Forms.CheckBox chkCmpny;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.GroupBox grpPayMethod;
        private System.Windows.Forms.RadioButton rdbCash;
        private System.Windows.Forms.RadioButton rdbBank;
    }
}