namespace Tourist_Management.Accounts
{
    partial class frmHotelDailyPay
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmHotelDailyPay));
            this.gbDateRange = new System.Windows.Forms.GroupBox();
            this.dtpToDate = new System.Windows.Forms.DateTimePicker();
            this.label1 = new System.Windows.Forms.Label();
            this.dtpFromDate = new System.Windows.Forms.DateTimePicker();
            this.label9 = new System.Windows.Forms.Label();
            this.btnPrint = new System.Windows.Forms.Button();
            this.label23 = new System.Windows.Forms.Label();
            this.grdDuePayDaily = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.btnOk = new System.Windows.Forms.Button();
            this.btnCancel = new System.Windows.Forms.Button();
            this.chkPrint = new System.Windows.Forms.CheckBox();
            this.btnGetTot = new System.Windows.Forms.Button();
            this.label12 = new System.Windows.Forms.Label();
            this.groupBox19 = new System.Windows.Forms.GroupBox();
            this.dtpConfirmDate = new System.Windows.Forms.DateTimePicker();
            this.label3 = new System.Windows.Forms.Label();
            this.dtpPaidDate = new System.Windows.Forms.DateTimePicker();
            this.label2 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.chkPrePay = new System.Windows.Forms.CheckBox();
            this.chkEbed = new System.Windows.Forms.CheckBox();
            this.chkOther = new System.Windows.Forms.CheckBox();
            this.chkGuide = new System.Windows.Forms.CheckBox();
            this.chkTodayPay = new System.Windows.Forms.CheckBox();
            this.chkAllPaid = new System.Windows.Forms.CheckBox();
            this.checkBox1 = new System.Windows.Forms.CheckBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.grdRoomPay = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.grdMealPay = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.label7 = new System.Windows.Forms.Label();
            this.groupBox10 = new System.Windows.Forms.GroupBox();
            this.txtConRate = new System.Windows.Forms.TextBox();
            this.btnDefRate = new System.Windows.Forms.Button();
            this.btnUpdate = new System.Windows.Forms.Button();
            this.pbPaySum = new System.Windows.Forms.ProgressBar();
            this.groupBox9 = new System.Windows.Forms.GroupBox();
            this.groupBox8 = new System.Windows.Forms.GroupBox();
            this.cmbCompany = new  Tourist_Management.User_Controls.ComboBox();
            this.label36 = new System.Windows.Forms.Label();
            this.pbImage = new System.Windows.Forms.PictureBox();
            this.lblCompLogo = new System.Windows.Forms.Label();
            this.btnEmail = new System.Windows.Forms.Button();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.chkCmpny = new System.Windows.Forms.CheckBox();
            this.lblPrePaid = new System.Windows.Forms.Label();
            this.grpPayMethod = new System.Windows.Forms.GroupBox();
            this.rdbCash = new System.Windows.Forms.RadioButton();
            this.rdbBank = new System.Windows.Forms.RadioButton();
            this.gbDateRange.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdDuePayDaily)).BeginInit();
            this.groupBox2.SuspendLayout();
            this.groupBox4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdRoomPay)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdMealPay)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbImage)).BeginInit();
            this.groupBox7.SuspendLayout();
            this.grpPayMethod.SuspendLayout();
            this.SuspendLayout();
            this.gbDateRange.BackColor = System.Drawing.Color.Transparent;
            this.gbDateRange.Controls.Add(this.dtpToDate);
            this.gbDateRange.Controls.Add(this.label1);
            this.gbDateRange.Controls.Add(this.dtpFromDate);
            this.gbDateRange.Controls.Add(this.label9);
            this.gbDateRange.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbDateRange.Location = new System.Drawing.Point(391, 19);
            this.gbDateRange.Name = "gbDateRange";
            this.gbDateRange.Size = new System.Drawing.Size(297, 75);
            this.gbDateRange.TabIndex = 333;
            this.gbDateRange.TabStop = false;
            this.dtpToDate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpToDate.Location = new System.Drawing.Point(80, 46);
            this.dtpToDate.Name = "dtpToDate";
            this.dtpToDate.Size = new System.Drawing.Size(212, 20);
            this.dtpToDate.TabIndex = 249;
            this.dtpToDate.ValueChanged += new System.EventHandler(this.dtpToDate_ValueChanged);
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(8, 46);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(52, 13);
            this.label1.TabIndex = 248;
            this.label1.Text = "Date To";
            this.dtpFromDate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpFromDate.Location = new System.Drawing.Point(80, 20);
            this.dtpFromDate.Name = "dtpFromDate";
            this.dtpFromDate.Size = new System.Drawing.Size(212, 20);
            this.dtpFromDate.TabIndex = 247;
            this.dtpFromDate.ValueChanged += new System.EventHandler(this.dtpFilterDate_ValueChanged);
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(8, 23);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(67, 13);
            this.label9.TabIndex = 246;
            this.label9.Text = "Date From";
            this.btnPrint.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPrint.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPrint.Image = global::Tourist_Management.Properties.Resources.search;
            this.btnPrint.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPrint.Location = new System.Drawing.Point(792, 615);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.Size = new System.Drawing.Size(79, 33);
            this.btnPrint.TabIndex = 336;
            this.btnPrint.Text = "&Preview";
            this.btnPrint.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPrint.UseVisualStyleBackColor = true;
            this.btnPrint.Click += new System.EventHandler(this.btnPrint_Click);
            this.label23.BackColor = System.Drawing.Color.Transparent;
            this.label23.Font = new System.Drawing.Font("Verdana", 15F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label23.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.label23.Location = new System.Drawing.Point(7, 308);
            this.label23.Name = "label23";
            this.label23.Size = new System.Drawing.Size(226, 54);
            this.label23.TabIndex = 334;
            this.label23.Text = "HOTEL DUE PAYMENTS  DAILY";
            this.label23.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.label23.UseCompatibleTextRendering = true;
            this.label23.Visible = false;
            this.grdDuePayDaily.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdDuePayDaily.ColumnInfo = "0,0,0,0,0,85,Columns:";
            this.grdDuePayDaily.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grdDuePayDaily.Location = new System.Drawing.Point(7, 145);
            this.grdDuePayDaily.Name = "grdDuePayDaily";
            this.grdDuePayDaily.Size = new System.Drawing.Size(1208, 230);
            this.grdDuePayDaily.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdDuePayDaily.Styles"));
            this.grdDuePayDaily.TabIndex = 337;
            this.grdDuePayDaily.AfterSelChange += new C1.Win.C1FlexGrid.RangeEventHandler(this.grdDuePayDaily_AfterSelChange);
            this.grdDuePayDaily.CellButtonClick += new C1.Win.C1FlexGrid.RowColEventHandler(this.grdDuePayDaily_CellButtonClick);
            this.btnOk.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnOk.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Image = global::Tourist_Management.Properties.Resources.floppy;
            this.btnOk.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOk.Location = new System.Drawing.Point(1053, 615);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(79, 33);
            this.btnOk.TabIndex = 335;
            this.btnOk.Text = "&Save";
            this.btnOk.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.btnCancel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCancel.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.Location = new System.Drawing.Point(1136, 615);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(79, 33);
            this.btnCancel.TabIndex = 339;
            this.btnCancel.Text = "&Close";
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.chkPrint.AutoSize = true;
            this.chkPrint.BackColor = System.Drawing.Color.Transparent;
            this.chkPrint.Checked = true;
            this.chkPrint.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkPrint.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkPrint.Location = new System.Drawing.Point(648, 622);
            this.chkPrint.Name = "chkPrint";
            this.chkPrint.Size = new System.Drawing.Size(136, 17);
            this.chkPrint.TabIndex = 340;
            this.chkPrint.Text = "Preview After Save";
            this.chkPrint.UseVisualStyleBackColor = false;
            this.btnGetTot.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnGetTot.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGetTot.Image = global::Tourist_Management.Properties.Resources.sum;
            this.btnGetTot.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGetTot.Location = new System.Drawing.Point(962, 615);
            this.btnGetTot.Name = "btnGetTot";
            this.btnGetTot.Size = new System.Drawing.Size(87, 33);
            this.btnGetTot.TabIndex = 342;
            this.btnGetTot.Text = "&Get Total";
            this.btnGetTot.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGetTot.UseVisualStyleBackColor = true;
            this.btnGetTot.Click += new System.EventHandler(this.btnGetTot_Click);
            this.label12.AutoSize = true;
            this.label12.BackColor = System.Drawing.Color.Transparent;
            this.label12.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label12.Location = new System.Drawing.Point(391, 12);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(116, 14);
            this.label12.TabIndex = 345;
            this.label12.Text = "FILTER BY DATE";
            this.groupBox19.BackColor = System.Drawing.Color.Gray;
            this.groupBox19.Location = new System.Drawing.Point(488, 24);
            this.groupBox19.Name = "groupBox19";
            this.groupBox19.Size = new System.Drawing.Size(207, 2);
            this.groupBox19.TabIndex = 344;
            this.groupBox19.TabStop = false;
            this.dtpConfirmDate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpConfirmDate.Location = new System.Drawing.Point(455, 103);
            this.dtpConfirmDate.Name = "dtpConfirmDate";
            this.dtpConfirmDate.Size = new System.Drawing.Size(212, 20);
            this.dtpConfirmDate.TabIndex = 349;
            this.dtpConfirmDate.Visible = false;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(396, 106);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(53, 13);
            this.label3.TabIndex = 348;
            this.label3.Text = "Confirm";
            this.label3.Visible = false;
            this.dtpPaidDate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpPaidDate.Location = new System.Drawing.Point(65, 16);
            this.dtpPaidDate.Name = "dtpPaidDate";
            this.dtpPaidDate.Size = new System.Drawing.Size(212, 20);
            this.dtpPaidDate.TabIndex = 347;
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(7, 17);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(31, 13);
            this.label2.TabIndex = 346;
            this.label2.Text = "Paid";
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label4.Location = new System.Drawing.Point(720, 13);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(190, 14);
            this.label4.TabIndex = 352;
            this.label4.Text = "SET PAID/CONFIRM DATES";
            this.groupBox1.BackColor = System.Drawing.Color.Gray;
            this.groupBox1.Location = new System.Drawing.Point(814, 25);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(189, 2);
            this.groupBox1.TabIndex = 351;
            this.groupBox1.TabStop = false;
            this.groupBox2.BackColor = System.Drawing.Color.Transparent;
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Controls.Add(this.dtpPaidDate);
            this.groupBox2.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.Location = new System.Drawing.Point(718, 19);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(287, 48);
            this.groupBox2.TabIndex = 350;
            this.groupBox2.TabStop = false;
            this.groupBox4.BackColor = System.Drawing.Color.Transparent;
            this.groupBox4.Controls.Add(this.chkPrePay);
            this.groupBox4.Controls.Add(this.chkEbed);
            this.groupBox4.Controls.Add(this.chkOther);
            this.groupBox4.Controls.Add(this.chkGuide);
            this.groupBox4.Controls.Add(this.chkTodayPay);
            this.groupBox4.Controls.Add(this.chkAllPaid);
            this.groupBox4.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox4.Location = new System.Drawing.Point(1031, 5);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(184, 135);
            this.groupBox4.TabIndex = 352;
            this.groupBox4.TabStop = false;
            this.chkPrePay.AutoSize = true;
            this.chkPrePay.BackColor = System.Drawing.Color.Transparent;
            this.chkPrePay.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkPrePay.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkPrePay.Location = new System.Drawing.Point(14, 113);
            this.chkPrePay.Name = "chkPrePay";
            this.chkPrePay.Size = new System.Drawing.Size(116, 17);
            this.chkPrePay.TabIndex = 350;
            this.chkPrePay.Text = "Pre payments";
            this.chkPrePay.UseVisualStyleBackColor = false;
            this.chkPrePay.CheckedChanged += new System.EventHandler(this.chkPrePay_CheckedChanged);
            this.chkEbed.AutoSize = true;
            this.chkEbed.BackColor = System.Drawing.Color.Transparent;
            this.chkEbed.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkEbed.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkEbed.Location = new System.Drawing.Point(13, 93);
            this.chkEbed.Name = "chkEbed";
            this.chkEbed.Size = new System.Drawing.Size(89, 17);
            this.chkEbed.TabIndex = 349;
            this.chkEbed.Text = "Extra Bed";
            this.chkEbed.UseVisualStyleBackColor = false;
            this.chkEbed.CheckedChanged += new System.EventHandler(this.chkEbed_CheckedChanged);
            this.chkOther.AutoSize = true;
            this.chkOther.BackColor = System.Drawing.Color.Transparent;
            this.chkOther.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkOther.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkOther.Location = new System.Drawing.Point(13, 74);
            this.chkOther.Name = "chkOther";
            this.chkOther.Size = new System.Drawing.Size(130, 17);
            this.chkOther.TabIndex = 348;
            this.chkOther.Text = "Other Payments";
            this.chkOther.UseVisualStyleBackColor = false;
            this.chkOther.CheckedChanged += new System.EventHandler(this.chkOther_CheckedChanged);
            this.chkGuide.AutoSize = true;
            this.chkGuide.BackColor = System.Drawing.Color.Transparent;
            this.chkGuide.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkGuide.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkGuide.Location = new System.Drawing.Point(13, 54);
            this.chkGuide.Name = "chkGuide";
            this.chkGuide.Size = new System.Drawing.Size(159, 17);
            this.chkGuide.TabIndex = 347;
            this.chkGuide.Text = "Separate Guide Rate";
            this.chkGuide.UseVisualStyleBackColor = false;
            this.chkGuide.CheckedChanged += new System.EventHandler(this.chkGuide_CheckedChanged);
            this.chkTodayPay.AutoSize = true;
            this.chkTodayPay.BackColor = System.Drawing.Color.Transparent;
            this.chkTodayPay.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkTodayPay.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkTodayPay.Location = new System.Drawing.Point(13, 13);
            this.chkTodayPay.Name = "chkTodayPay";
            this.chkTodayPay.Size = new System.Drawing.Size(87, 17);
            this.chkTodayPay.TabIndex = 345;
            this.chkTodayPay.Text = "Paid Only";
            this.chkTodayPay.UseVisualStyleBackColor = false;
            this.chkTodayPay.CheckedChanged += new System.EventHandler(this.chkTodayPay_CheckedChanged);
            this.chkAllPaid.AutoSize = true;
            this.chkAllPaid.BackColor = System.Drawing.Color.Transparent;
            this.chkAllPaid.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkAllPaid.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.chkAllPaid.Location = new System.Drawing.Point(13, 34);
            this.chkAllPaid.Name = "chkAllPaid";
            this.chkAllPaid.Size = new System.Drawing.Size(131, 17);
            this.chkAllPaid.TabIndex = 344;
            this.chkAllPaid.Text = "Mark All As Paid";
            this.chkAllPaid.UseVisualStyleBackColor = false;
            this.chkAllPaid.CheckedChanged += new System.EventHandler(this.chkAllPaid_CheckedChanged);
            this.checkBox1.AutoSize = true;
            this.checkBox1.BackColor = System.Drawing.Color.Transparent;
            this.checkBox1.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.checkBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.checkBox1.Location = new System.Drawing.Point(689, 108);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Size = new System.Drawing.Size(130, 17);
            this.checkBox1.TabIndex = 346;
            this.checkBox1.Text = "Confirm All Paid";
            this.checkBox1.UseVisualStyleBackColor = false;
            this.checkBox1.Visible = false;
            this.checkBox1.CheckedChanged += new System.EventHandler(this.checkBox1_CheckedChanged);
            this.groupBox3.BackColor = System.Drawing.Color.Gray;
            this.groupBox3.Location = new System.Drawing.Point(374, 15);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(4, 83);
            this.groupBox3.TabIndex = 352;
            this.groupBox3.TabStop = false;
            this.groupBox5.BackColor = System.Drawing.Color.Gray;
            this.groupBox5.Location = new System.Drawing.Point(705, 15);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(4, 83);
            this.groupBox5.TabIndex = 353;
            this.groupBox5.TabStop = false;
            this.groupBox6.BackColor = System.Drawing.Color.Gray;
            this.groupBox6.Location = new System.Drawing.Point(1011, 15);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(4, 83);
            this.groupBox6.TabIndex = 354;
            this.groupBox6.TabStop = false;
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label5.Location = new System.Drawing.Point(4, 123);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(145, 14);
            this.label5.TabIndex = 356;
            this.label5.Text = "PAYMENT SUMMARY";
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label6.Location = new System.Drawing.Point(4, 387);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(131, 14);
            this.label6.TabIndex = 358;
            this.label6.Text = "ROOM PAYMENTS ";
            this.grdRoomPay.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdRoomPay.ColumnInfo = "0,0,0,0,0,85,Columns:";
            this.grdRoomPay.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grdRoomPay.Location = new System.Drawing.Point(7, 407);
            this.grdRoomPay.Name = "grdRoomPay";
            this.grdRoomPay.Size = new System.Drawing.Size(688, 198);
            this.grdRoomPay.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdRoomPay.Styles"));
            this.grdRoomPay.TabIndex = 359;
            this.grdRoomPay.AfterSelChange += new C1.Win.C1FlexGrid.RangeEventHandler(this.grdRoomPay_AfterSelChange);
            this.grdMealPay.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdMealPay.ColumnInfo = "0,0,0,0,0,85,Columns:";
            this.grdMealPay.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grdMealPay.Location = new System.Drawing.Point(716, 407);
            this.grdMealPay.Name = "grdMealPay";
            this.grdMealPay.Size = new System.Drawing.Size(499, 198);
            this.grdMealPay.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdMealPay.Styles"));
            this.grdMealPay.TabIndex = 360;
            this.grdMealPay.AfterSelChange += new C1.Win.C1FlexGrid.RangeEventHandler(this.grdMealPay_AfterSelChange);
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.Transparent;
            this.label7.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label7.Location = new System.Drawing.Point(719, 387);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(125, 14);
            this.label7.TabIndex = 362;
            this.label7.Text = "MEAL PAYMENTS ";
            this.groupBox10.BackColor = System.Drawing.Color.Gray;
            this.groupBox10.Location = new System.Drawing.Point(707, 389);
            this.groupBox10.Name = "groupBox10";
            this.groupBox10.Size = new System.Drawing.Size(2, 218);
            this.groupBox10.TabIndex = 363;
            this.groupBox10.TabStop = false;
            this.txtConRate.BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            this.txtConRate.Location = new System.Drawing.Point(718, 73);
            this.txtConRate.Name = "txtConRate";
            this.txtConRate.Size = new System.Drawing.Size(135, 21);
            this.txtConRate.TabIndex = 364;
            this.txtConRate.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.btnDefRate.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnDefRate.Location = new System.Drawing.Point(857, 72);
            this.btnDefRate.Name = "btnDefRate";
            this.btnDefRate.Size = new System.Drawing.Size(148, 23);
            this.btnDefRate.TabIndex = 365;
            this.btnDefRate.Text = "Set Default Conv.Rate";
            this.btnDefRate.UseVisualStyleBackColor = true;
            this.btnDefRate.Click += new System.EventHandler(this.btnDefRate_Click);
            this.btnUpdate.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnUpdate.Font = new System.Drawing.Font("Verdana", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUpdate.Image = global::Tourist_Management.Properties.Resources.upload;
            this.btnUpdate.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUpdate.Location = new System.Drawing.Point(7, 607);
            this.btnUpdate.Name = "btnUpdate";
            this.btnUpdate.Size = new System.Drawing.Size(130, 42);
            this.btnUpdate.TabIndex = 366;
            this.btnUpdate.Text = "&Update Above Rates To Hotels";
            this.btnUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUpdate.UseVisualStyleBackColor = true;
            this.btnUpdate.Click += new System.EventHandler(this.btnUpdate_Click);
            this.pbPaySum.Location = new System.Drawing.Point(147, 133);
            this.pbPaySum.Maximum = 1000;
            this.pbPaySum.Name = "pbPaySum";
            this.pbPaySum.Size = new System.Drawing.Size(867, 3);
            this.pbPaySum.TabIndex = 367;
            this.groupBox9.BackColor = System.Drawing.Color.Gray;
            this.groupBox9.Location = new System.Drawing.Point(758, 396);
            this.groupBox9.Name = "groupBox9";
            this.groupBox9.Size = new System.Drawing.Size(457, 5);
            this.groupBox9.TabIndex = 361;
            this.groupBox9.TabStop = false;
            this.groupBox8.BackColor = System.Drawing.Color.Gray;
            this.groupBox8.Location = new System.Drawing.Point(101, 396);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new System.Drawing.Size(592, 5);
            this.groupBox8.TabIndex = 357;
            this.groupBox8.TabStop = false;
            this.cmbCompany.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCompany.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCompany.FormattingEnabled = true;
            this.cmbCompany.Location = new System.Drawing.Point(73, 20);
            this.cmbCompany.Name = "cmbCompany";
            this.cmbCompany.Size = new System.Drawing.Size(173, 21);
            this.cmbCompany.TabIndex = 380;
            this.cmbCompany.SelectedIndexChanged += new System.EventHandler(this.cmbCompany_SelectedIndexChanged);
            this.label36.AutoSize = true;
            this.label36.BackColor = System.Drawing.Color.Transparent;
            this.label36.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label36.ForeColor = System.Drawing.Color.Black;
            this.label36.Location = new System.Drawing.Point(6, 23);
            this.label36.Name = "label36";
            this.label36.Size = new System.Drawing.Size(62, 13);
            this.label36.TabIndex = 379;
            this.label36.Text = "Company";
            this.label36.Click += new System.EventHandler(this.label36_Click);
            this.pbImage.Location = new System.Drawing.Point(7, 5);
            this.pbImage.Name = "pbImage";
            this.pbImage.Size = new System.Drawing.Size(102, 107);
            this.pbImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbImage.TabIndex = 381;
            this.pbImage.TabStop = false;
            this.lblCompLogo.Location = new System.Drawing.Point(28, 36);
            this.lblCompLogo.Name = "lblCompLogo";
            this.lblCompLogo.Size = new System.Drawing.Size(67, 42);
            this.lblCompLogo.TabIndex = 413;
            this.lblCompLogo.Text = "Company Logo";
            this.lblCompLogo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEmail.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnEmail.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEmail.Location = new System.Drawing.Point(877, 615);
            this.btnEmail.Name = "btnEmail";
            this.btnEmail.Size = new System.Drawing.Size(79, 33);
            this.btnEmail.TabIndex = 414;
            this.btnEmail.Text = "&Email This";
            this.btnEmail.UseVisualStyleBackColor = true;
            this.btnEmail.Click += new System.EventHandler(this.btnEmail_Click);
            this.groupBox7.BackColor = System.Drawing.Color.Transparent;
            this.groupBox7.Controls.Add(this.chkCmpny);
            this.groupBox7.Controls.Add(this.cmbCompany);
            this.groupBox7.Controls.Add(this.label36);
            this.groupBox7.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold);
            this.groupBox7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.groupBox7.Location = new System.Drawing.Point(115, 9);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(253, 54);
            this.groupBox7.TabIndex = 415;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "COMPANY";
            this.chkCmpny.AutoSize = true;
            this.chkCmpny.Checked = true;
            this.chkCmpny.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkCmpny.Location = new System.Drawing.Point(82, 0);
            this.chkCmpny.Name = "chkCmpny";
            this.chkCmpny.Size = new System.Drawing.Size(15, 14);
            this.chkCmpny.TabIndex = 381;
            this.chkCmpny.UseVisualStyleBackColor = true;
            this.chkCmpny.CheckedChanged += new System.EventHandler(this.chkCmpny_CheckedChanged);
            this.lblPrePaid.BackColor = System.Drawing.Color.Transparent;
            this.lblPrePaid.Font = new System.Drawing.Font("Lucida Bright", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPrePaid.ForeColor = System.Drawing.Color.Red;
            this.lblPrePaid.Location = new System.Drawing.Point(139, 609);
            this.lblPrePaid.Name = "lblPrePaid";
            this.lblPrePaid.Size = new System.Drawing.Size(483, 41);
            this.lblPrePaid.TabIndex = 417;
            this.lblPrePaid.Text = "\"\"";
            this.grpPayMethod.BackColor = System.Drawing.Color.Transparent;
            this.grpPayMethod.Controls.Add(this.rdbCash);
            this.grpPayMethod.Controls.Add(this.rdbBank);
            this.grpPayMethod.Location = new System.Drawing.Point(115, 63);
            this.grpPayMethod.Name = "grpPayMethod";
            this.grpPayMethod.Size = new System.Drawing.Size(253, 41);
            this.grpPayMethod.TabIndex = 421;
            this.grpPayMethod.TabStop = false;
            this.grpPayMethod.Text = "Pay Method";
            this.rdbCash.AutoSize = true;
            this.rdbCash.Location = new System.Drawing.Point(65, 18);
            this.rdbCash.Name = "rdbCash";
            this.rdbCash.Size = new System.Drawing.Size(49, 17);
            this.rdbCash.TabIndex = 1;
            this.rdbCash.TabStop = true;
            this.rdbCash.Text = "Cash";
            this.rdbCash.UseVisualStyleBackColor = true;
            this.rdbBank.AutoSize = true;
            this.rdbBank.Location = new System.Drawing.Point(5, 18);
            this.rdbBank.Name = "rdbBank";
            this.rdbBank.Size = new System.Drawing.Size(50, 17);
            this.rdbBank.TabIndex = 0;
            this.rdbBank.TabStop = true;
            this.rdbBank.Text = "Bank";
            this.rdbBank.UseVisualStyleBackColor = true;
            this.rdbBank.CheckedChanged += new System.EventHandler(this.rdbBank_CheckedChanged);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(1221, 653);
            this.ControlBox = false;
            this.Controls.Add(this.grpPayMethod);
            this.Controls.Add(this.lblPrePaid);
            this.Controls.Add(this.groupBox7);
            this.Controls.Add(this.btnEmail);
            this.Controls.Add(this.lblCompLogo);
            this.Controls.Add(this.pbImage);
            this.Controls.Add(this.pbPaySum);
            this.Controls.Add(this.btnUpdate);
            this.Controls.Add(this.btnDefRate);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.txtConRate);
            this.Controls.Add(this.dtpConfirmDate);
            this.Controls.Add(this.checkBox1);
            this.Controls.Add(this.groupBox10);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.groupBox9);
            this.Controls.Add(this.grdMealPay);
            this.Controls.Add(this.grdRoomPay);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.groupBox8);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.groupBox6);
            this.Controls.Add(this.groupBox5);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox4);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.groupBox19);
            this.Controls.Add(this.label23);
            this.Controls.Add(this.btnGetTot);
            this.Controls.Add(this.chkPrint);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.gbDateRange);
            this.Controls.Add(this.btnPrint);
            this.Controls.Add(this.grdDuePayDaily);
            this.Controls.Add(this.btnOk);
            this.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmHotelDailyPay";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmHotelDailyPay_Load);
            this.gbDateRange.ResumeLayout(false);
            this.gbDateRange.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdDuePayDaily)).EndInit();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdRoomPay)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdMealPay)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbImage)).EndInit();
            this.groupBox7.ResumeLayout(false);
            this.groupBox7.PerformLayout();
            this.grpPayMethod.ResumeLayout(false);
            this.grpPayMethod.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.GroupBox gbDateRange;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Button btnPrint;
        private C1.Win.C1FlexGrid.C1FlexGrid grdDuePayDaily;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.CheckBox chkPrint;
        private System.Windows.Forms.DateTimePicker dtpFromDate;
        private System.Windows.Forms.DateTimePicker dtpToDate;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button btnGetTot;
        private System.Windows.Forms.Label label23;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.GroupBox groupBox19;
        private System.Windows.Forms.DateTimePicker dtpConfirmDate;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.DateTimePicker dtpPaidDate;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.CheckBox checkBox1;
        private System.Windows.Forms.CheckBox chkTodayPay;
        private System.Windows.Forms.CheckBox chkAllPaid;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.GroupBox groupBox6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private C1.Win.C1FlexGrid.C1FlexGrid grdRoomPay;
        private C1.Win.C1FlexGrid.C1FlexGrid grdMealPay;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.GroupBox groupBox10;
        private System.Windows.Forms.TextBox txtConRate;
        private System.Windows.Forms.Button btnDefRate;
        private System.Windows.Forms.CheckBox chkGuide;
        private System.Windows.Forms.CheckBox chkOther;
        private System.Windows.Forms.Button btnUpdate;
        private System.Windows.Forms.ProgressBar pbPaySum;
        private System.Windows.Forms.GroupBox groupBox9;
        private System.Windows.Forms.GroupBox groupBox8;
        private  Tourist_Management.User_Controls.ComboBox cmbCompany;
        private System.Windows.Forms.Label label36;
        private System.Windows.Forms.PictureBox pbImage;
        private System.Windows.Forms.Label lblCompLogo;
        private System.Windows.Forms.Button btnEmail;
        private System.Windows.Forms.CheckBox chkEbed;
        private System.Windows.Forms.GroupBox groupBox7;
        private System.Windows.Forms.CheckBox chkCmpny;
        private System.Windows.Forms.Label lblPrePaid;
        private System.Windows.Forms.CheckBox chkPrePay;
        private System.Windows.Forms.GroupBox grpPayMethod;
        private System.Windows.Forms.RadioButton rdbCash;
        private System.Windows.Forms.RadioButton rdbBank;
    }
}