namespace Tourist_Management.Accounts
{
    partial class frmIOUSettlement
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.dtpSettlement = new System.Windows.Forms.DateTimePicker();
            this.rtxtDescription = new System.Windows.Forms.RichTextBox();
            this.txtAmount = new System.Windows.Forms.TextBox();
            this.txtSettlementNo = new System.Windows.Forms.TextBox();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.drpPaymentTo = new Tourist_Management.DropDowns.DropSearch();
            this.drpSettlePerson = new Tourist_Management.DropDowns.DropSearch();
            this.btnPrint = new System.Windows.Forms.Button();
            this.chkPrint = new System.Windows.Forms.CheckBox();
            this.drpCompany = new Tourist_Management.DropDowns.DropSearch();
            this.label7 = new System.Windows.Forms.Label();
            this.btnTour = new System.Windows.Forms.Button();
            this.txtTourNo = new System.Windows.Forms.TextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.rdbDriver = new System.Windows.Forms.RadioButton();
            this.rdbGuide = new System.Windows.Forms.RadioButton();
            this.rdbHotel = new System.Windows.Forms.RadioButton();
            this.rdbAgent = new System.Windows.Forms.RadioButton();
            this.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(14, 14);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(87, 13);
            this.label1.TabIndex = 1;
            this.label1.Text = "Settlement No";
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Location = new System.Drawing.Point(14, 70);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(30, 13);
            this.label2.TabIndex = 2;
            this.label2.Text = "Date";
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Location = new System.Drawing.Point(14, 152);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(64, 13);
            this.label3.TabIndex = 3;
            this.label3.Text = "Payment To";
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Location = new System.Drawing.Point(14, 176);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(43, 13);
            this.label4.TabIndex = 4;
            this.label4.Text = "Amount";
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Location = new System.Drawing.Point(14, 206);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(60, 13);
            this.label5.TabIndex = 5;
            this.label5.Text = "Description";
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.Location = new System.Drawing.Point(14, 304);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(85, 13);
            this.label6.TabIndex = 6;
            this.label6.Text = "to Be Settled On";
            this.dtpSettlement.Location = new System.Drawing.Point(111, 70);
            this.dtpSettlement.Name = "dtpSettlement";
            this.dtpSettlement.Size = new System.Drawing.Size(215, 20);
            this.dtpSettlement.TabIndex = 7;
            this.rtxtDescription.Location = new System.Drawing.Point(111, 206);
            this.rtxtDescription.MaxLength = 500;
            this.rtxtDescription.Name = "rtxtDescription";
            this.rtxtDescription.Size = new System.Drawing.Size(216, 78);
            this.rtxtDescription.TabIndex = 10;
            this.rtxtDescription.Text = "";
            this.txtAmount.Location = new System.Drawing.Point(111, 176);
            this.txtAmount.Name = "txtAmount";
            this.txtAmount.Size = new System.Drawing.Size(215, 20);
            this.txtAmount.TabIndex = 11;
            this.txtSettlementNo.Enabled = false;
            this.txtSettlementNo.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSettlementNo.Location = new System.Drawing.Point(110, 11);
            this.txtSettlementNo.Name = "txtSettlementNo";
            this.txtSettlementNo.ReadOnly = true;
            this.txtSettlementNo.Size = new System.Drawing.Size(216, 20);
            this.txtSettlementNo.TabIndex = 12;
            this.btnCancel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCancel.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.Location = new System.Drawing.Point(260, 359);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(76, 29);
            this.btnCancel.TabIndex = 245;
            this.btnCancel.Text = "&Close";
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnOk.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnOk.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Image = global::Tourist_Management.Properties.Resources.floppy;
            this.btnOk.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOk.Location = new System.Drawing.Point(178, 359);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(76, 29);
            this.btnOk.TabIndex = 244;
            this.btnOk.Text = "&Save";
            this.btnOk.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.drpPaymentTo.BackColor = System.Drawing.Color.Transparent;
            this.drpPaymentTo.DataSource = null;
            this.drpPaymentTo.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpPaymentTo.Location = new System.Drawing.Point(110, 150);
            this.drpPaymentTo.Name = "drpPaymentTo";
            this.drpPaymentTo.SelectedText = "";
            this.drpPaymentTo.SelectedValue = "";
            this.drpPaymentTo.Size = new System.Drawing.Size(216, 20);
            this.drpPaymentTo.TabIndex = 262;
            this.drpSettlePerson.BackColor = System.Drawing.Color.Transparent;
            this.drpSettlePerson.DataSource = null;
            this.drpSettlePerson.Enabled = false;
            this.drpSettlePerson.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpSettlePerson.Location = new System.Drawing.Point(111, 301);
            this.drpSettlePerson.Name = "drpSettlePerson";
            this.drpSettlePerson.SelectedText = "";
            this.drpSettlePerson.SelectedValue = "";
            this.drpSettlePerson.Size = new System.Drawing.Size(216, 20);
            this.drpSettlePerson.TabIndex = 263;
            this.btnPrint.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPrint.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPrint.Image = global::Tourist_Management.Properties.Resources.search;
            this.btnPrint.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPrint.Location = new System.Drawing.Point(96, 359);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.Size = new System.Drawing.Size(76, 29);
            this.btnPrint.TabIndex = 264;
            this.btnPrint.Text = "&Preview";
            this.btnPrint.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPrint.UseVisualStyleBackColor = true;
            this.btnPrint.Click += new System.EventHandler(this.btnPrint_Click);
            this.chkPrint.AutoSize = true;
            this.chkPrint.BackColor = System.Drawing.Color.Transparent;
            this.chkPrint.Checked = true;
            this.chkPrint.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkPrint.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkPrint.Location = new System.Drawing.Point(17, 329);
            this.chkPrint.Name = "chkPrint";
            this.chkPrint.Size = new System.Drawing.Size(117, 17);
            this.chkPrint.TabIndex = 265;
            this.chkPrint.Text = "Print After Save";
            this.chkPrint.UseVisualStyleBackColor = false;
            this.drpCompany.BackColor = System.Drawing.Color.Transparent;
            this.drpCompany.DataSource = null;
            this.drpCompany.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpCompany.Location = new System.Drawing.Point(110, 96);
            this.drpCompany.Name = "drpCompany";
            this.drpCompany.SelectedText = "";
            this.drpCompany.SelectedValue = "";
            this.drpCompany.Size = new System.Drawing.Size(216, 20);
            this.drpCompany.TabIndex = 267;
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.Transparent;
            this.label7.Location = new System.Drawing.Point(14, 97);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(51, 13);
            this.label7.TabIndex = 266;
            this.label7.Text = "Company";
            this.btnTour.Location = new System.Drawing.Point(293, 36);
            this.btnTour.Name = "btnTour";
            this.btnTour.Size = new System.Drawing.Size(34, 23);
            this.btnTour.TabIndex = 268;
            this.btnTour.Text = "...";
            this.btnTour.UseVisualStyleBackColor = true;
            this.btnTour.Click += new System.EventHandler(this.btnTour_Click);
            this.txtTourNo.Enabled = false;
            this.txtTourNo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTourNo.ForeColor = System.Drawing.Color.Blue;
            this.txtTourNo.Location = new System.Drawing.Point(111, 37);
            this.txtTourNo.Name = "txtTourNo";
            this.txtTourNo.ReadOnly = true;
            this.txtTourNo.Size = new System.Drawing.Size(179, 21);
            this.txtTourNo.TabIndex = 269;
            this.label8.AutoSize = true;
            this.label8.BackColor = System.Drawing.Color.Transparent;
            this.label8.Location = new System.Drawing.Point(14, 41);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(43, 13);
            this.label8.TabIndex = 270;
            this.label8.Text = "Tour ID";
            this.rdbDriver.AutoSize = true;
            this.rdbDriver.BackColor = System.Drawing.Color.Transparent;
            this.rdbDriver.Checked = true;
            this.rdbDriver.Location = new System.Drawing.Point(113, 126);
            this.rdbDriver.Name = "rdbDriver";
            this.rdbDriver.Size = new System.Drawing.Size(53, 17);
            this.rdbDriver.TabIndex = 271;
            this.rdbDriver.TabStop = true;
            this.rdbDriver.Text = "Driver";
            this.rdbDriver.UseVisualStyleBackColor = false;
            this.rdbDriver.Visible = false;
            this.rdbDriver.CheckedChanged += new System.EventHandler(this.rdbDriver_CheckedChanged);
            this.rdbGuide.AutoSize = true;
            this.rdbGuide.BackColor = System.Drawing.Color.Transparent;
            this.rdbGuide.Location = new System.Drawing.Point(170, 126);
            this.rdbGuide.Name = "rdbGuide";
            this.rdbGuide.Size = new System.Drawing.Size(53, 17);
            this.rdbGuide.TabIndex = 272;
            this.rdbGuide.Text = "Guide";
            this.rdbGuide.UseVisualStyleBackColor = false;
            this.rdbGuide.Visible = false;
            this.rdbGuide.CheckedChanged += new System.EventHandler(this.rdbGuide_CheckedChanged);
            this.rdbHotel.AutoSize = true;
            this.rdbHotel.BackColor = System.Drawing.Color.Transparent;
            this.rdbHotel.Location = new System.Drawing.Point(285, 126);
            this.rdbHotel.Name = "rdbHotel";
            this.rdbHotel.Size = new System.Drawing.Size(50, 17);
            this.rdbHotel.TabIndex = 274;
            this.rdbHotel.Text = "Hotel";
            this.rdbHotel.UseVisualStyleBackColor = false;
            this.rdbHotel.Visible = false;
            this.rdbHotel.CheckedChanged += new System.EventHandler(this.rdbHotel_CheckedChanged);
            this.rdbAgent.AutoSize = true;
            this.rdbAgent.BackColor = System.Drawing.Color.Transparent;
            this.rdbAgent.Location = new System.Drawing.Point(228, 126);
            this.rdbAgent.Name = "rdbAgent";
            this.rdbAgent.Size = new System.Drawing.Size(53, 17);
            this.rdbAgent.TabIndex = 273;
            this.rdbAgent.Text = "Agent";
            this.rdbAgent.UseVisualStyleBackColor = false;
            this.rdbAgent.Visible = false;
            this.rdbAgent.CheckedChanged += new System.EventHandler(this.rdbAgent_CheckedChanged);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(350, 395);
            this.ControlBox = false;
            this.Controls.Add(this.rdbHotel);
            this.Controls.Add(this.rdbAgent);
            this.Controls.Add(this.rdbGuide);
            this.Controls.Add(this.rdbDriver);
            this.Controls.Add(this.drpCompany);
            this.Controls.Add(this.drpSettlePerson);
            this.Controls.Add(this.drpPaymentTo);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.btnTour);
            this.Controls.Add(this.txtTourNo);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.chkPrint);
            this.Controls.Add(this.btnPrint);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.txtSettlementNo);
            this.Controls.Add(this.txtAmount);
            this.Controls.Add(this.rtxtDescription);
            this.Controls.Add(this.dtpSettlement);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.Name = "frmIOUSettlement";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmIOU_Settlement_Load);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.DateTimePicker dtpSettlement;
        private System.Windows.Forms.RichTextBox rtxtDescription;
        private System.Windows.Forms.TextBox txtAmount;
        private System.Windows.Forms.TextBox txtSettlementNo;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnOk;
        private DropDowns.DropSearch drpPaymentTo;
        private DropDowns.DropSearch drpSettlePerson;
        private System.Windows.Forms.Button btnPrint;
        private System.Windows.Forms.CheckBox chkPrint;
        private DropDowns.DropSearch drpCompany;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Button btnTour;
        private System.Windows.Forms.TextBox txtTourNo;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.RadioButton rdbDriver;
        private System.Windows.Forms.RadioButton rdbGuide;
        private System.Windows.Forms.RadioButton rdbHotel;
        private System.Windows.Forms.RadioButton rdbAgent;
    }
}