namespace Tourist_Management.Accounts
{
    partial class frmIouViewer
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmIouViewer));
            this.groupBox35 = new System.Windows.Forms.GroupBox();
            this.rdbCancelled = new System.Windows.Forms.RadioButton();
            this.rdbAl = new System.Windows.Forms.RadioButton();
            this.rdbUnSettled = new System.Windows.Forms.RadioButton();
            this.rdbSettled = new System.Windows.Forms.RadioButton();
            this.btnICancel = new System.Windows.Forms.Button();
            this.btnIPreview = new System.Windows.Forms.Button();
            this.grdViewer = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.ucFilterByOther1 = new Tourist_Management.User_Controls.ucFilterByOther();
            this.ucFilterByDate1 = new Tourist_Management.User_Controls.ucFilterByDate();
            this.ucFilterByCompany1 = new Tourist_Management.User_Controls.ucFilterByCompany();
            this.btnFilter = new System.Windows.Forms.Button();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.rdbIOU = new System.Windows.Forms.RadioButton();
            this.rdbCash = new System.Windows.Forms.RadioButton();
            this.rdbChk = new System.Windows.Forms.RadioButton();
            this.groupBox35.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdViewer)).BeginInit();
            this.SuspendLayout();
            this.groupBox35.BackColor = System.Drawing.Color.Transparent;
            this.groupBox35.Controls.Add(this.rdbCancelled);
            this.groupBox35.Controls.Add(this.rdbAl);
            this.groupBox35.Controls.Add(this.rdbUnSettled);
            this.groupBox35.Controls.Add(this.rdbSettled);
            this.groupBox35.Font = new System.Drawing.Font("Lucida Bright", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox35.Location = new System.Drawing.Point(12, 108);
            this.groupBox35.Name = "groupBox35";
            this.groupBox35.Size = new System.Drawing.Size(336, 47);
            this.groupBox35.TabIndex = 378;
            this.groupBox35.TabStop = false;
            this.groupBox35.Text = "Payment State";
            this.rdbCancelled.AutoSize = true;
            this.rdbCancelled.Location = new System.Drawing.Point(191, 17);
            this.rdbCancelled.Name = "rdbCancelled";
            this.rdbCancelled.Size = new System.Drawing.Size(92, 19);
            this.rdbCancelled.TabIndex = 3;
            this.rdbCancelled.Text = "Cancelled";
            this.rdbCancelled.UseVisualStyleBackColor = true;
            this.rdbAl.AutoSize = true;
            this.rdbAl.Location = new System.Drawing.Point(289, 18);
            this.rdbAl.Name = "rdbAl";
            this.rdbAl.Size = new System.Drawing.Size(43, 19);
            this.rdbAl.TabIndex = 2;
            this.rdbAl.Text = "All";
            this.rdbAl.UseVisualStyleBackColor = true;
            this.rdbUnSettled.AutoSize = true;
            this.rdbUnSettled.Location = new System.Drawing.Point(85, 18);
            this.rdbUnSettled.Name = "rdbUnSettled";
            this.rdbUnSettled.Size = new System.Drawing.Size(100, 19);
            this.rdbUnSettled.TabIndex = 1;
            this.rdbUnSettled.Text = "UnSetteled";
            this.rdbUnSettled.UseVisualStyleBackColor = true;
            this.rdbSettled.AutoSize = true;
            this.rdbSettled.Checked = true;
            this.rdbSettled.Location = new System.Drawing.Point(6, 18);
            this.rdbSettled.Name = "rdbSettled";
            this.rdbSettled.Size = new System.Drawing.Size(74, 19);
            this.rdbSettled.TabIndex = 0;
            this.rdbSettled.TabStop = true;
            this.rdbSettled.Text = "Settled";
            this.rdbSettled.UseVisualStyleBackColor = true;
            this.btnICancel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnICancel.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnICancel.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnICancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnICancel.Location = new System.Drawing.Point(612, 495);
            this.btnICancel.Name = "btnICancel";
            this.btnICancel.Size = new System.Drawing.Size(72, 30);
            this.btnICancel.TabIndex = 380;
            this.btnICancel.Text = "&Cancel";
            this.btnICancel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnICancel.UseVisualStyleBackColor = true;
            this.btnICancel.Click += new System.EventHandler(this.btnICancel_Click);
            this.btnIPreview.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnIPreview.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnIPreview.Image = global::Tourist_Management.Properties.Resources.search;
            this.btnIPreview.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnIPreview.Location = new System.Drawing.Point(534, 495);
            this.btnIPreview.Name = "btnIPreview";
            this.btnIPreview.Size = new System.Drawing.Size(72, 30);
            this.btnIPreview.TabIndex = 379;
            this.btnIPreview.Text = "&Preview";
            this.btnIPreview.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnIPreview.UseVisualStyleBackColor = true;
            this.btnIPreview.Click += new System.EventHandler(this.btnIPreview_Click);
            this.grdViewer.BackColor = System.Drawing.Color.Transparent;
            this.grdViewer.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.grdViewer.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.grdViewer.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdViewer.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdViewer.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grdViewer.Location = new System.Drawing.Point(12, 163);
            this.grdViewer.Name = "grdViewer";
            this.grdViewer.Size = new System.Drawing.Size(671, 323);
            this.grdViewer.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdViewer.Styles"));
            this.grdViewer.TabIndex = 381;
            this.ucFilterByOther1.BackColor = System.Drawing.Color.Transparent;
            this.ucFilterByOther1.Location = new System.Drawing.Point(350, 107);
            this.ucFilterByOther1.Name = "ucFilterByOther1";
            this.ucFilterByOther1.Query = null;
            this.ucFilterByOther1.Size = new System.Drawing.Size(185, 50);
            this.ucFilterByOther1.TabIndex = 382;
            this.ucFilterByDate1.BackColor = System.Drawing.Color.Transparent;
            this.ucFilterByDate1.Location = new System.Drawing.Point(7, 44);
            this.ucFilterByDate1.Name = "ucFilterByDate1";
            this.ucFilterByDate1.Size = new System.Drawing.Size(453, 65);
            this.ucFilterByDate1.TabIndex = 383;
            this.ucFilterByCompany1.BackColor = System.Drawing.Color.Transparent;
            this.ucFilterByCompany1.Location = new System.Drawing.Point(456, 53);
            this.ucFilterByCompany1.Name = "ucFilterByCompany1";
            this.ucFilterByCompany1.Size = new System.Drawing.Size(231, 60);
            this.ucFilterByCompany1.TabIndex = 384;
            this.btnFilter.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnFilter.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFilter.Image = global::Tourist_Management.Properties.Resources.filter;
            this.btnFilter.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFilter.Location = new System.Drawing.Point(537, 117);
            this.btnFilter.Name = "btnFilter";
            this.btnFilter.Size = new System.Drawing.Size(146, 37);
            this.btnFilter.TabIndex = 385;
            this.btnFilter.Text = "&Filter";
            this.btnFilter.UseVisualStyleBackColor = true;
            this.btnFilter.Click += new System.EventHandler(this.btnFilter_Click);
            this.groupBox1.BackColor = System.Drawing.Color.White;
            this.groupBox1.Location = new System.Drawing.Point(10, 31);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(676, 2);
            this.groupBox1.TabIndex = 387;
            this.groupBox1.TabStop = false;
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.RoyalBlue;
            this.label1.Location = new System.Drawing.Point(41, 6);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(128, 18);
            this.label1.TabIndex = 386;
            this.label1.Text = "I.O.U. Viewer";
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Bold);
            this.label2.ForeColor = System.Drawing.Color.Blue;
            this.label2.Location = new System.Drawing.Point(354, 108);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(56, 14);
            this.label2.TabIndex = 388;
            this.label2.Text = "Paid To";
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.RoyalBlue;
            this.label3.Location = new System.Drawing.Point(542, 6);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(142, 18);
            this.label3.TabIndex = 389;
            this.label3.Text = "Cheque Viewer";
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.RoyalBlue;
            this.label4.Location = new System.Drawing.Point(273, 6);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(201, 18);
            this.label4.TabIndex = 390;
            this.label4.Text = "Cash Payment Viewer";
            this.rdbIOU.AutoSize = true;
            this.rdbIOU.BackColor = System.Drawing.Color.Transparent;
            this.rdbIOU.Checked = true;
            this.rdbIOU.Location = new System.Drawing.Point(25, 8);
            this.rdbIOU.Name = "rdbIOU";
            this.rdbIOU.Size = new System.Drawing.Size(14, 13);
            this.rdbIOU.TabIndex = 391;
            this.rdbIOU.TabStop = true;
            this.rdbIOU.UseVisualStyleBackColor = false;
            this.rdbIOU.CheckedChanged += new System.EventHandler(this.rdbIOU_CheckedChanged);
            this.rdbCash.AutoSize = true;
            this.rdbCash.BackColor = System.Drawing.Color.Transparent;
            this.rdbCash.Location = new System.Drawing.Point(256, 8);
            this.rdbCash.Name = "rdbCash";
            this.rdbCash.Size = new System.Drawing.Size(14, 13);
            this.rdbCash.TabIndex = 392;
            this.rdbCash.UseVisualStyleBackColor = false;
            this.rdbCash.CheckedChanged += new System.EventHandler(this.rdbCash_CheckedChanged);
            this.rdbChk.AutoSize = true;
            this.rdbChk.BackColor = System.Drawing.Color.Transparent;
            this.rdbChk.Location = new System.Drawing.Point(527, 8);
            this.rdbChk.Name = "rdbChk";
            this.rdbChk.Size = new System.Drawing.Size(14, 13);
            this.rdbChk.TabIndex = 393;
            this.rdbChk.UseVisualStyleBackColor = false;
            this.rdbChk.CheckedChanged += new System.EventHandler(this.rdbChk_CheckedChanged);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(692, 530);
            this.ControlBox = false;
            this.Controls.Add(this.rdbChk);
            this.Controls.Add(this.rdbCash);
            this.Controls.Add(this.rdbIOU);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.btnFilter);
            this.Controls.Add(this.ucFilterByCompany1);
            this.Controls.Add(this.ucFilterByDate1);
            this.Controls.Add(this.ucFilterByOther1);
            this.Controls.Add(this.grdViewer);
            this.Controls.Add(this.btnICancel);
            this.Controls.Add(this.btnIPreview);
            this.Controls.Add(this.groupBox35);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.Name = "frmIouViewer";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmIouViewer_Load);
            this.groupBox35.ResumeLayout(false);
            this.groupBox35.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdViewer)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.GroupBox groupBox35;
        private System.Windows.Forms.RadioButton rdbAl;
        private System.Windows.Forms.RadioButton rdbUnSettled;
        private System.Windows.Forms.RadioButton rdbSettled;
        private System.Windows.Forms.Button btnICancel;
        private System.Windows.Forms.Button btnIPreview;
        private System.Windows.Forms.RadioButton rdbCancelled;
        private C1.Win.C1FlexGrid.C1FlexGrid grdViewer;
        private Tourist_Management.User_Controls.ucFilterByOther ucFilterByOther1;
        private Tourist_Management.User_Controls.ucFilterByDate ucFilterByDate1;
        private Tourist_Management.User_Controls.ucFilterByCompany ucFilterByCompany1;
        private System.Windows.Forms.Button btnFilter;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.RadioButton rdbIOU;
        private System.Windows.Forms.RadioButton rdbCash;
        private System.Windows.Forms.RadioButton rdbChk;
    }
}