namespace Tourist_Management.Accounts
{
    partial class frmSupplementaryCRN
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmSupplementaryCRN));
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tpBasic = new System.Windows.Forms.TabPage();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.rdbCancel = new System.Windows.Forms.RadioButton();
            this.rdbNormal = new System.Windows.Forms.RadioButton();
            this.groupBox8 = new System.Windows.Forms.GroupBox();
            this.label8 = new System.Windows.Forms.Label();
            this.cmbInvoiceTo = new  Tourist_Management.User_Controls.ComboBox();
            this.btnAdd = new System.Windows.Forms.Button();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.drpCurrnecy = new Tourist_Management.DropDowns.DropSearch();
            this.txtRate = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.txtAmount = new System.Windows.Forms.TextBox();
            this.groupBox14 = new System.Windows.Forms.GroupBox();
            this.txtRemarks = new System.Windows.Forms.TextBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.drpInvoiceTo = new Tourist_Management.DropDowns.DropSearch();
            this.lblOtherName = new System.Windows.Forms.Label();
            this.txtOtherName = new System.Windows.Forms.TextBox();
            this.lblAgentClientName = new System.Windows.Forms.Label();
            this.lblAgentLbl = new System.Windows.Forms.Label();
            this.lblClientLbl = new System.Windows.Forms.Label();
            this.btnAddCont = new System.Windows.Forms.Button();
            this.label5 = new System.Windows.Forms.Label();
            this.cmbAgentCont = new  Tourist_Management.User_Controls.ComboBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.label10 = new System.Windows.Forms.Label();
            this.dtpDate = new System.Windows.Forms.DateTimePicker();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.btnTour = new System.Windows.Forms.Button();
            this.txtTourNo = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.txtInvoiceNo = new System.Windows.Forms.TextBox();
            this.lblReservation = new System.Windows.Forms.Label();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.btnRetrieve = new System.Windows.Forms.Button();
            this.grdPayments = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.tpEmail = new System.Windows.Forms.TabPage();
            this.chkExSum = new System.Windows.Forms.CheckBox();
            this.btnEmail = new System.Windows.Forms.Button();
            this.groupBox16 = new System.Windows.Forms.GroupBox();
            this.rtbBody = new System.Windows.Forms.RichTextBox();
            this.groupBox15 = new System.Windows.Forms.GroupBox();
            this.btnUpdateEmail = new System.Windows.Forms.Button();
            this.txtCC = new System.Windows.Forms.TextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.btnEmailConts = new System.Windows.Forms.Button();
            this.txtSubject = new System.Windows.Forms.TextBox();
            this.txtTo = new System.Windows.Forms.TextBox();
            this.label19 = new System.Windows.Forms.Label();
            this.label18 = new System.Windows.Forms.Label();
            this.btnPrint = new System.Windows.Forms.Button();
            this.chkPrint = new System.Windows.Forms.CheckBox();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.tabControl1.SuspendLayout();
            this.tpBasic.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox8.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.groupBox14.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.groupBox5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdPayments)).BeginInit();
            this.tpEmail.SuspendLayout();
            this.groupBox16.SuspendLayout();
            this.groupBox15.SuspendLayout();
            this.SuspendLayout();
            this.tabControl1.Controls.Add(this.tpBasic);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Controls.Add(this.tpEmail);
            this.tabControl1.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.tabControl1.Location = new System.Drawing.Point(12, 12);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(650, 360);
            this.tabControl1.TabIndex = 1;
            this.tpBasic.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tpBasic.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tpBasic.Controls.Add(this.groupBox2);
            this.tpBasic.Controls.Add(this.groupBox8);
            this.tpBasic.Controls.Add(this.btnAdd);
            this.tpBasic.Controls.Add(this.groupBox6);
            this.tpBasic.Controls.Add(this.groupBox14);
            this.tpBasic.Controls.Add(this.groupBox4);
            this.tpBasic.Controls.Add(this.groupBox3);
            this.tpBasic.Controls.Add(this.groupBox1);
            this.tpBasic.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.tpBasic.Location = new System.Drawing.Point(4, 22);
            this.tpBasic.Name = "tpBasic";
            this.tpBasic.Padding = new System.Windows.Forms.Padding(3);
            this.tpBasic.Size = new System.Drawing.Size(642, 334);
            this.tpBasic.TabIndex = 0;
            this.tpBasic.Text = "Add Payments";
            this.tpBasic.UseVisualStyleBackColor = true;
            this.groupBox2.Controls.Add(this.rdbCancel);
            this.groupBox2.Controls.Add(this.rdbNormal);
            this.groupBox2.Location = new System.Drawing.Point(371, 6);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(259, 47);
            this.groupBox2.TabIndex = 261;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Credit Note Type";
            this.rdbCancel.AutoSize = true;
            this.rdbCancel.Location = new System.Drawing.Point(187, 21);
            this.rdbCancel.Name = "rdbCancel";
            this.rdbCancel.Size = new System.Drawing.Size(64, 17);
            this.rdbCancel.TabIndex = 2;
            this.rdbCancel.Text = "Cancel";
            this.rdbCancel.UseVisualStyleBackColor = true;
            this.rdbCancel.Visible = false;
            this.rdbNormal.AutoSize = true;
            this.rdbNormal.Checked = true;
            this.rdbNormal.Location = new System.Drawing.Point(12, 21);
            this.rdbNormal.Name = "rdbNormal";
            this.rdbNormal.Size = new System.Drawing.Size(66, 17);
            this.rdbNormal.TabIndex = 0;
            this.rdbNormal.TabStop = true;
            this.rdbNormal.Text = "Normal";
            this.rdbNormal.UseVisualStyleBackColor = true;
            this.groupBox8.Controls.Add(this.label8);
            this.groupBox8.Controls.Add(this.cmbInvoiceTo);
            this.groupBox8.Location = new System.Drawing.Point(13, 72);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new System.Drawing.Size(349, 41);
            this.groupBox8.TabIndex = 256;
            this.groupBox8.TabStop = false;
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(13, 17);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(90, 13);
            this.label8.TabIndex = 253;
            this.label8.Text = "Credit Note To";
            this.cmbInvoiceTo.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbInvoiceTo.FormattingEnabled = true;
            this.cmbInvoiceTo.Items.AddRange(new object[] {
            "Agent",
            "Client",
            "Other"});
            this.cmbInvoiceTo.Location = new System.Drawing.Point(114, 12);
            this.cmbInvoiceTo.Name = "cmbInvoiceTo";
            this.cmbInvoiceTo.Size = new System.Drawing.Size(219, 21);
            this.cmbInvoiceTo.TabIndex = 0;
            this.cmbInvoiceTo.SelectedIndexChanged += new System.EventHandler(this.cmbInvoiceTo_SelectedIndexChanged);
            this.btnAdd.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnAdd.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAdd.Image = global::Tourist_Management.Properties.Resources.add32;
            this.btnAdd.ImageAlign = System.Drawing.ContentAlignment.TopCenter;
            this.btnAdd.Location = new System.Drawing.Point(565, 253);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new System.Drawing.Size(65, 47);
            this.btnAdd.TabIndex = 0;
            this.btnAdd.Text = "&Add";
            this.btnAdd.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btnAdd.UseVisualStyleBackColor = true;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            this.groupBox6.Controls.Add(this.drpCurrnecy);
            this.groupBox6.Controls.Add(this.txtRate);
            this.groupBox6.Controls.Add(this.label6);
            this.groupBox6.Controls.Add(this.label3);
            this.groupBox6.Controls.Add(this.label14);
            this.groupBox6.Controls.Add(this.txtAmount);
            this.groupBox6.Location = new System.Drawing.Point(370, 109);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(257, 109);
            this.groupBox6.TabIndex = 260;
            this.groupBox6.TabStop = false;
            this.drpCurrnecy.BackColor = System.Drawing.Color.Transparent;
            this.drpCurrnecy.DataSource = null;
            this.drpCurrnecy.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpCurrnecy.Location = new System.Drawing.Point(75, 17);
            this.drpCurrnecy.Name = "drpCurrnecy";
            this.drpCurrnecy.SelectedText = "";
            this.drpCurrnecy.SelectedValue = "";
            this.drpCurrnecy.Size = new System.Drawing.Size(170, 20);
            this.drpCurrnecy.TabIndex = 0;
            this.txtRate.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtRate.Location = new System.Drawing.Point(75, 45);
            this.txtRate.Name = "txtRate";
            this.txtRate.Size = new System.Drawing.Size(168, 21);
            this.txtRate.TabIndex = 1;
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(10, 77);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(51, 13);
            this.label6.TabIndex = 314;
            this.label6.Text = "Amount";
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(10, 47);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(33, 13);
            this.label3.TabIndex = 313;
            this.label3.Text = "Rate";
            this.label14.AutoSize = true;
            this.label14.Location = new System.Drawing.Point(10, 20);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(60, 13);
            this.label14.TabIndex = 312;
            this.label14.Text = "Currency";
            this.txtAmount.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.txtAmount.Location = new System.Drawing.Point(73, 74);
            this.txtAmount.Multiline = true;
            this.txtAmount.Name = "txtAmount";
            this.txtAmount.Size = new System.Drawing.Size(170, 23);
            this.txtAmount.TabIndex = 2;
            this.txtAmount.TextChanged += new System.EventHandler(this.txtAmount_TextChanged);
            this.groupBox14.Controls.Add(this.txtRemarks);
            this.groupBox14.Location = new System.Drawing.Point(13, 224);
            this.groupBox14.Name = "groupBox14";
            this.groupBox14.Size = new System.Drawing.Size(546, 93);
            this.groupBox14.TabIndex = 259;
            this.groupBox14.TabStop = false;
            this.groupBox14.Text = "Description";
            this.txtRemarks.Location = new System.Drawing.Point(13, 18);
            this.txtRemarks.Multiline = true;
            this.txtRemarks.Name = "txtRemarks";
            this.txtRemarks.Size = new System.Drawing.Size(513, 68);
            this.txtRemarks.TabIndex = 0;
            this.groupBox4.Controls.Add(this.drpInvoiceTo);
            this.groupBox4.Controls.Add(this.lblOtherName);
            this.groupBox4.Controls.Add(this.txtOtherName);
            this.groupBox4.Controls.Add(this.lblAgentClientName);
            this.groupBox4.Controls.Add(this.lblAgentLbl);
            this.groupBox4.Controls.Add(this.lblClientLbl);
            this.groupBox4.Controls.Add(this.btnAddCont);
            this.groupBox4.Controls.Add(this.label5);
            this.groupBox4.Controls.Add(this.cmbAgentCont);
            this.groupBox4.Location = new System.Drawing.Point(12, 120);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(351, 98);
            this.groupBox4.TabIndex = 257;
            this.groupBox4.TabStop = false;
            this.drpInvoiceTo.BackColor = System.Drawing.Color.Transparent;
            this.drpInvoiceTo.DataSource = null;
            this.drpInvoiceTo.Enabled = false;
            this.drpInvoiceTo.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpInvoiceTo.Location = new System.Drawing.Point(120, 14);
            this.drpInvoiceTo.Name = "drpInvoiceTo";
            this.drpInvoiceTo.SelectedText = "";
            this.drpInvoiceTo.SelectedValue = "";
            this.drpInvoiceTo.Size = new System.Drawing.Size(216, 20);
            this.drpInvoiceTo.TabIndex = 261;
            this.drpInvoiceTo.Click_Open += new System.EventHandler(this.drpInvoiceTo_Click_Open);
            this.drpInvoiceTo.Selected_TextChanged += new System.EventHandler(this.drpInvoiceTo_Selected_TextChanged);
            this.lblOtherName.AutoSize = true;
            this.lblOtherName.BackColor = System.Drawing.Color.Transparent;
            this.lblOtherName.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.lblOtherName.Location = new System.Drawing.Point(15, 16);
            this.lblOtherName.Name = "lblOtherName";
            this.lblOtherName.Size = new System.Drawing.Size(39, 13);
            this.lblOtherName.TabIndex = 10;
            this.lblOtherName.Text = "Other";
            this.lblOtherName.Visible = false;
            this.txtOtherName.Location = new System.Drawing.Point(120, 13);
            this.txtOtherName.Name = "txtOtherName";
            this.txtOtherName.Size = new System.Drawing.Size(219, 21);
            this.txtOtherName.TabIndex = 9;
            this.txtOtherName.Visible = false;
            this.lblAgentClientName.AutoSize = true;
            this.lblAgentClientName.Location = new System.Drawing.Point(123, 18);
            this.lblAgentClientName.Name = "lblAgentClientName";
            this.lblAgentClientName.Size = new System.Drawing.Size(106, 13);
            this.lblAgentClientName.TabIndex = 260;
            this.lblAgentClientName.Text = "AgentClientName";
            this.lblAgentClientName.Visible = false;
            this.lblAgentLbl.AutoSize = true;
            this.lblAgentLbl.Location = new System.Drawing.Point(15, 16);
            this.lblAgentLbl.Name = "lblAgentLbl";
            this.lblAgentLbl.Size = new System.Drawing.Size(76, 13);
            this.lblAgentLbl.TabIndex = 259;
            this.lblAgentLbl.Text = "Agent name";
            this.lblAgentLbl.Visible = false;
            this.lblClientLbl.AutoSize = true;
            this.lblClientLbl.Location = new System.Drawing.Point(12, 16);
            this.lblClientLbl.Name = "lblClientLbl";
            this.lblClientLbl.Size = new System.Drawing.Size(76, 13);
            this.lblClientLbl.TabIndex = 257;
            this.lblClientLbl.Text = "Client name";
            this.lblClientLbl.Visible = false;
            this.btnAddCont.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnAddCont.Enabled = false;
            this.btnAddCont.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddCont.Image = global::Tourist_Management.Properties.Resources.add_16;
            this.btnAddCont.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddCont.Location = new System.Drawing.Point(283, 52);
            this.btnAddCont.Name = "btnAddCont";
            this.btnAddCont.Size = new System.Drawing.Size(54, 24);
            this.btnAddCont.TabIndex = 256;
            this.btnAddCont.Text = "&Add";
            this.btnAddCont.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddCont.UseVisualStyleBackColor = true;
            this.btnAddCont.Click += new System.EventHandler(this.btnAddCont_Click);
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(12, 55);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(94, 13);
            this.label5.TabIndex = 255;
            this.label5.Text = "Contact Person";
            this.cmbAgentCont.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbAgentCont.Enabled = false;
            this.cmbAgentCont.FormattingEnabled = true;
            this.cmbAgentCont.Location = new System.Drawing.Point(119, 53);
            this.cmbAgentCont.Name = "cmbAgentCont";
            this.cmbAgentCont.Size = new System.Drawing.Size(161, 21);
            this.cmbAgentCont.TabIndex = 254;
            this.groupBox3.Controls.Add(this.label10);
            this.groupBox3.Controls.Add(this.dtpDate);
            this.groupBox3.Location = new System.Drawing.Point(369, 58);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(261, 48);
            this.groupBox3.TabIndex = 256;
            this.groupBox3.TabStop = false;
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(12, 19);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(34, 13);
            this.label10.TabIndex = 313;
            this.label10.Text = "Date";
            this.dtpDate.Location = new System.Drawing.Point(76, 16);
            this.dtpDate.Name = "dtpDate";
            this.dtpDate.Size = new System.Drawing.Size(165, 21);
            this.dtpDate.TabIndex = 0;
            this.groupBox1.Controls.Add(this.btnTour);
            this.groupBox1.Controls.Add(this.txtTourNo);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.txtInvoiceNo);
            this.groupBox1.Controls.Add(this.lblReservation);
            this.groupBox1.Location = new System.Drawing.Point(13, 2);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(351, 68);
            this.groupBox1.TabIndex = 254;
            this.groupBox1.TabStop = false;
            this.btnTour.Location = new System.Drawing.Point(301, 39);
            this.btnTour.Name = "btnTour";
            this.btnTour.Size = new System.Drawing.Size(37, 23);
            this.btnTour.TabIndex = 0;
            this.btnTour.Text = "...";
            this.btnTour.UseVisualStyleBackColor = true;
            this.btnTour.Click += new System.EventHandler(this.btnTour_Click);
            this.txtTourNo.Enabled = false;
            this.txtTourNo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTourNo.ForeColor = System.Drawing.Color.Blue;
            this.txtTourNo.Location = new System.Drawing.Point(115, 40);
            this.txtTourNo.Name = "txtTourNo";
            this.txtTourNo.ReadOnly = true;
            this.txtTourNo.Size = new System.Drawing.Size(179, 21);
            this.txtTourNo.TabIndex = 255;
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(14, 43);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(84, 13);
            this.label1.TabIndex = 254;
            this.label1.Text = "Reference No";
            this.txtInvoiceNo.Enabled = false;
            this.txtInvoiceNo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtInvoiceNo.ForeColor = System.Drawing.Color.Blue;
            this.txtInvoiceNo.Location = new System.Drawing.Point(115, 15);
            this.txtInvoiceNo.Name = "txtInvoiceNo";
            this.txtInvoiceNo.ReadOnly = true;
            this.txtInvoiceNo.Size = new System.Drawing.Size(221, 21);
            this.txtInvoiceNo.TabIndex = 253;
            this.lblReservation.AutoSize = true;
            this.lblReservation.Location = new System.Drawing.Point(14, 18);
            this.lblReservation.Name = "lblReservation";
            this.lblReservation.Size = new System.Drawing.Size(51, 13);
            this.lblReservation.TabIndex = 252;
            this.lblReservation.Text = "CRN No";
            this.tabPage2.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tabPage2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tabPage2.Controls.Add(this.groupBox5);
            this.tabPage2.Controls.Add(this.grdPayments);
            this.tabPage2.Location = new System.Drawing.Point(4, 22);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(642, 334);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "View Payments";
            this.tabPage2.UseVisualStyleBackColor = true;
            this.groupBox5.Controls.Add(this.btnRetrieve);
            this.groupBox5.Location = new System.Drawing.Point(459, 274);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(175, 55);
            this.groupBox5.TabIndex = 7;
            this.groupBox5.TabStop = false;
            this.btnRetrieve.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnRetrieve.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRetrieve.Image = global::Tourist_Management.Properties.Resources.arrow_left_green_48;
            this.btnRetrieve.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRetrieve.Location = new System.Drawing.Point(6, 14);
            this.btnRetrieve.Name = "btnRetrieve";
            this.btnRetrieve.Size = new System.Drawing.Size(165, 35);
            this.btnRetrieve.TabIndex = 3;
            this.btnRetrieve.Text = "&Retrieve Selected";
            this.btnRetrieve.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRetrieve.UseVisualStyleBackColor = true;
            this.btnRetrieve.Click += new System.EventHandler(this.btnRetrieve_Click);
            this.grdPayments.AllowEditing = false;
            this.grdPayments.AutoResize = false;
            this.grdPayments.BackColor = System.Drawing.Color.Transparent;
            this.grdPayments.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdPayments.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdPayments.Cursor = System.Windows.Forms.Cursors.Default;
            this.grdPayments.Location = new System.Drawing.Point(3, 3);
            this.grdPayments.Name = "grdPayments";
            this.grdPayments.Size = new System.Drawing.Size(633, 271);
            this.grdPayments.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdPayments.Styles"));
            this.grdPayments.TabIndex = 6;
            this.tpEmail.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.tpEmail.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tpEmail.Controls.Add(this.chkExSum);
            this.tpEmail.Controls.Add(this.btnEmail);
            this.tpEmail.Controls.Add(this.groupBox16);
            this.tpEmail.Controls.Add(this.groupBox15);
            this.tpEmail.Location = new System.Drawing.Point(4, 22);
            this.tpEmail.Name = "tpEmail";
            this.tpEmail.Padding = new System.Windows.Forms.Padding(3);
            this.tpEmail.Size = new System.Drawing.Size(642, 334);
            this.tpEmail.TabIndex = 2;
            this.tpEmail.Text = "Email";
            this.tpEmail.UseVisualStyleBackColor = true;
            this.chkExSum.AutoSize = true;
            this.chkExSum.Checked = true;
            this.chkExSum.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkExSum.Location = new System.Drawing.Point(438, 286);
            this.chkExSum.Name = "chkExSum";
            this.chkExSum.Size = new System.Drawing.Size(108, 17);
            this.chkExSum.TabIndex = 248;
            this.chkExSum.Text = "Attach Invoice";
            this.chkExSum.UseVisualStyleBackColor = true;
            this.btnEmail.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnEmail.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEmail.Location = new System.Drawing.Point(548, 283);
            this.btnEmail.Name = "btnEmail";
            this.btnEmail.Size = new System.Drawing.Size(87, 22);
            this.btnEmail.TabIndex = 247;
            this.btnEmail.Text = "&Email This";
            this.btnEmail.UseVisualStyleBackColor = true;
            this.btnEmail.Click += new System.EventHandler(this.btnEmail_Click);
            this.groupBox16.BackColor = System.Drawing.Color.Transparent;
            this.groupBox16.Controls.Add(this.rtbBody);
            this.groupBox16.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox16.Location = new System.Drawing.Point(8, 125);
            this.groupBox16.Name = "groupBox16";
            this.groupBox16.Size = new System.Drawing.Size(628, 141);
            this.groupBox16.TabIndex = 245;
            this.groupBox16.TabStop = false;
            this.groupBox16.Text = "Email Body";
            this.rtbBody.AccessibleRole = System.Windows.Forms.AccessibleRole.None;
            this.rtbBody.Location = new System.Drawing.Point(9, 19);
            this.rtbBody.Name = "rtbBody";
            this.rtbBody.Size = new System.Drawing.Size(608, 110);
            this.rtbBody.TabIndex = 0;
            this.rtbBody.Text = "";
            this.groupBox15.BackColor = System.Drawing.Color.Transparent;
            this.groupBox15.Controls.Add(this.btnUpdateEmail);
            this.groupBox15.Controls.Add(this.txtCC);
            this.groupBox15.Controls.Add(this.label9);
            this.groupBox15.Controls.Add(this.btnEmailConts);
            this.groupBox15.Controls.Add(this.txtSubject);
            this.groupBox15.Controls.Add(this.txtTo);
            this.groupBox15.Controls.Add(this.label19);
            this.groupBox15.Controls.Add(this.label18);
            this.groupBox15.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox15.Location = new System.Drawing.Point(8, 4);
            this.groupBox15.Name = "groupBox15";
            this.groupBox15.Size = new System.Drawing.Size(627, 115);
            this.groupBox15.TabIndex = 244;
            this.groupBox15.TabStop = false;
            this.groupBox15.Text = "General Details";
            this.btnUpdateEmail.BackColor = System.Drawing.SystemColors.Control;
            this.btnUpdateEmail.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnUpdateEmail.Location = new System.Drawing.Point(482, 22);
            this.btnUpdateEmail.Name = "btnUpdateEmail";
            this.btnUpdateEmail.Size = new System.Drawing.Size(135, 23);
            this.btnUpdateEmail.TabIndex = 10;
            this.btnUpdateEmail.Text = "Update Agent Email";
            this.btnUpdateEmail.UseVisualStyleBackColor = false;
            this.btnUpdateEmail.Click += new System.EventHandler(this.btnUpdateEmail_Click);
            this.txtCC.Location = new System.Drawing.Point(68, 51);
            this.txtCC.Name = "txtCC";
            this.txtCC.Size = new System.Drawing.Size(549, 21);
            this.txtCC.TabIndex = 9;
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(7, 54);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(25, 13);
            this.label9.TabIndex = 8;
            this.label9.Text = "CC";
            this.btnEmailConts.BackColor = System.Drawing.SystemColors.Control;
            this.btnEmailConts.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnEmailConts.Location = new System.Drawing.Point(443, 22);
            this.btnEmailConts.Name = "btnEmailConts";
            this.btnEmailConts.Size = new System.Drawing.Size(33, 23);
            this.btnEmailConts.TabIndex = 7;
            this.btnEmailConts.Text = "...";
            this.btnEmailConts.UseVisualStyleBackColor = false;
            this.btnEmailConts.Click += new System.EventHandler(this.btnEmailConts_Click);
            this.txtSubject.Location = new System.Drawing.Point(68, 77);
            this.txtSubject.Name = "txtSubject";
            this.txtSubject.Size = new System.Drawing.Size(549, 21);
            this.txtSubject.TabIndex = 5;
            this.txtTo.Location = new System.Drawing.Point(68, 24);
            this.txtTo.Name = "txtTo";
            this.txtTo.Size = new System.Drawing.Size(369, 21);
            this.txtTo.TabIndex = 4;
            this.label19.AutoSize = true;
            this.label19.Location = new System.Drawing.Point(7, 80);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(50, 13);
            this.label19.TabIndex = 2;
            this.label19.Text = "Subject";
            this.label18.AutoSize = true;
            this.label18.Location = new System.Drawing.Point(7, 27);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(21, 13);
            this.label18.TabIndex = 1;
            this.label18.Text = "To";
            this.btnPrint.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPrint.Enabled = false;
            this.btnPrint.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPrint.Image = global::Tourist_Management.Properties.Resources.search;
            this.btnPrint.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPrint.Location = new System.Drawing.Point(386, 381);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.Size = new System.Drawing.Size(87, 32);
            this.btnPrint.TabIndex = 6;
            this.btnPrint.Text = "&Preview";
            this.btnPrint.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPrint.UseVisualStyleBackColor = true;
            this.btnPrint.Click += new System.EventHandler(this.btnPrint_Click);
            this.chkPrint.AutoSize = true;
            this.chkPrint.BackColor = System.Drawing.Color.Transparent;
            this.chkPrint.Checked = true;
            this.chkPrint.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkPrint.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkPrint.Location = new System.Drawing.Point(260, 388);
            this.chkPrint.Name = "chkPrint";
            this.chkPrint.Size = new System.Drawing.Size(117, 17);
            this.chkPrint.TabIndex = 5;
            this.chkPrint.Text = "Print After Save";
            this.chkPrint.UseVisualStyleBackColor = false;
            this.btnCancel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCancel.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.Location = new System.Drawing.Point(573, 381);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(87, 32);
            this.btnCancel.TabIndex = 8;
            this.btnCancel.Text = "&Close";
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnOk.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnOk.Enabled = false;
            this.btnOk.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Image = global::Tourist_Management.Properties.Resources.floppy;
            this.btnOk.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOk.Location = new System.Drawing.Point(480, 381);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(87, 32);
            this.btnOk.TabIndex = 7;
            this.btnOk.Text = "&Save";
            this.btnOk.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(669, 425);
            this.ControlBox = false;
            this.Controls.Add(this.btnPrint);
            this.Controls.Add(this.chkPrint);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.tabControl1);
            this.Font = new System.Drawing.Font("Lucida Bright", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.Name = "frmSupplementaryCRN";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmSupplementary_Load);
            this.tabControl1.ResumeLayout(false);
            this.tpBasic.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox8.ResumeLayout(false);
            this.groupBox8.PerformLayout();
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            this.groupBox14.ResumeLayout(false);
            this.groupBox14.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdPayments)).EndInit();
            this.tpEmail.ResumeLayout(false);
            this.tpEmail.PerformLayout();
            this.groupBox16.ResumeLayout(false);
            this.groupBox15.ResumeLayout(false);
            this.groupBox15.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tpBasic;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.RadioButton rdbCancel;
        private System.Windows.Forms.RadioButton rdbNormal;
        private System.Windows.Forms.GroupBox groupBox8;
        private System.Windows.Forms.Label label8;
        private  Tourist_Management.User_Controls.ComboBox cmbInvoiceTo;
        private System.Windows.Forms.Button btnAdd;
        private System.Windows.Forms.GroupBox groupBox6;
        private DropDowns.DropSearch drpCurrnecy;
        private System.Windows.Forms.TextBox txtRate;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.TextBox txtAmount;
        private System.Windows.Forms.GroupBox groupBox14;
        private System.Windows.Forms.TextBox txtRemarks;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.Button btnAddCont;
        private System.Windows.Forms.Label label5;
        private  Tourist_Management.User_Controls.ComboBox cmbAgentCont;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.DateTimePicker dtpDate;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Button btnTour;
        private System.Windows.Forms.TextBox txtTourNo;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox txtInvoiceNo;
        private System.Windows.Forms.Label lblReservation;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.Button btnRetrieve;
        private C1.Win.C1FlexGrid.C1FlexGrid grdPayments;
        private System.Windows.Forms.TabPage tpEmail;
        private System.Windows.Forms.CheckBox chkExSum;
        private System.Windows.Forms.Button btnEmail;
        private System.Windows.Forms.GroupBox groupBox16;
        private System.Windows.Forms.RichTextBox rtbBody;
        private System.Windows.Forms.GroupBox groupBox15;
        private System.Windows.Forms.Button btnUpdateEmail;
        private System.Windows.Forms.TextBox txtCC;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Button btnEmailConts;
        private System.Windows.Forms.TextBox txtSubject;
        private System.Windows.Forms.TextBox txtTo;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.Button btnPrint;
        private System.Windows.Forms.CheckBox chkPrint;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.Label lblClientLbl;
        private System.Windows.Forms.Label lblAgentLbl;
        private System.Windows.Forms.Label lblAgentClientName;
        private DropDowns.DropSearch drpInvoiceTo;
        private System.Windows.Forms.TextBox txtOtherName;
        private System.Windows.Forms.Label lblOtherName;
    }
}