namespace Tourist_Management.Accounts
{
    partial class frmTourInvoice
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmTourInvoice));
            this.btnPrint = new System.Windows.Forms.Button();
            this.chkPrint = new System.Windows.Forms.CheckBox();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.rdbCancel = new System.Windows.Forms.RadioButton();
            this.rdbAmend = new System.Windows.Forms.RadioButton();
            this.rdbNormal = new System.Windows.Forms.RadioButton();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.drpBankBranch = new Tourist_Management.DropDowns.DropSearch();
            this.lblAccountNo = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.drpCurrnecy = new Tourist_Management.DropDowns.DropSearch();
            this.txtVat = new System.Windows.Forms.TextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.txtPaidAmt = new System.Windows.Forms.TextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.txtRate = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.txtAmount = new System.Windows.Forms.TextBox();
            this.groupBox14 = new System.Windows.Forms.GroupBox();
            this.txtRemarks = new System.Windows.Forms.TextBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.drpPaidTo = new Tourist_Management.DropDowns.DropSearch();
            this.btnAddCont = new System.Windows.Forms.Button();
            this.label5 = new System.Windows.Forms.Label();
            this.cmbAgentCont = new  Tourist_Management.User_Controls.ComboBox();
            this.label4 = new System.Windows.Forms.Label();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.label10 = new System.Windows.Forms.Label();
            this.dtpDate = new System.Windows.Forms.DateTimePicker();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.lblBookingName = new System.Windows.Forms.Label();
            this.btnTour = new System.Windows.Forms.Button();
            this.txtTourNo = new System.Windows.Forms.TextBox();
            this.lblReservation = new System.Windows.Forms.Label();
            this.grdPayments = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.label1 = new System.Windows.Forms.Label();
            this.lblInvoiceNo = new System.Windows.Forms.Label();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.rdbSuppInv = new System.Windows.Forms.RadioButton();
            this.rdbNormalInv = new System.Windows.Forms.RadioButton();
            this.label2 = new System.Windows.Forms.Label();
            this.chkDetail = new System.Windows.Forms.CheckBox();
            this.groupBox2.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.groupBox14.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdPayments)).BeginInit();
            this.groupBox5.SuspendLayout();
            this.SuspendLayout();
            this.btnPrint.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPrint.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPrint.Image = global::Tourist_Management.Properties.Resources.search;
            this.btnPrint.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPrint.Location = new System.Drawing.Point(359, 603);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.Size = new System.Drawing.Size(87, 32);
            this.btnPrint.TabIndex = 7;
            this.btnPrint.Text = "&Preview";
            this.btnPrint.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPrint.UseVisualStyleBackColor = true;
            this.btnPrint.Click += new System.EventHandler(this.btnPrint_Click);
            this.chkPrint.AutoSize = true;
            this.chkPrint.BackColor = System.Drawing.Color.Transparent;
            this.chkPrint.Checked = true;
            this.chkPrint.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkPrint.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkPrint.Location = new System.Drawing.Point(235, 612);
            this.chkPrint.Name = "chkPrint";
            this.chkPrint.Size = new System.Drawing.Size(117, 17);
            this.chkPrint.TabIndex = 5;
            this.chkPrint.Text = "Print After Save";
            this.chkPrint.UseVisualStyleBackColor = false;
            this.btnCancel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCancel.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Image = global::Tourist_Management.Properties.Resources.delete;
            this.btnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.Location = new System.Drawing.Point(546, 603);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(87, 32);
            this.btnCancel.TabIndex = 9;
            this.btnCancel.Text = "&Close";
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnOk.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnOk.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOk.Image = global::Tourist_Management.Properties.Resources.floppy;
            this.btnOk.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOk.Location = new System.Drawing.Point(453, 603);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(87, 32);
            this.btnOk.TabIndex = 8;
            this.btnOk.Text = "&Save";
            this.btnOk.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.groupBox2.BackColor = System.Drawing.Color.Transparent;
            this.groupBox2.Controls.Add(this.rdbCancel);
            this.groupBox2.Controls.Add(this.rdbAmend);
            this.groupBox2.Controls.Add(this.rdbNormal);
            this.groupBox2.Location = new System.Drawing.Point(370, 58);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(259, 47);
            this.groupBox2.TabIndex = 270;
            this.groupBox2.TabStop = false;
            this.rdbCancel.AutoSize = true;
            this.rdbCancel.Location = new System.Drawing.Point(181, 20);
            this.rdbCancel.Name = "rdbCancel";
            this.rdbCancel.Size = new System.Drawing.Size(58, 17);
            this.rdbCancel.TabIndex = 2;
            this.rdbCancel.Text = "Cancel";
            this.rdbCancel.UseVisualStyleBackColor = true;
            this.rdbAmend.AutoSize = true;
            this.rdbAmend.Location = new System.Drawing.Point(86, 21);
            this.rdbAmend.Name = "rdbAmend";
            this.rdbAmend.Size = new System.Drawing.Size(81, 17);
            this.rdbAmend.TabIndex = 1;
            this.rdbAmend.Text = "Amendment";
            this.rdbAmend.UseVisualStyleBackColor = true;
            this.rdbAmend.CheckedChanged += new System.EventHandler(this.rdbAmend_CheckedChanged);
            this.rdbNormal.AutoSize = true;
            this.rdbNormal.Checked = true;
            this.rdbNormal.Location = new System.Drawing.Point(12, 21);
            this.rdbNormal.Name = "rdbNormal";
            this.rdbNormal.Size = new System.Drawing.Size(58, 17);
            this.rdbNormal.TabIndex = 0;
            this.rdbNormal.TabStop = true;
            this.rdbNormal.Text = "Normal";
            this.rdbNormal.UseVisualStyleBackColor = true;
            this.groupBox7.BackColor = System.Drawing.Color.Transparent;
            this.groupBox7.Controls.Add(this.drpBankBranch);
            this.groupBox7.Controls.Add(this.lblAccountNo);
            this.groupBox7.Controls.Add(this.label7);
            this.groupBox7.Location = new System.Drawing.Point(16, 200);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(351, 63);
            this.groupBox7.TabIndex = 267;
            this.groupBox7.TabStop = false;
            this.drpBankBranch.BackColor = System.Drawing.Color.Transparent;
            this.drpBankBranch.DataSource = null;
            this.drpBankBranch.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpBankBranch.Location = new System.Drawing.Point(119, 13);
            this.drpBankBranch.Name = "drpBankBranch";
            this.drpBankBranch.SelectedText = "";
            this.drpBankBranch.SelectedValue = "";
            this.drpBankBranch.Size = new System.Drawing.Size(216, 20);
            this.drpBankBranch.TabIndex = 0;
            this.drpBankBranch.Selected_TextChanged += new System.EventHandler(this.drpBankBranch_Selected_TextChanged_1);
            this.lblAccountNo.AutoSize = true;
            this.lblAccountNo.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblAccountNo.ForeColor = System.Drawing.Color.Red;
            this.lblAccountNo.Location = new System.Drawing.Point(122, 39);
            this.lblAccountNo.Name = "lblAccountNo";
            this.lblAccountNo.Size = new System.Drawing.Size(21, 13);
            this.lblAccountNo.TabIndex = 315;
            this.lblAccountNo.Text = "\"\"";
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(13, 17);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(69, 13);
            this.label7.TabIndex = 244;
            this.label7.Text = "Bank Branch";
            this.groupBox6.BackColor = System.Drawing.Color.Transparent;
            this.groupBox6.Controls.Add(this.drpCurrnecy);
            this.groupBox6.Controls.Add(this.txtVat);
            this.groupBox6.Controls.Add(this.label9);
            this.groupBox6.Controls.Add(this.txtPaidAmt);
            this.groupBox6.Controls.Add(this.label8);
            this.groupBox6.Controls.Add(this.txtRate);
            this.groupBox6.Controls.Add(this.label6);
            this.groupBox6.Controls.Add(this.label3);
            this.groupBox6.Controls.Add(this.label14);
            this.groupBox6.Controls.Add(this.txtAmount);
            this.groupBox6.Location = new System.Drawing.Point(371, 144);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(260, 122);
            this.groupBox6.TabIndex = 269;
            this.groupBox6.TabStop = false;
            this.drpCurrnecy.BackColor = System.Drawing.Color.Transparent;
            this.drpCurrnecy.DataSource = null;
            this.drpCurrnecy.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpCurrnecy.Location = new System.Drawing.Point(75, 17);
            this.drpCurrnecy.Name = "drpCurrnecy";
            this.drpCurrnecy.SelectedText = "";
            this.drpCurrnecy.SelectedValue = "";
            this.drpCurrnecy.Size = new System.Drawing.Size(170, 20);
            this.drpCurrnecy.TabIndex = 0;
            this.drpCurrnecy.Selected_TextChanged += new System.EventHandler(this.drpCurrnecy_Selected_TextChanged);
            this.txtVat.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtVat.Location = new System.Drawing.Point(192, 42);
            this.txtVat.Name = "txtVat";
            this.txtVat.ReadOnly = true;
            this.txtVat.Size = new System.Drawing.Size(49, 20);
            this.txtVat.TabIndex = 319;
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(150, 46);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(39, 13);
            this.label9.TabIndex = 320;
            this.label9.Text = "VAT %";
            this.txtPaidAmt.Location = new System.Drawing.Point(74, 95);
            this.txtPaidAmt.Name = "txtPaidAmt";
            this.txtPaidAmt.Size = new System.Drawing.Size(170, 20);
            this.txtPaidAmt.TabIndex = 318;
            this.txtPaidAmt.Tag = "";
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(11, 101);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(49, 13);
            this.label8.TabIndex = 317;
            this.label8.Text = "Paid Amt";
            this.txtRate.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtRate.Location = new System.Drawing.Point(75, 42);
            this.txtRate.Name = "txtRate";
            this.txtRate.Size = new System.Drawing.Size(69, 20);
            this.txtRate.TabIndex = 1;
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(10, 69);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(43, 13);
            this.label6.TabIndex = 314;
            this.label6.Text = "Amount";
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(10, 44);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(30, 13);
            this.label3.TabIndex = 313;
            this.label3.Text = "Rate";
            this.label14.AutoSize = true;
            this.label14.Location = new System.Drawing.Point(10, 20);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(49, 13);
            this.label14.TabIndex = 312;
            this.label14.Text = "Currency";
            this.txtAmount.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.txtAmount.Enabled = false;
            this.txtAmount.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAmount.Location = new System.Drawing.Point(73, 66);
            this.txtAmount.Multiline = true;
            this.txtAmount.Name = "txtAmount";
            this.txtAmount.ReadOnly = true;
            this.txtAmount.Size = new System.Drawing.Size(170, 23);
            this.txtAmount.TabIndex = 2;
            this.groupBox14.BackColor = System.Drawing.Color.Transparent;
            this.groupBox14.Controls.Add(this.txtRemarks);
            this.groupBox14.Location = new System.Drawing.Point(16, 266);
            this.groupBox14.Name = "groupBox14";
            this.groupBox14.Size = new System.Drawing.Size(615, 76);
            this.groupBox14.TabIndex = 268;
            this.groupBox14.TabStop = false;
            this.groupBox14.Text = "Description";
            this.txtRemarks.Location = new System.Drawing.Point(13, 18);
            this.txtRemarks.Multiline = true;
            this.txtRemarks.Name = "txtRemarks";
            this.txtRemarks.Size = new System.Drawing.Size(593, 52);
            this.txtRemarks.TabIndex = 0;
            this.groupBox4.BackColor = System.Drawing.Color.Transparent;
            this.groupBox4.Controls.Add(this.drpPaidTo);
            this.groupBox4.Controls.Add(this.btnAddCont);
            this.groupBox4.Controls.Add(this.label5);
            this.groupBox4.Controls.Add(this.cmbAgentCont);
            this.groupBox4.Controls.Add(this.label4);
            this.groupBox4.Location = new System.Drawing.Point(15, 124);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(351, 73);
            this.groupBox4.TabIndex = 266;
            this.groupBox4.TabStop = false;
            this.drpPaidTo.BackColor = System.Drawing.Color.Transparent;
            this.drpPaidTo.DataSource = null;
            this.drpPaidTo.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drpPaidTo.Location = new System.Drawing.Point(119, 13);
            this.drpPaidTo.Name = "drpPaidTo";
            this.drpPaidTo.SelectedText = "";
            this.drpPaidTo.SelectedValue = "";
            this.drpPaidTo.Size = new System.Drawing.Size(216, 20);
            this.drpPaidTo.TabIndex = 0;
            this.drpPaidTo.Click_Open += new System.EventHandler(this.drpPaidTo_Click_Open);
            this.drpPaidTo.Selected_TextChanged += new System.EventHandler(this.drpPaidTo_Selected_TextChanged);
            this.btnAddCont.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnAddCont.Enabled = false;
            this.btnAddCont.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddCont.Image = global::Tourist_Management.Properties.Resources.add_16;
            this.btnAddCont.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddCont.Location = new System.Drawing.Point(283, 42);
            this.btnAddCont.Name = "btnAddCont";
            this.btnAddCont.Size = new System.Drawing.Size(54, 24);
            this.btnAddCont.TabIndex = 256;
            this.btnAddCont.Text = "&Add";
            this.btnAddCont.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddCont.UseVisualStyleBackColor = true;
            this.btnAddCont.Click += new System.EventHandler(this.btnAddCont_Click);
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(12, 45);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(80, 13);
            this.label5.TabIndex = 255;
            this.label5.Text = "Contact Person";
            this.cmbAgentCont.DropDownStyle =  System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbAgentCont.FormattingEnabled = true;
            this.cmbAgentCont.Location = new System.Drawing.Point(119, 43);
            this.cmbAgentCont.Name = "cmbAgentCont";
            this.cmbAgentCont.Size = new System.Drawing.Size(161, 21);
            this.cmbAgentCont.TabIndex = 254;
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(13, 17);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(58, 13);
            this.label4.TabIndex = 244;
            this.label4.Text = "Invoice To";
            this.groupBox3.BackColor = System.Drawing.Color.Transparent;
            this.groupBox3.Controls.Add(this.label10);
            this.groupBox3.Controls.Add(this.dtpDate);
            this.groupBox3.Location = new System.Drawing.Point(370, 102);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(261, 42);
            this.groupBox3.TabIndex = 265;
            this.groupBox3.TabStop = false;
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(12, 19);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(68, 13);
            this.label10.TabIndex = 313;
            this.label10.Text = "Invoice Date";
            this.dtpDate.Location = new System.Drawing.Point(95, 16);
            this.dtpDate.Name = "dtpDate";
            this.dtpDate.Size = new System.Drawing.Size(146, 20);
            this.dtpDate.TabIndex = 0;
            this.groupBox1.BackColor = System.Drawing.Color.Transparent;
            this.groupBox1.Controls.Add(this.lblBookingName);
            this.groupBox1.Controls.Add(this.btnTour);
            this.groupBox1.Controls.Add(this.txtTourNo);
            this.groupBox1.Controls.Add(this.lblReservation);
            this.groupBox1.Location = new System.Drawing.Point(16, 11);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(351, 68);
            this.groupBox1.TabIndex = 263;
            this.groupBox1.TabStop = false;
            this.lblBookingName.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBookingName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.lblBookingName.Location = new System.Drawing.Point(14, 44);
            this.lblBookingName.Name = "lblBookingName";
            this.lblBookingName.Size = new System.Drawing.Size(324, 13);
            this.lblBookingName.TabIndex = 256;
            this.lblBookingName.Text = "\"\"";
            this.lblBookingName.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTour.Location = new System.Drawing.Point(301, 15);
            this.btnTour.Name = "btnTour";
            this.btnTour.Size = new System.Drawing.Size(37, 23);
            this.btnTour.TabIndex = 0;
            this.btnTour.Text = "...";
            this.btnTour.UseVisualStyleBackColor = true;
            this.btnTour.Click += new System.EventHandler(this.btnTour_Click);
            this.txtTourNo.Enabled = false;
            this.txtTourNo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTourNo.ForeColor = System.Drawing.Color.Blue;
            this.txtTourNo.Location = new System.Drawing.Point(115, 16);
            this.txtTourNo.Name = "txtTourNo";
            this.txtTourNo.ReadOnly = true;
            this.txtTourNo.Size = new System.Drawing.Size(179, 21);
            this.txtTourNo.TabIndex = 255;
            this.lblReservation.AutoSize = true;
            this.lblReservation.Location = new System.Drawing.Point(14, 18);
            this.lblReservation.Name = "lblReservation";
            this.lblReservation.Size = new System.Drawing.Size(46, 13);
            this.lblReservation.TabIndex = 252;
            this.lblReservation.Text = "Tour No";
            this.grdPayments.AllowSorting = C1.Win.C1FlexGrid.AllowSortingEnum.None;
            this.grdPayments.AutoResize = false;
            this.grdPayments.BackColor = System.Drawing.Color.Transparent;
            this.grdPayments.BorderStyle = C1.Win.C1FlexGrid.Util.BaseControls.BorderStyleEnum.XpThemes;
            this.grdPayments.ColumnInfo = "0,0,0,0,0,90,Columns:";
            this.grdPayments.Location = new System.Drawing.Point(16, 347);
            this.grdPayments.Name = "grdPayments";
            this.grdPayments.Size = new System.Drawing.Size(617, 243);
            this.grdPayments.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("grdPayments.Styles"));
            this.grdPayments.TabIndex = 271;
            this.grdPayments.Click += new System.EventHandler(this.grdPayments_Click);
            this.grdPayments.KeyDown += new System.Windows.Forms.KeyEventHandler(this.grdPayments_KeyDown);
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label1.Location = new System.Drawing.Point(462, 6);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(93, 20);
            this.label1.TabIndex = 257;
            this.label1.Text = "Invoice No";
            this.lblInvoiceNo.BackColor = System.Drawing.Color.Transparent;
            this.lblInvoiceNo.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblInvoiceNo.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblInvoiceNo.Location = new System.Drawing.Point(403, 36);
            this.lblInvoiceNo.Name = "lblInvoiceNo";
            this.lblInvoiceNo.Size = new System.Drawing.Size(210, 20);
            this.lblInvoiceNo.TabIndex = 272;
            this.lblInvoiceNo.Text = "\"\"";
            this.lblInvoiceNo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.groupBox5.BackColor = System.Drawing.Color.Transparent;
            this.groupBox5.Controls.Add(this.rdbSuppInv);
            this.groupBox5.Controls.Add(this.rdbNormalInv);
            this.groupBox5.Controls.Add(this.label2);
            this.groupBox5.Location = new System.Drawing.Point(16, 85);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(350, 42);
            this.groupBox5.TabIndex = 314;
            this.groupBox5.TabStop = false;
            this.rdbSuppInv.AutoSize = true;
            this.rdbSuppInv.Location = new System.Drawing.Point(156, 18);
            this.rdbSuppInv.Name = "rdbSuppInv";
            this.rdbSuppInv.Size = new System.Drawing.Size(95, 17);
            this.rdbSuppInv.TabIndex = 315;
            this.rdbSuppInv.Text = "Supplementary";
            this.rdbSuppInv.UseVisualStyleBackColor = true;
            this.rdbNormalInv.AutoSize = true;
            this.rdbNormalInv.Checked = true;
            this.rdbNormalInv.Location = new System.Drawing.Point(92, 18);
            this.rdbNormalInv.Name = "rdbNormalInv";
            this.rdbNormalInv.Size = new System.Drawing.Size(58, 17);
            this.rdbNormalInv.TabIndex = 314;
            this.rdbNormalInv.TabStop = true;
            this.rdbNormalInv.Text = "Normal";
            this.rdbNormalInv.UseVisualStyleBackColor = true;
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(12, 19);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(69, 13);
            this.label2.TabIndex = 313;
            this.label2.Text = "Invoice Type";
            this.chkDetail.AutoSize = true;
            this.chkDetail.BackColor = System.Drawing.Color.Transparent;
            this.chkDetail.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkDetail.Location = new System.Drawing.Point(108, 612);
            this.chkDetail.Name = "chkDetail";
            this.chkDetail.Size = new System.Drawing.Size(119, 17);
            this.chkDetail.TabIndex = 315;
            this.chkDetail.Text = "Detailed Invoice";
            this.chkDetail.UseVisualStyleBackColor = false;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Tourist_Management.Properties.Resources.formbak1;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(642, 644);
            this.ControlBox = false;
            this.Controls.Add(this.chkDetail);
            this.Controls.Add(this.groupBox5);
            this.Controls.Add(this.lblInvoiceNo);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.grdPayments);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox7);
            this.Controls.Add(this.groupBox6);
            this.Controls.Add(this.groupBox14);
            this.Controls.Add(this.groupBox4);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.btnPrint);
            this.Controls.Add(this.chkPrint);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOk);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.Name = "frmTourInvoice";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmTourInvoice_Load);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox7.ResumeLayout(false);
            this.groupBox7.PerformLayout();
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            this.groupBox14.ResumeLayout(false);
            this.groupBox14.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdPayments)).EndInit();
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.Button btnPrint;
        private System.Windows.Forms.CheckBox chkPrint;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.RadioButton rdbCancel;
        private System.Windows.Forms.RadioButton rdbAmend;
        private System.Windows.Forms.RadioButton rdbNormal;
        private System.Windows.Forms.GroupBox groupBox7;
        private DropDowns.DropSearch drpBankBranch;
        private System.Windows.Forms.Label lblAccountNo;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.GroupBox groupBox6;
        private DropDowns.DropSearch drpCurrnecy;
        private System.Windows.Forms.TextBox txtRate;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.TextBox txtAmount;
        private System.Windows.Forms.GroupBox groupBox14;
        private System.Windows.Forms.TextBox txtRemarks;
        private System.Windows.Forms.GroupBox groupBox4;
        private DropDowns.DropSearch drpPaidTo;
        private System.Windows.Forms.Button btnAddCont;
        private System.Windows.Forms.Label label5;
        private  Tourist_Management.User_Controls.ComboBox cmbAgentCont;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.DateTimePicker dtpDate;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Button btnTour;
        private System.Windows.Forms.TextBox txtTourNo;
        private System.Windows.Forms.Label lblReservation;
        private C1.Win.C1FlexGrid.C1FlexGrid grdPayments;
        private System.Windows.Forms.Label lblBookingName;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label lblInvoiceNo;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.RadioButton rdbSuppInv;
        private System.Windows.Forms.RadioButton rdbNormalInv;
        private System.Windows.Forms.TextBox txtPaidAmt;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox txtVat;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.CheckBox chkDetail;
    }
}